local EpicMusicPlayer = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer", true)
if not EpicMusicPlayer then return end

local list  -- forward declare once

-- playlist metadata
local listName         = "SL Essentials 3"
local expansion        = 8
local playlistVersion  = "4.0"

if _G.LE_EXPANSION_LEVEL_CURRENT >= expansion then
    -- defer loading until the player is in the world:
    local f = CreateFrame("Frame")
    f:RegisterEvent("PLAYER_ENTERING_WORLD")
    f:SetScript("OnEvent", function(self, event)
        if list then
            EpicMusicPlayer:AddPlayList(list)
        end
        self:UnregisterEvent(event)
        self:SetScript("OnEvent", nil)
    end)
end

list = {
	["listName"] = listName,
	["playlistVersion"] = playlistVersion,
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "To Be Kyrian A",
		path = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_a.mp3",
		id =  3853486,
		duration = 125,
		artist = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "To be kyrian B",
		path = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_b.mp3",
		id =  3853488,
		duration = 111,
		artist = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "To Be Kyrian Doubt H",
		path = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_doubt_h.mp3",
		id =  3853508,
		duration = 194,
		artist = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "To Be Kyrian E",
		path = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_e.mp3",
		id =  3853522,
		duration = 113,
		artist = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "To Be Kyrian F",
		path = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_f.mp3",
		id =  3853524,
		duration = 136,
		artist = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "To Be Kyrian G",
		path = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_g.mp3",
		id =  3853526,
		duration = 109,
		artist = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "To Be Kyrian H",
		path = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_h.mp3",
		id =  3853528,
		duration = 366,
		artist = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "To Be Kyrian I",
		path = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_i.mp3",
		id =  3853530,
		duration = 118,
		artist = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "To Be Kyrian J",
		path = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_j.mp3",
		id =  3853532,
		duration = 121,
		artist = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "To Be Kyrian O",
		path = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_o.mp3",
		id =  3853534,
		duration = 137,
		artist = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "To Be Kyrian R",
		path = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_r.mp3",
		id =  3853540,
		duration = 111,
		artist = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Utherconfront",
		path = "sound\\music\\shadowlands\\mus_90_utherconfront.mp3",
		id =  3931066,
		duration = 164,
		artist = "Glenn Stafford, Tracy Bush",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.1.0 Shadowlands",
		title = "Revendreth Sired A",
		path = "sound\\music\\shadowlands\\mus_91_revendreth_sired_a.mp3",
		id =  4198445,
		duration = 98,
		artist = "Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.1.0 Shadowlands",
		title = "Revendreth Sired B",
		path = "sound\\music\\shadowlands\\mus_91_revendreth_sired_b.mp3",
		id =  4198447,
		duration = 114,
		artist = "Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.1.0 Shadowlands",
		title = "Revendreth Sired C",
		path = "sound\\music\\shadowlands\\mus_91_revendreth_sired_c.mp3",
		id =  4198449,
		duration = 99,
		artist = "Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.1.0 Shadowlands",
		title = "Revendreth Sired D",
		path = "sound\\music\\shadowlands\\mus_91_revendreth_sired_d.mp3",
		id =  4198451,
		duration = 99,
		artist = "Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.1.0 Shadowlands",
		title = "Revendreth Sired H",
		path = "sound\\music\\shadowlands\\mus_91_revendreth_sired_h.mp3",
		id =  4198453,
		duration = 126,
		artist = "Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.2.0 Shadowlands",
		title = "Domination Anduin Action A",
		path = "sound\\music\\shadowlands\\mus_92_domination_anduin_action_a.mp3",
		id =  4423076,
		duration = 103,
		artist = "Neal Acree",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.2.0 Shadowlands",
		title = "Domination Anduin Action B",
		path = "sound\\music\\shadowlands\\mus_92_domination_anduin_action_b.mp3",
		id =  4423078,
		duration = 105,
		artist = "Neal Acree",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.2.0 Shadowlands",
		title = "Domination Anduin Action C",
		path = "sound\\music\\shadowlands\\mus_92_domination_anduin_action_c.mp3",
		id =  4423080,
		duration = 105,
		artist = "Neal Acree",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Choice Oblivion Dark Domination",
		path = "sound\\music\\shadowlands\\mus_90_aw_choice_oblivion_dark_domination.mp3",
		id =  3857085,
		duration = 140,
		artist = "David Arkenstone, Neal Acree, Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nightfae A",
		path = "sound\\music\\shadowlands\\mus_90_aw_nightfae_a.mp3",
		id =  3853282,
		duration = 114,
		artist = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nightfae B",
		path = "sound\\music\\shadowlands\\mus_90_aw_nightfae_b.mp3",
		id =  3853284,
		duration = 119,
		artist = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nightfae C",
		path = "sound\\music\\shadowlands\\mus_90_aw_nightfae_c.mp3",
		id =  3853286,
		duration = 130,
		artist = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nightfae D",
		path = "sound\\music\\shadowlands\\mus_90_aw_nightfae_d.mp3",
		id =  3853288,
		duration = 123,
		artist = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nightfae F",
		path = "sound\\music\\shadowlands\\mus_90_aw_nightfae_f.mp3",
		id =  3853290,
		duration = 101,
		artist = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nightfae H",
		path = "sound\\music\\shadowlands\\mus_90_aw_nightfae_h.mp3",
		id =  3853294,
		duration = 171,
		artist = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nightfae I",
		path = "sound\\music\\shadowlands\\mus_90_aw_nightfae_i.mp3",
		id =  3853296,
		duration = 122,
		artist = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nightfae J",
		path = "sound\\music\\shadowlands\\mus_90_aw_nightfae_j.mp3",
		id =  3853304,
		duration = 126,
		artist = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nightfae K",
		path = "sound\\music\\shadowlands\\mus_90_aw_nightfae_k.mp3",
		id =  3853306,
		duration = 145,
		artist = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nightfae L",
		path = "sound\\music\\shadowlands\\mus_90_aw_nightfae_l.mp3",
		id =  3853308,
		duration = 103,
		artist = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nightfae M",
		path = "sound\\music\\shadowlands\\mus_90_aw_nightfae_m.mp3",
		id =  3853310,
		duration = 132,
		artist = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Celestial A",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_a.mp3",
		id =  3853312,
		duration = 122,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Celestial B",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_b.mp3",
		id =  3853314,
		duration = 122,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Celestial C",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_c.mp3",
		id =  3853316,
		duration = 132,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Celestial D",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_d.mp3",
		id =  3853318,
		duration = 132,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Celestial E",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_e.mp3",
		id =  3853320,
		duration = 118,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Celestial H",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_h.mp3",
		id =  3853322,
		duration = 122,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Celestial I",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_i.mp3",
		id =  3853324,
		duration = 103,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Celestial J",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_j.mp3",
		id =  3853326,
		duration = 125,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Celestial K",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_k.mp3",
		id =  3853328,
		duration = 113,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Celestial L",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_l.mp3",
		id =  3853330,
		duration = 113,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Celestial M",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_m.mp3",
		id =  3853332,
		duration = 125,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Devious A",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_devious_a.mp3",
		id =  3853334,
		duration = 123,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Devious H",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_devious_h.mp3",
		id =  3853348,
		duration = 123,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Hollow A",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_hollow_a.mp3",
		id =  3853354,
		duration = 160,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Hollow B",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_hollow_b.mp3",
		id =  3853356,
		duration = 158,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Hollow C",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_hollow_c.mp3",
		id =  3853358,
		duration = 158,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Hollow D",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_hollow_d.mp3",
		id =  3853360,
		duration = 156,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Hollow E",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_hollow_e.mp3",
		id =  3853362,
		duration = 156,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Hollow H",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_hollow_h.mp3",
		id =  3853364,
		duration = 156,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Hunger A",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_hunger_a.mp3",
		id =  3853366,
		duration = 135,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Hunger H",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_hunger_h.mp3",
		id =  3853376,
		duration = 137,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Melancholy Dream A",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_a.mp3",
		id =  3853378,
		duration = 143,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Melancholy Dream B",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_b.mp3",
		id =  3853380,
		duration = 143,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Melancholy Dream C",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_c.mp3",
		id =  3853382,
		duration = 122,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Melancholy Dream D",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_d.mp3",
		id =  3853384,
		duration = 122,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Melancholy Dream E",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_e.mp3",
		id =  3853386,
		duration = 131,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Melancholy Dream F",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_f.mp3",
		id =  3853388,
		duration = 133,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Melancholy Dream H",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_h.mp3",
		id =  3853390,
		duration = 122,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Melancholy Dream I",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_i.mp3",
		id =  3853392,
		duration = 122,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Melancholy Dream K",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_k.mp3",
		id =  3853394,
		duration = 109,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Melancholy Dream M",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_m.mp3",
		id =  3853398,
		duration = 102,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Nocturne Mischief H",
		path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_mischief_h.mp3",
		id =  3853406,
		duration = 117,
		artist = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Aspirantsjourney Doubt Domination",
		path = "sound\\music\\shadowlands\\mus_90_ba_aspirantsjourney_doubt_domination.mp3",
		id =  3857093,
		duration = 114,
		artist = "Glenn Stafford, Neal Acree, David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Kyrian A",
		path = "sound\\music\\shadowlands\\mus_90_ba_kyrian_a.mp3",
		id =  3853456,
		duration = 149,
		artist = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Kyrian B",
		path = "sound\\music\\shadowlands\\mus_90_ba_kyrian_b.mp3",
		id =  3853458,
		duration = 149,
		artist = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Kyrian C",
		path = "sound\\music\\shadowlands\\mus_90_ba_kyrian_c.mp3",
		id =  3853460,
		duration = 121,
		artist = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Kyrian D",
		path = "sound\\music\\shadowlands\\mus_90_ba_kyrian_d.mp3",
		id =  3853462,
		duration = 128,
		artist = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Kyrian E",
		path = "sound\\music\\shadowlands\\mus_90_ba_kyrian_e.mp3",
		id =  3853464,
		duration = 136,
		artist = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Kyrian F",
		path = "sound\\music\\shadowlands\\mus_90_ba_kyrian_f.mp3",
		id =  3853466,
		duration = 135,
		artist = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Kyrian G",
		path = "sound\\music\\shadowlands\\mus_90_ba_kyrian_g.mp3",
		id =  3853468,
		duration = 109,
		artist = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Kyrian H",
		path = "sound\\music\\shadowlands\\mus_90_ba_kyrian_h.mp3",
		id =  3853470,
		duration = 239,
		artist = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Kyrian I",
		path = "sound\\music\\shadowlands\\mus_90_ba_kyrian_i.mp3",
		id =  3853472,
		duration = 152,
		artist = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Kyrian J",
		path = "sound\\music\\shadowlands\\mus_90_ba_kyrian_j.mp3",
		id =  3853480,
		duration = 116,
		artist = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Kyrian K",
		path = "sound\\music\\shadowlands\\mus_90_ba_kyrian_k.mp3",
		id =  3853482,
		duration = 106,
		artist = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Kyrian L",
		path = "sound\\music\\shadowlands\\mus_90_ba_kyrian_l.mp3",
		id =  3853550,
		duration = 133,
		artist = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Hopeabandoned Domination",
		path = "sound\\music\\shadowlands\\mus_90_maw_hopeabandoned_domination.mp3",
		id =  3885313,
		duration = 136,
		artist = "Grant Kirkhope, Neal Acree, David Arkenstone",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Themaw Ambient A",
		path = "sound\\music\\shadowlands\\mus_90_maw_themaw_ambient_a.mp3",
		id =  3919997,
		duration = 121,
		artist = "Blizzard Entertainment",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Themaw Ambient B",
		path = "sound\\music\\shadowlands\\mus_90_maw_themaw_ambient_b.mp3",
		id =  3919999,
		duration = 124,
		artist = "Blizzard Entertainment",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Themaw Ambient C",
		path = "sound\\music\\shadowlands\\mus_90_maw_themaw_ambient_c.mp3",
		id =  3920001,
		duration = 126,
		artist = "Blizzard Entertainment",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Themaw Ambient D",
		path = "sound\\music\\shadowlands\\mus_90_maw_themaw_ambient_d.mp3",
		id =  3920003,
		duration = 116,
		artist = "Blizzard Entertainment",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Themaw Ambient E",
		path = "sound\\music\\shadowlands\\mus_90_maw_themaw_ambient_e.mp3",
		id =  3920005,
		duration = 114,
		artist = "Blizzard Entertainment",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Themaw Ambient F",
		path = "sound\\music\\shadowlands\\mus_90_maw_themaw_ambient_f.mp3",
		id =  3920007,
		duration = 118,
		artist = "Blizzard Entertainment",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Torghast Action A",
		path = "sound\\music\\shadowlands\\mus_90_maw_torghast_action_a.mp3",
		id =  3853566,
		duration = 129,
		artist = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Torghast Action B",
		path = "sound\\music\\shadowlands\\mus_90_maw_torghast_action_b.mp3",
		id =  3853568,
		duration = 106,
		artist = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Torghast Action C",
		path = "sound\\music\\shadowlands\\mus_90_maw_torghast_action_c.mp3",
		id =  3853570,
		duration = 126,
		artist = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Torghast Action D",
		path = "sound\\music\\shadowlands\\mus_90_maw_torghast_action_d.mp3",
		id =  3853572,
		duration = 122,
		artist = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Torghast Action H",
		path = "sound\\music\\shadowlands\\mus_90_maw_torghast_action_h.mp3",
		id =  3853576,
		duration = 129,
		artist = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Torghast Ambient J",
		path = "sound\\music\\shadowlands\\mus_90_maw_torghast_ambient_j.mp3",
		id =  3931036,
		duration = 115,
		artist = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Torghast Ambient K",
		path = "sound\\music\\shadowlands\\mus_90_maw_torghast_ambient_k.mp3",
		id =  3931038,
		duration = 102,
		artist = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Torghast Ambient N",
		path = "sound\\music\\shadowlands\\mus_90_maw_torghast_ambient_n.mp3",
		id =  3931044,
		duration = 104,
		artist = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Sansprimus H",
		path = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_h.mp3",
		id =  3853678,
		duration = 166,
		artist = "Glenn Stafford, Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Sansprimus Hero A",
		path = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_a.mp3",
		id =  3853680,
		duration = 110,
		artist = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Sansprimus Hero B",
		path = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_b.mp3",
		id =  3853682,
		duration = 107,
		artist = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Sansprimus Hero C",
		path = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_c.mp3",
		id =  3853684,
		duration = 116,
		artist = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Sansprimus Hero D",
		path = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_d.mp3",
		id =  3853686,
		duration = 124,
		artist = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Sansprimus Hero H",
		path = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_h.mp3",
		id =  3853688,
		duration = 133,
		artist = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Sansprimus M",
		path = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_m.mp3",
		id =  3853696,
		duration = 102,
		artist = "Glenn Stafford, Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		album = "WoW 9.0.0 Shadowlands",
		title = "Sansprimus Paranoid F",
		path = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_paranoid_f.mp3",
		id =  3853708,
		duration = 101,
		artist = "Glenn Stafford, Grant Kirkhope",
		["WoW"] =  "None",
	},
}