local EpicMusicPlayer = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer", true)
if not EpicMusicPlayer then return end

local list  -- forward declare once

-- playlist metadata
local listName         = "SL Essentials 2"
local expansion        = 7 -- Shadowlands
local playlistVersion  = "4.0"

if _G.LE_EXPANSION_LEVEL_CURRENT > expansion then
    -- defer loading until the player is in the world:
    local f = CreateFrame("Frame")
    f:RegisterEvent("PLAYER_ENTERING_WORLD")
    f:SetScript("OnEvent", function(self, event)
        if list then
            EpicMusicPlayer:AddPlayList(list)
        end
        self:UnregisterEvent(event)
        self:SetScript("OnEvent", nil)
    end)
end

list = {
	["listName"] = listName,
	["playlistVersion"] = playlistVersion,
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Through The Roof of the World",
        path = "sound\\music\\shadowlands\\mus_90_throughtheroofoftheworld_maintitle.mp3",
        id = 3850553,
        duration = 684,
        artist = "Main Title",
        ["Wow"] = "true"
    },
    {
        album = "WoW 9.1.0 Shadowlands",
        title = "Domination Anduin",
        path = "sound\\music\\shadowlands\\mus_91_domination_anduin.mp3",
        id = 4198457,
        duration = 134,
        artist = "Neal Acree",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Sansprimus Hero H",
        path = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_h.mp3",
        id = 3853688,
        duration = 133,
        artist = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Sansprimus Hero D",
        path = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_d.mp3",
        id = 3853686,
        duration = 124,
        artist = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Sansprimus Hero C",
        path = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_c.mp3",
        id = 3853684,
        duration = 116,
        artist = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.1.0 Shadowlands",
        title = "Sanctum Of Domination E",
        path = "sound\\music\\shadowlands\\mus_91_sanctum_of_domination_e.mp3",
        id = 4204911,
        duration = 113,
        artist = "D Arkenstone",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Celestial Battle Domination A",
        path = "sound\\music\\shadowlands\\mus_92_celestial_battle_domination_a.mp3",
        id = 4423096,
        duration = 111,
        artist = "Jake Lefkowitz; Neal Acree",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Sansprimus Hero A",
        path = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_a.mp3",
        id = 3853680,
        duration = 110,
        artist = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Celestial Battle Domination C",
        path = "sound\\music\\shadowlands\\mus_92_celestial_battle_domination_c.mp3",
        id = 4423100,
        duration = 110,
        artist = "Jake Lefkowitz; Neal Acree",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.1.0 Shadowlands",
        title = "Sanctum Of Domination C",
        path = "sound\\music\\shadowlands\\mus_91_sanctum_of_domination_c.mp3",
        id = 4204907,
        duration = 109,
        artist = "D Arkenstone",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Sansprimus Hero B",
        path = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_b.mp3",
        id = 3853682,
        duration = 107,
        artist = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Celestial Battle Domination D",
        path = "sound\\music\\shadowlands\\mus_92_celestial_battle_domination_d.mp3",
        id = 4423102,
        duration = 105,
        artist = "Jake Lefkowitz; Neal Acree",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Domination Anduin Action B",
        path = "sound\\music\\shadowlands\\mus_92_domination_anduin_action_b.mp3",
        id = 4423078,
        duration = 105,
        artist = "Neal Acree",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Domination Anduin Action C",
        path = "sound\\music\\shadowlands\\mus_92_domination_anduin_action_c.mp3",
        id = 4423080,
        duration = 105,
        artist = "Neal Acree",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Celestial Battle Domination B",
        path = "sound\\music\\shadowlands\\mus_92_celestial_battle_domination_b.mp3",
        id = 4423098,
        duration = 104,
        artist = "Jake Lefkowitz; Neal Acree",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.1.0 Shadowlands",
        title = "Sanctum Of Domination F",
        path = "sound\\music\\shadowlands\\mus_91_sanctum_of_domination_f.mp3",
        id = 4204915,
        duration = 103,
        artist = "D Arkenstone",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Domination Anduin Action A",
        path = "sound\\music\\shadowlands\\mus_92_domination_anduin_action_a.mp3",
        id = 4423076,
        duration = 103,
        artist = "Neal Acree",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Ritual Sinister Domination",
        path = "sound\\music\\shadowlands\\mus_90_rd_ritual_sinister_domination.mp3",
        id = 3885329,
        duration = 101,
        artist = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.1.0 Shadowlands",
        title = "Sanctum Of Domination H",
        path = "sound\\music\\shadowlands\\mus_91_sanctum_of_domination_h.mp3",
        id = 4204913,
        duration = 101,
        artist = "D Arkenstone",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.1.0 Shadowlands",
        title = "Sanctum Of Domination D",
        path = "sound\\music\\shadowlands\\mus_91_sanctum_of_domination_d.mp3",
        id = 4204909,
        duration = 100,
        artist = "D Arkenstone",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.1.0 Shadowlands",
        title = "Sanctum Of Domination A",
        path = "sound\\music\\shadowlands\\mus_91_sanctum_of_domination_a.mp3",
        id = 4204903,
        duration = 95,
        artist = "D Arkenstone",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.1.0 Shadowlands",
        title = "Sanctum Of Domination B",
        path = "sound\\music\\shadowlands\\mus_91_sanctum_of_domination_b.mp3",
        id = 4204905,
        duration = 91,
        artist = "D Arkenstone",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Sansprimus Domination",
        path = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_domination.mp3",
        id = 3857097,
        duration = 69,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.1.0 Shadowlands",
        title = "Scene Anduins Goodbye",
        path = "sound\\music\\shadowlands\\mus_91_scene_anduins_goodbye.mp3",
        id = 4204811,
        duration = 93,
        artist = "N Acree",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.1.0 Shadowlands",
        title = "Scene Primus Returns",
        path = "sound\\music\\shadowlands\\mus_91_scene_primus_returns.mp3",
        id = 4204825,
        duration = 81,
        artist = "Acree",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Zereth Mortis Intro H",
        path = "sound\\music\\shadowlands\\mus_92_zereth_mortis_intro_h.mp3",
        id = 4423292,
        duration = 250,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Nocturne Celestial C",
        path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_c.mp3",
        id = 3853316,
        duration = 132,
        artist = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Nocturne Celestial D",
        path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_d.mp3",
        id = 3853318,
        duration = 132,
        artist = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Nocturne Celestial J",
        path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_j.mp3",
        id = 3853326,
        duration = 125,
        artist = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Nocturne Celestial M",
        path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_m.mp3",
        id = 3853332,
        duration = 125,
        artist = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Nocturne Celestial A",
        path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_a.mp3",
        id = 3853312,
        duration = 122,
        artist = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Nocturne Celestial B",
        path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_b.mp3",
        id = 3853314,
        duration = 122,
        artist = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Nocturne Celestial H",
        path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_h.mp3",
        id = 3853322,
        duration = 122,
        artist = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Nocturne Celestial E",
        path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_e.mp3",
        id = 3853320,
        duration = 118,
        artist = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Nocturne Celestial K",
        path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_k.mp3",
        id = 3853328,
        duration = 113,
        artist = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Nocturne Celestial L",
        path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_l.mp3",
        id = 3853330,
        duration = 113,
        artist = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Zereth Mortis Barren A",
        path = "sound\\music\\shadowlands\\mus_92_zereth_mortis_barren_a.mp3",
        id = 4423204,
        duration = 204,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Nocturne Celestial I",
        path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_i.mp3",
        id = 3853324,
        duration = 103,
        artist = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Zereth Mortis Barren H",
        path = "sound\\music\\shadowlands\\mus_92_zereth_mortis_barren_h.mp3",
        id = 4423210,
        duration = 197,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Decadence Pride H",
        path = "sound\\music\\shadowlands\\mus_90_rd_decadence_pride_h.mp3",
        id = 3853820,
        duration = 184,
        artist = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Jailers Chain H",
        path = "sound\\music\\shadowlands\\mus_92_jailers_chain_h.mp3",
        id = 4423298,
        duration = 179,
        artist = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Zereth Mortis Tranquility G",
        path = "sound\\music\\shadowlands\\mus_92_zereth_mortis_tranquility_g.mp3",
        id = 4423326,
        duration = 178,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Celestial Battle H",
        path = "sound\\music\\shadowlands\\mus_92_celestial_battle_h.mp3",
        id = 4423110,
        duration = 175,
        artist = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Shadow Sylvanas Freewill H",
        path = "sound\\music\\shadowlands\\mus_90_shadow_sylvanas_freewill_h.mp3",
        id = 3850505,
        duration = 172,
        artist = "Sam Cardon",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Sansprimus H",
        path = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_h.mp3",
        id = 3853678,
        duration = 166,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Zereth Mortis Tranquility F",
        path = "sound\\music\\shadowlands\\mus_92_zereth_mortis_tranquility_f.mp3",
        id = 4423322,
        duration = 165,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Zereth Mortis Mystery B",
        path = "sound\\music\\shadowlands\\mus_92_zereth_mortis_mystery_b.mp3",
        id = 4423308,
        duration = 164,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Zereth Mortis Tranquility H",
        path = "sound\\music\\shadowlands\\mus_92_zereth_mortis_tranquility_h.mp3",
        id = 4423324,
        duration = 164,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Zereth Mortis Tranquility E",
        path = "sound\\music\\shadowlands\\mus_92_zereth_mortis_tranquility_e.mp3",
        id = 4423320,
        duration = 162,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.1.0 Shadowlands",
        title = "Korthia Lostarchives H",
        path = "sound\\music\\shadowlands\\mus_91_korthia_lostarchives_h.mp3",
        id = 4198318,
        duration = 160,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.5 Shadowlands",
        title = "Scene Anduin Sylvanas Epilogue",
        path = "sound\\music\\shadowlands\\mus_925_scene_anduin_sylvanas_epilogue.mp3",
        id = 4547329,
        duration = 159,
        artist = "G Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.1.0 Shadowlands",
        title = "Korthia Lostarchives A",
        path = "sound\\music\\shadowlands\\mus_91_korthia_lostarchives_a.mp3",
        id = 4198314,
        duration = 153,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.1.0 Shadowlands",
        title = "Korthia Lostarchives B",
        path = "sound\\music\\shadowlands\\mus_91_korthia_lostarchives_b.mp3",
        id = 4198316,
        duration = 153,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Zereth Mortis Intro B",
        path = "sound\\music\\shadowlands\\mus_92_zereth_mortis_intro_b.mp3",
        id = 4423286,
        duration = 148,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Shadow Sylvanas Freewill D",
        path = "sound\\music\\shadowlands\\mus_90_shadow_sylvanas_freewill_d.mp3",
        id = 3850503,
        duration = 144,
        artist = "Sam Cardon",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Shadow Sylvanas Freewill A",
        path = "sound\\music\\shadowlands\\mus_90_shadow_sylvanas_freewill_a.mp3",
        id = 3850497,
        duration = 139,
        artist = "Sam Cardon",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Ritual Sinister H",
        path = "sound\\music\\shadowlands\\mus_90_rd_ritual_sinister_h.mp3",
        id = 3853868,
        duration = 138,
        artist = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Zereth Mortis Barren C",
        path = "sound\\music\\shadowlands\\mus_92_zereth_mortis_barren_c.mp3",
        id = 4423208,
        duration = 136,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Ritual Feral A",
        path = "sound\\music\\shadowlands\\mus_90_rd_ritual_feral_a.mp3",
        id = 3853842,
        duration = 135,
        artist = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Ritual Sinister E",
        path = "sound\\music\\shadowlands\\mus_90_rd_ritual_sinister_e.mp3",
        id = 3853864,
        duration = 135,
        artist = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Celestial Battle F",
        path = "sound\\music\\shadowlands\\mus_92_celestial_battle_f.mp3",
        id = 4423106,
        duration = 135,
        artist = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Celestial Battle G",
        path = "sound\\music\\shadowlands\\mus_92_celestial_battle_g.mp3",
        id = 4423108,
        duration = 135,
        artist = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Decadence Pride B",
        path = "sound\\music\\shadowlands\\mus_90_rd_decadence_pride_b.mp3",
        id = 3853810,
        duration = 133,
        artist = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Celestial Battle I",
        path = "sound\\music\\shadowlands\\mus_92_celestial_battle_i.mp3",
        id = 4423112,
        duration = 133,
        artist = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Zereth Mortis Intro C",
        path = "sound\\music\\shadowlands\\mus_92_zereth_mortis_intro_c.mp3",
        id = 4423288,
        duration = 132,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Zereth Mortis Intro D",
        path = "sound\\music\\shadowlands\\mus_92_zereth_mortis_intro_d.mp3",
        id = 4423290,
        duration = 132,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Decadence Pride A",
        path = "sound\\music\\shadowlands\\mus_90_rd_decadence_pride_a.mp3",
        id = 3853808,
        duration = 131,
        artist = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Celestial Battle C",
        path = "sound\\music\\shadowlands\\mus_92_celestial_battle_c.mp3",
        id = 4423092,
        duration = 130,
        artist = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Torghast Action A",
        path = "sound\\music\\shadowlands\\mus_90_maw_torghast_action_a.mp3",
        id = 3853566,
        duration = 129,
        artist = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Torghast Action H",
        path = "sound\\music\\shadowlands\\mus_90_maw_torghast_action_h.mp3",
        id = 3853576,
        duration = 129,
        artist = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Ritual Feral H",
        path = "sound\\music\\shadowlands\\mus_90_rd_ritual_feral_h.mp3",
        id = 3853852,
        duration = 129,
        artist = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Celestial Battle E",
        path = "sound\\music\\shadowlands\\mus_92_celestial_battle_e.mp3",
        id = 4423104,
        duration = 128,
        artist = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Torghast Action C",
        path = "sound\\music\\shadowlands\\mus_90_maw_torghast_action_c.mp3",
        id = 3853570,
        duration = 126,
        artist = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Decadence Pride D",
        path = "sound\\music\\shadowlands\\mus_90_rd_decadence_pride_d.mp3",
        id = 3853814,
        duration = 126,
        artist = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.1.0 Shadowlands",
        title = "Revendreth Sired H",
        path = "sound\\music\\shadowlands\\mus_91_revendreth_sired_h.mp3",
        id = 4198453,
        duration = 126,
        artist = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.1.0 Shadowlands",
        title = "Uther Reflection H",
        path = "sound\\music\\shadowlands\\mus_91_uther_reflection_h.mp3",
        id = 4198351,
        duration = 123,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Celestial Battle B",
        path = "sound\\music\\shadowlands\\mus_92_celestial_battle_b.mp3",
        id = 4423090,
        duration = 123,
        artist = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Celestial Battle Unbroken D",
        path = "sound\\music\\shadowlands\\mus_92_celestial_battle_unbroken_d.mp3",
        id = 4423126,
        duration = 123,
        artist = "J. Lefkowitz",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Torghast Action D",
        path = "sound\\music\\shadowlands\\mus_90_maw_torghast_action_d.mp3",
        id = 3853572,
        duration = 122,
        artist = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Shadow Sylvanas Freewill B",
        path = "sound\\music\\shadowlands\\mus_90_shadow_sylvanas_freewill_b.mp3",
        id = 3850499,
        duration = 122,
        artist = "Sam Cardon",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Celestial Battle D",
        path = "sound\\music\\shadowlands\\mus_92_celestial_battle_d.mp3",
        id = 4423094,
        duration = 120,
        artist = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Ritual Feral B",
        path = "sound\\music\\shadowlands\\mus_90_rd_ritual_feral_b.mp3",
        id = 3853844,
        duration = 119,
        artist = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Shadow Sylvanas Freewill C",
        path = "sound\\music\\shadowlands\\mus_90_shadow_sylvanas_freewill_c.mp3",
        id = 3850501,
        duration = 117,
        artist = "Sam Cardon",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Jailers Chain A",
        path = "sound\\music\\shadowlands\\mus_92_jailers_chain_a.mp3",
        id = 4423294,
        duration = 117,
        artist = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Jailers Chain B",
        path = "sound\\music\\shadowlands\\mus_92_jailers_chain_b.mp3",
        id = 4423296,
        duration = 116,
        artist = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Zereth Mortis Barren B",
        path = "sound\\music\\shadowlands\\mus_92_zereth_mortis_barren_b.mp3",
        id = 4423206,
        duration = 116,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.1.0 Shadowlands",
        title = "Nightwarrior Tides A",
        path = "sound\\music\\shadowlands\\mus_91_nightwarrior_tides_a.mp3",
        id = 4204863,
        duration = 115,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.1.0 Shadowlands",
        title = "Nightwarrior Tides B",
        path = "sound\\music\\shadowlands\\mus_91_nightwarrior_tides_b.mp3",
        id = 4204921,
        duration = 115,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.1.0 Shadowlands",
        title = "Nightwarrior Tides H",
        path = "sound\\music\\shadowlands\\mus_91_nightwarrior_tides_h.mp3",
        id = 4204865,
        duration = 115,
        artist = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.2.0 Shadowlands",
        title = "Celestial Battle A",
        path = "sound\\music\\shadowlands\\mus_92_celestial_battle_a.mp3",
        id = 4423088,
        duration = 115,
        artist = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.1.0 Shadowlands",
        title = "Revendreth Sired B",
        path = "sound\\music\\shadowlands\\mus_91_revendreth_sired_b.mp3",
        id = 4198447,
        duration = 114,
        artist = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Shadow Domination Battle A",
        path = "sound\\music\\shadowlands\\mus_90_shadow_domination_battle_a.mp3",
        id = 3850487,
        duration = 112,
        artist = "Neal Acree",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Shadow Domination Battle B",
        path = "sound\\music\\shadowlands\\mus_90_shadow_domination_battle_b.mp3",
        id = 3850489,
        duration = 110,
        artist = "Neal Acree",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Shadow Domination Battle C",
        path = "sound\\music\\shadowlands\\mus_90_shadow_domination_battle_c.mp3",
        id = 3850491,
        duration = 110,
        artist = "Neal Acree",
        ["Wow"] = "true",
    },
    {
        album = "WoW 9.0.0 Shadowlands",
        title = "Shadow Domination Battle H",
        path = "sound\\music\\shadowlands\\mus_90_shadow_domination_battle_h.mp3",
        id = 3850493,
        duration = 110,
        artist = "Neal Acree",
        ["Wow"] = "true",
    },
}