local EpicMusicPlayer = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer", true)
if not EpicMusicPlayer then return end

local list  -- forward declare once

-- playlist metadata
local listName         = "SL Essentials 2"
local expansion        = 7 -- Shadowlands
local playlistVersion  = "4.0"

if _G.LE_EXPANSION_LEVEL_CURRENT > expansion then
    -- defer loading until the player is in the world:
    local f = CreateFrame("Frame")
    f:RegisterEvent("PLAYER_ENTERING_WORLD")
    f:SetScript("OnEvent", function(self, event)
        if list then
            EpicMusicPlayer:AddPlayList(list)
        end
        self:UnregisterEvent(event)
        self:SetScript("OnEvent", nil)
    end)
end

list = {
	["listName"] = listName,
	["playlistVersion"] = playlistVersion,
	["locked"] =  "true", 
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Through The Roof of the World",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_throughtheroofoftheworld_maintitle.mp3",
        ["Id"] = 3850553,
        ["Length"] = 684,
        ["Artist"] = "Main Title",
        ["Wow"] = "true"
    },
    {
        ["Album"] = "WoW 9.1.0 Shadowlands",
        ["Song"] = "Domination Anduin",
        ["Name"] = "sound\\music\\shadowlands\\mus_91_domination_anduin.mp3",
        ["Id"] = 4198457,
        ["Length"] = 134,
        ["Artist"] = "Neal Acree",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Sansprimus Hero H",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_h.mp3",
        ["Id"] = 3853688,
        ["Length"] = 133,
        ["Artist"] = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Sansprimus Hero D",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_d.mp3",
        ["Id"] = 3853686,
        ["Length"] = 124,
        ["Artist"] = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Sansprimus Hero C",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_c.mp3",
        ["Id"] = 3853684,
        ["Length"] = 116,
        ["Artist"] = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.1.0 Shadowlands",
        ["Song"] = "Sanctum Of Domination E",
        ["Name"] = "sound\\music\\shadowlands\\mus_91_sanctum_of_domination_e.mp3",
        ["Id"] = 4204911,
        ["Length"] = 113,
        ["Artist"] = "D Arkenstone",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Celestial Battle Domination A",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_celestial_battle_domination_a.mp3",
        ["Id"] = 4423096,
        ["Length"] = 111,
        ["Artist"] = "Jake Lefkowitz; Neal Acree",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Sansprimus Hero A",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_a.mp3",
        ["Id"] = 3853680,
        ["Length"] = 110,
        ["Artist"] = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Celestial Battle Domination C",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_celestial_battle_domination_c.mp3",
        ["Id"] = 4423100,
        ["Length"] = 110,
        ["Artist"] = "Jake Lefkowitz; Neal Acree",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.1.0 Shadowlands",
        ["Song"] = "Sanctum Of Domination C",
        ["Name"] = "sound\\music\\shadowlands\\mus_91_sanctum_of_domination_c.mp3",
        ["Id"] = 4204907,
        ["Length"] = 109,
        ["Artist"] = "D Arkenstone",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Sansprimus Hero B",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_b.mp3",
        ["Id"] = 3853682,
        ["Length"] = 107,
        ["Artist"] = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Celestial Battle Domination D",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_celestial_battle_domination_d.mp3",
        ["Id"] = 4423102,
        ["Length"] = 105,
        ["Artist"] = "Jake Lefkowitz; Neal Acree",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Domination Anduin Action B",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_domination_anduin_action_b.mp3",
        ["Id"] = 4423078,
        ["Length"] = 105,
        ["Artist"] = "Neal Acree",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Domination Anduin Action C",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_domination_anduin_action_c.mp3",
        ["Id"] = 4423080,
        ["Length"] = 105,
        ["Artist"] = "Neal Acree",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Celestial Battle Domination B",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_celestial_battle_domination_b.mp3",
        ["Id"] = 4423098,
        ["Length"] = 104,
        ["Artist"] = "Jake Lefkowitz; Neal Acree",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.1.0 Shadowlands",
        ["Song"] = "Sanctum Of Domination F",
        ["Name"] = "sound\\music\\shadowlands\\mus_91_sanctum_of_domination_f.mp3",
        ["Id"] = 4204915,
        ["Length"] = 103,
        ["Artist"] = "D Arkenstone",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Domination Anduin Action A",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_domination_anduin_action_a.mp3",
        ["Id"] = 4423076,
        ["Length"] = 103,
        ["Artist"] = "Neal Acree",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Ritual Sinister Domination",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_rd_ritual_sinister_domination.mp3",
        ["Id"] = 3885329,
        ["Length"] = 101,
        ["Artist"] = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.1.0 Shadowlands",
        ["Song"] = "Sanctum Of Domination H",
        ["Name"] = "sound\\music\\shadowlands\\mus_91_sanctum_of_domination_h.mp3",
        ["Id"] = 4204913,
        ["Length"] = 101,
        ["Artist"] = "D Arkenstone",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.1.0 Shadowlands",
        ["Song"] = "Sanctum Of Domination D",
        ["Name"] = "sound\\music\\shadowlands\\mus_91_sanctum_of_domination_d.mp3",
        ["Id"] = 4204909,
        ["Length"] = 100,
        ["Artist"] = "D Arkenstone",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.1.0 Shadowlands",
        ["Song"] = "Sanctum Of Domination A",
        ["Name"] = "sound\\music\\shadowlands\\mus_91_sanctum_of_domination_a.mp3",
        ["Id"] = 4204903,
        ["Length"] = 95,
        ["Artist"] = "D Arkenstone",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.1.0 Shadowlands",
        ["Song"] = "Sanctum Of Domination B",
        ["Name"] = "sound\\music\\shadowlands\\mus_91_sanctum_of_domination_b.mp3",
        ["Id"] = 4204905,
        ["Length"] = 91,
        ["Artist"] = "D Arkenstone",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Sansprimus Domination",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_domination.mp3",
        ["Id"] = 3857097,
        ["Length"] = 69,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.1.0 Shadowlands",
        ["Song"] = "Scene Anduins Goodbye",
        ["Name"] = "sound\\music\\shadowlands\\mus_91_scene_anduins_goodbye.mp3",
        ["Id"] = 4204811,
        ["Length"] = 93,
        ["Artist"] = "N Acree",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.1.0 Shadowlands",
        ["Song"] = "Scene Primus Returns",
        ["Name"] = "sound\\music\\shadowlands\\mus_91_scene_primus_returns.mp3",
        ["Id"] = 4204825,
        ["Length"] = 81,
        ["Artist"] = "Acree",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Zereth Mortis Intro H",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_zereth_mortis_intro_h.mp3",
        ["Id"] = 4423292,
        ["Length"] = 250,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Nocturne Celestial C",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_c.mp3",
        ["Id"] = 3853316,
        ["Length"] = 132,
        ["Artist"] = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Nocturne Celestial D",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_d.mp3",
        ["Id"] = 3853318,
        ["Length"] = 132,
        ["Artist"] = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Nocturne Celestial J",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_j.mp3",
        ["Id"] = 3853326,
        ["Length"] = 125,
        ["Artist"] = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Nocturne Celestial M",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_m.mp3",
        ["Id"] = 3853332,
        ["Length"] = 125,
        ["Artist"] = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Nocturne Celestial A",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_a.mp3",
        ["Id"] = 3853312,
        ["Length"] = 122,
        ["Artist"] = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Nocturne Celestial B",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_b.mp3",
        ["Id"] = 3853314,
        ["Length"] = 122,
        ["Artist"] = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Nocturne Celestial H",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_h.mp3",
        ["Id"] = 3853322,
        ["Length"] = 122,
        ["Artist"] = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Nocturne Celestial E",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_e.mp3",
        ["Id"] = 3853320,
        ["Length"] = 118,
        ["Artist"] = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Nocturne Celestial K",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_k.mp3",
        ["Id"] = 3853328,
        ["Length"] = 113,
        ["Artist"] = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Nocturne Celestial L",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_l.mp3",
        ["Id"] = 3853330,
        ["Length"] = 113,
        ["Artist"] = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Zereth Mortis Barren A",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_zereth_mortis_barren_a.mp3",
        ["Id"] = 4423204,
        ["Length"] = 204,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Nocturne Celestial I",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_i.mp3",
        ["Id"] = 3853324,
        ["Length"] = 103,
        ["Artist"] = "David Arkenstone",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Zereth Mortis Barren H",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_zereth_mortis_barren_h.mp3",
        ["Id"] = 4423210,
        ["Length"] = 197,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Decadence Pride H",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_rd_decadence_pride_h.mp3",
        ["Id"] = 3853820,
        ["Length"] = 184,
        ["Artist"] = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Jailers Chain H",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_jailers_chain_h.mp3",
        ["Id"] = 4423298,
        ["Length"] = 179,
        ["Artist"] = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Zereth Mortis Tranquility G",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_zereth_mortis_tranquility_g.mp3",
        ["Id"] = 4423326,
        ["Length"] = 178,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Celestial Battle H",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_celestial_battle_h.mp3",
        ["Id"] = 4423110,
        ["Length"] = 175,
        ["Artist"] = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Shadow Sylvanas Freewill H",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_shadow_sylvanas_freewill_h.mp3",
        ["Id"] = 3850505,
        ["Length"] = 172,
        ["Artist"] = "Sam Cardon",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Sansprimus H",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_h.mp3",
        ["Id"] = 3853678,
        ["Length"] = 166,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Zereth Mortis Tranquility F",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_zereth_mortis_tranquility_f.mp3",
        ["Id"] = 4423322,
        ["Length"] = 165,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Zereth Mortis Mystery B",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_zereth_mortis_mystery_b.mp3",
        ["Id"] = 4423308,
        ["Length"] = 164,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Zereth Mortis Tranquility H",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_zereth_mortis_tranquility_h.mp3",
        ["Id"] = 4423324,
        ["Length"] = 164,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Zereth Mortis Tranquility E",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_zereth_mortis_tranquility_e.mp3",
        ["Id"] = 4423320,
        ["Length"] = 162,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.1.0 Shadowlands",
        ["Song"] = "Korthia Lostarchives H",
        ["Name"] = "sound\\music\\shadowlands\\mus_91_korthia_lostarchives_h.mp3",
        ["Id"] = 4198318,
        ["Length"] = 160,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.5 Shadowlands",
        ["Song"] = "Scene Anduin Sylvanas Epilogue",
        ["Name"] = "sound\\music\\shadowlands\\mus_925_scene_anduin_sylvanas_epilogue.mp3",
        ["Id"] = 4547329,
        ["Length"] = 159,
        ["Artist"] = "G Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.1.0 Shadowlands",
        ["Song"] = "Korthia Lostarchives A",
        ["Name"] = "sound\\music\\shadowlands\\mus_91_korthia_lostarchives_a.mp3",
        ["Id"] = 4198314,
        ["Length"] = 153,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.1.0 Shadowlands",
        ["Song"] = "Korthia Lostarchives B",
        ["Name"] = "sound\\music\\shadowlands\\mus_91_korthia_lostarchives_b.mp3",
        ["Id"] = 4198316,
        ["Length"] = 153,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Zereth Mortis Intro B",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_zereth_mortis_intro_b.mp3",
        ["Id"] = 4423286,
        ["Length"] = 148,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Shadow Sylvanas Freewill D",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_shadow_sylvanas_freewill_d.mp3",
        ["Id"] = 3850503,
        ["Length"] = 144,
        ["Artist"] = "Sam Cardon",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Shadow Sylvanas Freewill A",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_shadow_sylvanas_freewill_a.mp3",
        ["Id"] = 3850497,
        ["Length"] = 139,
        ["Artist"] = "Sam Cardon",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Ritual Sinister H",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_rd_ritual_sinister_h.mp3",
        ["Id"] = 3853868,
        ["Length"] = 138,
        ["Artist"] = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Zereth Mortis Barren C",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_zereth_mortis_barren_c.mp3",
        ["Id"] = 4423208,
        ["Length"] = 136,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Ritual Feral A",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_rd_ritual_feral_a.mp3",
        ["Id"] = 3853842,
        ["Length"] = 135,
        ["Artist"] = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Ritual Sinister E",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_rd_ritual_sinister_e.mp3",
        ["Id"] = 3853864,
        ["Length"] = 135,
        ["Artist"] = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Celestial Battle F",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_celestial_battle_f.mp3",
        ["Id"] = 4423106,
        ["Length"] = 135,
        ["Artist"] = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Celestial Battle G",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_celestial_battle_g.mp3",
        ["Id"] = 4423108,
        ["Length"] = 135,
        ["Artist"] = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Decadence Pride B",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_rd_decadence_pride_b.mp3",
        ["Id"] = 3853810,
        ["Length"] = 133,
        ["Artist"] = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Celestial Battle I",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_celestial_battle_i.mp3",
        ["Id"] = 4423112,
        ["Length"] = 133,
        ["Artist"] = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Zereth Mortis Intro C",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_zereth_mortis_intro_c.mp3",
        ["Id"] = 4423288,
        ["Length"] = 132,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Zereth Mortis Intro D",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_zereth_mortis_intro_d.mp3",
        ["Id"] = 4423290,
        ["Length"] = 132,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Decadence Pride A",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_rd_decadence_pride_a.mp3",
        ["Id"] = 3853808,
        ["Length"] = 131,
        ["Artist"] = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Celestial Battle C",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_celestial_battle_c.mp3",
        ["Id"] = 4423092,
        ["Length"] = 130,
        ["Artist"] = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Torghast Action A",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_maw_torghast_action_a.mp3",
        ["Id"] = 3853566,
        ["Length"] = 129,
        ["Artist"] = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Torghast Action H",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_maw_torghast_action_h.mp3",
        ["Id"] = 3853576,
        ["Length"] = 129,
        ["Artist"] = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Ritual Feral H",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_rd_ritual_feral_h.mp3",
        ["Id"] = 3853852,
        ["Length"] = 129,
        ["Artist"] = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Celestial Battle E",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_celestial_battle_e.mp3",
        ["Id"] = 4423104,
        ["Length"] = 128,
        ["Artist"] = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Torghast Action C",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_maw_torghast_action_c.mp3",
        ["Id"] = 3853570,
        ["Length"] = 126,
        ["Artist"] = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Decadence Pride D",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_rd_decadence_pride_d.mp3",
        ["Id"] = 3853814,
        ["Length"] = 126,
        ["Artist"] = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.1.0 Shadowlands",
        ["Song"] = "Revendreth Sired H",
        ["Name"] = "sound\\music\\shadowlands\\mus_91_revendreth_sired_h.mp3",
        ["Id"] = 4198453,
        ["Length"] = 126,
        ["Artist"] = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.1.0 Shadowlands",
        ["Song"] = "Uther Reflection H",
        ["Name"] = "sound\\music\\shadowlands\\mus_91_uther_reflection_h.mp3",
        ["Id"] = 4198351,
        ["Length"] = 123,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Celestial Battle B",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_celestial_battle_b.mp3",
        ["Id"] = 4423090,
        ["Length"] = 123,
        ["Artist"] = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Celestial Battle Unbroken D",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_celestial_battle_unbroken_d.mp3",
        ["Id"] = 4423126,
        ["Length"] = 123,
        ["Artist"] = "J. Lefkowitz",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Torghast Action D",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_maw_torghast_action_d.mp3",
        ["Id"] = 3853572,
        ["Length"] = 122,
        ["Artist"] = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Shadow Sylvanas Freewill B",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_shadow_sylvanas_freewill_b.mp3",
        ["Id"] = 3850499,
        ["Length"] = 122,
        ["Artist"] = "Sam Cardon",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Celestial Battle D",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_celestial_battle_d.mp3",
        ["Id"] = 4423094,
        ["Length"] = 120,
        ["Artist"] = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Ritual Feral B",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_rd_ritual_feral_b.mp3",
        ["Id"] = 3853844,
        ["Length"] = 119,
        ["Artist"] = "Grant Kirkhope",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Shadow Sylvanas Freewill C",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_shadow_sylvanas_freewill_c.mp3",
        ["Id"] = 3850501,
        ["Length"] = 117,
        ["Artist"] = "Sam Cardon",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Jailers Chain A",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_jailers_chain_a.mp3",
        ["Id"] = 4423294,
        ["Length"] = 117,
        ["Artist"] = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Jailers Chain B",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_jailers_chain_b.mp3",
        ["Id"] = 4423296,
        ["Length"] = 116,
        ["Artist"] = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Zereth Mortis Barren B",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_zereth_mortis_barren_b.mp3",
        ["Id"] = 4423206,
        ["Length"] = 116,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.1.0 Shadowlands",
        ["Song"] = "Nightwarrior Tides A",
        ["Name"] = "sound\\music\\shadowlands\\mus_91_nightwarrior_tides_a.mp3",
        ["Id"] = 4204863,
        ["Length"] = 115,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.1.0 Shadowlands",
        ["Song"] = "Nightwarrior Tides B",
        ["Name"] = "sound\\music\\shadowlands\\mus_91_nightwarrior_tides_b.mp3",
        ["Id"] = 4204921,
        ["Length"] = 115,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.1.0 Shadowlands",
        ["Song"] = "Nightwarrior Tides H",
        ["Name"] = "sound\\music\\shadowlands\\mus_91_nightwarrior_tides_h.mp3",
        ["Id"] = 4204865,
        ["Length"] = 115,
        ["Artist"] = "Glenn Stafford",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.2.0 Shadowlands",
        ["Song"] = "Celestial Battle A",
        ["Name"] = "sound\\music\\shadowlands\\mus_92_celestial_battle_a.mp3",
        ["Id"] = 4423088,
        ["Length"] = 115,
        ["Artist"] = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.1.0 Shadowlands",
        ["Song"] = "Revendreth Sired B",
        ["Name"] = "sound\\music\\shadowlands\\mus_91_revendreth_sired_b.mp3",
        ["Id"] = 4198447,
        ["Length"] = 114,
        ["Artist"] = "Jake Lefkowitz",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Shadow Domination Battle A",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_shadow_domination_battle_a.mp3",
        ["Id"] = 3850487,
        ["Length"] = 112,
        ["Artist"] = "Neal Acree",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Shadow Domination Battle B",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_shadow_domination_battle_b.mp3",
        ["Id"] = 3850489,
        ["Length"] = 110,
        ["Artist"] = "Neal Acree",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Shadow Domination Battle C",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_shadow_domination_battle_c.mp3",
        ["Id"] = 3850491,
        ["Length"] = 110,
        ["Artist"] = "Neal Acree",
        ["Wow"] = "true",
    },
    {
        ["Album"] = "WoW 9.0.0 Shadowlands",
        ["Song"] = "Shadow Domination Battle H",
        ["Name"] = "sound\\music\\shadowlands\\mus_90_shadow_domination_battle_h.mp3",
        ["Id"] = 3850493,
        ["Length"] = 110,
        ["Artist"] = "Neal Acree",
        ["Wow"] = "true",
    },
}