local EpicMusicPlayer = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer", true)
if not EpicMusicPlayer then return end

local list  -- forward declare once

-- playlist metadata
local listName         = "SL Essentials 3"
local expansion        = 8
local playlistVersion  = "4.0"

if _G.LE_EXPANSION_LEVEL_CURRENT >= expansion then
    -- defer loading until the player is in the world:
    local f = CreateFrame("Frame")
    f:RegisterEvent("PLAYER_ENTERING_WORLD")
    f:SetScript("OnEvent", function(self, event)
        if list then
            EpicMusicPlayer:AddPlayList(list)
        end
        self:UnregisterEvent(event)
        self:SetScript("OnEvent", nil)
    end)
end

list = {
	["listName"] = listName,
	["playlistVersion"] = playlistVersion,
	["locked"] =  "true",
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "To Be Kyrian A",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_a.mp3",
		["Id"] =  3853486,
		["Length"] = 125,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "To be kyrian B",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_b.mp3",
		["Id"] =  3853488,
		["Length"] = 111,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "To Be Kyrian Doubt H",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_doubt_h.mp3",
		["Id"] =  3853508,
		["Length"] = 194,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "To Be Kyrian E",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_e.mp3",
		["Id"] =  3853522,
		["Length"] = 113,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "To Be Kyrian F",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_f.mp3",
		["Id"] =  3853524,
		["Length"] = 136,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "To Be Kyrian G",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_g.mp3",
		["Id"] =  3853526,
		["Length"] = 109,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "To Be Kyrian H",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_h.mp3",
		["Id"] =  3853528,
		["Length"] = 366,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "To Be Kyrian I",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_i.mp3",
		["Id"] =  3853530,
		["Length"] = 118,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "To Be Kyrian J",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_j.mp3",
		["Id"] =  3853532,
		["Length"] = 121,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "To Be Kyrian O",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_o.mp3",
		["Id"] =  3853534,
		["Length"] = 137,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "To Be Kyrian R",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_tobekyrian_r.mp3",
		["Id"] =  3853540,
		["Length"] = 111,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Utherconfront",
		["Name"] = "sound\\music\\shadowlands\\mus_90_utherconfront.mp3",
		["Id"] =  3931066,
		["Length"] = 164,
		["Artist"] = "Glenn Stafford, Tracy Bush",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.1.0 Shadowlands",
		["Song"] = "Revendreth Sired A",
		["Name"] = "sound\\music\\shadowlands\\mus_91_revendreth_sired_a.mp3",
		["Id"] =  4198445,
		["Length"] = 98,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.1.0 Shadowlands",
		["Song"] = "Revendreth Sired B",
		["Name"] = "sound\\music\\shadowlands\\mus_91_revendreth_sired_b.mp3",
		["Id"] =  4198447,
		["Length"] = 114,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.1.0 Shadowlands",
		["Song"] = "Revendreth Sired C",
		["Name"] = "sound\\music\\shadowlands\\mus_91_revendreth_sired_c.mp3",
		["Id"] =  4198449,
		["Length"] = 99,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.1.0 Shadowlands",
		["Song"] = "Revendreth Sired D",
		["Name"] = "sound\\music\\shadowlands\\mus_91_revendreth_sired_d.mp3",
		["Id"] =  4198451,
		["Length"] = 99,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.1.0 Shadowlands",
		["Song"] = "Revendreth Sired H",
		["Name"] = "sound\\music\\shadowlands\\mus_91_revendreth_sired_h.mp3",
		["Id"] =  4198453,
		["Length"] = 126,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.2.0 Shadowlands",
		["Song"] = "Domination Anduin Action A",
		["Name"] = "sound\\music\\shadowlands\\mus_92_domination_anduin_action_a.mp3",
		["Id"] =  4423076,
		["Length"] = 103,
		["Artist"] = "Neal Acree",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.2.0 Shadowlands",
		["Song"] = "Domination Anduin Action B",
		["Name"] = "sound\\music\\shadowlands\\mus_92_domination_anduin_action_b.mp3",
		["Id"] =  4423078,
		["Length"] = 105,
		["Artist"] = "Neal Acree",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.2.0 Shadowlands",
		["Song"] = "Domination Anduin Action C",
		["Name"] = "sound\\music\\shadowlands\\mus_92_domination_anduin_action_c.mp3",
		["Id"] =  4423080,
		["Length"] = 105,
		["Artist"] = "Neal Acree",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Choice Oblivion Dark Domination",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_choice_oblivion_dark_domination.mp3",
		["Id"] =  3857085,
		["Length"] = 140,
		["Artist"] = "David Arkenstone, Neal Acree, Glenn Stafford",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nightfae A",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nightfae_a.mp3",
		["Id"] =  3853282,
		["Length"] = 114,
		["Artist"] = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nightfae B",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nightfae_b.mp3",
		["Id"] =  3853284,
		["Length"] = 119,
		["Artist"] = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nightfae C",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nightfae_c.mp3",
		["Id"] =  3853286,
		["Length"] = 130,
		["Artist"] = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nightfae D",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nightfae_d.mp3",
		["Id"] =  3853288,
		["Length"] = 123,
		["Artist"] = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nightfae F",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nightfae_f.mp3",
		["Id"] =  3853290,
		["Length"] = 101,
		["Artist"] = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nightfae H",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nightfae_h.mp3",
		["Id"] =  3853294,
		["Length"] = 171,
		["Artist"] = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nightfae I",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nightfae_i.mp3",
		["Id"] =  3853296,
		["Length"] = 122,
		["Artist"] = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nightfae J",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nightfae_j.mp3",
		["Id"] =  3853304,
		["Length"] = 126,
		["Artist"] = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nightfae K",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nightfae_k.mp3",
		["Id"] =  3853306,
		["Length"] = 145,
		["Artist"] = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nightfae L",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nightfae_l.mp3",
		["Id"] =  3853308,
		["Length"] = 103,
		["Artist"] = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nightfae M",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nightfae_m.mp3",
		["Id"] =  3853310,
		["Length"] = 132,
		["Artist"] = "David Arkenstone, Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Celestial A",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_a.mp3",
		["Id"] =  3853312,
		["Length"] = 122,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Celestial B",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_b.mp3",
		["Id"] =  3853314,
		["Length"] = 122,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Celestial C",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_c.mp3",
		["Id"] =  3853316,
		["Length"] = 132,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Celestial D",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_d.mp3",
		["Id"] =  3853318,
		["Length"] = 132,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Celestial E",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_e.mp3",
		["Id"] =  3853320,
		["Length"] = 118,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Celestial H",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_h.mp3",
		["Id"] =  3853322,
		["Length"] = 122,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Celestial I",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_i.mp3",
		["Id"] =  3853324,
		["Length"] = 103,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Celestial J",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_j.mp3",
		["Id"] =  3853326,
		["Length"] = 125,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Celestial K",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_k.mp3",
		["Id"] =  3853328,
		["Length"] = 113,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Celestial L",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_l.mp3",
		["Id"] =  3853330,
		["Length"] = 113,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Celestial M",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_celestial_m.mp3",
		["Id"] =  3853332,
		["Length"] = 125,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Devious A",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_devious_a.mp3",
		["Id"] =  3853334,
		["Length"] = 123,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Devious H",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_devious_h.mp3",
		["Id"] =  3853348,
		["Length"] = 123,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Hollow A",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_hollow_a.mp3",
		["Id"] =  3853354,
		["Length"] = 160,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Hollow B",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_hollow_b.mp3",
		["Id"] =  3853356,
		["Length"] = 158,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Hollow C",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_hollow_c.mp3",
		["Id"] =  3853358,
		["Length"] = 158,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Hollow D",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_hollow_d.mp3",
		["Id"] =  3853360,
		["Length"] = 156,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Hollow E",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_hollow_e.mp3",
		["Id"] =  3853362,
		["Length"] = 156,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Hollow H",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_hollow_h.mp3",
		["Id"] =  3853364,
		["Length"] = 156,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Hunger A",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_hunger_a.mp3",
		["Id"] =  3853366,
		["Length"] = 135,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Hunger H",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_hunger_h.mp3",
		["Id"] =  3853376,
		["Length"] = 137,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Melancholy Dream A",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_a.mp3",
		["Id"] =  3853378,
		["Length"] = 143,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Melancholy Dream B",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_b.mp3",
		["Id"] =  3853380,
		["Length"] = 143,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Melancholy Dream C",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_c.mp3",
		["Id"] =  3853382,
		["Length"] = 122,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Melancholy Dream D",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_d.mp3",
		["Id"] =  3853384,
		["Length"] = 122,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Melancholy Dream E",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_e.mp3",
		["Id"] =  3853386,
		["Length"] = 131,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Melancholy Dream F",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_f.mp3",
		["Id"] =  3853388,
		["Length"] = 133,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Melancholy Dream H",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_h.mp3",
		["Id"] =  3853390,
		["Length"] = 122,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Melancholy Dream I",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_i.mp3",
		["Id"] =  3853392,
		["Length"] = 122,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Melancholy Dream K",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_k.mp3",
		["Id"] =  3853394,
		["Length"] = 109,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Melancholy Dream M",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_melancholy_dream_m.mp3",
		["Id"] =  3853398,
		["Length"] = 102,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Nocturne Mischief H",
		["Name"] = "sound\\music\\shadowlands\\mus_90_aw_nocturne_mischief_h.mp3",
		["Id"] =  3853406,
		["Length"] = 117,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Aspirantsjourney Doubt Domination",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_aspirantsjourney_doubt_domination.mp3",
		["Id"] =  3857093,
		["Length"] = 114,
		["Artist"] = "Glenn Stafford, Neal Acree, David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Kyrian A",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_kyrian_a.mp3",
		["Id"] =  3853456,
		["Length"] = 149,
		["Artist"] = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Kyrian B",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_kyrian_b.mp3",
		["Id"] =  3853458,
		["Length"] = 149,
		["Artist"] = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Kyrian C",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_kyrian_c.mp3",
		["Id"] =  3853460,
		["Length"] = 121,
		["Artist"] = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Kyrian D",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_kyrian_d.mp3",
		["Id"] =  3853462,
		["Length"] = 128,
		["Artist"] = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Kyrian E",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_kyrian_e.mp3",
		["Id"] =  3853464,
		["Length"] = 136,
		["Artist"] = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Kyrian F",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_kyrian_f.mp3",
		["Id"] =  3853466,
		["Length"] = 135,
		["Artist"] = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Kyrian G",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_kyrian_g.mp3",
		["Id"] =  3853468,
		["Length"] = 109,
		["Artist"] = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Kyrian H",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_kyrian_h.mp3",
		["Id"] =  3853470,
		["Length"] = 239,
		["Artist"] = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Kyrian I",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_kyrian_i.mp3",
		["Id"] =  3853472,
		["Length"] = 152,
		["Artist"] = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Kyrian J",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_kyrian_j.mp3",
		["Id"] =  3853480,
		["Length"] = 116,
		["Artist"] = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Kyrian K",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_kyrian_k.mp3",
		["Id"] =  3853482,
		["Length"] = 106,
		["Artist"] = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Kyrian L",
		["Name"] = "sound\\music\\shadowlands\\mus_90_ba_kyrian_l.mp3",
		["Id"] =  3853550,
		["Length"] = 133,
		["Artist"] = "Glenn Stafford, Jake Lefkowitz",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Hopeabandoned Domination",
		["Name"] = "sound\\music\\shadowlands\\mus_90_maw_hopeabandoned_domination.mp3",
		["Id"] =  3885313,
		["Length"] = 136,
		["Artist"] = "Grant Kirkhope, Neal Acree, David Arkenstone",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Themaw Ambient A",
		["Name"] = "sound\\music\\shadowlands\\mus_90_maw_themaw_ambient_a.mp3",
		["Id"] =  3919997,
		["Length"] = 121,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Themaw Ambient B",
		["Name"] = "sound\\music\\shadowlands\\mus_90_maw_themaw_ambient_b.mp3",
		["Id"] =  3919999,
		["Length"] = 124,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Themaw Ambient C",
		["Name"] = "sound\\music\\shadowlands\\mus_90_maw_themaw_ambient_c.mp3",
		["Id"] =  3920001,
		["Length"] = 126,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Themaw Ambient D",
		["Name"] = "sound\\music\\shadowlands\\mus_90_maw_themaw_ambient_d.mp3",
		["Id"] =  3920003,
		["Length"] = 116,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Themaw Ambient E",
		["Name"] = "sound\\music\\shadowlands\\mus_90_maw_themaw_ambient_e.mp3",
		["Id"] =  3920005,
		["Length"] = 114,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Themaw Ambient F",
		["Name"] = "sound\\music\\shadowlands\\mus_90_maw_themaw_ambient_f.mp3",
		["Id"] =  3920007,
		["Length"] = 118,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Torghast Action A",
		["Name"] = "sound\\music\\shadowlands\\mus_90_maw_torghast_action_a.mp3",
		["Id"] =  3853566,
		["Length"] = 129,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Torghast Action B",
		["Name"] = "sound\\music\\shadowlands\\mus_90_maw_torghast_action_b.mp3",
		["Id"] =  3853568,
		["Length"] = 106,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Torghast Action C",
		["Name"] = "sound\\music\\shadowlands\\mus_90_maw_torghast_action_c.mp3",
		["Id"] =  3853570,
		["Length"] = 126,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Torghast Action D",
		["Name"] = "sound\\music\\shadowlands\\mus_90_maw_torghast_action_d.mp3",
		["Id"] =  3853572,
		["Length"] = 122,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Torghast Action H",
		["Name"] = "sound\\music\\shadowlands\\mus_90_maw_torghast_action_h.mp3",
		["Id"] =  3853576,
		["Length"] = 129,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Torghast Ambient J",
		["Name"] = "sound\\music\\shadowlands\\mus_90_maw_torghast_ambient_j.mp3",
		["Id"] =  3931036,
		["Length"] = 115,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Torghast Ambient K",
		["Name"] = "sound\\music\\shadowlands\\mus_90_maw_torghast_ambient_k.mp3",
		["Id"] =  3931038,
		["Length"] = 102,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Torghast Ambient N",
		["Name"] = "sound\\music\\shadowlands\\mus_90_maw_torghast_ambient_n.mp3",
		["Id"] =  3931044,
		["Length"] = 104,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Sansprimus H",
		["Name"] = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_h.mp3",
		["Id"] =  3853678,
		["Length"] = 166,
		["Artist"] = "Glenn Stafford, Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Sansprimus Hero A",
		["Name"] = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_a.mp3",
		["Id"] =  3853680,
		["Length"] = 110,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Sansprimus Hero B",
		["Name"] = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_b.mp3",
		["Id"] =  3853682,
		["Length"] = 107,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Sansprimus Hero C",
		["Name"] = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_c.mp3",
		["Id"] =  3853684,
		["Length"] = 116,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Sansprimus Hero D",
		["Name"] = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_d.mp3",
		["Id"] =  3853686,
		["Length"] = 124,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Sansprimus Hero H",
		["Name"] = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_h.mp3",
		["Id"] =  3853688,
		["Length"] = 133,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Sansprimus M",
		["Name"] = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_m.mp3",
		["Id"] =  3853696,
		["Length"] = 102,
		["Artist"] = "Glenn Stafford, Grant Kirkhope",
		["WoW"] =  "None",
	},
	{
		["Album"] = "WoW 9.0.0 Shadowlands",
		["Song"] = "Sansprimus Paranoid F",
		["Name"] = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_paranoid_f.mp3",
		["Id"] =  3853708,
		["Length"] = 101,
		["Artist"] = "Glenn Stafford, Grant Kirkhope",
		["WoW"] =  "None",
	},
}