local L = LibStub("AceLocale-3.0"):GetLocale("EpicMusicPlayer")

local playlist3 = {
	["listName"] = L["Battle for Azeroth"],
	["playlistVersion"] = "3.1",
	["playlistType"] = "generated",
	{
		["Album"] = "WoW7.3.5",
		["Song"] = "mus_735_pointofimpact_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_735_pointofimpact_a.mp3",
    ["Id"] = 1862322,
		["Length"] = 134,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW7.3.5",
		["Song"] = "mus_735_pointofimpact_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_735_pointofimpact_b.mp3",
    ["Id"] = 1862323,
		["Length"] = 143,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW7.3.5",
		["Song"] = "mus_735_pointofimpact_battle_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_735_pointofimpact_battle_h.mp3",
    ["Id"] = 1862324,
		["Length"] = 127,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW7.3.5",
		["Song"] = "mus_735_pointofimpact_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_735_pointofimpact_c.mp3",
    ["Id"] = 1862325,
		["Length"] = 163,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW7.3.5",
		["Song"] = "mus_735_pointofimpact_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_735_pointofimpact_d.mp3",
    ["Id"] = 1862326,
		["Length"] = 143,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW7.3.5",
		["Song"] = "mus_735_pointofimpact_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_735_pointofimpact_h.mp3",
    ["Id"] = 1862327,
		["Length"] = 144,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_alliancevictory_3_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_alliancevictory_3_h.mp3",
    ["Id"] = 2146576,
		["Length"] = 21,
		["Artist"] = "Glenn Stafford, Jason Hayes, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ashvanecompany_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ashvanecompany_a.mp3",
    ["Id"] = 2143489,
		["Length"] = 125,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ashvanecompany_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ashvanecompany_b.mp3",
    ["Id"] = 2143491,
		["Length"] = 108,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ashvanecompany_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ashvanecompany_c.mp3",
    ["Id"] = 2143492,
		["Length"] = 108,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ashvanecompany_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ashvanecompany_d.mp3",
    ["Id"] = 2143493,
		["Length"] = 132,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ashvanecompany_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ashvanecompany_e.mp3",
    ["Id"] = 2143494,
		["Length"] = 132,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ashvanecompany_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ashvanecompany_h.mp3",
    ["Id"] = 2143495,
		["Length"] = 125,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ataldazar_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ataldazar_a.mp3",
    ["Id"] = 2146227,
		["Length"] = 93,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ataldazar_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ataldazar_b.mp3",
    ["Id"] = 2146228,
		["Length"] = 93,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ataldazar_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ataldazar_c.mp3",
    ["Id"] = 2146229,
		["Length"] = 93,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ataldazar_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ataldazar_d.mp3",
    ["Id"] = 2146230,
		["Length"] = 93,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ataldazar_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ataldazar_h.mp3",
    ["Id"] = 2146231,
		["Length"] = 93,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_beforethestorm_maintitle",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_beforethestorm_maintitle.mp3",
    ["Id"] = 2146580,
		["Length"] = 677,
		["Artist"] = "Glenn Stafford, Neal Acree, Sam Cardon, Clint Bajakian, David Arkenstone, Leo Kaliski, Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_bloodmagic_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_bloodmagic_a.mp3",
    ["Id"] = 2150454,
		["Length"] = 89,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_bloodmagic_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_bloodmagic_b.mp3",
    ["Id"] = 1780904,
		["Length"] = 89,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_bloodmagic_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_bloodmagic_c.mp3",
    ["Id"] = 1780905,
		["Length"] = 89,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_bloodmagic_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_bloodmagic_h.mp3",
    ["Id"] = 1780908,
		["Length"] = 89,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_bloodsacrifice_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_bloodsacrifice_a.mp3",
    ["Id"] = 1780909,
		["Length"] = 99,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_bloodsacrifice_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_bloodsacrifice_b.mp3",
    ["Id"] = 1780910,
		["Length"] = 99,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_bloodsacrifice_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_bloodsacrifice_c.mp3",
    ["Id"] = 2146232,
		["Length"] = 99,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_bloodsacrifice_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_bloodsacrifice_d.mp3",
    ["Id"] = 2146233,
		["Length"] = 99,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_bloodsacrifice_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_bloodsacrifice_h.mp3",
    ["Id"] = 1780911,
		["Length"] = 99,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_boralus_intro",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_boralus_intro.mp3",
    ["Id"] = 2175189,
		["Length"] = 26,
		["Artist"] = "Sam Cardon, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_cityofgold_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_cityofgold_a.mp3",
    ["Id"] = 2146234,
		["Length"] = 81,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_cityofgold_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_cityofgold_b.mp3",
    ["Id"] = 2146235,
		["Length"] = 81,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_cityofgold_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_cityofgold_h.mp3",
    ["Id"] = 2146236,
		["Length"] = 81,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_classicbattle_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_classicbattle_a.mp3",
    ["Id"] = 2146581,
		["Length"] = 163,
		["Artist"] = "Glenn Stafford, Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_classicbattle_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_classicbattle_b.mp3",
    ["Id"] = 2146582,
		["Length"] = 164,
		["Artist"] = "Glenn Stafford, Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_classicbattle_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_classicbattle_c.mp3",
    ["Id"] = 2148018,
		["Length"] = 102,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_classicbattle_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_classicbattle_d.mp3",
    ["Id"] = 2148019,
		["Length"] = 87,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_classicbattle_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_classicbattle_e.mp3",
    ["Id"] = 2148020,
		["Length"] = 92,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_classicbattle_f",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_classicbattle_f.mp3",
    ["Id"] = 2148021,
		["Length"] = 102,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_classicbattle_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_classicbattle_h.mp3",
    ["Id"] = 2146583,
		["Length"] = 163,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_crimsonforest_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_crimsonforest_a.mp3",
    ["Id"] = 2144113,
		["Length"] = 213,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_crimsonforest_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_crimsonforest_b.mp3",
    ["Id"] = 2144114,
		["Length"] = 133,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_crimsonforest_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_crimsonforest_c.mp3",
    ["Id"] = 2144115,
		["Length"] = 133,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_crimsonforest_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_crimsonforest_h.mp3",
    ["Id"] = 2144116,
		["Length"] = 135,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_crimsonrise_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_crimsonrise_a.mp3",
    ["Id"] = 2143496,
		["Length"] = 76,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_crimsonrise_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_crimsonrise_b.mp3",
    ["Id"] = 2143497,
		["Length"] = 76,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_crimsonrise_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_crimsonrise_c.mp3",
    ["Id"] = 2143498,
		["Length"] = 76,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_crimsonrise_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_crimsonrise_d.mp3",
    ["Id"] = 2143499,
		["Length"] = 76,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_crimsonrise_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_crimsonrise_h.mp3",
    ["Id"] = 2143500,
		["Length"] = 76,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_darkirondwarves_1_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_darkirondwarves_1_a.mp3",
    ["Id"] = 2146584,
		["Length"] = 21,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_darkirondwarves_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_darkirondwarves_1_h.mp3",
    ["Id"] = 2146585,
		["Length"] = 21,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_darkirondwarves_2_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_darkirondwarves_2_a.mp3",
    ["Id"] = 2146586,
		["Length"] = 14,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_darkirondwarves_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_darkirondwarves_2_h.mp3",
    ["Id"] = 2146587,
		["Length"] = 14,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_darkirondwarves_3_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_darkirondwarves_3_a.mp3",
    ["Id"] = 2146588,
		["Length"] = 36,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_darkirondwarves_3_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_darkirondwarves_3_h.mp3",
    ["Id"] = 2146589,
		["Length"] = 36,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_darkirondwarves_4_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_darkirondwarves_4_a.mp3",
    ["Id"] = 2146590,
		["Length"] = 46,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_darkirondwarves_4_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_darkirondwarves_4_h.mp3",
    ["Id"] = 2146591,
		["Length"] = 47,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_divebar_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_divebar_a.mp3",
    ["Id"] = 2180702,
		["Length"] = 120,
		["Artist"] = "Sam Cardon, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_divebar_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_divebar_b.mp3",
    ["Id"] = 2180703,
		["Length"] = 86,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_divebar_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_divebar_c.mp3",
    ["Id"] = 2180704,
		["Length"] = 108,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_drustvar_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_drustvar_a.mp3",
    ["Id"] = 1780912,
		["Length"] = 165,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_drustvar_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_drustvar_b.mp3",
    ["Id"] = 1780913,
		["Length"] = 164,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_drustvar_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_drustvar_c.mp3",
    ["Id"] = 2146592,
		["Length"] = 167,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_drustvar_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_drustvar_h.mp3",
    ["Id"] = 1780914,
		["Length"] = 165,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_freeholdcombat_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_freeholdcombat_a.mp3",
    ["Id"] = 2146593,
		["Length"] = 90,
		["Artist"] = "Glenn Stafford, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_freeholdcombat_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_freeholdcombat_h.mp3",
    ["Id"] = 2146594,
		["Length"] = 90,
		["Artist"] = "Glenn Stafford, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_freehold_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_freehold_a.mp3",
    ["Id"] = 1780915,
		["Length"] = 107,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_freehold_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_freehold_b.mp3",
    ["Id"] = 1780916,
		["Length"] = 125,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_freehold_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_freehold_h.mp3",
    ["Id"] = 1780917,
		["Length"] = 125,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_glenbrookwoods_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_glenbrookwoods_a.mp3",
    ["Id"] = 1780918,
		["Length"] = 119,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_glenbrookwoods_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_glenbrookwoods_b.mp3",
    ["Id"] = 1780919,
		["Length"] = 118,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_glenbrookwoods_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_glenbrookwoods_c.mp3",
    ["Id"] = 2146595,
		["Length"] = 43,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_glenbrookwoods_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_glenbrookwoods_d.mp3",
    ["Id"] = 2146596,
		["Length"] = 72,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_glenbrookwoods_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_glenbrookwoods_h.mp3",
    ["Id"] = 1780920,
		["Length"] = 118,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_goblingreed_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_goblingreed_a.mp3",
    ["Id"] = 2145659,
		["Length"] = 103,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_goblingreed_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_goblingreed_b.mp3",
    ["Id"] = 2145660,
		["Length"] = 94,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_goblingreed_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_goblingreed_c.mp3",
    ["Id"] = 2145661,
		["Length"] = 103,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_goblingreed_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_goblingreed_d.mp3",
    ["Id"] = 2145662,
		["Length"] = 94,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_goblingreed_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_goblingreed_e.mp3",
    ["Id"] = 2145663,
		["Length"] = 193,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_goblingreed_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_goblingreed_h.mp3",
    ["Id"] = 2145664,
		["Length"] = 193,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_heartofsethraliss_1_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_heartofsethraliss_1_a.mp3",
    ["Id"] = 2146597,
		["Length"] = 56,
		["Artist"] = "Glenn Stafford, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_heartofsethraliss_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_heartofsethraliss_1_h.mp3",
    ["Id"] = 2146598,
		["Length"] = 56,
		["Artist"] = "Glenn Stafford, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_heartofsethraliss_2_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_heartofsethraliss_2_a.mp3",
    ["Id"] = 2146599,
		["Length"] = 64,
		["Artist"] = "Glenn Stafford, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_heartofsethraliss_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_heartofsethraliss_2_h.mp3",
    ["Id"] = 2146600,
		["Length"] = 64,
		["Artist"] = "Glenn Stafford, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_hordevictory_3_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_hordevictory_3_h.mp3",
    ["Id"] = 2146606,
		["Length"] = 19,
		["Artist"] = "Glenn Stafford, Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_houseashvane_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_houseashvane_a.mp3",
    ["Id"] = 2146237,
		["Length"] = 113,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_houseashvane_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_houseashvane_h.mp3",
    ["Id"] = 2146238,
		["Length"] = 112,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_housewaycrest_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_housewaycrest_a.mp3",
    ["Id"] = 1780921,
		["Length"] = 112,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_housewaycrest_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_housewaycrest_b.mp3",
    ["Id"] = 1780922,
		["Length"] = 97,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_housewaycrest_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_housewaycrest_c.mp3",
    ["Id"] = 1780923,
		["Length"] = 97,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_housewaycrest_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_housewaycrest_h.mp3",
    ["Id"] = 1780924,
		["Length"] = 97,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_adventure_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_adventure_a.mp3",
    ["Id"] = 2146607,
		["Length"] = 85,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_adventure_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_adventure_b.mp3",
    ["Id"] = 2148002,
		["Length"] = 115,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_adventure_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_adventure_c.mp3",
    ["Id"] = 2148003,
		["Length"] = 101,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_adventure_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_adventure_d.mp3",
    ["Id"] = 2148004,
		["Length"] = 105,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_adventure_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_adventure_e.mp3",
    ["Id"] = 2148005,
		["Length"] = 102,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_adventure_f",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_adventure_f.mp3",
    ["Id"] = 2148006,
		["Length"] = 100,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_adventure_h1",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_adventure_h1.mp3",
    ["Id"] = 2146608,
		["Length"] = 92,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_adventure_h2",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_adventure_h2.mp3",
    ["Id"] = 2146609,
		["Length"] = 92,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_mystical_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_mystical_a.mp3",
    ["Id"] = 2146613,
		["Length"] = 157,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_mystical_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_mystical_b.mp3",
    ["Id"] = 2146614,
		["Length"] = 157,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_mystical_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_mystical_c.mp3",
    ["Id"] = 2167269,
		["Length"] = 71,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_mystical_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_mystical_d.mp3",
    ["Id"] = 2167270,
		["Length"] = 47,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_mystical_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_mystical_e.mp3",
    ["Id"] = 2167271,
		["Length"] = 60,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_mystical_h1",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_mystical_h1.mp3",
    ["Id"] = 2146615,
		["Length"] = 157,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_mystical_h2",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_mystical_h2.mp3",
    ["Id"] = 2146616,
		["Length"] = 157,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_mystical_victory",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_mystical_victory.mp3",
    ["Id"] = 2167272,
		["Length"] = 14,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_winter_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_winter_a.mp3",
    ["Id"] = 2146617,
		["Length"] = 154,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_winter_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_winter_b.mp3",
    ["Id"] = 2146618,
		["Length"] = 154,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_winter_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_winter_c.mp3",
    ["Id"] = 2167273,
		["Length"] = 66,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_winter_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_winter_d.mp3",
    ["Id"] = 2167274,
		["Length"] = 90,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_winter_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_winter_h.mp3",
    ["Id"] = 2146619,
		["Length"] = 154,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_winter_victory",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_winter_victory.mp3",
    ["Id"] = 2167275,
		["Length"] = 18,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kthir_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kthir_a.mp3",
    ["Id"] = 2145665,
		["Length"] = 131,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kthir_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kthir_b.mp3",
    ["Id"] = 2145666,
		["Length"] = 131,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kthir_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kthir_c.mp3",
    ["Id"] = 2145667,
		["Length"] = 111,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kthir_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kthir_h.mp3",
    ["Id"] = 2145668,
		["Length"] = 131,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiran_highseas_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiran_highseas_a.mp3",
    ["Id"] = 1781897,
		["Length"] = 143,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiran_highseas_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiran_highseas_b.mp3",
    ["Id"] = 2146242,
		["Length"] = 143,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiran_highseas_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiran_highseas_h.mp3",
    ["Id"] = 1781896,
		["Length"] = 143,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiran_parley_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiran_parley_a.mp3",
    ["Id"] = 2146620,
		["Length"] = 64,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiran_parley_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiran_parley_b.mp3",
    ["Id"] = 2146621,
		["Length"] = 64,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiran_parley_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiran_parley_h.mp3",
    ["Id"] = 2146622,
		["Length"] = 64,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiran_parley_jukebox",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiran_parley_jukebox.mp3",
    ["Id"] = 2179261,
		["Length"] = 55,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_day_01",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_day_01.mp3",
    ["Id"] = 2144117,
		["Length"] = 78,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_day_04",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_day_04.mp3",
    ["Id"] = 2144120,
		["Length"] = 75,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_day_05",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_day_05.mp3",
    ["Id"] = 2144121,
		["Length"] = 82,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_day_08",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_day_08.mp3",
    ["Id"] = 2144124,
		["Length"] = 76,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_day_09",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_day_09.mp3",
    ["Id"] = 2144125,
		["Length"] = 77,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_night_02",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_night_02.mp3",
    ["Id"] = 2144128,
		["Length"] = 75,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_night_04",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_night_04.mp3",
    ["Id"] = 2144130,
		["Length"] = 72,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_night_05",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_night_05.mp3",
    ["Id"] = 2144131,
		["Length"] = 77,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_night_06",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_night_06.mp3",
    ["Id"] = 2144132,
		["Length"] = 82,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_night_09",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_night_09.mp3",
    ["Id"] = 2144135,
		["Length"] = 76,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_d.mp3",
    ["Id"] = 2144139,
		["Length"] = 132,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_day_02",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_day_02.mp3",
    ["Id"] = 2144141,
		["Length"] = 68,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_day_03",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_day_03.mp3",
    ["Id"] = 2144142,
		["Length"] = 68,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_day_04",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_day_04.mp3",
    ["Id"] = 2144143,
		["Length"] = 128,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_day_05",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_day_05.mp3",
    ["Id"] = 2144144,
		["Length"] = 92,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_day_06",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_day_06.mp3",
    ["Id"] = 2144145,
		["Length"] = 70,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_day_07",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_day_07.mp3",
    ["Id"] = 2144146,
		["Length"] = 141,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_night_01",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_night_01.mp3",
    ["Id"] = 2144150,
		["Length"] = 94,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_night_02",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_night_02.mp3",
    ["Id"] = 2144151,
		["Length"] = 92,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_night_04",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_night_04.mp3",
    ["Id"] = 2144153,
		["Length"] = 72,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_night_06",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_night_06.mp3",
    ["Id"] = 2144155,
		["Length"] = 141,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_night_10",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_night_10.mp3",
    ["Id"] = 2144159,
		["Length"] = 93,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_b.mp3",
    ["Id"] = 2144161,
		["Length"] = 151,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_day_03",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_day_03.mp3",
    ["Id"] = 2144164,
		["Length"] = 76,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_day_04",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_day_04.mp3",
    ["Id"] = 2144165,
		["Length"] = 76,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_day_10",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_day_10.mp3",
    ["Id"] = 2144171,
		["Length"] = 72,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_day_11",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_day_11.mp3",
    ["Id"] = 2144172,
		["Length"] = 72,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_day_12",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_day_12.mp3",
    ["Id"] = 2144173,
		["Length"] = 76,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_night_03",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_night_03.mp3",
    ["Id"] = 2144177,
		["Length"] = 70,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_night_04",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_night_04.mp3",
    ["Id"] = 2144178,
		["Length"] = 70,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_night_07",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_night_07.mp3",
    ["Id"] = 2144181,
		["Length"] = 72,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_night_09",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_night_09.mp3",
    ["Id"] = 2144183,
		["Length"] = 72,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_winter",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_winter.mp3",
    ["Id"] = 2180705,
		["Length"] = 40,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_akunda_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_akunda_a.mp3",
    ["Id"] = 2146244,
		["Length"] = 36,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_akunda_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_akunda_b.mp3",
    ["Id"] = 2146245,
		["Length"] = 36,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_akunda_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_akunda_c.mp3",
    ["Id"] = 2146246,
		["Length"] = 36,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_akunda_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_akunda_h.mp3",
    ["Id"] = 2146247,
		["Length"] = 36,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_bwonsamdi_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_bwonsamdi_c.mp3",
    ["Id"] = 2146250,
		["Length"] = 36,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_bwonsamdi_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_bwonsamdi_d.mp3",
    ["Id"] = 2146251,
		["Length"] = 36,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_bwonsamdi_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_bwonsamdi_h.mp3",
    ["Id"] = 2146252,
		["Length"] = 38,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_paku_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_paku_a.mp3",
    ["Id"] = 2146258,
		["Length"] = 41,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_paku_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_paku_d.mp3",
    ["Id"] = 2146261,
		["Length"] = 41,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_shadra_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_shadra_d.mp3",
    ["Id"] = 2146267,
		["Length"] = 55,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_shadra_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_shadra_h.mp3",
    ["Id"] = 2146268,
		["Length"] = 55,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_1_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_1_a.mp3",
    ["Id"] = 2143504,
		["Length"] = 109,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_1_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_1_b.mp3",
    ["Id"] = 2143505,
		["Length"] = 35,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_1_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_1_c.mp3",
    ["Id"] = 2143506,
		["Length"] = 56,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_1_h.mp3",
    ["Id"] = 2143507,
		["Length"] = 109,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_2_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_2_a.mp3",
    ["Id"] = 2143508,
		["Length"] = 59,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_2_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_2_b.mp3",
    ["Id"] = 2143509,
		["Length"] = 59,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_2_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_2_c.mp3",
    ["Id"] = 2143510,
		["Length"] = 60,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_2_h.mp3",
    ["Id"] = 2143511,
		["Length"] = 59,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_3_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_3_a.mp3",
    ["Id"] = 2143512,
		["Length"] = 42,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_3_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_3_b.mp3",
    ["Id"] = 2143513,
		["Length"] = 49,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_3_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_3_c.mp3",
    ["Id"] = 2143514,
		["Length"] = 79,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_3_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_3_h.mp3",
    ["Id"] = 2143515,
		["Length"] = 45,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_1_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_1_a.mp3",
    ["Id"] = 2143516,
		["Length"] = 80,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_1_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_1_b.mp3",
    ["Id"] = 2143517,
		["Length"] = 83,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_1_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_1_c.mp3",
    ["Id"] = 2143518,
		["Length"] = 78,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_1_h.mp3",
    ["Id"] = 2143519,
		["Length"] = 80,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_2_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_2_a.mp3",
    ["Id"] = 2143520,
		["Length"] = 80,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_2_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_2_b.mp3",
    ["Id"] = 2143521,
		["Length"] = 26,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_2_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_2_c.mp3",
    ["Id"] = 2143522,
		["Length"] = 55,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_2_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_2_d.mp3",
    ["Id"] = 2143523,
		["Length"] = 46,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_2_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_2_e.mp3",
    ["Id"] = 2143524,
		["Length"] = 95,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_2_h.mp3",
    ["Id"] = 2143525,
		["Length"] = 80,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_maghar_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_maghar_a.mp3",
    ["Id"] = 2146626,
		["Length"] = 244,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_maghar_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_maghar_b.mp3",
    ["Id"] = 2146627,
		["Length"] = 143,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_maghar_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_maghar_c.mp3",
    ["Id"] = 2146628,
		["Length"] = 143,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_maghar_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_maghar_d.mp3",
    ["Id"] = 2146629,
		["Length"] = 142,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_maghar_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_maghar_h.mp3",
    ["Id"] = 2146630,
		["Length"] = 142,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nagaincursion_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nagaincursion_a.mp3",
    ["Id"] = 2146631,
		["Length"] = 154,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nagaincursion_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nagaincursion_b.mp3",
    ["Id"] = 2146632,
		["Length"] = 154,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nagaincursion_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nagaincursion_c.mp3",
    ["Id"] = 2146633,
		["Length"] = 69,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nagaincursion_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nagaincursion_h.mp3",
    ["Id"] = 2146634,
		["Length"] = 154,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nazmirswamp_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nazmirswamp_a.mp3",
    ["Id"] = 2143526,
		["Length"] = 156,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nazmirswamp_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nazmirswamp_b.mp3",
    ["Id"] = 2143527,
		["Length"] = 103,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nazmirswamp_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nazmirswamp_c.mp3",
    ["Id"] = 2143528,
		["Length"] = 102,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nazmirswamp_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nazmirswamp_d.mp3",
    ["Id"] = 2143529,
		["Length"] = 93,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nazmirswamp_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nazmirswamp_e.mp3",
    ["Id"] = 2143530,
		["Length"] = 97,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nazmirswamp_f",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nazmirswamp_f.mp3",
    ["Id"] = 2143531,
		["Length"] = 126,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nazmirswamp_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nazmirswamp_h.mp3",
    ["Id"] = 2143532,
		["Length"] = 155,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_outlawharbor_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_outlawharbor_a.mp3",
    ["Id"] = 1780933,
		["Length"] = 172,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_outlawharbor_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_outlawharbor_b.mp3",
    ["Id"] = 1780934,
		["Length"] = 169,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_outlawharbor_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_outlawharbor_c.mp3",
    ["Id"] = 2146635,
		["Length"] = 173,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_outlawharbor_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_outlawharbor_h.mp3",
    ["Id"] = 1780935,
		["Length"] = 172,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_pointofimpact_pvp_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_pointofimpact_pvp_a.mp3",
    ["Id"] = 2145669,
		["Length"] = 72,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_pointofimpact_pvp_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_pointofimpact_pvp_b.mp3",
    ["Id"] = 2145670,
		["Length"] = 63,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_pointofimpact_pvp_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_pointofimpact_pvp_c.mp3",
    ["Id"] = 2145671,
		["Length"] = 49,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_pointofimpact_pvp_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_pointofimpact_pvp_d.mp3",
    ["Id"] = 2145672,
		["Length"] = 48,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_pointofimpact_pvp_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_pointofimpact_pvp_e.mp3",
    ["Id"] = 2145673,
		["Length"] = 32,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_pointofimpact_pvp_f",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_pointofimpact_pvp_f.mp3",
    ["Id"] = 2145674,
		["Length"] = 31,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_pointofimpact_pvp_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_pointofimpact_pvp_h.mp3",
    ["Id"] = 2145675,
		["Length"] = 125,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_quilboar_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_quilboar_a.mp3",
    ["Id"] = 2143533,
		["Length"] = 98,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_quilboar_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_quilboar_h.mp3",
    ["Id"] = 2143534,
		["Length"] = 97,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_ard",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_ard.mp3",
    ["Id"] = 2187938,
		["Length"] = 39,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_aro",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_aro.mp3",
    ["Id"] = 2187939,
		["Length"] = 36,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_bem",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_bem.mp3",
    ["Id"] = 2198101,
		["Length"] = 42,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_bog",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_bog.mp3",
    ["Id"] = 2198102,
		["Length"] = 68,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_btt",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_btt.mp3",
    ["Id"] = 2202584,
		["Length"] = 51,
		["Artist"] = "Jason Hayes, Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_kag",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_kag.mp3",
    ["Id"] = 2187940,
		["Length"] = 82,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_mhi",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_mhi.mp3",
    ["Id"] = 2187942,
		["Length"] = 39,
		["Artist"] = "Glenn Stafford, Adam Burgess",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_nlc",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_nlc.mp3",
    ["Id"] = 2198103,
		["Length"] = 80,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_sdb",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_sdb.mp3",
    ["Id"] = 2198104,
		["Length"] = 69,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_sha",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_sha.mp3",
    ["Id"] = 2198105,
		["Length"] = 52,
		["Artist"] = "Derek Duke, Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_sma",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_sma.mp3",
    ["Id"] = 2202582,
		["Length"] = 49,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_tsc",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_tsc.mp3",
    ["Id"] = 2187943,
		["Length"] = 68,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_tzf",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_tzf.mp3",
    ["Id"] = 2187944,
		["Length"] = 144,
		["Artist"] = "Neal Acree, Sam Cardon, David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_vmr",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_vmr.mp3",
    ["Id"] = 2198106,
		["Length"] = 78,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_ztc",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_ztc.mp3",
    ["Id"] = 2202583,
		["Length"] = 69,
		["Artist"] = "David Arkenstone, Sam Cardon, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_sethrak_1_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_sethrak_1_a.mp3",
    ["Id"] = 2146636,
		["Length"] = 70,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_sethrak_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_sethrak_1_h.mp3",
    ["Id"] = 2151743,
		["Length"] = 73,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_sethrak_2_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_sethrak_2_a.mp3",
    ["Id"] = 2146638,
		["Length"] = 74,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_sethrak_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_sethrak_2_h.mp3",
    ["Id"] = 2146639,
		["Length"] = 76,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_1_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_1_a.mp3",
    ["Id"] = 2145676,
		["Length"] = 16,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_1_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_1_b.mp3",
    ["Id"] = 2145677,
		["Length"] = 12,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_1_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_1_c.mp3",
    ["Id"] = 2145678,
		["Length"] = 30,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_1_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_1_d.mp3",
    ["Id"] = 2145679,
		["Length"] = 50,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_1_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_1_e.mp3",
    ["Id"] = 2145680,
		["Length"] = 50,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_1_h.mp3",
    ["Id"] = 2145681,
		["Length"] = 64,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_2_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_2_a.mp3",
    ["Id"] = 2145682,
		["Length"] = 75,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_2_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_2_b.mp3",
    ["Id"] = 2145683,
		["Length"] = 21,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_2_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_2_d.mp3",
    ["Id"] = 2145685,
		["Length"] = 38,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_2_h.mp3",
    ["Id"] = 2145686,
		["Length"] = 82,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_sirenssong_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_sirenssong_a.mp3",
    ["Id"] = 2146640,
		["Length"] = 64,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_sirenssong_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_sirenssong_b.mp3",
    ["Id"] = 2146641,
		["Length"] = 58,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_sirenssong_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_sirenssong_c.mp3",
    ["Id"] = 2146642,
		["Length"] = 57,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_sirenssong_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_sirenssong_h.mp3",
    ["Id"] = 2146644,
		["Length"] = 58,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_stormsong_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_stormsong_a.mp3",
    ["Id"] = 2150455,
		["Length"] = 300,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_stormsong_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_stormsong_b.mp3",
    ["Id"] = 2150456,
		["Length"] = 307,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_stormsong_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_stormsong_c.mp3",
    ["Id"] = 2150457,
		["Length"] = 179,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_stormsong_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_stormsong_d.mp3",
    ["Id"] = 2150458,
		["Length"] = 298,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_stormsong_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_stormsong_e.mp3",
    ["Id"] = 2150459,
		["Length"] = 160,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_stormsong_g",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_stormsong_g.mp3",
    ["Id"] = 2150461,
		["Length"] = 224,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_stormsong_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_stormsong_h.mp3",
    ["Id"] = 2150462,
		["Length"] = 297,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_thetortollan_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_thetortollan_a.mp3",
    ["Id"] = 2146271,
		["Length"] = 128,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_thetortollan_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_thetortollan_b.mp3",
    ["Id"] = 2146272,
		["Length"] = 128,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_thetortollan_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_thetortollan_c.mp3",
    ["Id"] = 2150463,
		["Length"] = 125,
		["Artist"] = "Sam Cardon, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_thetortollan_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_thetortollan_d.mp3",
    ["Id"] = 2150464,
		["Length"] = 75,
		["Artist"] = "Sam Cardon, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_thetortollan_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_thetortollan_h.mp3",
    ["Id"] = 2146273,
		["Length"] = 128,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_toldagor_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_toldagor_a.mp3",
    ["Id"] = 2143535,
		["Length"] = 86,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_toldagor_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_toldagor_b.mp3",
    ["Id"] = 2143536,
		["Length"] = 89,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_toldagor_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_toldagor_c.mp3",
    ["Id"] = 2143537,
		["Length"] = 86,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_toldagor_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_toldagor_d.mp3",
    ["Id"] = 2143538,
		["Length"] = 91,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_toldagor_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_toldagor_h.mp3",
    ["Id"] = 2143539,
		["Length"] = 91,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_vanquished_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_vanquished_a.mp3",
    ["Id"] = 1780941,
		["Length"] = 140,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_vanquished_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_vanquished_b.mp3",
    ["Id"] = 1780942,
		["Length"] = 140,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_vanquished_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_vanquished_c.mp3",
    ["Id"] = 2146274,
		["Length"] = 140,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_vanquished_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_vanquished_h.mp3",
    ["Id"] = 1780943,
		["Length"] = 140,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_voldun_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_voldun_a.mp3",
    ["Id"] = 2146275,
		["Length"] = 151,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_voldun_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_voldun_b.mp3",
    ["Id"] = 2150465,
		["Length"] = 150,
		["Artist"] = "Sam Cardon, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_voldun_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_voldun_c.mp3",
    ["Id"] = 2150466,
		["Length"] = 72,
		["Artist"] = "Sam Cardon, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_voldun_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_voldun_d.mp3",
    ["Id"] = 2150467,
		["Length"] = 92,
		["Artist"] = "Sam Cardon, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_voldun_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_voldun_e.mp3",
    ["Id"] = 2150468,
		["Length"] = 149,
		["Artist"] = "Sam Cardon, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_voldun_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_voldun_h.mp3",
    ["Id"] = 2146276,
		["Length"] = 151,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_vulpera_1_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_vulpera_1_b.mp3",
    ["Id"] = 2145688,
		["Length"] = 121,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_vulpera_1_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_vulpera_1_c.mp3",
    ["Id"] = 2145689,
		["Length"] = 95,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_vulpera_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_vulpera_1_h.mp3",
    ["Id"] = 2145690,
		["Length"] = 123,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_vulpera_2_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_vulpera_2_d.mp3",
    ["Id"] = 2179161,
		["Length"] = 39,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_vulpera_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_vulpera_2_h.mp3",
    ["Id"] = 2145694,
		["Length"] = 75,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_a.mp3",
    ["Id"] = 2146645,
		["Length"] = 135,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_b.mp3",
    ["Id"] = 2146646,
		["Length"] = 203,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_c.mp3",
    ["Id"] = 2146647,
		["Length"] = 129,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_d.mp3",
    ["Id"] = 2146648,
		["Length"] = 130,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_e.mp3",
    ["Id"] = 2146649,
		["Length"] = 129,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_f",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_f.mp3",
    ["Id"] = 2148022,
		["Length"] = 118,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_g",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_g.mp3",
    ["Id"] = 2148023,
		["Length"] = 88,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_h.mp3",
    ["Id"] = 2143540,
		["Length"] = 137,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_i",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_i.mp3",
    ["Id"] = 2148024,
		["Length"] = 95,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_j",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_j.mp3",
    ["Id"] = 2148025,
		["Length"] = 83,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_k",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_k.mp3",
    ["Id"] = 2148026,
		["Length"] = 89,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_l",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_l.mp3",
    ["Id"] = 2148027,
		["Length"] = 90,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_m",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_m.mp3",
    ["Id"] = 2148028,
		["Length"] = 97,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_n",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_n.mp3",
    ["Id"] = 2148029,
		["Length"] = 99,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_o",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_o.mp3",
    ["Id"] = 2148030,
		["Length"] = 85,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_p",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_p.mp3",
    ["Id"] = 2148031,
		["Length"] = 92,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_drust_1_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_drust_1_a.mp3",
    ["Id"] = 2146650,
		["Length"] = 48,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_drust_1_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_drust_1_b.mp3",
    ["Id"] = 2150469,
		["Length"] = 48,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_drust_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_drust_1_h.mp3",
    ["Id"] = 2146651,
		["Length"] = 48,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_drust_2_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_drust_2_a.mp3",
    ["Id"] = 2146652,
		["Length"] = 54,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_drust_2_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_drust_2_b.mp3",
    ["Id"] = 2150470,
		["Length"] = 54,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_drust_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_drust_2_h.mp3",
    ["Id"] = 2146653,
		["Length"] = 54,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_woods_1_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_woods_1_a.mp3",
    ["Id"] = 2146654,
		["Length"] = 43,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_woods_1_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_woods_1_b.mp3",
    ["Id"] = 2150471,
		["Length"] = 42,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_woods_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_woods_1_h.mp3",
    ["Id"] = 2146655,
		["Length"] = 43,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_woods_2_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_woods_2_a.mp3",
    ["Id"] = 2146656,
		["Length"] = 52,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_woods_2_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_woods_2_b.mp3",
    ["Id"] = 2150472,
		["Length"] = 52,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_woods_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_woods_2_h.mp3",
    ["Id"] = 2146657,
		["Length"] = 53,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestwedding_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestwedding_a.mp3",
    ["Id"] = 2203963,
		["Length"] = 38,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestwedding_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestwedding_b.mp3",
    ["Id"] = 2203964,
		["Length"] = 77,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_windrunner_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_windrunner_b.mp3",
    ["Id"] = 2146762,
		["Length"] = 72,
		["Artist"] = "Glenn Stafford, Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_windrunner_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_windrunner_c.mp3",
    ["Id"] = 2146763,
		["Length"] = 129,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_windrunner_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_windrunner_d.mp3",
    ["Id"] = 2146764,
		["Length"] = 81,
		["Artist"] = "Glenn Stafford, Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_windrunner_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_windrunner_e.mp3",
    ["Id"] = 2146765,
		["Length"] = 50,
		["Artist"] = "Glenn Stafford, Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_windrunner_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_windrunner_h.mp3",
    ["Id"] = 2146766,
		["Length"] = 129,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zandalarilament_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zandalarilament_a.mp3",
    ["Id"] = 1780948,
		["Length"] = 82,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zandalarilament_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zandalarilament_b.mp3",
    ["Id"] = 1780949,
		["Length"] = 82,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zandalarilament_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zandalarilament_h.mp3",
    ["Id"] = 1780950,
		["Length"] = 82,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarbazaar_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarbazaar_1_h.mp3",
    ["Id"] = 2143541,
		["Length"] = 148,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarbazaar_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarbazaar_2_h.mp3",
    ["Id"] = 2143542,
		["Length"] = 140,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarjungle_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_a.mp3",
    ["Id"] = 2143543,
		["Length"] = 159,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarjungle_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_e.mp3",
    ["Id"] = 2148033,
		["Length"] = 111,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarjungle_f",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_f.mp3",
    ["Id"] = 2148034,
		["Length"] = 117,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarjungle_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_h.mp3",
    ["Id"] = 2143546,
		["Length"] = 162,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarjungle_i",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_i.mp3",
    ["Id"] = 2148036,
		["Length"] = 122,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarjungle_l",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_l.mp3",
    ["Id"] = 2148039,
		["Length"] = 101,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarjungle_o",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_o.mp3",
    ["Id"] = 2148042,
		["Length"] = 92,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarjungle_q",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_q.mp3",
    ["Id"] = 2148044,
		["Length"] = 92,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazar_1_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazar_1_a.mp3",
    ["Id"] = 2146277,
		["Length"] = 72,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazar_1_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazar_1_b.mp3",
    ["Id"] = 2146278,
		["Length"] = 72,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazar_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazar_1_h.mp3",
    ["Id"] = 2146279,
		["Length"] = 72,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazar_2_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazar_2_a.mp3",
    ["Id"] = 2146280,
		["Length"] = 85,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazar_2_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazar_2_b.mp3",
    ["Id"] = 2146281,
		["Length"] = 85,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazar_2_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazar_2_c.mp3",
    ["Id"] = 2146282,
		["Length"] = 85,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazar_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazar_2_h.mp3",
    ["Id"] = 2146283,
		["Length"] = 85,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
}
local EpicMusicPlayer = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer")

if not EpicMusicPlayer then return end
EpicMusicPlayer:AddPlayList("Battle for Azeroth", playlist3, false, true)
