--Created by PlaylistCreator version 4.0
local EpicMusicPlayer = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer")
if not EpicMusicPlayer then return end

local playlist1 = {
	["listName"] = "Classic",
	["playlistVersion"] = "4.0",
	["locked"] =  "true",
	{
		["Album"] = "",
		["Song"] = "darnassus intro",
		["Name"] = "sound\\music\\citymusic\\darnassus\\darnassus intro.mp3",
    ["Id"] = 53183,
		["Length"] = 39,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "darnassus walking 1",
		["Name"] = "sound\\music\\citymusic\\darnassus\\darnassus walking 1.mp3",
    ["Id"] = 53184,
		["Length"] = 85,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "darnassus walking 2",
		["Name"] = "sound\\music\\citymusic\\darnassus\\darnassus walking 2.mp3",
    ["Id"] = 53185,
		["Length"] = 69,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "darnassus walking 3",
		["Name"] = "sound\\music\\citymusic\\darnassus\\darnassus walking 3.mp3",
    ["Id"] = 53186,
		["Length"] = 67,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "druid grove",
		["Name"] = "sound\\music\\citymusic\\darnassus\\druid grove.mp3",
    ["Id"] = 53187,
		["Length"] = 44,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "warrior terrace",
		["Name"] = "sound\\music\\citymusic\\darnassus\\warrior terrace.mp3",
    ["Id"] = 53188,
		["Length"] = 53,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "gnomeragon01-zone",
		["Name"] = "sound\\music\\citymusic\\gnomeragon\\gnomeragon01-zone.mp3",
    ["Id"] = 53189,
		["Length"] = 64,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "gnomeragon02-zone",
		["Name"] = "sound\\music\\citymusic\\gnomeragon\\gnomeragon02-zone.mp3",
    ["Id"] = 53190,
		["Length"] = 64,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "ironforge intro",
		["Name"] = "sound\\music\\citymusic\\ironforge\\ironforge intro.mp3",
    ["Id"] = 53191,
		["Length"] = 86,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "ironforge walking 01",
		["Name"] = "sound\\music\\citymusic\\ironforge\\ironforge walking 01.mp3",
    ["Id"] = 53192,
		["Length"] = 123,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "IronforgeWalking02",
		["Name"] = "sound\\music\\citymusic\\ironforge\\ironforge walking 02.mp3",
    ["Id"] = 53193,
		["Length"] = 50,
		["Artist"] = "Brian Farr",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "ironforge walking 03 (glenn)",
		["Name"] = "sound\\music\\citymusic\\ironforge\\ironforge walking 03 (glenn).mp3",
    ["Id"] = 53194,
		["Length"] = 81,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "ironforge walking 04",
		["Name"] = "sound\\music\\citymusic\\ironforge\\ironforge walking 04.mp3",
    ["Id"] = 53195,
		["Length"] = 70,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "tinkertownintro-moment",
		["Name"] = "sound\\music\\citymusic\\ironforge\\tinkertownintro_moment.mp3",
    ["Id"] = 53196,
		["Length"] = 51,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "orgrimmar01-moment",
		["Name"] = "sound\\music\\citymusic\\orgrimmar\\orgrimmar01-moment.mp3",
    ["Id"] = 53197,
		["Length"] = 68,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "orgrimmar01-zone",
		["Name"] = "sound\\music\\citymusic\\orgrimmar\\orgrimmar01-zone.mp3",
    ["Id"] = 53198,
		["Length"] = 68,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "orgrimmar02-moment",
		["Name"] = "sound\\music\\citymusic\\orgrimmar\\orgrimmar02-moment.mp3",
    ["Id"] = 53199,
		["Length"] = 62,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "orgrimmar02-zone",
		["Name"] = "sound\\music\\citymusic\\orgrimmar\\orgrimmar02-zone.mp3",
    ["Id"] = 53200,
		["Length"] = 62,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "Signpost- Ogrimmar",
		["Name"] = "sound\\music\\citymusic\\orgrimmar\\orgrimmar_intro-moment.mp3",
    ["Id"] = 53201,
		["Length"] = 40,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "stormwind02-moment",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind01-moment.mp3",
    ["Id"] = 53202,
		["Length"] = 54,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "stormwind01-moment",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind02-moment.mp3",
    ["Id"] = 53203,
		["Length"] = 35,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "stormwind03-moment",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind03-moment.mp3",
    ["Id"] = 53204,
		["Length"] = 69,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "stormwind04-zone",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind04-zone.mp3",
    ["Id"] = 53205,
		["Length"] = 62,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "stormwind05-zone",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind05-zone.mp3",
    ["Id"] = 53206,
		["Length"] = 60,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "stormwind06-live",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind06-zone.mp3",
    ["Id"] = 53207,
		["Length"] = 53,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "stormwind07-live",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind07-zone.mp3",
    ["Id"] = 53208,
		["Length"] = 86,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "stormwind08-zone",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind08-zone.mp3",
    ["Id"] = 53209,
		["Length"] = 77,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "stormwind_highseas-moment",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind_highseas-moment.mp3",
    ["Id"] = 53210,
		["Length"] = 133,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "stormwind_intro-moment",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind_intro-moment.mp3",
    ["Id"] = 53211,
		["Length"] = 66,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "thunderbluff intro",
		["Name"] = "sound\\music\\citymusic\\thunderbluff\\thunderbluff intro.mp3",
    ["Id"] = 53212,
		["Length"] = 46,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "thunderbluff walking 01",
		["Name"] = "sound\\music\\citymusic\\thunderbluff\\thunderbluff walking 01.mp3",
    ["Id"] = 53213,
		["Length"] = 117,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "thunderbluff walking 02",
		["Name"] = "sound\\music\\citymusic\\thunderbluff\\thunderbluff walking 02.mp3",
    ["Id"] = 53214,
		["Length"] = 116,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "thunderbluff walking 03",
		["Name"] = "sound\\music\\citymusic\\thunderbluff\\thunderbluff walking 03.mp3",
    ["Id"] = 53215,
		["Length"] = 121,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "undercity01-zone",
		["Name"] = "sound\\music\\citymusic\\undercity\\undercity01-zone.mp3",
    ["Id"] = 53216,
		["Length"] = 67,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "undercity02-zone",
		["Name"] = "sound\\music\\citymusic\\undercity\\undercity02-zone.mp3",
    ["Id"] = 53217,
		["Length"] = 85,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "undercity03_zone",
		["Name"] = "sound\\music\\citymusic\\undercity\\undercity03-zone.mp3",
    ["Id"] = 53218,
		["Length"] = 75,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "undercityintro-moment",
		["Name"] = "sound\\music\\citymusic\\undercity\\undercityintro-moment.mp3",
    ["Id"] = 53219,
		["Length"] = 28,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "wow_main_theme",
		["Name"] = "sound\\music\\gluescreenmusic\\wow_main_theme.mp3",
    ["Id"] = 53223,
		["Length"] = 161,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "ZulGurubVoodoo",
		["Name"] = "sound\\music\\musical moments\\zulgurubvoodoo.mp3",
    ["Id"] = 53254,
		["Length"] = 84,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "angelic01",
		["Name"] = "sound\\music\\musical moments\\angelic\\angelic01.mp3",
    ["Id"] = 53224,
		["Length"] = 47,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "battle01",
		["Name"] = "sound\\music\\musical moments\\battle\\battle01.mp3",
    ["Id"] = 53225,
		["Length"] = 48,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "battle02",
		["Name"] = "sound\\music\\musical moments\\battle\\battle02.mp3",
    ["Id"] = 53226,
		["Length"] = 62,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "battle03",
		["Name"] = "sound\\music\\musical moments\\battle\\battle03.mp3",
    ["Id"] = 53227,
		["Length"] = 27,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "battle04",
		["Name"] = "sound\\music\\musical moments\\battle\\battle04.mp3",
    ["Id"] = 53228,
		["Length"] = 36,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "battle05",
		["Name"] = "sound\\music\\musical moments\\battle\\battle05.mp3",
    ["Id"] = 53229,
		["Length"] = 44,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "battle06",
		["Name"] = "sound\\music\\musical moments\\battle\\battle06.mp3",
    ["Id"] = 53230,
		["Length"] = 62,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "gloomy01",
		["Name"] = "sound\\music\\musical moments\\gloomy\\gloomy01.mp3",
    ["Id"] = 53231,
		["Length"] = 36,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "gloomy02",
		["Name"] = "sound\\music\\musical moments\\gloomy\\gloomy02.mp3",
    ["Id"] = 53232,
		["Length"] = 39,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "haunted01",
		["Name"] = "sound\\music\\musical moments\\haunted\\haunted01.mp3",
    ["Id"] = 53234,
		["Length"] = 62,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "haunted02",
		["Name"] = "sound\\music\\musical moments\\haunted\\haunted02.mp3",
    ["Id"] = 53235,
		["Length"] = 60,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "magic01-moment",
		["Name"] = "sound\\music\\musical moments\\magic\\magic01-moment.mp3",
    ["Id"] = 53236,
		["Length"] = 63,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "magic01-zone1",
		["Name"] = "sound\\music\\musical moments\\magic\\magic01-zone1.mp3",
    ["Id"] = 53237,
		["Length"] = 33,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "magic01-zone2",
		["Name"] = "sound\\music\\musical moments\\magic\\magic01-zone2.mp3",
    ["Id"] = 53238,
		["Length"] = 39,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9",
		["Song"] = "Ahn Qiraj Theme",
		["Name"] = "sound\\music\\musical moments\\mystery\\ahnqirajintro1.mp3",
    ["Id"] = 53239,
		["Length"] = 143,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "mystery01-zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery01-zone.mp3",
    ["Id"] = 53240,
		["Length"] = 60,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "mystery02-zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery02-zone.mp3",
    ["Id"] = 53241,
		["Length"] = 53,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "mystery03-zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery03-zone.mp3",
    ["Id"] = 53242,
		["Length"] = 60,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "mystery04-zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery04-zone.mp3",
    ["Id"] = 53243,
		["Length"] = 64,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World Of Warcraft",
		["Song"] = "mystery05-zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery05-zone.mp3",
    ["Id"] = 53244,
		["Length"] = 81,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World Of Warcraft",
		["Song"] = "mystery06-zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery06-zone.mp3",
    ["Id"] = 53245,
		["Length"] = 65,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World Of Warcraft",
		["Song"] = "mystery07-zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery07-zone.mp3",
    ["Id"] = 53246,
		["Length"] = 83,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World Of Warcraft",
		["Song"] = "mystery08-zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery08-zone.mp3",
    ["Id"] = 53247,
		["Length"] = 83,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World Of Warcraft",
		["Song"] = "mystery09-zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery09-zone.mp3",
    ["Id"] = 53248,
		["Length"] = 82,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World Of Warcraft",
		["Song"] = "mystery10-zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery10-zone.mp3",
    ["Id"] = 53249,
		["Length"] = 62,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "monestary01",
		["Name"] = "sound\\music\\musical moments\\sacred\\sacred01.mp3",
    ["Id"] = 53250,
		["Length"] = 16,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "sacred02",
		["Name"] = "sound\\music\\musical moments\\sacred\\sacred02.mp3",
    ["Id"] = 53251,
		["Length"] = 19,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "spooky01-moment",
		["Name"] = "sound\\music\\musical moments\\spooky\\spooky01-moment.mp3",
    ["Id"] = 53252,
		["Length"] = 25,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "swamp01",
		["Name"] = "sound\\music\\musical moments\\swamp\\swamp01.mp3",
    ["Id"] = 53253,
		["Length"] = 34,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "DMFaire_1",
		["Name"] = "sound\\music\\worldevents\\darkmoonfaire_1.mp3",
    ["Id"] = 53256,
		["Length"] = 28,
		["Artist"] = "D. Arkenstone/R.Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "DMFaire_2",
		["Name"] = "sound\\music\\worldevents\\darkmoonfaire_2.mp3",
    ["Id"] = 53257,
		["Length"] = 74,
		["Artist"] = "D. Arkenstone/R.Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "DMFaire_3",
		["Name"] = "sound\\music\\worldevents\\darkmoonfaire_3.mp3",
    ["Id"] = 53258,
		["Length"] = 58,
		["Artist"] = "D. Arkenstone/R.Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "DMFaire_4",
		["Name"] = "sound\\music\\worldevents\\darkmoonfaire_4.mp3",
    ["Id"] = 53259,
		["Length"] = 37,
		["Artist"] = "D. Arkenstone/R.Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9",
		["Song"] = "Ahn Qiraj Exterior Walking 1",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajexteriorwalking1.mp3",
    ["Id"] = 53261,
		["Length"] = 67,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9",
		["Song"] = "Ahn Qiraj Exterior 2",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajexteriorwalking2.mp3",
    ["Id"] = 53262,
		["Length"] = 84,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9",
		["Song"] = "Ahn Qiraj Exterior 3",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajexteriorwalking3.mp3",
    ["Id"] = 53263,
		["Length"] = 57,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9",
		["Song"] = "Ahn Qiraj Exterior 4",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajexteriorwalking4.mp3",
    ["Id"] = 53264,
		["Length"] = 59,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9",
		["Song"] = "AQBreath1",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajinterior1.mp3",
    ["Id"] = 53265,
		["Length"] = 52,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9",
		["Song"] = "AQBreath2",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajinterior2.mp3",
    ["Id"] = 53266,
		["Length"] = 81,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9",
		["Song"] = "AQBreath3",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajinterior3.mp3",
    ["Id"] = 53267,
		["Length"] = 67,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9",
		["Song"] = "AhnQirajInteriorCenterRoom1",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajinteriorcenterroom1.mp3",
    ["Id"] = 53268,
		["Length"] = 69,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9",
		["Song"] = "Fireflies1",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajinteriorintromain.mp3",
    ["Id"] = 53269,
		["Length"] = 69,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9",
		["Song"] = "AQKingRoom",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajkingroom.mp3",
    ["Id"] = 53270,
		["Length"] = 73,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9",
		["Song"] = "AQTriangle1",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom1.mp3",
    ["Id"] = 53271,
		["Length"] = 23,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9",
		["Song"] = "AQTriangle2",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom2.mp3",
    ["Id"] = 53272,
		["Length"] = 17,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9",
		["Song"] = "AQTriangle3",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom3.mp3",
    ["Id"] = 53273,
		["Length"] = 15,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9",
		["Song"] = "AQTriangle4",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom4.mp3",
    ["Id"] = 53274,
		["Length"] = 19,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9",
		["Song"] = "AQTriangle5",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom5.mp3",
    ["Id"] = 53275,
		["Length"] = 31,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9",
		["Song"] = "AQTriangle6",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom6.mp3",
    ["Id"] = 53276,
		["Length"] = 20,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9",
		["Song"] = "AQTriangle7",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom7.mp3",
    ["Id"] = 53277,
		["Length"] = 17,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "daybarrendry01",
		["Name"] = "sound\\music\\zonemusic\\barrendry\\daybarrendry01.mp3",
    ["Id"] = 53299,
		["Length"] = 64,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "daybarrendry02",
		["Name"] = "sound\\music\\zonemusic\\barrendry\\daybarrendry02.mp3",
    ["Id"] = 53300,
		["Length"] = 64,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "DayBarrenDry03",
		["Name"] = "sound\\music\\zonemusic\\barrendry\\daybarrendry03.mp3",
    ["Id"] = 53301,
		["Length"] = 55,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "nightbarrendry01",
		["Name"] = "sound\\music\\zonemusic\\barrendry\\nightbarrendry01.mp3",
    ["Id"] = 53302,
		["Length"] = 67,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "nightbarrendry02",
		["Name"] = "sound\\music\\zonemusic\\barrendry\\nightbarrendry02.mp3",
    ["Id"] = 53303,
		["Length"] = 40,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "nightbarrendry03",
		["Name"] = "sound\\music\\zonemusic\\barrendry\\nightbarrendry03.mp3",
    ["Id"] = 53304,
		["Length"] = 47,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "Felwood_zone1",
		["Name"] = "sound\\music\\zonemusic\\cursedland\\cursedland01.mp3",
    ["Id"] = 53426,
		["Length"] = 54,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "cursedland02_zone",
		["Name"] = "sound\\music\\zonemusic\\cursedland\\cursedland02.mp3",
    ["Id"] = 53427,
		["Length"] = 58,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "cursedland03_zone",
		["Name"] = "sound\\music\\zonemusic\\cursedland\\cursedland03.mp3",
    ["Id"] = 53428,
		["Length"] = 64,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "cursedland04",
		["Name"] = "sound\\music\\zonemusic\\cursedland\\cursedland04.mp3",
    ["Id"] = 53429,
		["Length"] = 79,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "cursedland05",
		["Name"] = "sound\\music\\zonemusic\\cursedland\\cursedland05.mp3",
    ["Id"] = 53430,
		["Length"] = 82,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "cursedland06",
		["Name"] = "sound\\music\\zonemusic\\cursedland\\cursedland06.mp3",
    ["Id"] = 53431,
		["Length"] = 74,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "daydesert01",
		["Name"] = "sound\\music\\zonemusic\\desert\\daydesert01.mp3",
    ["Id"] = 53432,
		["Length"] = 65,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "daydesert02",
		["Name"] = "sound\\music\\zonemusic\\desert\\daydesert02.mp3",
    ["Id"] = 53433,
		["Length"] = 81,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "daydesert03",
		["Name"] = "sound\\music\\zonemusic\\desert\\daydesert03.mp3",
    ["Id"] = 53434,
		["Length"] = 54,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "nightdesert01",
		["Name"] = "sound\\music\\zonemusic\\desert\\nightdesert01.mp3",
    ["Id"] = 53435,
		["Length"] = 77,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "nightdesert02",
		["Name"] = "sound\\music\\zonemusic\\desert\\nightdesert02.mp3",
    ["Id"] = 53436,
		["Length"] = 62,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "nightdesert03",
		["Name"] = "sound\\music\\zonemusic\\desert\\nightdesert03.mp3",
    ["Id"] = 53437,
		["Length"] = 57,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "EnchantedForest01",
		["Name"] = "sound\\music\\zonemusic\\enchantedforest\\enchantedforest01.mp3",
    ["Id"] = 53453,
		["Length"] = 49,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "EnchantedForest02",
		["Name"] = "sound\\music\\zonemusic\\enchantedforest\\enchantedforest02.mp3",
    ["Id"] = 53454,
		["Length"] = 67,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "enchantedforest03",
		["Name"] = "sound\\music\\zonemusic\\enchantedforest\\enchantedforest03.mp3",
    ["Id"] = 53455,
		["Length"] = 234,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "EnchantedForest04",
		["Name"] = "sound\\music\\zonemusic\\enchantedforest\\enchantedforest04.mp3",
    ["Id"] = 53456,
		["Length"] = 60,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "EnchantedForest05",
		["Name"] = "sound\\music\\zonemusic\\enchantedforest\\enchantedforest05.mp3",
    ["Id"] = 53457,
		["Length"] = 70,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "DayEvilForest01",
		["Name"] = "sound\\music\\zonemusic\\evilforest\\dayevilforest01.mp3",
    ["Id"] = 53486,
		["Length"] = 70,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "DayEvilForest02",
		["Name"] = "sound\\music\\zonemusic\\evilforest\\dayevilforest02.mp3",
    ["Id"] = 53487,
		["Length"] = 72,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "DayEvilForest03",
		["Name"] = "sound\\music\\zonemusic\\evilforest\\dayevilforest03.mp3",
    ["Id"] = 53488,
		["Length"] = 70,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "NightEvilForest01",
		["Name"] = "sound\\music\\zonemusic\\evilforest\\nightevilforest01.mp3",
    ["Id"] = 53489,
		["Length"] = 57,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "NightEvilForest02",
		["Name"] = "sound\\music\\zonemusic\\evilforest\\nightevilforest02.mp3",
    ["Id"] = 53490,
		["Length"] = 75,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "NightEvilForest03",
		["Name"] = "sound\\music\\zonemusic\\evilforest\\nightevilforest03.mp3",
    ["Id"] = 53491,
		["Length"] = 70,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "DayForest01",
		["Name"] = "sound\\music\\zonemusic\\forest\\dayforest01.mp3",
    ["Id"] = 53492,
		["Length"] = 55,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "DayForest02",
		["Name"] = "sound\\music\\zonemusic\\forest\\dayforest02.mp3",
    ["Id"] = 53493,
		["Length"] = 72,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "DayForest03",
		["Name"] = "sound\\music\\zonemusic\\forest\\dayforest03.mp3",
    ["Id"] = 53494,
		["Length"] = 64,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "NightForest01",
		["Name"] = "sound\\music\\zonemusic\\forest\\nightforest01.mp3",
    ["Id"] = 53495,
		["Length"] = 53,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "NightForest02",
		["Name"] = "sound\\music\\zonemusic\\forest\\nightforest02.mp3",
    ["Id"] = 53496,
		["Length"] = 42,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "NightForest03",
		["Name"] = "sound\\music\\zonemusic\\forest\\nightforest03.mp3",
    ["Id"] = 53497,
		["Length"] = 59,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "NightForest04",
		["Name"] = "sound\\music\\zonemusic\\forest\\nightforest04.mp3",
    ["Id"] = 53498,
		["Length"] = 54,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "",
		["Song"] = "ghostmusic03",
		["Name"] = "sound\\music\\zonemusic\\ghostmusic\\ghostmusic03.mp3",
    ["Id"] = 53519,
		["Length"] = 62,
		["Artist"] = "",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "DayJungle01",
		["Name"] = "sound\\music\\zonemusic\\jungle\\dayjungle01.mp3",
    ["Id"] = 53541,
		["Length"] = 46,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "DayJungle02",
		["Name"] = "sound\\music\\zonemusic\\jungle\\dayjungle02.mp3",
    ["Id"] = 53542,
		["Length"] = 98,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "DayJungle03",
		["Name"] = "sound\\music\\zonemusic\\jungle\\dayjungle03.mp3",
    ["Id"] = 53543,
		["Length"] = 48,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "NightJungle01",
		["Name"] = "sound\\music\\zonemusic\\jungle\\nightjungle01.mp3",
    ["Id"] = 53544,
		["Length"] = 54,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "NightJungle02",
		["Name"] = "sound\\music\\zonemusic\\jungle\\nightjungle02.mp3",
    ["Id"] = 53545,
		["Length"] = 53,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "NightJungle03",
		["Name"] = "sound\\music\\zonemusic\\jungle\\nightjungle03.mp3",
    ["Id"] = 53546,
		["Length"] = 89,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "DayMountain01",
		["Name"] = "sound\\music\\zonemusic\\mountain\\daymountain01.mp3",
    ["Id"] = 53577,
		["Length"] = 120,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "daymountain02",
		["Name"] = "sound\\music\\zonemusic\\mountain\\daymountain02.mp3",
    ["Id"] = 53578,
		["Length"] = 66,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "daymountain03",
		["Name"] = "sound\\music\\zonemusic\\mountain\\daymountain03.mp3",
    ["Id"] = 53579,
		["Length"] = 80,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "NightMountain01",
		["Name"] = "sound\\music\\zonemusic\\mountain\\nightmountain01.mp3",
    ["Id"] = 53580,
		["Length"] = 64,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "NightMountain02",
		["Name"] = "sound\\music\\zonemusic\\mountain\\nightmountain02.mp3",
    ["Id"] = 53581,
		["Length"] = 63,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "NightMountain03",
		["Name"] = "sound\\music\\zonemusic\\mountain\\nightmountain03.mp3",
    ["Id"] = 53582,
		["Length"] = 69,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "NightMountain04",
		["Name"] = "sound\\music\\zonemusic\\mountain\\nightmountain04.mp3",
    ["Id"] = 53583,
		["Length"] = 63,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "AbominationBoss1",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasabominationboss1.mp3",
    ["Id"] = 53591,
		["Length"] = 61,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "AbominationBoss2",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasabominationboss2.mp3",
    ["Id"] = 53592,
		["Length"] = 67,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "AbominationWing1",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasabominationwing1.mp3",
    ["Id"] = 53593,
		["Length"] = 61,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "AbominationWing2",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasabominationwing2.mp3",
    ["Id"] = 53594,
		["Length"] = 66,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "AbominationWing3",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasabominationwing3.mp3",
    ["Id"] = 53595,
		["Length"] = 61,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "Frostwyrm1",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasfrostwyrm1.mp3",
    ["Id"] = 53596,
		["Length"] = 57,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "Frostwyrm2",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasfrostwyrm2.mp3",
    ["Id"] = 53597,
		["Length"] = 81,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "Frostwyrm3",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasfrostwyrm3.mp3",
    ["Id"] = 53598,
		["Length"] = 61,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "Frostwyrm4",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasfrostwyrm4.mp3",
    ["Id"] = 53599,
		["Length"] = 60,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "HubBase1",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramashubbase1.mp3",
    ["Id"] = 53600,
		["Length"] = 72,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "HubBase2",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramashubbase2.mp3",
    ["Id"] = 53601,
		["Length"] = 81,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "KelThuzad1A",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramaskelthuzad1.mp3",
    ["Id"] = 53602,
		["Length"] = 94,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "KelThuzad2A",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramaskelthuzad2.mp3",
    ["Id"] = 53603,
		["Length"] = 97,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "KelThuzad3A",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramaskelthuzad3.mp3",
    ["Id"] = 53604,
		["Length"] = 75,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "PlagueBoss1",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasplagueboss1.mp3",
    ["Id"] = 53605,
		["Length"] = 86,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "PlagueWing1",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasplaguewing1.mp3",
    ["Id"] = 53606,
		["Length"] = 87,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "PlagueWing2",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasplaguewing2.mp3",
    ["Id"] = 53607,
		["Length"] = 71,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "PlagueWing3",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasplaguewing3.mp3",
    ["Id"] = 53608,
		["Length"] = 76,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "SpiderBoss1",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasspiderboss1.mp3",
    ["Id"] = 53609,
		["Length"] = 60,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "SpiderBoss2",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasspiderboss2.mp3",
    ["Id"] = 53610,
		["Length"] = 63,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "SpiderWing1",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasspiderwing1.mp3",
    ["Id"] = 53611,
		["Length"] = 88,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "SpiderWing2",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasspiderwing2.mp3",
    ["Id"] = 53612,
		["Length"] = 67,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "Patch 1.11",
		["Song"] = "SpiderWing3",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasspiderwing3.mp3",
    ["Id"] = 53613,
		["Length"] = 47,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11",
		["Song"] = "NaxxramasWalking1",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramaswalking1.mp3",
    ["Id"] = 53614,
		["Length"] = 101,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11",
		["Song"] = "NaxxramasWalking2",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramaswalking2.mp3",
    ["Id"] = 53615,
		["Length"] = 72,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11",
		["Song"] = "NaxxramasWalking3",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramaswalking3.mp3",
    ["Id"] = 53616,
		["Length"] = 86,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11",
		["Song"] = "NaxxramasWalking4",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramaswalking4.mp3",
    ["Id"] = 53617,
		["Length"] = 82,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11",
		["Song"] = "NaxxramasWalking5",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramaswalking5.mp3",
    ["Id"] = 53618,
		["Length"] = 99,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11",
		["Song"] = "NaxxramasWalking6",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramaswalking6.mp3",
    ["Id"] = 53619,
		["Length"] = 99,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "DayPlains01",
		["Name"] = "sound\\music\\zonemusic\\plains\\dayplains01.mp3",
    ["Id"] = 53680,
		["Length"] = 53,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "DayPlains02",
		["Name"] = "sound\\music\\zonemusic\\plains\\dayplains02.mp3",
    ["Id"] = 53681,
		["Length"] = 76,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "NightPlains01",
		["Name"] = "sound\\music\\zonemusic\\plains\\nightplains01.mp3",
    ["Id"] = 53682,
		["Length"] = 58,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "NightPlains02",
		["Name"] = "sound\\music\\zonemusic\\plains\\nightplains02.mp3",
    ["Id"] = 53683,
		["Length"] = 68,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "pvp1",
		["Name"] = "sound\\music\\zonemusic\\pvp\\pvp1.mp3",
    ["Id"] = 53684,
		["Length"] = 46,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "PVP2",
		["Name"] = "sound\\music\\zonemusic\\pvp\\pvp2.mp3",
    ["Id"] = 53685,
		["Length"] = 52,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft 1.12",
		["Song"] = "pvp_d",
		["Name"] = "sound\\music\\zonemusic\\pvp\\pvp3.mp3",
    ["Id"] = 53686,
		["Length"] = 40,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft 1.12",
		["Song"] = "pvp_e",
		["Name"] = "sound\\music\\zonemusic\\pvp\\pvp4.mp3",
    ["Id"] = 53687,
		["Length"] = 62,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft 1.12",
		["Song"] = "pvp_f",
		["Name"] = "sound\\music\\zonemusic\\pvp\\pvp5.mp3",
    ["Id"] = 53688,
		["Length"] = 61,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "soggyplace-zone1",
		["Name"] = "sound\\music\\zonemusic\\soggyplace\\soggyplace-zone1.mp3",
    ["Id"] = 53695,
		["Length"] = 97,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "soggyplace-zone2",
		["Name"] = "sound\\music\\zonemusic\\soggyplace\\soggyplace-zone2.mp3",
    ["Id"] = 53696,
		["Length"] = 97,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "soggyplace-zone3",
		["Name"] = "sound\\music\\zonemusic\\soggyplace\\soggyplace-zone3.mp3",
    ["Id"] = 53697,
		["Length"] = 90,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "soggyplace-zone4",
		["Name"] = "sound\\music\\zonemusic\\soggyplace\\soggyplace-zone4.mp3",
    ["Id"] = 53698,
		["Length"] = 89,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "soggyplace-zone5",
		["Name"] = "sound\\music\\zonemusic\\soggyplace\\soggyplace-zone5.mp3",
    ["Id"] = 53699,
		["Length"] = 70,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "tavern01_zone1",
		["Name"] = "sound\\music\\zonemusic\\tavernalliance\\tavernalliance01.mp3",
    ["Id"] = 53737,
		["Length"] = 47,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "tavern01_zone2",
		["Name"] = "sound\\music\\zonemusic\\tavernalliance\\tavernalliance02.mp3",
    ["Id"] = 53738,
		["Length"] = 51,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "tavern02_zone1",
		["Name"] = "sound\\music\\zonemusic\\tavernhorde\\tavernhorde01.mp3",
    ["Id"] = 53744,
		["Length"] = 48,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "tavern02_zone2",
		["Name"] = "sound\\music\\zonemusic\\tavernhorde\\tavernhorde02.mp3",
    ["Id"] = 53745,
		["Length"] = 39,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "TavernHorde_zone3",
		["Name"] = "sound\\music\\zonemusic\\tavernhorde\\tavernhorde03.mp3",
    ["Id"] = 53746,
		["Length"] = 47,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "undead_dance",
		["Name"] = "sound\\music\\zonemusic\\tavernhorde\\undead_dance.mp3",
    ["Id"] = 53747,
		["Length"] = 25,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "DayVolcanic01-new",
		["Name"] = "sound\\music\\zonemusic\\volcanic\\dayvolcanic01.mp3",
    ["Id"] = 53812,
		["Length"] = 72,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft",
		["Song"] = "DayVolcanic02-new",
		["Name"] = "sound\\music\\zonemusic\\volcanic\\dayvolcanic02.mp3",
    ["Id"] = 53813,
		["Length"] = 87,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "NightVolcanic01",
		["Name"] = "sound\\music\\zonemusic\\volcanic\\nightvolcanic01.mp3",
    ["Id"] = 53814,
		["Length"] = 71,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "World of Warcraft mp3s",
		["Song"] = "NightVolcanic02",
		["Name"] = "sound\\music\\zonemusic\\volcanic\\nightvolcanic02.mp3",
    ["Id"] = 53815,
		["Length"] = 64,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
}
EpicMusicPlayer:AddPlayList("Classic", playlist1, false)
