--Created by PlaylistCreator version 4.0
local EpicMusicPlayer = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer")
if not EpicMusicPlayer then return end

local playlist1 = {
	["listName"] = "Classic",
	["playlistVersion"] = "4.0",
	["locked"] =  "true",
---------------------------------
--Patch 1.1 Music Starts Here--
---------------------------------
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "World of Warcraft",
		["Name"] = "sound\\music\\gluescreenmusic\\wow_main_theme.mp3",
		["Id"] =  53223,
		["Length"] = 161,
		["Artist"] = "Main Title",
		["WoW"] =  "true",
	},
--A--
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Angelic 01",
		["Name"] = "sound\\music\\musical moments\\angelic\\angelic01.mp3",
		["Id"] =  53224,
		["Length"] = 47,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
--B--
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Battle 01",
		["Name"] = "sound\\music\\musical moments\\battle\\battle01.mp3",
		["Id"] =  53225,
		["Length"] = 48,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Battle 02",
		["Name"] = "sound\\music\\musical moments\\battle\\battle02.mp3",
		["Id"] =  53226,
		["Length"] = 62,
		["Artist"] = "Unknown",
		["WoW"] =  "true", 
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Battle 03",
		["Name"] = "sound\\music\\musical moments\\battle\\battle03.mp3",
		["Id"] =  53227,
		["Length"] = 27,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Battle 04",
		["Name"] = "sound\\music\\musical moments\\battle\\battle04.mp3",
		["Id"] =  53228,
		["Length"] = 36,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Battle 05",
		["Name"] = "sound\\music\\musical moments\\battle\\battle05.mp3",
		["Id"] =  53229,
		["Length"] = 44,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Battle 06",
		["Name"] = "sound\\music\\musical moments\\battle\\battle06.mp3",
		["Id"] =  53230,
		["Length"] = 62,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
--C--
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Cursed Land 01",
		["Name"] = "sound\\music\\zonemusic\\cursedland\\cursedland01.mp3",
		["Id"] =  53426,
		["Length"] = 54,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Cursed Land 02",
		["Name"] = "sound\\music\\zonemusic\\cursedland\\cursedland02.mp3",
		["Id"] =  53427,
		["Length"] = 58,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Cursed Land 03",
		["Name"] = "sound\\music\\zonemusic\\cursedland\\cursedland03.mp3",
		["Id"] =  53428,
		["Length"] = 64,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Cursed Land 04",
		["Name"] = "sound\\music\\zonemusic\\cursedland\\cursedland04.mp3",
		["Id"] =  53429,
		["Length"] = 79,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Cursed Land 05",
		["Name"] = "sound\\music\\zonemusic\\cursedland\\cursedland05.mp3",
		["Id"] =  53430,
		["Length"] = 82,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Cursed Land 06",
		["Name"] = "sound\\music\\zonemusic\\cursedland\\cursedland06.mp3",
		["Id"] =  53431,
		["Length"] = 74,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
--D--	
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Darkmoon Faire 1",
		["Name"] = "sound\\music\\worldevents\\darkmoonfaire_1.mp3",
		["Id"] =  53256,
		["Length"] = 28,
		["Artist"] = "D. Arkenstone, R. Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Darkmoon Faire 2",
		["Name"] = "sound\\music\\worldevents\\darkmoonfaire_2.mp3",
		["Id"] =  53257,
		["Length"] = 74,
		["Artist"] = "D. Arkenstone, R. Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Darkmoon Faire 3",
		["Name"] = "sound\\music\\worldevents\\darkmoonfaire_3.mp3",
		["Id"] =  53258,
		["Length"] = 58,
		["Artist"] = "D. Arkenstone, R. Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Darkmoon Faire 4",
		["Name"] = "sound\\music\\worldevents\\darkmoonfaire_4.mp3",
		["Id"] =  53259,
		["Length"] = 37,
		["Artist"] = "D. Arkenstone, R. Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Darnassus Intro",
		["Name"] = "sound\\music\\citymusic\\darnassus\\darnassus intro.mp3",
		["Id"] =  53183,
		["Length"] = 39,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Darnassus Walking 1",
		["Name"] = "sound\\music\\citymusic\\darnassus\\darnassus walking 1.mp3",
		["Id"] =  53184,
		["Length"] = 85,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Darnassus Walking 2",
		["Name"] = "sound\\music\\citymusic\\darnassus\\darnassus walking 2.mp3",
		["Id"] =  53185,
		["Length"] = 69,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Darnassus Walking 1",
		["Name"] = "sound\\music\\citymusic\\darnassus\\darnassus walking 3.mp3",
		["Id"] =  53186,
		["Length"] = 67,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Darnassus Druid Grove",
		["Name"] = "sound\\music\\citymusic\\darnassus\\druid grove.mp3",
		["Id"] =  53187,
		["Length"] = 44,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Darnassus Warrior Terrace",
		["Name"] = "sound\\music\\citymusic\\darnassus\\warrior terrace.mp3",
		["Id"] =  53188,
		["Length"] = 53,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Barren Dry 01",
		["Name"] = "sound\\music\\zonemusic\\barrendry\\daybarrendry01.mp3",
		["Id"] =  53299,
		["Length"] = 64,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Barren Dry 02",
		["Name"] = "sound\\music\\zonemusic\\barrendry\\daybarrendry02.mp3",
		["Id"] =  53300,
		["Length"] = 64,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Barren Dry 03",
		["Name"] = "sound\\music\\zonemusic\\barrendry\\daybarrendry03.mp3",
		["Id"] =  53301,
		["Length"] = 55,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},	
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Desert 01",
		["Name"] = "sound\\music\\zonemusic\\desert\\daydesert01.mp3",
		["Id"] =  53432,
		["Length"] = 65,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Desert 02",
		["Name"] = "sound\\music\\zonemusic\\desert\\daydesert02.mp3",
		["Id"] =  53433,
		["Length"] = 81,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Desert 03",
		["Name"] = "sound\\music\\zonemusic\\desert\\daydesert03.mp3",
		["Id"] =  53434,
		["Length"] = 54,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Evil Forest 01",
		["Name"] = "sound\\music\\zonemusic\\evilforest\\dayevilforest01.mp3",
		["Id"] =  53486,
		["Length"] = 70,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Evil Forest 02",
		["Name"] = "sound\\music\\zonemusic\\evilforest\\dayevilforest02.mp3",
		["Id"] =  53487,
		["Length"] = 72,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Evil Forest 03",
		["Name"] = "sound\\music\\zonemusic\\evilforest\\dayevilforest03.mp3",
		["Id"] =  53488,
		["Length"] = 70,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Forest 01",
		["Name"] = "sound\\music\\zonemusic\\forest\\dayforest01.mp3",
		["Id"] =  53492,
		["Length"] = 55,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Forest 02",
		["Name"] = "sound\\music\\zonemusic\\forest\\dayforest02.mp3",
		["Id"] =  53493,
		["Length"] = 72,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Forest 03",
		["Name"] = "sound\\music\\zonemusic\\forest\\dayforest03.mp3",
		["Id"] =  53494,
		["Length"] = 64,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Jungle 01",
		["Name"] = "sound\\music\\zonemusic\\jungle\\dayjungle01.mp3",
		["Id"] =  53541,
		["Length"] = 46,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Jungle 02",
		["Name"] = "sound\\music\\zonemusic\\jungle\\dayjungle02.mp3",
		["Id"] =  53542,
		["Length"] = 98,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Jungle 03",
		["Name"] = "sound\\music\\zonemusic\\jungle\\dayjungle03.mp3",
		["Id"] =  53543,
		["Length"] = 48,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Mountain 01",
		["Name"] = "sound\\music\\zonemusic\\mountain\\daymountain01.mp3",
		["Id"] =  53577,
		["Length"] = 120,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Mountain 02",
		["Name"] = "sound\\music\\zonemusic\\mountain\\daymountain02.mp3",
		["Id"] =  53578,
		["Length"] = 66,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Mountain 03",
		["Name"] = "sound\\music\\zonemusic\\mountain\\daymountain03.mp3",
		["Id"] =  53579,
		["Length"] = 80,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},	
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Plains 01",
		["Name"] = "sound\\music\\zonemusic\\plains\\dayplains01.mp3",
		["Id"] =  53680,
		["Length"] = 53,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Plains 02",
		["Name"] = "sound\\music\\zonemusic\\plains\\dayplains02.mp3",
		["Id"] =  53681,
		["Length"] = 76,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Volcanic 01",
		["Name"] = "sound\\music\\zonemusic\\volcanic\\dayvolcanic01.mp3",
		["Id"] =  53812,
		["Length"] = 72,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Day Volcanic 02",
		["Name"] = "sound\\music\\zonemusic\\volcanic\\dayvolcanic02.mp3",
		["Id"] =  53813,
		["Length"] = 87,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},	
--E-- 
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Enchanted Forest 01",
		["Name"] = "sound\\music\\zonemusic\\enchantedforest\\enchantedforest01.mp3",
		["Id"] =  53453,
		["Length"] = 49,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Enchanted Forest 02",
		["Name"] = "sound\\music\\zonemusic\\enchantedforest\\enchantedforest02.mp3",
		["Id"] =  53454,
		["Length"] = 67,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Enchanted Forest 03",
		["Name"] = "sound\\music\\zonemusic\\enchantedforest\\enchantedforest03.mp3",
		["Id"] =  53455,
		["Length"] = 234,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Enchanted Forest 04",
		["Name"] = "sound\\music\\zonemusic\\enchantedforest\\enchantedforest04.mp3",
		["Id"] =  53456,
		["Length"] = 60,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Enchanted Forest 05",
		["Name"] = "sound\\music\\zonemusic\\enchantedforest\\enchantedforest05.mp3",
		["Id"] =  53457,
		["Length"] = 70,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
--F-- 

--G-- 
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Ghost Muisc 03",
		["Name"] = "sound\\music\\zonemusic\\ghostmusic\\ghostmusic03.mp3",
		["Id"] =  53519,
		["Length"] = 62,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Gloomy 01",
		["Name"] = "sound\\music\\musical moments\\gloomy\\gloomy01.mp3",
		["Id"] =  53231,
		["Length"] = 36,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Gloomy 02",
		["Name"] = "sound\\music\\musical moments\\gloomy\\gloomy02.mp3",
		["Id"] =  53232,
		["Length"] = 39,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Gnomeregan Event B",
		["Name"] = "sound\\music\\event\\gnomeregan_event_b.mp3",
		["Id"] =  369053,
		["Length"] = 61,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Gnomeregan Event C",
		["Name"] = "sound\\music\\event\\gnomeregan_event_c.mp3",
		["Id"] =  369054,
		["Length"] = 35,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Gnomeregan Event Complete",
		["Name"] = "sound\\music\\event\\gnomeregan_event_complete.mp3",
		["Id"] =  369055,
		["Length"] = 63,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Gnomeregan Event D",
		["Name"] = "sound\\music\\event\\gnomeregan_event_d.mp3",
		["Id"] =  369056,
		["Length"] = 38,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Gnomeregan Event E",
		["Name"] = "sound\\music\\event\\gnomeregan_event_e.mp3",
		["Id"] =  369057,
		["Length"] = 34,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Gnomeregan Event Intro",
		["Name"] = "sound\\music\\event\\gnomeregan_event_intro.mp3",
		["Id"] =  369058,
		["Length"] = 88,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Gnomeragon Zone 01",
		["Name"] = "sound\\music\\citymusic\\gnomeragon\\gnomeragon01-zone.mp3",
		["Id"] =  53189,
		["Length"] = 64,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Gnomeragon Zone 02",
		["Name"] = "sound\\music\\citymusic\\gnomeragon\\gnomeragon02-zone.mp3",
		["Id"] =  53190,
		["Length"] = 64,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},	
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Guldan's Entrance Theme",
		["Name"] = "sound\\music\\musical moments\\guldansentrancetheme.mp3",
		["Id"] =  53233,
		["Length"] = 100,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},	
--H--
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Haunted 01",
		["Name"] = "sound\\music\\musical moments\\haunted\\haunted01.mp3",
		["Id"] =  53234,
		["Length"] = 62,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Haunted 02",
		["Name"] = "sound\\music\\musical moments\\haunted\\haunted02.mp3",
		["Id"] =  53235,
		["Length"] = 60,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
--I--
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Ironforge Intro",
		["Name"] = "sound\\music\\citymusic\\ironforge\\ironforge intro.mp3",
		["Id"] =  53191,
		["Length"] = 86,
		["Artist"] = "Brian Farr",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Ironforge Walking 1",
		["Name"] = "sound\\music\\citymusic\\ironforge\\ironforge walking 01.mp3",
		["Id"] =  53192,
		["Length"] = 123,
		["Artist"] = "Brian Farr",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Ironforge Walking 2",
		["Name"] = "sound\\music\\citymusic\\ironforge\\ironforge walking 02.mp3",
		["Id"] =  53193,
		["Length"] = 50,
		["Artist"] = "Brian Farr",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Ironforge Walking 3",
		["Name"] = "sound\\music\\citymusic\\ironforge\\ironforge walking 03 (glenn).mp3",
		["Id"] =  53194,
		["Length"] = 81,
		["Artist"] = "Brian Farr",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Ironforge Walking 4",
		["Name"] = "sound\\music\\citymusic\\ironforge\\ironforge walking 04.mp3",
		["Id"] =  53195,
		["Length"] = 70,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
--J--

--K--

--L--
--M--
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Magic 01 Moment",
		["Name"] = "sound\\music\\musical moments\\magic\\magic01-moment.mp3",
		["Id"] =  53236,
		["Length"] = 63,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Magic 01 Zone 1",
		["Name"] = "sound\\music\\musical moments\\magic\\magic01-zone1.mp3",
		["Id"] =  53237,
		["Length"] = 33,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Magic 01 Zone 2",
		["Name"] = "sound\\music\\musical moments\\magic\\magic01-zone2.mp3",
		["Id"] =  53238,
		["Length"] = 39,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Mystery 01 Zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery01-zone.mp3",
		["Id"] =  53240,
		["Length"] = 60,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Mystery 02 Zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery02-zone.mp3",
		["Id"] =  53241,
		["Length"] = 53,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Mystery 03 Zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery03-zone.mp3",
		["Id"] =  53242,
		["Length"] = 60,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Mystery 04 Zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery04-zone.mp3",
		["Id"] =  53243,
		["Length"] = 64,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Mystery 05 Zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery05-zone.mp3",
		["Id"] =  53244,
		["Length"] = 81,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Mystery 06 Zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery06-zone.mp3",
		["Id"] =  53245,
		["Length"] = 65,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Mystery 07 Zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery07-zone.mp3",
		["Id"] =  53246,
		["Length"] = 83,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Mystery 08 Zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery08-zone.mp3",
		["Id"] =  53247,
		["Length"] = 83,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Mystery 09 Zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery09-zone.mp3",
		["Id"] =  53248,
		["Length"] = 82,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Mystery 10 Zone",
		["Name"] = "sound\\music\\musical moments\\mystery\\mystery10-zone.mp3",
		["Id"] =  53249,
		["Length"] = 62,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
--N--
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Barren Dry 01",
		["Name"] = "sound\\music\\zonemusic\\barrendry\\nightbarrendry01.mp3",
		["Id"] =  53302,
		["Length"] = 67,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Barren Dry 02",
		["Name"] = "sound\\music\\zonemusic\\barrendry\\nightbarrendry02.mp3",
		["Id"] =  53303,
		["Length"] = 40,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Barren Dry 03",
		["Name"] = "sound\\music\\zonemusic\\barrendry\\nightbarrendry03.mp3",
		["Id"] =  53304,
		["Length"] = 47,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Desert 01",
		["Name"] = "sound\\music\\zonemusic\\desert\\nightdesert01.mp3",
		["Id"] =  53435,
		["Length"] = 77,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Desert 02",
		["Name"] = "sound\\music\\zonemusic\\desert\\nightdesert02.mp3",
		["Id"] =  53436,
		["Length"] = 62,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Desert 03",
		["Name"] = "sound\\music\\zonemusic\\desert\\nightdesert03.mp3",
		["Id"] =  53437,
		["Length"] = 57,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Evil Forest 01",
		["Name"] = "sound\\music\\zonemusic\\evilforest\\nightevilforest01.mp3",
		["Id"] =  53489,
		["Length"] = 57,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Evil Forest 02",
		["Name"] = "sound\\music\\zonemusic\\evilforest\\nightevilforest02.mp3",
		["Id"] =  53490,
		["Length"] = 75,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Evil Forest 03",
		["Name"] = "sound\\music\\zonemusic\\evilforest\\nightevilforest03.mp3",
		["Id"] =  53491,
		["Length"] = 70,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Forest 01",
		["Name"] = "sound\\music\\zonemusic\\forest\\nightforest01.mp3",
		["Id"] =  53495,
		["Length"] = 53,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Forest 02",
		["Name"] = "sound\\music\\zonemusic\\forest\\nightforest02.mp3",
		["Id"] =  53496,
		["Length"] = 42,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Forest 03",
		["Name"] = "sound\\music\\zonemusic\\forest\\nightforest03.mp3",
		["Id"] =  53497,
		["Length"] = 59,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Forest 04",
		["Name"] = "sound\\music\\zonemusic\\forest\\nightforest04.mp3",
		["Id"] =  53498,
		["Length"] = 54,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Jungle 01",
		["Name"] = "sound\\music\\zonemusic\\jungle\\nightjungle01.mp3",
		["Id"] =  53544,
		["Length"] = 54,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Jungle 02",
		["Name"] = "sound\\music\\zonemusic\\jungle\\nightjungle02.mp3",
		["Id"] =  53545,
		["Length"] = 53,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Jungle 03",
		["Name"] = "sound\\music\\zonemusic\\jungle\\nightjungle03.mp3",
		["Id"] =  53546,
		["Length"] = 89,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Mountain 01",
		["Name"] = "sound\\music\\zonemusic\\mountain\\nightmountain01.mp3",
		["Id"] =  53580,
		["Length"] = 64,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Mountain 02",
		["Name"] = "sound\\music\\zonemusic\\mountain\\nightmountain02.mp3",
		["Id"] =  53581,
		["Length"] = 63,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Mountain 03",
		["Name"] = "sound\\music\\zonemusic\\mountain\\nightmountain03.mp3",
		["Id"] =  53582,
		["Length"] = 69,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Mountain 04",
		["Name"] = "sound\\music\\zonemusic\\mountain\\nightmountain04.mp3",
		["Id"] =  53583,
		["Length"] = 63,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Plains 01",
		["Name"] = "sound\\music\\zonemusic\\plains\\nightplains01.mp3",
		["Id"] =  53682,
		["Length"] = 58,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Plains 02",
		["Name"] = "sound\\music\\zonemusic\\plains\\nightplains02.mp3",
		["Id"] =  53683,
		["Length"] = 68,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Volcanic 01",
		["Name"] = "sound\\music\\zonemusic\\volcanic\\nightvolcanic01.mp3",
		["Id"] =  53814,
		["Length"] = 71,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Night Volcanic 02",
		["Name"] = "sound\\music\\zonemusic\\volcanic\\nightvolcanic02.mp3",
		["Id"] =  53815,
		["Length"] = 64,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},	
--O--
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Orgrimmar 1 Moment",
		["Name"] = "sound\\music\\citymusic\\orgrimmar\\orgrimmar01-moment.mp3",
		["Id"] =  53197,
		["Length"] = 68,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Orgrimmar 1 Zone",
		["Name"] = "sound\\music\\citymusic\\orgrimmar\\orgrimmar01-zone.mp3",
		["Id"] =  53198,
		["Length"] = 68,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Orgrimmar 2 Moment",
		["Name"] = "sound\\music\\citymusic\\orgrimmar\\orgrimmar02-moment.mp3",
		["Id"] =  53199,
		["Length"] = 62,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Orgrimmar 2 Zone",
		["Name"] = "sound\\music\\citymusic\\orgrimmar\\orgrimmar02-zone.mp3",
		["Id"] =  53200,
		["Length"] = 62,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Orgrimmar Intro Moment",
		["Name"] = "sound\\music\\citymusic\\orgrimmar\\orgrimmar_intro-moment.mp3",
		["Id"] =  53201,
		["Length"] = 40,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
--P--
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "PVP 6-1",
		["Name"] = "sound\\music\\zonemusic\\pvp\\mus_pvp6_01.mp3",
		["Id"] =  521021,
		["Length"] = 157,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "PVP 6-2",
		["Name"] = "sound\\music\\zonemusic\\pvp\\mus_pvp6_02.mp3",
		["Id"] =  521022,
		["Length"] = 162,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "PVP 7 Moment 1-1",
		["Name"] = "sound\\music\\zonemusic\\pvp\\mus_pvp7moment1_01.mp3",
		["Id"] =  521023,
		["Length"] = 40,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "PVP 7 Moment 1-2",
		["Name"] = "sound\\music\\zonemusic\\pvp\\mus_pvp7moment1_02.mp3",
		["Id"] =  521024,
		["Length"] = 42,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "PVP 7 Moment 2-1",
		["Name"] = "sound\\music\\zonemusic\\pvp\\mus_pvp7moment2_01.mp3",
		["Id"] =  521025,
		["Length"] = 36,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "PVP 7 Moment 2-2",
		["Name"] = "sound\\music\\zonemusic\\pvp\\mus_pvp7moment2_02.mp3",
		["Id"] =  521026,
		["Length"] = 36,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "PVP 7 Moment 3-1",
		["Name"] = "sound\\music\\zonemusic\\pvp\\mus_pvp7moment3_01.mp3",
		["Id"] =  521027,
		["Length"] = 40,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "PVP 7 Stinger End",
		["Name"] = "sound\\music\\zonemusic\\pvp\\mus_pvp7stingerend_01.mp3",
		["Id"] =  521028,
		["Length"] = 31,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "PVP 7 Stinger Intro",
		["Name"] = "sound\\music\\zonemusic\\pvp\\mus_pvp7stingerintro_01.mp3",
		["Id"] =  521029,
		["Length"] = 21,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "PVP 7-1",
		["Name"] = "sound\\music\\zonemusic\\pvp\\mus_pvp7_01.mp3",
		["Id"] =  521030,
		["Length"] = 99,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "PVP 7-2",
		["Name"] = "sound\\music\\zonemusic\\pvp\\mus_pvp7_02.mp3",
		["Id"] =  521031,
		["Length"] = 99,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
--Q--
--R--
--S--
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Sacred 01 (Monastery 01)",
		["Name"] = "sound\\music\\musical moments\\sacred\\sacred01.mp3",
		["Id"] =  53250,
		["Length"] = 16,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Sacred 02",
		["Name"] = "sound\\music\\musical moments\\sacred\\sacred02.mp3",
		["Id"] =  53251,
		["Length"] = 19,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Soggy Place Zone 1",
		["Name"] = "sound\\music\\zonemusic\\soggyplace\\soggyplace-zone1.mp3",
		["Id"] =  53695,
		["Length"] = 97,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Soggy Place Zone 2",
		["Name"] = "sound\\music\\zonemusic\\soggyplace\\soggyplace-zone2.mp3",
		["Id"] =  53696,
		["Length"] = 97,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Soggy Place Zone 3",
		["Name"] = "sound\\music\\zonemusic\\soggyplace\\soggyplace-zone3.mp3",
		["Id"] =  53697,
		["Length"] = 90,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Soggy Place Zone 4",
		["Name"] = "sound\\music\\zonemusic\\soggyplace\\soggyplace-zone4.mp3",
		["Id"] =  53698,
		["Length"] = 89,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Soggy Place Zone 5",
		["Name"] = "sound\\music\\zonemusic\\soggyplace\\soggyplace-zone5.mp3",
		["Id"] =  53699,
		["Length"] = 70,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},	
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Spooky 01 Moment",
		["Name"] = "sound\\music\\musical moments\\spooky\\spooky01-moment.mp3",
		["Id"] =  53252,
		["Length"] = 25,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Stormwind 1 Moment",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind01-moment.mp3",
		["Id"] =  53202,
		["Length"] = 54,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Stormwind 2 Moment",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind02-moment.mp3",
		["Id"] =  53203,
		["Length"] = 35,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Stormwind 3 Moment",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind03-moment.mp3",
		["Id"] =  53204,
		["Length"] = 69,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Stormwind 4 Zone",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind04-zone.mp3",
		["Id"] =  53205,
		["Length"] = 62,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Stormwind 5 Zone",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind05-zone.mp3",
		["Id"] =  53206,
		["Length"] = 60,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Stormwind 6 Zone",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind06-zone.mp3",
		["Id"] =  53207,
		["Length"] = 53,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Stormwind 7 Zone",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind07-zone.mp3",
		["Id"] =  53208,
		["Length"] = 86,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Stormwind 8 Zone",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind08-zone.mp3",
		["Id"] =  53209,
		["Length"] = 77,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Stormwind High Seas Moment",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind_highseas-moment.mp3",
		["Id"] =  53210,
		["Length"] = 133,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Stormwind Intro Moment",
		["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind_intro-moment.mp3",
		["Id"] =  53211,
		["Length"] = 66,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Swamp 01",
		["Name"] = "sound\\music\\musical moments\\swamp\\swamp01.mp3",
		["Id"] =  53253,
		["Length"] = 34,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},		
--T--
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Tavern Alliance 1",
		["Name"] = "sound\\music\\zonemusic\\tavernalliance\\tavernalliance01.mp3",
		["Id"] =  53737,
		["Length"] = 47,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Tavern Alliance 2",
		["Name"] = "sound\\music\\zonemusic\\tavernalliance\\tavernalliance02.mp3",
		["Id"] =  53738,
		["Length"] = 51,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Tavern Horde 1",
		["Name"] = "sound\\music\\zonemusic\\tavernhorde\\tavernhorde01.mp3",
		["Id"] =  53744,
		["Length"] = 48,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Tavern Horde 2",
		["Name"] = "sound\\music\\zonemusic\\tavernhorde\\tavernhorde02.mp3",
		["Id"] =  53745,
		["Length"] = 39,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Tavern Horde 3",
		["Name"] = "sound\\music\\zonemusic\\tavernhorde\\tavernhorde03.mp3",
		["Id"] =  53746,
		["Length"] = 47,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Tinker Town Intro",
		["Name"] = "sound\\music\\citymusic\\ironforge\\tinkertownintro_moment.mp3",
		["Id"] =  53196,
		["Length"] = 51,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Thunder Bluff Intro",
		["Name"] = "sound\\music\\citymusic\\thunderbluff\\thunderbluff intro.mp3",
		["Id"] =  53212,
		["Length"] = 46,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Thunder Bluff Walking 1",
		["Name"] = "sound\\music\\citymusic\\thunderbluff\\thunderbluff walking 01.mp3",
		["Id"] =  53213,
		["Length"] = 117,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Thunder Bluff Walking 2",
		["Name"] = "sound\\music\\citymusic\\thunderbluff\\thunderbluff walking 02.mp3",
		["Id"] =  53214,
		["Length"] = 116,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Thunder Bluff Walking 3",
		["Name"] = "sound\\music\\citymusic\\thunderbluff\\thunderbluff walking 03.mp3",
		["Id"] =  53215,
		["Length"] = 121,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},	
--U--
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Undead Dance",
		["Name"] = "sound\\music\\zonemusic\\tavernhorde\\undead_dance.mp3",
		["Id"] =  53747,
		["Length"] = 25,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Undercity 1 Zone",
		["Name"] = "sound\\music\\citymusic\\undercity\\undercity01-zone.mp3",
		["Id"] =  53216,
		["Length"] = 67,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Undercity 2 Zone",
		["Name"] = "sound\\music\\citymusic\\undercity\\undercity02-zone.mp3",
		["Id"] =  53217,
		["Length"] = 85,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Undercity 3 Zone",
		["Name"] = "sound\\music\\citymusic\\undercity\\undercity03-zone.mp3",
		["Id"] =  53218,
		["Length"] = 75,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Undercity Intro Moment",
		["Name"] = "sound\\music\\citymusic\\undercity\\undercityintro-moment.mp3",
		["Id"] =  53219,
		["Length"] = 28,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
--V--
--W--
--X--
--Y--
--Z--	
	{
		["Album"] = "WoW 1.1 - World of Warcraft",
		["Song"] = "Zul'Gurub Voodoo",
		["Name"] = "sound\\music\\musical moments\\zulgurubvoodoo.mp3",
		["Id"] =  53254,
		["Length"] = 84,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
--------------------------------
--Patch 1.9 Music Starts Here--
--------------------------------
	{
		["Album"] = "WoW 1.9 - The Gates of Ahn'Qiraj",
		["Song"] = "Ahn'Qiraj Breath 1",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajinterior1.mp3",
		["Id"] =  53265,
		["Length"] = 52,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9 - The Gates of Ahn'Qiraj",
		["Song"] = "Ahn'Qiraj Breath 2",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajinterior2.mp3",
		["Id"] =  53266,
		["Length"] = 81,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9 - The Gates of Ahn'Qiraj",
		["Song"] = "Ahn'Qiraj Breath 3",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajinterior3.mp3",
		["Id"] =  53267,
		["Length"] = 67,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9 - The Gates of Ahn'Qiraj",
		["Song"] = "Ahn'Qiraj Fireflies 1",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajinteriorintromain.mp3",
		["Id"] =  53269,
		["Length"] = 69,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9 - The Gates of Ahn'Qiraj",
		["Song"] = "Ahn'Qiraj Exterior 1",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajexteriorwalking1.mp3",
		["Id"] =  53261,
		["Length"] = 67,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9 - The Gates of Ahn'Qiraj",
		["Song"] = "Ahn'Qiraj Exterior 2",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajexteriorwalking2.mp3",
		["Id"] =  53262,
		["Length"] = 84,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9 - The Gates of Ahn'Qiraj",
		["Song"] = "Ahn'Qiraj Exterior 3",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajexteriorwalking3.mp3",
		["Id"] =  53263,
		["Length"] = 57,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9 - The Gates of Ahn'Qiraj",
		["Song"] = "Ahn'Qiraj Exterior 4",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajexteriorwalking4.mp3",
		["Id"] =  53264,
		["Length"] = 59,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},	
	{
		["Album"] = "WoW 1.9 - The Gates of Ahn'Qiraj",
		["Song"] = "Ahn'Qiraj Interior Center Room 1",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajinteriorcenterroom1.mp3",
		["Id"] =  53268,
		["Length"] = 69,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},	
	{
		["Album"] = "WoW 1.9 - The Gates of Ahn'Qiraj",
		["Song"] = "Ahn'Qiraj Intro Theme",
		["Name"] = "sound\\music\\musical moments\\mystery\\ahnqirajintro1.mp3",
		["Id"] =  53239,
		["Length"] = 143,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},	
	{
		["Album"] = "WoW 1.9 - The Gates of Ahn'Qiraj",
		["Song"] = "Ahn'Qiraj King Room",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajkingroom.mp3",
		["Id"] =  53270,
		["Length"] = 73,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9 - The Gates of Ahn'Qiraj",
		["Song"] = "Ahn'Qiraj Triangle 1",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom1.mp3",
		["Id"] =  53271,
		["Length"] = 23,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9 - The Gates of Ahn'Qiraj",
		["Song"] = "Ahn'Qiraj Triangle 2",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom2.mp3",
		["Id"] =  53272,
		["Length"] = 17,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9 - The Gates of Ahn'Qiraj",
		["Song"] = "Ahn'Qiraj Triangle 3",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom3.mp3",
		["Id"] =  53273,
		["Length"] = 15,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9 - The Gates of Ahn'Qiraj",
		["Song"] = "Ahn'Qiraj Triangle 4",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom4.mp3",
		["Id"] =  53274,
		["Length"] = 19,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9 - The Gates of Ahn'Qiraj",
		["Song"] = "Ahn'Qiraj Triangle 5",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom5.mp3",
		["Id"] =  53275,
		["Length"] = 31,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9 - The Gates of Ahn'Qiraj",
		["Song"] = "Ahn'Qiraj Triangle 6",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom6.mp3",
		["Id"] =  53276,
		["Length"] = 20,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.9 - The Gates of Ahn'Qiraj",
		["Song"] = "Ahn'Qiraj Triangle 7",
		["Name"] = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom7.mp3",
		["Id"] =  53277,
		["Length"] = 17,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},	
--------------------------------
--Patch 1.11 Music Starts Here--
--------------------------------
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Abomination Boss 1",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasabominationboss1.mp3",
		["Id"] =  53591,
		["Length"] = 61,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Abomination Boss 2",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasabominationboss2.mp3",
		["Id"] =  53592,
		["Length"] = 67,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Abomination Wing 1",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasabominationwing1.mp3",
		["Id"] =  53593,
		["Length"] = 61,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Abomination Wing 2",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasabominationwing2.mp3",
		["Id"] =  53594,
		["Length"] = 66,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Abomination Wing 3",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasabominationwing3.mp3",
		["Id"] =  53595,
		["Length"] = 61,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Frostwyrm 1",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasfrostwyrm1.mp3",
		["Id"] =  53596,
		["Length"] = 57,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Frostwyrm 2",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasfrostwyrm2.mp3",
		["Id"] =  53597,
		["Length"] = 81,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Frostwyrm 3",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasfrostwyrm3.mp3",
		["Id"] =  53598,
		["Length"] = 61,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Frostwyrm 4",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasfrostwyrm4.mp3",
		["Id"] =  53599,
		["Length"] = 60,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Hub Base 1",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramashubbase1.mp3",
		["Id"] =  53600,
		["Length"] = 72,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Hub Base 2",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramashubbase2.mp3",
		["Id"] =  53601,
		["Length"] = 81,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Kel'Thuzad 1A",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramaskelthuzad1.mp3",
		["Id"] =  53602,
		["Length"] = 94,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Kel'Thuzad 2A",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramaskelthuzad2.mp3",
		["Id"] =  53603,
		["Length"] = 97,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Kel'Thuzad 3A",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramaskelthuzad3.mp3",
		["Id"] =  53604,
		["Length"] = 75,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Plague Boss 1",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasplagueboss1.mp3",
		["Id"] =  53605,
		["Length"] = 86,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Plague Wing 1",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasplaguewing1.mp3",
		["Id"] =  53606,
		["Length"] = 87,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Plague Wing 2",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasplaguewing2.mp3",
		["Id"] =  53607,
		["Length"] = 71,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Plague Wing 3",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasplaguewing3.mp3",
		["Id"] =  53608,
		["Length"] = 76,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Spider Boss 1",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasspiderboss1.mp3",
		["Id"] =  53609,
		["Length"] = 60,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Spider Boss 2",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasspiderboss2.mp3",
		["Id"] =  53610,
		["Length"] = 63,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Spider Wing 1",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasspiderwing1.mp3",
		["Id"] =  53611,
		["Length"] = 88,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Spider Wing 2",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasspiderwing2.mp3",
		["Id"] =  53612,
		["Length"] = 67,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Spider Wing 3",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramasspiderwing3.mp3",
		["Id"] =  53613,
		["Length"] = 47,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Naxxramas Walking 1",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramaswalking1.mp3",
		["Id"] =  53614,
		["Length"] = 101,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Naxxramas Walking 2",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramaswalking2.mp3",
		["Id"] =  53615,
		["Length"] = 72,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Naxxramas Walking 3",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramaswalking3.mp3",
		["Id"] =  53616,
		["Length"] = 86,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Naxxramas Walking 4",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramaswalking4.mp3",
		["Id"] =  53617,
		["Length"] = 82,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Naxxramas Walking 5",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramaswalking5.mp3",
		["Id"] =  53618,
		["Length"] = 99,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.11 - Shadow of the Necropolis",
		["Song"] = "Naxxramas Walking 6",
		["Name"] = "sound\\music\\zonemusic\\naxxramas\\naxxramaswalking6.mp3",
		["Id"] =  53619,
		["Length"] = 99,
		["Artist"] = "Matt Uelmen",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.12 - Drums of War",
		["Song"] = "PVP 1",
		["Name"] = "sound\\music\\zonemusic\\pvp\\pvp1.mp3",
		["Id"] =  53684,
		["Length"] = 46,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.12 - Drums of War",
		["Song"] = "PVP 2",
		["Name"] = "sound\\music\\zonemusic\\pvp\\pvp2.mp3",
		["Id"] =  53685,
		["Length"] = 52,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.12 - Drums of War",
		["Song"] = "PVP 3",
		["Name"] = "sound\\music\\zonemusic\\pvp\\pvp3.mp3",
		["Id"] =  53686,
		["Length"] = 40,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.12 - Drums of War",
		["Song"] = "PVP 4",
		["Name"] = "sound\\music\\zonemusic\\pvp\\pvp4.mp3",
		["Id"] =  53687,
		["Length"] = 62,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 1.12 - Drums of War",
		["Song"] = "PVP 5",
		["Name"] = "sound\\music\\zonemusic\\pvp\\pvp5.mp3",
		["Id"] =  53688,
		["Length"] = 61,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},		
	{
		["Album"] = "WarCraft III Expansion",
		["Song"] = "Power Of The Horde",
		["Name"] = "sound\\music\\zonemusic\\dmf_l70etc01.mp3",
		["Id"] =  53438,
		["Length"] = 281,
		["Artist"] = "Tenth Level Tauren Chieftain",
		["WoW"] =  "true",
	},	
}
EpicMusicPlayer:AddPlayList("Classic", playlist1, false, true)
