--Created by PlaylistCreator version 4.0
local EpicMusicPlayer = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer")
if not EpicMusicPlayer then return end

local playlist1 = {
	["listName"] = "Draenor",
	["playlistVersion"] = "4.0",
	["locked"] =  "true",
-------------------------------
--Patch 6.0 Music Starts Here--
-------------------------------
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "A Siege of Worlds",
		["Name"] = "sound\\music\\draenor\\mus_60_asiegeofworlds_maintitle.mp3",
		["Id"] =  1042428,
		["Length"] = 726,
		["Artist"] = "Main Title",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "A Hero's Sacrifice v1",
		["Name"] = "sound\\music\\draenor\\mus_60_aherossacrifice_v1.mp3",
		["Id"] =  1068302,
		["Length"] = 116,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "A Hero's Sacrifice v2",
		["Name"] = "sound\\music\\draenor\\mus_60_aherossacrifice_v2.mp3",
		["Id"] =  1068303,
		["Length"] = 101,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "A Hero's Sacrifice v3A",
		["Name"] = "sound\\music\\draenor\\mus_60_aherossacrifice_v3a.mp3",
		["Id"] =  1068304,
		["Length"] = 55,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "A Hero's Sacrifice v3B",
		["Name"] = "sound\\music\\draenor\\mus_60_aherossacrifice_v3b.mp3",
		["Id"] =  1068305,
		["Length"] = 60,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "A Hero's Sacrifice v4",
		["Name"] = "sound\\music\\draenor\\mus_60_aherossacrifice_v4.mp3",
		["Id"] =  1068306,
		["Length"] = 24,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "A Hero's Sacrifice v5",
		["Name"] = "sound\\music\\draenor\\mus_60_aherossacrifice_v5.mp3",
		["Id"] =  1068307,
		["Length"] = 67,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "A Light in the Darkness v1",
		["Name"] = "sound\\music\\draenor\\mus_60_alightinthedarkness_v1.mp3",
		["Id"] =  1068308,
		["Length"] = 155,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "A Light in the Darkness v2",
		["Name"] = "sound\\music\\draenor\\mus_60_alightinthedarkness_v2.mp3",
		["Id"] =  1068309,
		["Length"] = 137,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "A Light in the Darkness v3",
		["Name"] = "sound\\music\\draenor\\mus_60_alightinthedarkness_v3.mp3",
		["Id"] =  1061098,
		["Length"] = 153,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "A Light in the Darkness v3A",
		["Name"] = "sound\\music\\draenor\\mus_60_alightinthedarkness_v3a.mp3",
		["Id"] =  1061099,
		["Length"] = 69,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Arak 2 H",
		["Name"] = "sound\\music\\draenor\\mus_60_arak2_h.mp3",
		["Id"] =  1064152,
		["Length"] = 157,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Army Life H",
		["Name"] = "sound\\music\\draenor\\mus_60_armylife_h.mp3",
		["Id"] =  1064153,
		["Length"] = 141,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Army A",
		["Name"] = "sound\\music\\draenor\\mus_60_army_a.mp3",
		["Id"] =  1080405,
		["Length"] = 142,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Army Stinger1",
		["Name"] = "sound\\music\\draenor\\mus_60_army_stinger1.mp3",
		["Id"] =  1080406,
		["Length"] = 11,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Army Stinger2",
		["Name"] = "sound\\music\\draenor\\mus_60_army_stinger2.mp3",
		["Id"] =  1080407,
		["Length"] = 12,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "A Siege of Worlds v2",
		["Name"] = "sound\\music\\draenor\\mus_60_asiegeofworlds_maintitle.mp3",
		["Id"] =  1042428,
		["Length"] = 726,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "BFreedom H1",
		["Name"] = "sound\\music\\draenor\\mus_60_bfreedom_h1.mp3",
		["Id"] =  1064154,
		["Length"] = 67,
		["Artist"] = "Craig Stuart Garfinkle",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "BFreedom H2",
		["Name"] = "sound\\music\\draenor\\mus_60_bfreedom_h2.mp3",
		["Id"] =  1064155,
		["Length"] = 106,
		["Artist"] = "Craig Stuart Garfinkle",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Blackrock A",
		["Name"] = "sound\\music\\draenor\\mus_60_blackrock_a.mp3",
		["Id"] =  1080491,
		["Length"] = 83,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Blackrock B",
		["Name"] = "sound\\music\\draenor\\mus_60_blackrock_b.mp3",
		["Id"] =  1080492,
		["Length"] = 41,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Blackrock C",
		["Name"] = "sound\\music\\draenor\\mus_60_blackrock_c.mp3",
		["Id"] =  1080493,
		["Length"] = 39,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Blackrock D",
		["Name"] = "sound\\music\\draenor\\mus_60_blackrock_d.mp3",
		["Id"] =  1080494,
		["Length"] = 8,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Blackrock E",
		["Name"] = "sound\\music\\draenor\\mus_60_blackrock_e.mp3",
		["Id"] =  1080495,
		["Length"] = 37,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Blackrock H",
		["Name"] = "sound\\music\\draenor\\mus_60_blackrock_h.mp3",
		["Id"] =  1080496,
		["Length"] = 188,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Call of the Warrior A",
		["Name"] = "sound\\music\\draenor\\mus_60_callofthewarrior_a.mp3",
		["Id"] =  1080518,
		["Length"] = 150,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Call of the Warrior C",
		["Name"] = "sound\\music\\draenor\\mus_60_callofthewarrior_c.mp3",
		["Id"] =  1080519,
		["Length"] = 150,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Call of the Warrior H",
		["Name"] = "sound\\music\\draenor\\mus_60_callofthewarrior_h.mp3",
		["Id"] =  1080520,
		["Length"] = 150,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Caverns of Life H",
		["Name"] = "sound\\music\\draenor\\mus_60_cavernsoflife_h.mp3",
		["Id"] =  1064156,
		["Length"] = 112,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Chieftans Gather H",
		["Name"] = "sound\\music\\draenor\\mus_60_chieftansgather_h.mp3",
		["Id"] =  1067039,
		["Length"] = 96,
		["Artist"] = "Eimear Noone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Cold Mountain Duet H",
		["Name"] = "sound\\music\\draenor\\mus_60_coldmountain_duet_h.mp3",
		["Id"] =  1080507,
		["Length"] = 156,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Eagle of Draenor H",
		["Name"] = "sound\\music\\draenor\\mus_60_eagleofdraenor_h.mp3",
		["Id"] =  1064157,
		["Length"] = 126,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Eagle A",
		["Name"] = "sound\\music\\draenor\\mus_60_eagle_a.mp3",
		["Id"] =  1080408,
		["Length"] = 127,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Eagle B",
		["Name"] = "sound\\music\\draenor\\mus_60_eagle_b.mp3",
		["Id"] =  1080409,
		["Length"] = 59,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Eagle C",
		["Name"] = "sound\\music\\draenor\\mus_60_eagle_c.mp3",
		["Id"] =  1080410,
		["Length"] = 30,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Eagle D",
		["Name"] = "sound\\music\\draenor\\mus_60_eagle_d.mp3",
		["Id"] =  1080411,
		["Length"] = 27,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "Elune's Shadow A",
		["Name"] = "sound\\music\\draenor\\mus_60_elunesshadow_a.mp3",
		["Id"] =  936323,
		["Length"] = 44,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "Elune's Shadow B",
		["Name"] = "sound\\music\\draenor\\mus_60_elunesshadow_b.mp3",
		["Id"] =  936324,
		["Length"] = 33,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "Elune's Shadow C",
		["Name"] = "sound\\music\\draenor\\mus_60_elunesshadow_c.mp3",
		["Id"] =  936325,
		["Length"] = 52,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "Elune's Shadow H",
		["Name"] = "sound\\music\\draenor\\mus_60_elunesshadow_h.mp3",
		["Id"] =  936326,
		["Length"] = 94,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "Eternal Night H",
		["Name"] = "sound\\music\\draenor\\mus_60_eternalnight_h.mp3",
		["Id"] =  936327,
		["Length"] = 75,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Ethereal Embers C",
		["Name"] = "sound\\music\\draenor\\mus_60_etherealembers_c.mp3",
		["Id"] =  1061100,
		["Length"] = 80,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Ethereal Embers D",
		["Name"] = "sound\\music\\draenor\\mus_60_etherealembers_d.mp3",
		["Id"] =  1061101,
		["Length"] = 79,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Ethereal Embers E",
		["Name"] = "sound\\music\\draenor\\mus_60_etherealembers_e.mp3",
		["Id"] =  1061102,
		["Length"] = 81,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Ethereal Embers F",
		["Name"] = "sound\\music\\draenor\\mus_60_etherealembers_f.mp3",
		["Id"] =  1061103,
		["Length"] = 74,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Ethereal Embers H",
		["Name"] = "sound\\music\\draenor\\mus_60_etherealembers_h.mp3",
		["Id"] =  1061104,
		["Length"] = 79,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Ethereal Essence H1",
		["Name"] = "sound\\music\\draenor\\mus_60_etherealessence_h1.mp3",
		["Id"] =  1064158,
		["Length"] = 102,
		["Artist"] = "Craig Stuart Garfinkle",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Ethereal Essence H2",
		["Name"] = "sound\\music\\draenor\\mus_60_etherealessence_h2.mp3",
		["Id"] =  1064159,
		["Length"] = 87,
		["Artist"] = "Craig Stuart Garfinkle",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "Fel Wasteland A",
		["Name"] = "sound\\music\\draenor\\mus_60_felwasteland_a.mp3",
		["Id"] =  936328,
		["Length"] = 71,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "Fel Wasteland B",
		["Name"] = "sound\\music\\draenor\\mus_60_felwasteland_b.mp3",
		["Id"] =  936329,
		["Length"] = 90,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "Fel Wasteland C",
		["Name"] = "sound\\music\\draenor\\mus_60_felwasteland_c.mp3",
		["Id"] =  936330,
		["Length"] = 31,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "Fel Wasteland H",
		["Name"] = "sound\\music\\draenor\\mus_60_felwasteland_h.mp3",
		["Id"] =  936331,
		["Length"] = 85,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "Foreshadowing H",
		["Name"] = "sound\\music\\draenor\\mus_60_foreshadowing_h.mp3",
		["Id"] =  936332,
		["Length"] = 124,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "Forsaken A",
		["Name"] = "sound\\music\\draenor\\mus_60_forsaken_a.mp3",
		["Id"] =  936333,
		["Length"] = 82,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "Forsaken H",
		["Name"] = "sound\\music\\draenor\\mus_60_forsaken_h.mp3",
		["Id"] =  936334,
		["Length"] = 124,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "Gardens of Karabor A",
		["Name"] = "sound\\music\\draenor\\mus_60_gardensofkarabor_a.mp3",
		["Id"] =  936335,
		["Length"] = 99,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "Gardens of Karabor B",
		["Name"] = "sound\\music\\draenor\\mus_60_gardensofkarabor_b.mp3",
		["Id"] =  936336,
		["Length"] = 47,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "Gardens of Karabor H",
		["Name"] = "sound\\music\\draenor\\mus_60_gardensofkarabor_h.mp3",
		["Id"] =  936337,
		["Length"] = 126,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Garrison Building Complete",
		["Name"] = "sound\\music\\draenor\\mus_60_garrisonbuildingcomplete.mp3",
		["Id"] =  1080412,
		["Length"] = 13,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Garrison Building Complete v2",
		["Name"] = "sound\\music\\draenor\\mus_60_garrisonbuildingcomplete2.mp3",
		["Id"] =  1087470,
		["Length"] = 8,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Grinspiration A",
		["Name"] = "sound\\music\\draenor\\mus_60_grinspiration_a.mp3",
		["Id"] =  1067040,
		["Length"] = 89,
		["Artist"] = "Craig Stuart Garfinkle",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Grinspiration B",
		["Name"] = "sound\\music\\draenor\\mus_60_grinspiration_b.mp3",
		["Id"] =  1067041,
		["Length"] = 81,
		["Artist"] = "Craig Stuart Garfinkle",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Grinspiration C",
		["Name"] = "sound\\music\\draenor\\mus_60_grinspiration_c.mp3",
		["Id"] =  1067042,
		["Length"] = 123,
		["Artist"] = "Craig Stuart Garfinkle",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Grinspiration H1",
		["Name"] = "sound\\music\\draenor\\mus_60_grinspiration_h1.mp3",
		["Id"] =  1067043,
		["Length"] = 101,
		["Artist"] = "Craig Stuart Garfinkle",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Grinspiration H2",
		["Name"] = "sound\\music\\draenor\\mus_60_grinspiration_h2.mp3",
		["Id"] =  1067044,
		["Length"] = 84,
		["Artist"] = "Craig Stuart Garfinkle",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Grommash Hellscream v3",
		["Name"] = "sound\\music\\draenor\\mus_60_grommashhellscreamv_3.mp3",
		["Id"] =  1061108,
		["Length"] = 72,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Grommash Hellscream v1",
		["Name"] = "sound\\music\\draenor\\mus_60_grommashhellscream_v1.mp3",
		["Id"] =  1061105,
		["Length"] = 165,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Grommash Hellscream v2A",
		["Name"] = "sound\\music\\draenor\\mus_60_grommashhellscream_v2a.mp3",
		["Id"] =  1061106,
		["Length"] = 47,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Grommash Hellscream v2B",
		["Name"] = "sound\\music\\draenor\\mus_60_grommashhellscream_v2b.mp3",
		["Id"] =  1061107,
		["Length"] = 55,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Herding Clans H",
		["Name"] = "sound\\music\\draenor\\mus_60_herdingclans_h.mp3",
		["Id"] =  1064160,
		["Length"] = 131,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Iron Dawn v1",
		["Name"] = "sound\\music\\draenor\\mus_60_irondawn_v1.mp3",
		["Id"] =  1061109,
		["Length"] = 150,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Iron Dawn v2",
		["Name"] = "sound\\music\\draenor\\mus_60_irondawn_v2.mp3",
		["Id"] =  1061110,
		["Length"] = 97,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Iron Dawn v3A",
		["Name"] = "sound\\music\\draenor\\mus_60_irondawn_v3a.mp3",
		["Id"] =  1061111,
		["Length"] = 59,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Iron Dawn v3B",
		["Name"] = "sound\\music\\draenor\\mus_60_irondawn_v3b.mp3",
		["Id"] =  1061112,
		["Length"] = 75,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Iron Dawn v4",
		["Name"] = "sound\\music\\draenor\\mus_60_irondawn_v4.mp3",
		["Id"] =  1061113,
		["Length"] = 154,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Keepers of the Temple H",
		["Name"] = "sound\\music\\draenor\\mus_60_keepersofthetemple_h.mp3",
		["Id"] =  1067045,
		["Length"] = 190,
		["Artist"] = "Eimear Noone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Khadgar's Plan v1",
		["Name"] = "sound\\music\\draenor\\mus_60_khadgarsplan_v1.mp3",
		["Id"] =  1061114,
		["Length"] = 144,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Khadgar's Plan v2",
		["Name"] = "sound\\music\\draenor\\mus_60_khadgarsplan_v2.mp3",
		["Id"] =  1061115,
		["Length"] = 127,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Khadgar's Plan v3",
		["Name"] = "sound\\music\\draenor\\mus_60_khadgarsplan_v3.mp3",
		["Id"] =  1061116,
		["Length"] = 139,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Khadgar's Plan v4",
		["Name"] = "sound\\music\\draenor\\mus_60_khadgarsplan_v4.mp3",
		["Id"] =  1061117,
		["Length"] = 114,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Laborious Misery A",
		["Name"] = "sound\\music\\draenor\\mus_60_laboriousmisery_a.mp3",
		["Id"] =  1061118,
		["Length"] = 68,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Laborious Misery H",
		["Name"] = "sound\\music\\draenor\\mus_60_laboriousmisery_h.mp3",
		["Id"] =  1061119,
		["Length"] = 69,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Magnificent Desolation 2A1",
		["Name"] = "sound\\music\\draenor\\mus_60_magnificentdesolation2_a1.mp3",
		["Id"] =  1067555,
		["Length"] = 83,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Magnificent Desolation 2A2",
		["Name"] = "sound\\music\\draenor\\mus_60_magnificentdesolation2_a2.mp3",
		["Id"] =  1067556,
		["Length"] = 97,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Magnificent Desolation 2H",
		["Name"] = "sound\\music\\draenor\\mus_60_magnificentdesolation2_h.mp3",
		["Id"] =  1067557,
		["Length"] = 239,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Magnificent Desolation 2H1",
		["Name"] = "sound\\music\\draenor\\mus_60_magnificentdesolation2_h1.mp3",
		["Id"] =  1067558,
		["Length"] = 130,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Magnificent Desolation 2H2",
		["Name"] = "sound\\music\\draenor\\mus_60_magnificentdesolation2_h2.mp3",
		["Id"] =  1067559,
		["Length"] = 111,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "Magnificent Desolation A",
		["Name"] = "sound\\music\\draenor\\mus_60_magnificentdesolation_a.mp3",
		["Id"] =  936338,
		["Length"] = 236,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "Magnificent Desolation B",
		["Name"] = "sound\\music\\draenor\\mus_60_magnificentdesolation_b.mp3",
		["Id"] =  936339,
		["Length"] = 158,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "Magnificent Desolation H",
		["Name"] = "sound\\music\\draenor\\mus_60_magnificentdesolation_h.mp3",
		["Id"] =  936340,
		["Length"] = 236,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Magnificent Desolation Piano A",
		["Name"] = "sound\\music\\draenor\\mus_60_magnificentdesolation_piano_a.mp3",
		["Id"] =  1080508,
		["Length"] = 35,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Malach H1",
		["Name"] = "sound\\music\\draenor\\mus_60_malach_h1.mp3",
		["Id"] =  1067046,
		["Length"] = 127,
		["Artist"] = "Eimear Noone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Malach H2",
		["Name"] = "sound\\music\\draenor\\mus_60_malach_h2.mp3",
		["Id"] =  1067047,
		["Length"] = 139,
		["Artist"] = "Eimear Noone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Malach H3",
		["Name"] = "sound\\music\\draenor\\mus_60_malach_h3.mp3",
		["Id"] =  1067048,
		["Length"] = 46,
		["Artist"] = "Eimear Noone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Malach H4",
		["Name"] = "sound\\music\\draenor\\mus_60_malach_h4.mp3",
		["Id"] =  1067049,
		["Length"] = 66,
		["Artist"] = "Eimear Noone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Malevolent Mystique A",
		["Name"] = "sound\\music\\draenor\\mus_60_malevolentmystique_a.mp3",
		["Id"] =  1061120,
		["Length"] = 78,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Malevolent Mystique B1",
		["Name"] = "sound\\music\\draenor\\mus_60_malevolentmystique_b1.mp3",
		["Id"] =  1061121,
		["Length"] = 78,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Malevolent Mystique B2",
		["Name"] = "sound\\music\\draenor\\mus_60_malevolentmystique_b2.mp3",
		["Id"] =  1061122,
		["Length"] = 88,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Malevolent Mystique C",
		["Name"] = "sound\\music\\draenor\\mus_60_malevolentmystique_c.mp3",
		["Id"] =  1061123,
		["Length"] = 90,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Malevolent Mystique H",
		["Name"] = "sound\\music\\draenor\\mus_60_malevolentmystique_h.mp3",
		["Id"] =  1061124,
		["Length"] = 124,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Malevolent Prescience B",
		["Name"] = "sound\\music\\draenor\\mus_60_malevolentprescience_b.mp3",
		["Id"] =  1061125,
		["Length"] = 66,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Malevolent Prescience H",
		["Name"] = "sound\\music\\draenor\\mus_60_malevolentprescience_h.mp3",
		["Id"] =  1061126,
		["Length"] = 145,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Man Down A1",
		["Name"] = "sound\\music\\draenor\\mus_60_mandown_a1.mp3",
		["Id"] =  1061127,
		["Length"] = 62,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Man Down A2",
		["Name"] = "sound\\music\\draenor\\mus_60_mandown_a2.mp3",
		["Id"] =  1061128,
		["Length"] = 60,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Man Down A3",
		["Name"] = "sound\\music\\draenor\\mus_60_mandown_a3.mp3",
		["Id"] =  1061129,
		["Length"] = 61,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Man Down B",
		["Name"] = "sound\\music\\draenor\\mus_60_mandown_b.mp3",
		["Id"] =  1061130,
		["Length"] = 82,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Man Down C",
		["Name"] = "sound\\music\\draenor\\mus_60_mandown_c.mp3",
		["Id"] =  1061131,
		["Length"] = 82,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Man Down D",
		["Name"] = "sound\\music\\draenor\\mus_60_mandown_d.mp3",
		["Id"] =  1061132,
		["Length"] = 168,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Man Down E",
		["Name"] = "sound\\music\\draenor\\mus_60_mandown_e.mp3",
		["Id"] =  1061133,
		["Length"] = 102,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Man Down F",
		["Name"] = "sound\\music\\draenor\\mus_60_mandown_f.mp3",
		["Id"] =  1061134,
		["Length"] = 89,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Man Down H1",
		["Name"] = "sound\\music\\draenor\\mus_60_mandown_h1.mp3",
		["Id"] =  1061135,
		["Length"] = 60,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mobilize A",
		["Name"] = "sound\\music\\draenor\\mus_60_mobilize_a.mp3",
		["Id"] =  1080413,
		["Length"] = 141,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mobilize B1",
		["Name"] = "sound\\music\\draenor\\mus_60_mobilize_b1.mp3",
		["Id"] =  1080414,
		["Length"] = 115,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mobilize B2",
		["Name"] = "sound\\music\\draenor\\mus_60_mobilize_b2.mp3",
		["Id"] =  1080415,
		["Length"] = 107,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mobilize C1",
		["Name"] = "sound\\music\\draenor\\mus_60_mobilize_c1.mp3",
		["Id"] =  1080416,
		["Length"] = 113,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mobilize C2",
		["Name"] = "sound\\music\\draenor\\mus_60_mobilize_c2.mp3",
		["Id"] =  1080417,
		["Length"] = 123,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mobilize D",
		["Name"] = "sound\\music\\draenor\\mus_60_mobilize_d.mp3",
		["Id"] =  1080418,
		["Length"] = 58,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mobilize E Stinger",
		["Name"] = "sound\\music\\draenor\\mus_60_mobilize_e_stinger.mp3",
		["Id"] =  1080419,
		["Length"] = 22,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mobilize H",
		["Name"] = "sound\\music\\draenor\\mus_60_mobilize_h.mp3",
		["Id"] =  1064161,
		["Length"] = 157,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mountains Intro Amb1",
		["Name"] = "sound\\music\\draenor\\mus_60_mountainsintro_a1.mp3",
		["Id"] =  1080423,
		["Length"] = 223,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mountains Intro Amb2",
		["Name"] = "sound\\music\\draenor\\mus_60_mountainsintro_a2.mp3",
		["Id"] =  1080424,
		["Length"] = 106,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mountains of Nagrand A1",
		["Name"] = "sound\\music\\draenor\\mus_60_mountainsofnagrand_a1.mp3",
		["Id"] =  1080425,
		["Length"] = 70,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mountains of Nagrand A2",
		["Name"] = "sound\\music\\draenor\\mus_60_mountainsofnagrand_a2.mp3",
		["Id"] =  1080426,
		["Length"] = 123,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mountains of Nagrand B",
		["Name"] = "sound\\music\\draenor\\mus_60_mountainsofnagrand_b.mp3",
		["Id"] =  1080427,
		["Length"] = 120,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mountains of Nagrand H",
		["Name"] = "sound\\music\\draenor\\mus_60_mountainsofnagrand_h.mp3",
		["Id"] =  1064162,
		["Length"] = 193,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mountains Ambient 2",
		["Name"] = "sound\\music\\draenor\\mus_60_mountains_ambient2.mp3",
		["Id"] =  1080420,
		["Length"] = 72,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mountains Ambient 3",
		["Name"] = "sound\\music\\draenor\\mus_60_mountains_ambient3.mp3",
		["Id"] =  1080421,
		["Length"] = 81,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mountains Stinger1",
		["Name"] = "sound\\music\\draenor\\mus_60_mountains_stinger1.mp3",
		["Id"] =  1080422,
		["Length"] = 16,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mystic A1",
		["Name"] = "sound\\music\\draenor\\mus_60_mystic_a1.mp3",
		["Id"] =  1067050,
		["Length"] = 73,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mystic A2",
		["Name"] = "sound\\music\\draenor\\mus_60_mystic_a2.mp3",
		["Id"] =  1067051,
		["Length"] = 86,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mystic B1",
		["Name"] = "sound\\music\\draenor\\mus_60_mystic_b1.mp3",
		["Id"] =  1067052,
		["Length"] = 58,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mystic B2",
		["Name"] = "sound\\music\\draenor\\mus_60_mystic_b2.mp3",
		["Id"] =  1067053,
		["Length"] = 63,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mystic C",
		["Name"] = "sound\\music\\draenor\\mus_60_mystic_c.mp3",
		["Id"] =  1067054,
		["Length"] = 68,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mystic C2",
		["Name"] = "sound\\music\\draenor\\mus_60_mystic_c2.mp3",
		["Id"] =  1067055,
		["Length"] = 87,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mystic D1",
		["Name"] = "sound\\music\\draenor\\mus_60_mystic_d1.mp3",
		["Id"] =  1067056,
		["Length"] = 65,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mystic D2",
		["Name"] = "sound\\music\\draenor\\mus_60_mystic_d2.mp3",
		["Id"] =  1067057,
		["Length"] = 83,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mystic E",
		["Name"] = "sound\\music\\draenor\\mus_60_mystic_e.mp3",
		["Id"] =  1067058,
		["Length"] = 22,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mystic F",
		["Name"] = "sound\\music\\draenor\\mus_60_mystic_f.mp3",
		["Id"] =  1067059,
		["Length"] = 25,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mystic G",
		["Name"] = "sound\\music\\draenor\\mus_60_mystic_g.mp3",
		["Id"] =  1067060,
		["Length"] = 15,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Mystic H",
		["Name"] = "sound\\music\\draenor\\mus_60_mystic_h.mp3",
		["Id"] =  1064163,
		["Length"] = 134,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Nagrand v1",
		["Name"] = "sound\\music\\draenor\\mus_60_nagrand_v1.mp3",
		["Id"] =  1061136,
		["Length"] = 149,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Nagrand v2",
		["Name"] = "sound\\music\\draenor\\mus_60_nagrand_v2.mp3",
		["Id"] =  1061137,
		["Length"] = 149,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Nagrand v3A",
		["Name"] = "sound\\music\\draenor\\mus_60_nagrand_v3a.mp3",
		["Id"] =  1061138,
		["Length"] = 62,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Nagrand v3B",
		["Name"] = "sound\\music\\draenor\\mus_60_nagrand_v3b.mp3",
		["Id"] =  1061139,
		["Length"] = 57,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Nagrand v4",
		["Name"] = "sound\\music\\draenor\\mus_60_nagrand_v4.mp3",
		["Id"] =  1061140,
		["Length"] = 86,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Nagrand v5",
		["Name"] = "sound\\music\\draenor\\mus_60_nagrand_v5.mp3",
		["Id"] =  1061141,
		["Length"] = 79,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Nagrand v6",
		["Name"] = "sound\\music\\draenor\\mus_60_nagrand_v6.mp3",
		["Id"] =  1061142,
		["Length"] = 133,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Nagrand v7",
		["Name"] = "sound\\music\\draenor\\mus_60_nagrand_v7.mp3",
		["Id"] =  1061143,
		["Length"] = 88,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Night Spires v1",
		["Name"] = "sound\\music\\draenor\\mus_60_nightspires_v1.mp3",
		["Id"] =  1061144,
		["Length"] = 135,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Night Spires v2",
		["Name"] = "sound\\music\\draenor\\mus_60_nightspires_v2.mp3",
		["Id"] =  1061145,
		["Length"] = 115,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Night Spires v3",
		["Name"] = "sound\\music\\draenor\\mus_60_nightspires_v3.mp3",
		["Id"] =  1061146,
		["Length"] = 134,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Night Spires v4",
		["Name"] = "sound\\music\\draenor\\mus_60_nightspires_v4.mp3",
		["Id"] =  1061147,
		["Length"] = 121,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Ogre Mines A1",
		["Name"] = "sound\\music\\draenor\\mus_60_ogremines_a1.mp3",
		["Id"] =  1067560,
		["Length"] = 130,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Ogre Mines A2",
		["Name"] = "sound\\music\\draenor\\mus_60_ogremines_a2.mp3",
		["Id"] =  1067561,
		["Length"] = 126,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Ogre Mines B",
		["Name"] = "sound\\music\\draenor\\mus_60_ogremines_b.mp3",
		["Id"] =  1067562,
		["Length"] = 133,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Ogre Mines H1",
		["Name"] = "sound\\music\\draenor\\mus_60_ogremines_h1.mp3",
		["Id"] =  1067563,
		["Length"] = 131,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Ogre Mines H2",
		["Name"] = "sound\\music\\draenor\\mus_60_ogremines_h2.mp3",
		["Id"] =  1067564,
		["Length"] = 124,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Patience Point A1",
		["Name"] = "sound\\music\\draenor\\mus_60_patiencepoint_a1.mp3",
		["Id"] =  1061148,
		["Length"] = 77,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Patience Point A2",
		["Name"] = "sound\\music\\draenor\\mus_60_patiencepoint_a2.mp3",
		["Id"] =  1061149,
		["Length"] = 97,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Patience Point B1",
		["Name"] = "sound\\music\\draenor\\mus_60_patiencepoint_b1.mp3",
		["Id"] =  1061150,
		["Length"] = 77,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Patience Point B2",
		["Name"] = "sound\\music\\draenor\\mus_60_patiencepoint_b2.mp3",
		["Id"] =  1061151,
		["Length"] = 97,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Patience Point H",
		["Name"] = "sound\\music\\draenor\\mus_60_patiencepoint_h.mp3",
		["Id"] =  1061152,
		["Length"] = 179,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Plight of the Ogres H1",
		["Name"] = "sound\\music\\draenor\\mus_60_plightoftheogres_h1.mp3",
		["Id"] =  1067061,
		["Length"] = 99,
		["Artist"] = "Craig Stuart Garfinkle",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Plight of the Ogres H2",
		["Name"] = "sound\\music\\draenor\\mus_60_plightoftheogres_h2.mp3",
		["Id"] =  1067062,
		["Length"] = 77,
		["Artist"] = "Craig Stuart Garfinkle",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "Premonition H",
		["Name"] = "sound\\music\\draenor\\mus_60_premonition_h.mp3",
		["Id"] =  936341,
		["Length"] = 131,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Prevalent Confliction A",
		["Name"] = "sound\\music\\draenor\\mus_60_prevalentconfliction_a.mp3",
		["Id"] =  1061153,
		["Length"] = 94,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Protect the Throne Intro H",
		["Name"] = "sound\\music\\draenor\\mus_60_protectthethrone_h1.mp3",
		["Id"] =  1067063,
		["Length"] = 67,
		["Artist"] = "Eimear Noone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Protect the Throne H2",
		["Name"] = "sound\\music\\draenor\\mus_60_protectthethrone_h2.mp3",
		["Id"] =  1067064,
		["Length"] = 98,
		["Artist"] = "Eimear Noone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Protect the Throne H3",
		["Name"] = "sound\\music\\draenor\\mus_60_protectthethrone_h3.mp3",
		["Id"] =  1067065,
		["Length"] = 92,
		["Artist"] = "Eimear Noone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Proudmoore H",
		["Name"] = "sound\\music\\draenor\\mus_60_proudmoore_h.mp3",
		["Id"] =  1064164,
		["Length"] = 104,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Quiet Heart A",
		["Name"] = "sound\\music\\draenor\\mus_60_quietheart_a.mp3",
		["Id"] =  1067565,
		["Length"] = 224,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Quiet Heart A1",
		["Name"] = "sound\\music\\draenor\\mus_60_quietheart_a1.mp3",
		["Id"] =  1067566,
		["Length"] = 108,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Quiet Heart A2",
		["Name"] = "sound\\music\\draenor\\mus_60_quietheart_a2.mp3",
		["Id"] =  1067567,
		["Length"] = 116,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Quiet Heart H",
		["Name"] = "sound\\music\\draenor\\mus_60_quietheart_h.mp3",
		["Id"] =  1067568,
		["Length"] = 229,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Quiet Heart H1",
		["Name"] = "sound\\music\\draenor\\mus_60_quietheart_h1.mp3",
		["Id"] =  1067569,
		["Length"] = 114,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Quiet Heart H2",
		["Name"] = "sound\\music\\draenor\\mus_60_quietheart_h2.mp3",
		["Id"] =  1067570,
		["Length"] = 118,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Rise to the Dark H1",
		["Name"] = "sound\\music\\draenor\\mus_60_risetothedark_h1.mp3",
		["Id"] =  1067066,
		["Length"] = 93,
		["Artist"] = "Eimear Noone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Rise to the Dark H2",
		["Name"] = "sound\\music\\draenor\\mus_60_risetothedark_h2.mp3",
		["Id"] =  1067067,
		["Length"] = 124,
		["Artist"] = "Eimear Noone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Sacrifice 2A",
		["Name"] = "sound\\music\\draenor\\mus_60_sacrifice_2a.mp3",
		["Id"] =  1061154,
		["Length"] = 89,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Sacrifice 2H",
		["Name"] = "sound\\music\\draenor\\mus_60_sacrifice_2h.mp3",
		["Id"] =  1061155,
		["Length"] = 88,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Sacrifice B",
		["Name"] = "sound\\music\\draenor\\mus_60_sacrifice_b.mp3",
		["Id"] =  1061156,
		["Length"] = 89,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Shadowmoon Pt1A",
		["Name"] = "sound\\music\\draenor\\mus_60_shadowmoonpt1_a.mp3",
		["Id"] =  1067571,
		["Length"] = 110,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Shadowmoon Pt1H",
		["Name"] = "sound\\music\\draenor\\mus_60_shadowmoonpt1_h.mp3",
		["Id"] =  1067572,
		["Length"] = 138,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Shadowmoon Rising H",
		["Name"] = "sound\\music\\draenor\\mus_60_shadowmoonrising_h.mp3",
		["Id"] =  1067068,
		["Length"] = 155,
		["Artist"] = "Eimear Noone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Shadowmoon Sunset Intro H",
		["Name"] = "sound\\music\\draenor\\mus_60_shadowmoonsunsetintro_h.mp3",
		["Id"] =  1067069,
		["Length"] = 70,
		["Artist"] = "Craig Stuart Garfinkle",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Shadowmoon Sunset Reprise H",
		["Name"] = "sound\\music\\draenor\\mus_60_shadowmoonsunsetreprise_h.mp3",
		["Id"] =  1067070,
		["Length"] = 45,
		["Artist"] = "Craig Stuart Garfinkle",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Shadowmoon v1",
		["Name"] = "sound\\music\\draenor\\mus_60_shadowmoon_v1.mp3",
		["Id"] =  1061157,
		["Length"] = 128,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Shadowmoon v2",
		["Name"] = "sound\\music\\draenor\\mus_60_shadowmoon_v2.mp3",
		["Id"] =  1061158,
		["Length"] = 127,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Shadowmoon v3",
		["Name"] = "sound\\music\\draenor\\mus_60_shadowmoon_v3.mp3",
		["Id"] =  1061159,
		["Length"] = 122,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Shadowmoon v4",
		["Name"] = "sound\\music\\draenor\\mus_60_shadowmoon_v4.mp3",
		["Id"] =  1061160,
		["Length"] = 61,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Shadowmoon v5",
		["Name"] = "sound\\music\\draenor\\mus_60_shadowmoon_v5.mp3",
		["Id"] =  1061161,
		["Length"] = 94,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Shakedown A",
		["Name"] = "sound\\music\\draenor\\mus_60_shakedown_a.mp3",
		["Id"] =  1061162,
		["Length"] = 103,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Shakedown B",
		["Name"] = "sound\\music\\draenor\\mus_60_shakedown_b.mp3",
		["Id"] =  1061163,
		["Length"] = 65,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Shakedown C",
		["Name"] = "sound\\music\\draenor\\mus_60_shakedown_c.mp3",
		["Id"] =  1061164,
		["Length"] = 102,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Smack the Giant H1",
		["Name"] = "sound\\music\\draenor\\mus_60_smackthegiant_h1.mp3",
		["Id"] =  1067071,
		["Length"] = 55,
		["Artist"] = "Craig Stuart Garfinkle",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Smack the Giant H2",
		["Name"] = "sound\\music\\draenor\\mus_60_smackthegiant_h2.mp3",
		["Id"] =  1067072,
		["Length"] = 53,
		["Artist"] = "Craig Stuart Garfinkle",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Smack the Giant H3",
		["Name"] = "sound\\music\\draenor\\mus_60_smackthegiant_h3.mp3",
		["Id"] =  1067073,
		["Length"] = 52,
		["Artist"] = "Craig Stuart Garfinkle",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Smack the Giant H4",
		["Name"] = "sound\\music\\draenor\\mus_60_smackthegiant_h4.mp3",
		["Id"] =  1067074,
		["Length"] = 21,
		["Artist"] = "Craig Stuart Garfinkle",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Spires of Arak v1",
		["Name"] = "sound\\music\\draenor\\mus_60_spiresofarak_v1.mp3",
		["Id"] =  1061165,
		["Length"] = 158,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Spires of Arak v2",
		["Name"] = "sound\\music\\draenor\\mus_60_spiresofarak_v2.mp3",
		["Id"] =  1061166,
		["Length"] = 101,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Spires of Arak v4",
		["Name"] = "sound\\music\\draenor\\mus_60_spiresofarak_v4.mp3",
		["Id"] =  1061167,
		["Length"] = 56,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Stormlords on the March H1",
		["Name"] = "sound\\music\\draenor\\mus_60_stormlordsonthemarch_h1.mp3",
		["Id"] =  1067075,
		["Length"] = 88,
		["Artist"] = "Eimear Noone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Stormlords on the March H2",
		["Name"] = "sound\\music\\draenor\\mus_60_stormlordsonthemarch_h2.mp3",
		["Id"] =  1067076,
		["Length"] = 46,
		["Artist"] = "Eimear Noone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Stormlords on the March H3",
		["Name"] = "sound\\music\\draenor\\mus_60_stormlordsonthemarch_h3.mp3",
		["Id"] =  1067077,
		["Length"] = 101,
		["Artist"] = "Eimear Noone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "The Clans Join A",
		["Name"] = "sound\\music\\draenor\\mus_60_theclansjoin_a.mp3",
		["Id"] =  936342,
		["Length"] = 212,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "The Clans Join B",
		["Name"] = "sound\\music\\draenor\\mus_60_theclansjoin_b.mp3",
		["Id"] =  936343,
		["Length"] = 212,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor (BC)",
		["Song"] = "The Clans Join H",
		["Name"] = "sound\\music\\draenor\\mus_60_theclansjoin_h.mp3",
		["Id"] =  936344,
		["Length"] = 212,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Tome A",
		["Name"] = "sound\\music\\draenor\\mus_60_tome_a.mp3",
		["Id"] =  1061171,
		["Length"] = 54,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Tome B",
		["Name"] = "sound\\music\\draenor\\mus_60_tome_b.mp3",
		["Id"] =  1061172,
		["Length"] = 55,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Tome H",
		["Name"] = "sound\\music\\draenor\\mus_60_tome_h.mp3",
		["Id"] =  1061173,
		["Length"] = 56,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Traversing the Spires A",
		["Name"] = "sound\\music\\draenor\\mus_60_traversingthespires_a.mp3",
		["Id"] =  1067573,
		["Length"] = 128,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Traversing the Spires B",
		["Name"] = "sound\\music\\draenor\\mus_60_traversingthespires_b.mp3",
		["Id"] =  1067574,
		["Length"] = 123,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Traversing the Spires C",
		["Name"] = "sound\\music\\draenor\\mus_60_traversingthespires_c.mp3",
		["Id"] =  1067575,
		["Length"] = 156,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Traversing the Spires H1",
		["Name"] = "sound\\music\\draenor\\mus_60_traversingthespires_h1.mp3",
		["Id"] =  1067576,
		["Length"] = 128,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Traversing the Spires H2",
		["Name"] = "sound\\music\\draenor\\mus_60_traversingthespires_h2.mp3",
		["Id"] =  1067577,
		["Length"] = 127,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Ts Have It A",
		["Name"] = "sound\\music\\draenor\\mus_60_tshaveit_a.mp3",
		["Id"] =  1061174,
		["Length"] = 115,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Ts Have It B",
		["Name"] = "sound\\music\\draenor\\mus_60_tshaveit_b.mp3",
		["Id"] =  1061175,
		["Length"] = 52,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Ts Have It H",
		["Name"] = "sound\\music\\draenor\\mus_60_tshaveit_h.mp3",
		["Id"] =  1061177,
		["Length"] = 164,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Village A",
		["Name"] = "sound\\music\\draenor\\mus_60_village_a.mp3",
		["Id"] =  1067078,
		["Length"] = 151,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Village B",
		["Name"] = "sound\\music\\draenor\\mus_60_village_b.mp3",
		["Id"] =  1067079,
		["Length"] = 91,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Village C1",
		["Name"] = "sound\\music\\draenor\\mus_60_village_c1.mp3",
		["Id"] =  1067080,
		["Length"] = 63,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Village C2",
		["Name"] = "sound\\music\\draenor\\mus_60_village_c2.mp3",
		["Id"] =  1067081,
		["Length"] = 88,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Village D",
		["Name"] = "sound\\music\\draenor\\mus_60_village_d.mp3",
		["Id"] =  1067082,
		["Length"] = 91,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Village E",
		["Name"] = "sound\\music\\draenor\\mus_60_village_e.mp3",
		["Id"] =  1067083,
		["Length"] = 9,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Village F",
		["Name"] = "sound\\music\\draenor\\mus_60_village_f.mp3",
		["Id"] =  1067084,
		["Length"] = 11,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Village H",
		["Name"] = "sound\\music\\draenor\\mus_60_village_h.mp3",
		["Id"] =  1064165,
		["Length"] = 150,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Voce C",
		["Name"] = "sound\\music\\draenor\\mus_60_voce_c.mp3",
		["Id"] =  1061178,
		["Length"] = 48,
		["Artist"] = "Edo Guidotti",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Vows A1",
		["Name"] = "sound\\music\\draenor\\mus_60_vows_a1.mp3",
		["Id"] =  1067578,
		["Length"] = 55,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Vows A2",
		["Name"] = "sound\\music\\draenor\\mus_60_vows_a2.mp3",
		["Id"] =  1067579,
		["Length"] = 49,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Vows A3",
		["Name"] = "sound\\music\\draenor\\mus_60_vows_a3.mp3",
		["Id"] =  1067580,
		["Length"] = 101,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Vows B",
		["Name"] = "sound\\music\\draenor\\mus_60_vows_b.mp3",
		["Id"] =  1067581,
		["Length"] = 118,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Vows C1",
		["Name"] = "sound\\music\\draenor\\mus_60_vows_c1.mp3",
		["Id"] =  1067582,
		["Length"] = 82,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Vows C2",
		["Name"] = "sound\\music\\draenor\\mus_60_vows_c2.mp3",
		["Id"] =  1067583,
		["Length"] = 98,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Vows C3",
		["Name"] = "sound\\music\\draenor\\mus_60_vows_c3.mp3",
		["Id"] =  1067584,
		["Length"] = 130,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Vows D1",
		["Name"] = "sound\\music\\draenor\\mus_60_vows_d1.mp3",
		["Id"] =  1067585,
		["Length"] = 89,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Vows D2",
		["Name"] = "sound\\music\\draenor\\mus_60_vows_d2.mp3",
		["Id"] =  1067586,
		["Length"] = 86,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Vows H1",
		["Name"] = "sound\\music\\draenor\\mus_60_vows_h1.mp3",
		["Id"] =  1067587,
		["Length"] = 100,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Vows H2",
		["Name"] = "sound\\music\\draenor\\mus_60_vows_h2.mp3",
		["Id"] =  1067588,
		["Length"] = 85,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Vows H3",
		["Name"] = "sound\\music\\draenor\\mus_60_vows_h3.mp3",
		["Id"] =  1067589,
		["Length"] = 103,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Vows H4",
		["Name"] = "sound\\music\\draenor\\mus_60_vows_h4.mp3",
		["Id"] =  1067590,
		["Length"] = 107,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Vows H5",
		["Name"] = "sound\\music\\draenor\\mus_60_vows_h5.mp3",
		["Id"] =  1067591,
		["Length"] = 117,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Warriors Journey A",
		["Name"] = "sound\\music\\draenor\\mus_60_warriorsjourney_a.mp3",
		["Id"] =  1067085,
		["Length"] = 65,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Warriors Journey B1",
		["Name"] = "sound\\music\\draenor\\mus_60_warriorsjourney_b1.mp3",
		["Id"] =  1067086,
		["Length"] = 65,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Warriors Journey B2",
		["Name"] = "sound\\music\\draenor\\mus_60_warriorsjourney_b2.mp3",
		["Id"] =  1067087,
		["Length"] = 53,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Warriors Journey B3",
		["Name"] = "sound\\music\\draenor\\mus_60_warriorsjourney_b3.mp3",
		["Id"] =  1067088,
		["Length"] = 66,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Warriors Journey C",
		["Name"] = "sound\\music\\draenor\\mus_60_warriorsjourney_c.mp3",
		["Id"] =  1067089,
		["Length"] = 17,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Warriors Journey D",
		["Name"] = "sound\\music\\draenor\\mus_60_warriorsjourney_d.mp3",
		["Id"] =  1067090,
		["Length"] = 16,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Warriors Journey E",
		["Name"] = "sound\\music\\draenor\\mus_60_warriorsjourney_e.mp3",
		["Id"] =  1067091,
		["Length"] = 17,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Warriors Journey H1",
		["Name"] = "sound\\music\\draenor\\mus_60_warriorsjourney_h1.mp3",
		["Id"] =  1064166,
		["Length"] = 92,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Warriors Journey H2",
		["Name"] = "sound\\music\\draenor\\mus_60_warriorsjourney_h2.mp3",
		["Id"] =  1064167,
		["Length"] = 73,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Warriors Journey H3",
		["Name"] = "sound\\music\\draenor\\mus_60_warriorsjourney_h3.mp3",
		["Id"] =  1064168,
		["Length"] = 72,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Warriors Journey H4",
		["Name"] = "sound\\music\\draenor\\mus_60_warriorsjourney_h4.mp3",
		["Id"] =  1064169,
		["Length"] = 79,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Warsong v1",
		["Name"] = "sound\\music\\draenor\\mus_60_warsong_v1.mp3",
		["Id"] =  1064170,
		["Length"] = 153,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Warsong v2",
		["Name"] = "sound\\music\\draenor\\mus_60_warsong_v2.mp3",
		["Id"] =  1064171,
		["Length"] = 152,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Warsong v3A",
		["Name"] = "sound\\music\\draenor\\mus_60_warsong_v3a.mp3",
		["Id"] =  1061179,
		["Length"] = 83,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Warsong v3B",
		["Name"] = "sound\\music\\draenor\\mus_60_warsong_v3b.mp3",
		["Id"] =  1061180,
		["Length"] = 72,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Warsong v4",
		["Name"] = "sound\\music\\draenor\\mus_60_warsong_v4.mp3",
		["Id"] =  1061181,
		["Length"] = 155,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Wolf at the Gates A",
		["Name"] = "sound\\music\\draenor\\mus_60_wolfatthegates_a.mp3",
		["Id"] =  1080510,
		["Length"] = 162,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Wolf at the Gates B",
		["Name"] = "sound\\music\\draenor\\mus_60_wolfatthegates_b.mp3",
		["Id"] =  1080511,
		["Length"] = 162,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Wolf at the Gates H",
		["Name"] = "sound\\music\\draenor\\mus_60_wolfatthegates_h.mp3",
		["Id"] =  1080514,
		["Length"] = 162,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Wonder A",
		["Name"] = "sound\\music\\draenor\\mus_60_wonder_a.mp3",
		["Id"] =  1067092,
		["Length"] = 19,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Wonder H",
		["Name"] = "sound\\music\\draenor\\mus_60_wonder_h.mp3",
		["Id"] =  1064172,
		["Length"] = 153,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "World Expo A1",
		["Name"] = "sound\\music\\draenor\\mus_60_worldexpo_a1.mp3",
		["Id"] =  1067093,
		["Length"] = 54,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "World Expo A2",
		["Name"] = "sound\\music\\draenor\\mus_60_worldexpo_a2.mp3",
		["Id"] =  1067094,
		["Length"] = 54,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "World Expo A3",
		["Name"] = "sound\\music\\draenor\\mus_60_worldexpo_a3.mp3",
		["Id"] =  1067095,
		["Length"] = 60,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "World Expo B",
		["Name"] = "sound\\music\\draenor\\mus_60_worldexpo_b.mp3",
		["Id"] =  1067096,
		["Length"] = 15,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "World Expo C",
		["Name"] = "sound\\music\\draenor\\mus_60_worldexpo_c.mp3",
		["Id"] =  1067097,
		["Length"] = 22,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "World Expo D",
		["Name"] = "sound\\music\\draenor\\mus_60_worldexpo_d.mp3",
		["Id"] =  1067098,
		["Length"] = 22,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "World Expo E1",
		["Name"] = "sound\\music\\draenor\\mus_60_worldexpo_e1.mp3",
		["Id"] =  1067099,
		["Length"] = 56,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "World Expo E2",
		["Name"] = "sound\\music\\draenor\\mus_60_worldexpo_e2.mp3",
		["Id"] =  1067100,
		["Length"] = 64,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "World Expo F1",
		["Name"] = "sound\\music\\draenor\\mus_60_worldexpo_f1.mp3",
		["Id"] =  1067101,
		["Length"] = 64,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "World Expo F2",
		["Name"] = "sound\\music\\draenor\\mus_60_worldexpo_f2.mp3",
		["Id"] =  1067102,
		["Length"] = 64,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "World Expo F3",
		["Name"] = "sound\\music\\draenor\\mus_60_worldexpo_f3.mp3",
		["Id"] =  1067103,
		["Length"] = 39,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "World Expo G",
		["Name"] = "sound\\music\\draenor\\mus_60_worldexpo_g.mp3",
		["Id"] =  1067104,
		["Length"] = 19,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "World Expo H",
		["Name"] = "sound\\music\\draenor\\mus_60_worldexpo_h.mp3",
		["Id"] =  1064173,
		["Length"] = 168,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
-------------------------------
--Patch 6.0 Music Starts Here--
-------------------------------	
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Falling 1A",
		["Name"] = "sound\\music\\draenor\\mus_62_falling_1a.mp3",
		["Id"] =  1146873,
		["Length"] = 71,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Falling 1B",
		["Name"] = "sound\\music\\draenor\\mus_62_falling_1b.mp3",
		["Id"] =  1146874,
		["Length"] = 74,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Falling 2H",
		["Name"] = "sound\\music\\draenor\\mus_62_falling_2h.mp3",
		["Id"] =  1146875,
		["Length"] = 71,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Fel Essence A",
		["Name"] = "sound\\music\\draenor\\mus_62_felessence_a.mp3",
		["Id"] =  1146876,
		["Length"] = 86,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Fel Essence B",
		["Name"] = "sound\\music\\draenor\\mus_62_felessence_b.mp3",
		["Id"] =  1146877,
		["Length"] = 60,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Fel Essence C",
		["Name"] = "sound\\music\\draenor\\mus_62_felessence_c.mp3",
		["Id"] =  1146878,
		["Length"] = 46,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Fel Essence D",
		["Name"] = "sound\\music\\draenor\\mus_62_felessence_d.mp3",
		["Id"] =  1146879,
		["Length"] = 48,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Fel Essence H",
		["Name"] = "sound\\music\\draenor\\mus_62_felessence_h.mp3",
		["Id"] =  1146880,
		["Length"] = 120,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Feu De L'Enfer A",
		["Name"] = "sound\\music\\draenor\\mus_62_feudelenfer_a.mp3",
		["Id"] =  1146881,
		["Length"] = 116,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Feu De L'Enfer H",
		["Name"] = "sound\\music\\draenor\\mus_62_feudelenfer_h.mp3",
		["Id"] =  1146882,
		["Length"] = 119,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Lost Moon A",
		["Name"] = "sound\\music\\draenor\\mus_62_lostmoon_a.mp3",
		["Id"] =  1146883,
		["Length"] = 79,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Lost Moon B",
		["Name"] = "sound\\music\\draenor\\mus_62_lostmoon_b.mp3",
		["Id"] =  1146884,
		["Length"] = 60,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Lost Moon H",
		["Name"] = "sound\\music\\draenor\\mus_62_lostmoon_h.mp3",
		["Id"] =  1146885,
		["Length"] = 88,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Mortal Night A",
		["Name"] = "sound\\music\\draenor\\mus_62_mortalnight_a.mp3",
		["Id"] =  1146886,
		["Length"] = 50,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Mortal Night B",
		["Name"] = "sound\\music\\draenor\\mus_62_mortalnight_b.mp3",
		["Id"] =  1146887,
		["Length"] = 13,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Mortal Night C",
		["Name"] = "sound\\music\\draenor\\mus_62_mortalnight_c.mp3",
		["Id"] =  1146888,
		["Length"] = 74,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Mortal Night H",
		["Name"] = "sound\\music\\draenor\\mus_62_mortalnight_h.mp3",
		["Id"] =  1146889,
		["Length"] = 152,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Tanaander A",
		["Name"] = "sound\\music\\draenor\\mus_62_tanaander_a.mp3",
		["Id"] =  1146890,
		["Length"] = 118,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Tanaander B",
		["Name"] = "sound\\music\\draenor\\mus_62_tanaander_b.mp3",
		["Id"] =  1146891,
		["Length"] = 118,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Tanaander C",
		["Name"] = "sound\\music\\draenor\\mus_62_tanaander_c.mp3",
		["Id"] =  1146892,
		["Length"] = 125,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Tanaander H",
		["Name"] = "sound\\music\\draenor\\mus_62_tanaander_h.mp3",
		["Id"] =  1146893,
		["Length"] = 125,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Tanaan Gloom A",
		["Name"] = "sound\\music\\draenor\\mus_62_tanaangloom_a.mp3",
		["Id"] =  1146894,
		["Length"] = 109,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Tanaan Gloom B",
		["Name"] = "sound\\music\\draenor\\mus_62_tanaangloom_b.mp3",
		["Id"] =  1146895,
		["Length"] = 103,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Tanaan Gloom C",
		["Name"] = "sound\\music\\draenor\\mus_62_tanaangloom_c.mp3",
		["Id"] =  1146896,
		["Length"] = 62,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Tanaan Gloom H",
		["Name"] = "sound\\music\\draenor\\mus_62_tanaangloom_h.mp3",
		["Id"] =  1146897,
		["Length"] = 114,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "The Wanderer A",
		["Name"] = "sound\\music\\draenor\\mus_62_thewanderer_a.mp3",
		["Id"] =  1146898,
		["Length"] = 138,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "The Wanderer B",
		["Name"] = "sound\\music\\draenor\\mus_62_thewanderer_b.mp3",
		["Id"] =  1146899,
		["Length"] = 71,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "The Wanderer H",
		["Name"] = "sound\\music\\draenor\\mus_62_thewanderer_h.mp3",
		["Id"] =  1146900,
		["Length"] = 161,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Undaunted A",
		["Name"] = "sound\\music\\draenor\\mus_62_undaunted_a.mp3",
		["Id"] =  1146901,
		["Length"] = 101,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Undaunted B",
		["Name"] = "sound\\music\\draenor\\mus_62_undaunted_b.mp3",
		["Id"] =  1146902,
		["Length"] = 87,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.2 - Fury of Hellfire",
		["Song"] = "Undaunted H",
		["Name"] = "sound\\music\\draenor\\mus_62_undaunted_h.mp3",
		["Id"] =  1146903,
		["Length"] = 101,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 3.3 - Fall of the Lich King",
		["Song"] = "Invincible",
		["Name"] = "sound\\music\\draenor\\mus_invincible.mp3",
		["Id"] =  1100052,
		["Length"] = 197,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
}
EpicMusicPlayer:AddPlayList("Draenor", playlist1, false, true)
