-- EpicMusicPlayer playlist created by EpicPlaylistCreator version 0.1.
local _, _, _, tocversion = GetBuildInfo()
if tocversion < 80200 then return end

local L = LibStub("AceLocale-3.0"):GetLocale("EpicMusicPlayer")

local playlist1={
  ["listName"] = L["Draenor"],
  ["playlistVersion"] = "3.1",
  ["locked"] =  "true",
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Hero's Sacrifice v1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_AHerosSacrifice_v1.mp3",
    ["Id"] = 1068302,
    ["Length"] = 117,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Hero's Sacrifice v2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_AHerosSacrifice_v2.mp3",
    ["Id"] = 1068303,
    ["Length"] = 102,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Hero's Sacrifice v3A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_AHerosSacrifice_v3A.mp3",
    ["Id"] = 1068304,
    ["Length"] = 55,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Hero's Sacrifice v3B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_AHerosSacrifice_v3B.mp3",
    ["Id"] = 1068305,
    ["Length"] = 60,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Hero's Sacrifice v4",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_AHerosSacrifice_v4.mp3",
    ["Id"] = 1068306,
    ["Length"] = 24,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Hero's Sacrifice v5",
    ["Name"] = "sound\\music\\Draenor\\mus_60_AHerosSacrifice_v5.mp3",
    ["Id"] = 1068307,
    ["Length"] = 67,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Light in the Darkness v1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_ALightintheDarkness_v1.mp3",
    ["Id"] = 1068308,
    ["Length"] = 155,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Light in the Darkness v2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_ALightintheDarkness_v2.mp3",
    ["Id"] = 1068309,
    ["Length"] = 137,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Light in the Darkness v3",
    ["Name"] = "sound\\music\\Draenor\\mus_60_ALightintheDarkness_v3.mp3",
    ["Id"] = 1061098,
    ["Length"] = 154,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Light in the Darkness v3A",
    ["Name"] = "sound\\music\\Draenor\\mus_60_ALightintheDarkness_v3a.mp3",
    ["Id"] = 1061099,
    ["Length"] = 70,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Arak 2 H",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Arak2_H.mp3",
    ["Id"] = 1064152,
    ["Length"] = 157,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Army A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Army_A.mp3",
    ["Id"] = 1080405,
    ["Length"] = 143,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Army Stinger1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Army_Stinger1.mp3",
    ["Id"] = 1080406,
    ["Length"] = 12,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Army Stinger2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Army_Stinger2.mp3",
    ["Id"] = 1080407,
    ["Length"] = 13,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Siege of Worlds v2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ASiegeofWorlds_MainTitle.mp3",
    ["Id"] = 1042428,
    ["Length"] = 727,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Blackrock A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Blackrock_A.mp3",
    ["Id"] = 1080491,
    ["Length"] = 83,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Caverns of Life H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_CavernsofLife_H.mp3",
    ["Id"] = 1064156,
    ["Length"] = 112,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Chieftans Gather H",
    ["Name"] = "sound\\music\\Draenor\\mus_60_ChieftansGather_H.mp3",
    ["Id"] = 1067039,
    ["Length"] = 97,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Cold Mountain Duet H",
    ["Name"] = "sound\\music\\Draenor\\mus_60_ColdMountain_Duet_H.mp3",
    ["Id"] = 1080507,
    ["Length"] = 156,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Elune's Shadow A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ElunesShadow_A.mp3",
    ["Id"] = 936323,
    ["Length"] = 45,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Elune's Shadow B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ElunesShadow_B.mp3",
    ["Id"] = 936324,
    ["Length"] = 34,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Elune's Shadow C",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ElunesShadow_C.mp3",
    ["Id"] = 936325,
    ["Length"] = 52,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Elune's Shadow H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ElunesShadow_H.mp3",
    ["Id"] = 936326,
    ["Length"] = 94,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Eternal Night H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_EternalNight_H.mp3",
    ["Id"] = 936327,
    ["Length"] = 76,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Ethereal Essence H1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_EtherealEssence_H1.mp3",
    ["Id"] = 1064158,
    ["Length"] = 102,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Ethereal Essence H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_EtherealEssence_H2.mp3",
    ["Id"] = 1064159,
    ["Length"] = 88,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Fel Wasteland A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_FelWasteland_A.mp3",
    ["Id"] = 936328,
    ["Length"] = 71,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Fel Wasteland B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_FelWasteland_B.mp3",
    ["Id"] = 936329,
    ["Length"] = 90,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Fel Wasteland C",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_FelWasteland_C.mp3",
    ["Id"] = 936330,
    ["Length"] = 32,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Fel Wasteland H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_FelWasteland_H.mp3",
    ["Id"] = 936331,
    ["Length"] = 85,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Foreshadowing H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Foreshadowing_H.mp3",
    ["Id"] = 936332,
    ["Length"] = 124,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Forsaken A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Forsaken_A.mp3",
    ["Id"] = 936333,
    ["Length"] = 82,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Forsaken H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Forsaken_H.mp3",
    ["Id"] = 936334,
    ["Length"] = 125,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Gardens of Karabor A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_GardensOfKarabor_A.mp3",
    ["Id"] = 936335,
    ["Length"] = 99,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Gardens of Karabor B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_GardensOfKarabor_B.mp3",
    ["Id"] = 936336,
    ["Length"] = 47,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Gardens of Karabor H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_GardensOfKarabor_H.mp3",
    ["Id"] = 936337,
    ["Length"] = 127,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Garrison Building Complete",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_GarrisonBuildingComplete.mp3",
    ["Id"] = 1080412,
    ["Length"] = 14,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Garrison Building Complete v2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_GarrisonBuildingComplete2.mp3",
    ["Id"] = 1087470,
    ["Length"] = 8,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Grinspiration A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Grinspiration_A.mp3",
    ["Id"] = 1067040,
    ["Length"] = 90,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Grinspiration B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Grinspiration_B.mp3",
    ["Id"] = 1067041,
    ["Length"] = 82,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Grinspiration C",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Grinspiration_C.mp3",
    ["Id"] = 1067042,
    ["Length"] = 124,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Grinspiration H1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Grinspiration_H1.mp3",
    ["Id"] = 1067043,
    ["Length"] = 101,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Grinspiration H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Grinspiration_H2.mp3",
    ["Id"] = 1067044,
    ["Length"] = 84,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Grommash Hellscream v1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_GrommashHellscream_v1.mp3",
    ["Id"] = 1061105,
    ["Length"] = 165,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Grommash Hellscream v2A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_GrommashHellscream_v2A.mp3",
    ["Id"] = 1061106,
    ["Length"] = 48,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Grommash Hellscream v2B",
    ["Name"] = "sound\\music\\Draenor\\mus_60_GrommashHellscream_v2B.mp3",
    ["Id"] = 1061107,
    ["Length"] = 55,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Grommash Hellscream v3",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_GrommashHellscreamv_3.mp3",
    ["Id"] = 1061108,
    ["Length"] = 73,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Herding Clans H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_HerdingClans_H.mp3",
    ["Id"] = 1064160,
    ["Length"] = 132,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Iron Dawn v1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_IronDawn_v1.mp3",
    ["Id"] = 1061109,
    ["Length"] = 151,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Iron Dawn v2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_IronDawn_v2.mp3",
    ["Id"] = 1061110,
    ["Length"] = 97,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Iron Dawn v3A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_IronDawn_v3A.mp3",
    ["Id"] = 1061111,
    ["Length"] = 60,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Iron Dawn v3B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_IronDawn_v3B.mp3",
    ["Id"] = 1061112,
    ["Length"] = 75,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Iron Dawn v4",
    ["Name"] = "sound\\music\\Draenor\\mus_60_IronDawn_v4.mp3",
    ["Id"] = 1061113,
    ["Length"] = 154,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Keepers of the Temple H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_KeepersoftheTemple_H.mp3",
    ["Id"] = 1067045,
    ["Length"] = 190,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Khadgar's Plan v1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_KhadgarsPlan_v1.mp3",
    ["Id"] = 1061114,
    ["Length"] = 145,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Khadgar's Plan v2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_KhadgarsPlan_v2.mp3",
    ["Id"] = 1061115,
    ["Length"] = 128,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Khadgar's Plan v3",
    ["Name"] = "sound\\music\\Draenor\\mus_60_KhadgarsPlan_v3.mp3",
    ["Id"] = 1061116,
    ["Length"] = 139,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Khadgar's Plan v4",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_KhadgarsPlan_v4.mp3",
    ["Id"] = 1061117,
    ["Length"] = 114,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Magnificent Desolation 2A1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_MagnificentDesolation2_A1.mp3",
    ["Id"] = 1067555,
    ["Length"] = 83,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Magnificent Desolation 2A2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_MagnificentDesolation2_A2.mp3",
    ["Id"] = 1067556,
    ["Length"] = 97,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Magnificent Desolation 2H",
    ["Name"] = "sound\\music\\Draenor\\mus_60_MagnificentDesolation2_H.mp3",
    ["Id"] = 1067557,
    ["Length"] = 239,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Magnificent Desolation 2H1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_MagnificentDesolation2_H1.mp3",
    ["Id"] = 1067558,
    ["Length"] = 130,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Magnificent Desolation 2H2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_MagnificentDesolation2_H2.mp3",
    ["Id"] = 1067559,
    ["Length"] = 111,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Magnificent Desolation A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_MagnificentDesolation_A.mp3",
    ["Id"] = 936338,
    ["Length"] = 237,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Magnificent Desolation B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_MagnificentDesolation_B.mp3",
    ["Id"] = 936339,
    ["Length"] = 159,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Magnificent Desolation H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_MagnificentDesolation_H.mp3",
    ["Id"] = 936340,
    ["Length"] = 237,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Magnificent Desolation Piano A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_MagnificentDesolation_Piano_A.mp3",
    ["Id"] = 1080508,
    ["Length"] = 35,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Malach H1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Malach_H1.mp3",
    ["Id"] = 1067046,
    ["Length"] = 128,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Malach H2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Malach_H2.mp3",
    ["Id"] = 1067047,
    ["Length"] = 140,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Malach H3",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Malach_H3.mp3",
    ["Id"] = 1067048,
    ["Length"] = 46,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Malach H4",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Malach_H4.mp3",
    ["Id"] = 1067049,
    ["Length"] = 66,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mobilize E Stinger",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Mobilize_E_Stinger.mp3",
    ["Id"] = 1080419,
    ["Length"] = 23,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mountains Ambient 2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Mountains_Ambient2.mp3",
    ["Id"] = 1080420,
    ["Length"] = 72,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mountains Ambient 3",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Mountains_Ambient3.mp3",
    ["Id"] = 1080421,
    ["Length"] = 81,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mountains Stinger1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Mountains_Stinger1.mp3",
    ["Id"] = 1080422,
    ["Length"] = 17,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mountains Intro Amb1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_MountainsIntro_A1.mp3",
    ["Id"] = 1080423,
    ["Length"] = 224,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mountains Intro Amb2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_MountainsIntro_A2.mp3",
    ["Id"] = 1080424,
    ["Length"] = 107,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mystic B1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Mystic_B1.mp3",
    ["Id"] = 1067052,
    ["Length"] = 58,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mystic C",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Mystic_C.mp3",
    ["Id"] = 1067054,
    ["Length"] = 68,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mystic C2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Mystic_C2.mp3",
    ["Id"] = 1067055,
    ["Length"] = 87,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mystic D1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Mystic_D1.mp3",
    ["Id"] = 1067056,
    ["Length"] = 65,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mystic D2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Mystic_D2.mp3",
    ["Id"] = 1067057,
    ["Length"] = 83,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Nagrand v1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Nagrand_v1.mp3",
    ["Id"] = 1061136,
    ["Length"] = 149,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Nagrand v2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Nagrand_v2.mp3",
    ["Id"] = 1061137,
    ["Length"] = 149,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Nagrand v3A",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Nagrand_v3A.mp3",
    ["Id"] = 1061138,
    ["Length"] = 62,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Nagrand v3B",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Nagrand_v3B.mp3",
    ["Id"] = 1061139,
    ["Length"] = 58,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Nagrand v4",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Nagrand_v4.mp3",
    ["Id"] = 1061140,
    ["Length"] = 87,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Nagrand v5",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Nagrand_v5.mp3",
    ["Id"] = 1061141,
    ["Length"] = 79,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Nagrand v6",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Nagrand_v6.mp3",
    ["Id"] = 1061142,
    ["Length"] = 134,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Nagrand v7",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Nagrand_v7.mp3",
    ["Id"] = 1061143,
    ["Length"] = 88,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Night Spires v1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_NightSpires_v1.mp3",
    ["Id"] = 1061144,
    ["Length"] = 136,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Night Spires v2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_NightSpires_v2.mp3",
    ["Id"] = 1061145,
    ["Length"] = 115,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Night Spires v3",
    ["Name"] = "sound\\music\\Draenor\\mus_60_NightSpires_v3.mp3",
    ["Id"] = 1061146,
    ["Length"] = 135,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Night Spires v4",
    ["Name"] = "sound\\music\\Draenor\\mus_60_NightSpires_v4.mp3",
    ["Id"] = 1061147,
    ["Length"] = 122,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Ogre Mines A1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_OgreMines_A1.mp3",
    ["Id"] = 1067560,
    ["Length"] = 131,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Ogre Mines A2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_OgreMines_A2.mp3",
    ["Id"] = 1067561,
    ["Length"] = 127,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Ogre Mines B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_OgreMines_B.mp3",
    ["Id"] = 1067562,
    ["Length"] = 133,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Ogre Mines H1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_OgreMines_H1.mp3",
    ["Id"] = 1067563,
    ["Length"] = 131,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Ogre Mines H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_OgreMines_H2.mp3",
    ["Id"] = 1067564,
    ["Length"] = 124,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Plight of the Ogres H1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_PlightoftheOgres_H1.mp3",
    ["Id"] = 1067061,
    ["Length"] = 100,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Plight of the Ogres H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_PlightoftheOgres_H2.mp3",
    ["Id"] = 1067062,
    ["Length"] = 78,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Premonition H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Premonition_H.mp3",
    ["Id"] = 936341,
    ["Length"] = 132,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Protect the Throne Intro H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ProtecttheThrone_H1.mp3",
    ["Id"] = 1067063,
    ["Length"] = 67,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Protect the Throne H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ProtecttheThrone_H2.mp3",
    ["Id"] = 1067064,
    ["Length"] = 98,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Protect the Throne H3",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ProtecttheThrone_H3.mp3",
    ["Id"] = 1067065,
    ["Length"] = 92,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Proudmoore H",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Proudmoore_H.mp3",
    ["Id"] = 1064164,
    ["Length"] = 104,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Quiet Heart A",
    ["Name"] = "sound\\music\\Draenor\\mus_60_QuietHeart_a.mp3",
    ["Id"] = 1067565,
    ["Length"] = 224,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Quiet Heart A1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_QuietHeart_a1.mp3",
    ["Id"] = 1067566,
    ["Length"] = 109,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Quiet Heart A2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_QuietHeart_a2.mp3",
    ["Id"] = 1067567,
    ["Length"] = 117,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Quiet Heart H",
    ["Name"] = "sound\\music\\Draenor\\mus_60_QuietHeart_H.mp3",
    ["Id"] = 1067568,
    ["Length"] = 230,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Quiet Heart H1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_QuietHeart_H1.mp3",
    ["Id"] = 1067569,
    ["Length"] = 114,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Quiet Heart H2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_QuietHeart_H2.mp3",
    ["Id"] = 1067570,
    ["Length"] = 119,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Rise to the Dark H1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_RisetotheDark_H1.mp3",
    ["Id"] = 1067066,
    ["Length"] = 94,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Rise to the Dark H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_RisetotheDark_H2.mp3",
    ["Id"] = 1067067,
    ["Length"] = 124,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Sacrifice 2A",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Sacrifice_2A.mp3",
    ["Id"] = 1061154,
    ["Length"] = 89,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Sacrifice 2H",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Sacrifice_2H.mp3",
    ["Id"] = 1061155,
    ["Length"] = 89,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon v1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Shadowmoon_v1.mp3",
    ["Id"] = 1061157,
    ["Length"] = 128,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon v2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Shadowmoon_v2.mp3",
    ["Id"] = 1061158,
    ["Length"] = 127,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon v3",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Shadowmoon_v3.mp3",
    ["Id"] = 1061159,
    ["Length"] = 123,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon v4",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Shadowmoon_v4.mp3",
    ["Id"] = 1061160,
    ["Length"] = 61,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon v5",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Shadowmoon_v5.mp3",
    ["Id"] = 1061161,
    ["Length"] = 95,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon Pt1A",
    ["Name"] = "sound\\music\\Draenor\\mus_60_ShadowmoonPt1_A.mp3",
    ["Id"] = 1067571,
    ["Length"] = 111,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon Pt1H",
    ["Name"] = "sound\\music\\Draenor\\mus_60_ShadowmoonPt1_H.mp3",
    ["Id"] = 1067572,
    ["Length"] = 139,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon Rising H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ShadowmoonRising_H.mp3",
    ["Id"] = 1067068,
    ["Length"] = 155,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon Sunset Intro H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ShadowmoonSunsetIntro_H.mp3",
    ["Id"] = 1067069,
    ["Length"] = 70,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon Sunset Reprise H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ShadowmoonSunsetReprise_H.mp3",
    ["Id"] = 1067070,
    ["Length"] = 46,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Smack the Giant H1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_SmacktheGiant_H1.mp3",
    ["Id"] = 1067071,
    ["Length"] = 55,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Smack the Giant H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_SmacktheGiant_H2.mp3",
    ["Id"] = 1067072,
    ["Length"] = 53,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Smack the Giant H3",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_SmacktheGiant_H3.mp3",
    ["Id"] = 1067073,
    ["Length"] = 53,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Smack the Giant H4",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_SmacktheGiant_H4.mp3",
    ["Id"] = 1067074,
    ["Length"] = 22,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Spires of Arak v1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_SpiresofArak_v1.mp3",
    ["Id"] = 1061165,
    ["Length"] = 159,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Spires of Arak v2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_SpiresofArak_v2.mp3",
    ["Id"] = 1061166,
    ["Length"] = 102,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Spires of Arak v4",
    ["Name"] = "sound\\music\\Draenor\\mus_60_SpiresofArak_v4.mp3",
    ["Id"] = 1061167,
    ["Length"] = 56,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Stormlords on the March H1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_StormlordsontheMarch_H1.mp3",
    ["Id"] = 1067075,
    ["Length"] = 88,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Stormlords on the March H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_StormlordsontheMarch_H2.mp3",
    ["Id"] = 1067076,
    ["Length"] = 47,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Stormlords on the March H3",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_StormlordsontheMarch_H3.mp3",
    ["Id"] = 1067077,
    ["Length"] = 102,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "The Clans Join A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_TheClansJoin_A.mp3",
    ["Id"] = 936342,
    ["Length"] = 213,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "The Clans Join B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_TheClansJoin_B.mp3",
    ["Id"] = 936343,
    ["Length"] = 213,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "The Clans Join H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_TheClansJoin_H.mp3",
    ["Id"] = 936344,
    ["Length"] = 213,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Traversing the Spires A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_TraversingtheSpires_A.mp3",
    ["Id"] = 1067573,
    ["Length"] = 128,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Traversing the Spires B",
    ["Name"] = "sound\\music\\Draenor\\mus_60_TraversingtheSpires_B.mp3",
    ["Id"] = 1067574,
    ["Length"] = 124,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Traversing the Spires C",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_TraversingtheSpires_C.mp3",
    ["Id"] = 1067575,
    ["Length"] = 157,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Traversing the Spires H1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_TraversingtheSpires_H1.mp3",
    ["Id"] = 1067576,
    ["Length"] = 129,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Traversing the Spires H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_TraversingtheSpires_H2.mp3",
    ["Id"] = 1067577,
    ["Length"] = 127,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Village C1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Village_C1.mp3",
    ["Id"] = 1067080,
    ["Length"] = 63,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Village C2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Village_C2.mp3",
    ["Id"] = 1067081,
    ["Length"] = 88,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows A1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_A1.mp3",
    ["Id"] = 1067578,
    ["Length"] = 56,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows A2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_A2.mp3",
    ["Id"] = 1067579,
    ["Length"] = 50,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows A3",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_A3.mp3",
    ["Id"] = 1067580,
    ["Length"] = 102,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows B",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Vows_B.mp3",
    ["Id"] = 1067581,
    ["Length"] = 119,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows C1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_C1.mp3",
    ["Id"] = 1067582,
    ["Length"] = 82,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows C2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_C2.mp3",
    ["Id"] = 1067583,
    ["Length"] = 98,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows C3",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_C3.mp3",
    ["Id"] = 1067584,
    ["Length"] = 131,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows D1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Vows_D1.mp3",
    ["Id"] = 1067585,
    ["Length"] = 89,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows D2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_D2.mp3",
    ["Id"] = 1067586,
    ["Length"] = 87,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows H1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_H1.mp3",
    ["Id"] = 1067587,
    ["Length"] = 100,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_H2.mp3",
    ["Id"] = 1067588,
    ["Length"] = 85,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows H3",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_H3.mp3",
    ["Id"] = 1067589,
    ["Length"] = 103,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows H4",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Vows_H4.mp3",
    ["Id"] = 1067590,
    ["Length"] = 107,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows H5",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_H5.mp3",
    ["Id"] = 1067591,
    ["Length"] = 117,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Warsong v1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Warsong_v1.mp3",
    ["Id"] = 1064170,
    ["Length"] = 153,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Warsong v2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Warsong_v2.mp3",
    ["Id"] = 1064171,
    ["Length"] = 153,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Warsong v3A",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Warsong_v3A.mp3",
    ["Id"] = 1061179,
    ["Length"] = 84,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Warsong v3B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Warsong_v3B.mp3",
    ["Id"] = 1061180,
    ["Length"] = 72,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Warsong v4",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Warsong_v4.mp3",
    ["Id"] = 1061181,
    ["Length"] = 155,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo A1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_WorldExpo_A1.mp3",
    ["Id"] = 1067093,
    ["Length"] = 55,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo A2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_WorldExpo_A2.mp3",
    ["Id"] = 1067094,
    ["Length"] = 55,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo A3",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_a3.mp3",
    ["Id"] = 1067095,
    ["Length"] = 61,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo B",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_b.mp3",
    ["Id"] = 1067096,
    ["Length"] = 15,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo C",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_c.mp3",
    ["Id"] = 1067097,
    ["Length"] = 23,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo D",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_d.mp3",
    ["Id"] = 1067098,
    ["Length"] = 23,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo E1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_e1.mp3",
    ["Id"] = 1067099,
    ["Length"] = 56,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo E2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_e2.mp3",
    ["Id"] = 1067100,
    ["Length"] = 65,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo F1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_f1.mp3",
    ["Id"] = 1067101,
    ["Length"] = 64,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo F2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_f2.mp3",
    ["Id"] = 1067102,
    ["Length"] = 65,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo F3",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_f3.mp3",
    ["Id"] = 1067103,
    ["Length"] = 39,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo G",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_g.mp3",
    ["Id"] = 1067104,
    ["Length"] = 20,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo H",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_h.mp3",
    ["Id"] = 1064173,
    ["Length"] = 169,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Falling 1A",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Falling_1A.mp3",
    ["Id"] = 1146873,
    ["Length"] = 71,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Falling 1B",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Falling_1B.mp3",
    ["Id"] = 1146874,
    ["Length"] = 74,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Falling 2H",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Falling_2H.mp3",
    ["Id"] = 1146875,
    ["Length"] = 71,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Fel Essence A",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_FelEssence_A.mp3",
    ["Id"] = 1146876,
    ["Length"] = 86,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Fel Essence B",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_FelEssence_B.mp3",
    ["Id"] = 1146877,
    ["Length"] = 60,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Fel Essence C",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_FelEssence_C.mp3",
    ["Id"] = 1146878,
    ["Length"] = 46,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Fel Essence D",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_FelEssence_D.mp3",
    ["Id"] = 1146879,
    ["Length"] = 49,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Fel Essence H",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_FelEssence_H.mp3",
    ["Id"] = 1146880,
    ["Length"] = 121,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Feu De L'Enfer A",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_FeuDeLEnfer_A.mp3",
    ["Id"] = 1146881,
    ["Length"] = 116,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Feu De L'Enfer H",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_FeuDeLEnfer_H.mp3",
    ["Id"] = 1146882,
    ["Length"] = 119,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Lost Moon A",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_LostMoon_A.mp3",
    ["Id"] = 1146883,
    ["Length"] = 79,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Lost Moon B",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_LostMoon_B.mp3",
    ["Id"] = 1146884,
    ["Length"] = 60,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Lost Moon H",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_LostMoon_H.mp3",
    ["Id"] = 1146885,
    ["Length"] = 88,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Mortal Night A",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_MortalNight_A.mp3",
    ["Id"] = 1146886,
    ["Length"] = 50,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Mortal Night B",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_MortalNight_B.mp3",
    ["Id"] = 1146887,
    ["Length"] = 14,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Mortal Night C",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_MortalNight_C.mp3",
    ["Id"] = 1146888,
    ["Length"] = 74,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Mortal Night H",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_MortalNight_H.mp3",
    ["Id"] = 1146889,
    ["Length"] = 152,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Tanaander A",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Tanaander_A.mp3",
    ["Id"] = 1146890,
    ["Length"] = 119,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Tanaander B",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Tanaander_B.mp3",
    ["Id"] = 1146891,
    ["Length"] = 119,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Tanaander C",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Tanaander_C.mp3",
    ["Id"] = 1146892,
    ["Length"] = 125,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Tanaander H",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Tanaander_H.mp3",
    ["Id"] = 1146893,
    ["Length"] = 125,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Tanaan Gloom A",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_TanaanGloom_A.mp3",
    ["Id"] = 1146894,
    ["Length"] = 109,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Tanaan Gloom B",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_TanaanGloom_B.mp3",
    ["Id"] = 1146895,
    ["Length"] = 103,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Tanaan Gloom C",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_TanaanGloom_C.mp3",
    ["Id"] = 1146896,
    ["Length"] = 63,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Tanaan Gloom H",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_TanaanGloom_H.mp3",
    ["Id"] = 1146897,
    ["Length"] = 115,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "The Wanderer A",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_TheWanderer_A.mp3",
    ["Id"] = 1146898,
    ["Length"] = 138,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "The Wanderer B",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_TheWanderer_B.mp3",
    ["Id"] = 1146899,
    ["Length"] = 72,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "The Wanderer H",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_TheWanderer_H.mp3",
    ["Id"] = 1146900,
    ["Length"] = 162,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Undaunted A",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Undaunted_A.mp3",
    ["Id"] = 1146901,
    ["Length"] = 102,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Undaunted B",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Undaunted_B.mp3",
    ["Id"] = 1146902,
    ["Length"] = 87,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Undaunted H",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Undaunted_H.mp3",
    ["Id"] = 1146903,
    ["Length"] = 101,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "Fall of the Lich King",
    ["Song"] = "Invincible",
    ["Name"] = "sound\\music\\Draenor\\MUS_Invincible.mp3",
    ["Id"] = 1100052,
    ["Length"] = 197,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
}
local EpicMusicPlayer = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer")if not EpicMusicPlayer then return end
EpicMusicPlayer:AddPlayList("Draenor", playlist1, false, true)
