-- EpicMusicPlayer playlist created by EpicPlaylistCreator version 0.1.
local playlist1={
  ["listName"] = "Draenor",
  ["playlistVersion"] = "3.1",
  ["playlistType"] = "generated",
  ["musicDir"] = "MyMusic\\",
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Hero's Sacrifice v1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_AHerosSacrifice_v1.mp3",
    ["Length"] = 117,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Hero's Sacrifice v2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_AHerosSacrifice_v2.mp3",
    ["Length"] = 102,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Hero's Sacrifice v3A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_AHerosSacrifice_v3A.mp3",
    ["Length"] = 55,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Hero's Sacrifice v3B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_AHerosSacrifice_v3B.mp3",
    ["Length"] = 60,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Hero's Sacrifice v4",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_AHerosSacrifice_v4.mp3",
    ["Length"] = 24,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Hero's Sacrifice v5",
    ["Name"] = "sound\\music\\Draenor\\mus_60_AHerosSacrifice_v5.mp3",
    ["Length"] = 67,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Light in the Darkness v1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_ALightintheDarkness_v1.mp3",
    ["Length"] = 155,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Light in the Darkness v2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_ALightintheDarkness_v2.mp3",
    ["Length"] = 137,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Light in the Darkness v3",
    ["Name"] = "sound\\music\\Draenor\\mus_60_ALightintheDarkness_v3.mp3",
    ["Length"] = 154,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Light in the Darkness v3A",
    ["Name"] = "sound\\music\\Draenor\\mus_60_ALightintheDarkness_v3a.mp3",
    ["Length"] = 70,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Arak 2 H",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Arak2_H.mp3",
    ["Length"] = 157,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Army A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Army_A.mp3",
    ["Length"] = 143,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Army Stinger1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Army_Stinger1.mp3",
    ["Length"] = 12,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Army Stinger2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Army_Stinger2.mp3",
    ["Length"] = 13,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "A Siege of Worlds v2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ASiegeofWorlds_MainTitle.mp3",
    ["Length"] = 727,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Blackrock A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Blackrock_A.mp3",
    ["Length"] = 83,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Caverns of Life H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_CavernsofLife_H.mp3",
    ["Length"] = 112,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Chieftans Gather H",
    ["Name"] = "sound\\music\\Draenor\\mus_60_ChieftansGather_H.mp3",
    ["Length"] = 97,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Cold Mountain Duet H",
    ["Name"] = "sound\\music\\Draenor\\mus_60_ColdMountain_Duet_H.mp3",
    ["Length"] = 156,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Elune's Shadow A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ElunesShadow_A.mp3",
    ["Length"] = 45,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Elune's Shadow B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ElunesShadow_B.mp3",
    ["Length"] = 34,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Elune's Shadow C",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ElunesShadow_C.mp3",
    ["Length"] = 52,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Elune's Shadow H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ElunesShadow_H.mp3",
    ["Length"] = 94,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Eternal Night H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_EternalNight_H.mp3",
    ["Length"] = 76,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Ethereal Essence H1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_EtherealEssence_H1.mp3",
    ["Length"] = 102,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Ethereal Essence H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_EtherealEssence_H2.mp3",
    ["Length"] = 88,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Fel Wasteland A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_FelWasteland_A.mp3",
    ["Length"] = 71,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Fel Wasteland B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_FelWasteland_B.mp3",
    ["Length"] = 90,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Fel Wasteland C",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_FelWasteland_C.mp3",
    ["Length"] = 32,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Fel Wasteland H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_FelWasteland_H.mp3",
    ["Length"] = 85,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Foreshadowing H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Foreshadowing_H.mp3",
    ["Length"] = 124,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Forsaken A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Forsaken_A.mp3",
    ["Length"] = 82,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Forsaken H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Forsaken_H.mp3",
    ["Length"] = 125,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Gardens of Karabor A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_GardensOfKarabor_A.mp3",
    ["Length"] = 99,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Gardens of Karabor B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_GardensOfKarabor_B.mp3",
    ["Length"] = 47,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Gardens of Karabor H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_GardensOfKarabor_H.mp3",
    ["Length"] = 127,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Garrison Building Complete",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_GarrisonBuildingComplete.mp3",
    ["Length"] = 14,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Garrison Building Complete v2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_GarrisonBuildingComplete2.mp3",
    ["Length"] = 8,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Grinspiration A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Grinspiration_A.mp3",
    ["Length"] = 90,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Grinspiration B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Grinspiration_B.mp3",
    ["Length"] = 82,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Grinspiration C",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Grinspiration_C.mp3",
    ["Length"] = 124,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Grinspiration H1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Grinspiration_H1.mp3",
    ["Length"] = 101,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Grinspiration H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Grinspiration_H2.mp3",
    ["Length"] = 84,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Grommash Hellscream v1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_GrommashHellscream_v1.mp3",
    ["Length"] = 165,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Grommash Hellscream v2A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_GrommashHellscream_v2A.mp3",
    ["Length"] = 48,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Grommash Hellscream v2B",
    ["Name"] = "sound\\music\\Draenor\\mus_60_GrommashHellscream_v2B.mp3",
    ["Length"] = 55,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Grommash Hellscream v3",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_GrommashHellscreamv_3.mp3",
    ["Length"] = 73,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Herding Clans H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_HerdingClans_H.mp3",
    ["Length"] = 132,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Iron Dawn v1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_IronDawn_v1.mp3",
    ["Length"] = 151,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Iron Dawn v2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_IronDawn_v2.mp3",
    ["Length"] = 97,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Iron Dawn v3A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_IronDawn_v3A.mp3",
    ["Length"] = 60,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Iron Dawn v3B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_IronDawn_v3B.mp3",
    ["Length"] = 75,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Iron Dawn v4",
    ["Name"] = "sound\\music\\Draenor\\mus_60_IronDawn_v4.mp3",
    ["Length"] = 154,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Keepers of the Temple H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_KeepersoftheTemple_H.mp3",
    ["Length"] = 190,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Khadgar's Plan v1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_KhadgarsPlan_v1.mp3",
    ["Length"] = 145,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Khadgar's Plan v2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_KhadgarsPlan_v2.mp3",
    ["Length"] = 128,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Khadgar's Plan v3",
    ["Name"] = "sound\\music\\Draenor\\mus_60_KhadgarsPlan_v3.mp3",
    ["Length"] = 139,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Khadgar's Plan v4",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_KhadgarsPlan_v4.mp3",
    ["Length"] = 114,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Magnificent Desolation 2A1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_MagnificentDesolation2_A1.mp3",
    ["Length"] = 83,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Magnificent Desolation 2A2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_MagnificentDesolation2_A2.mp3",
    ["Length"] = 97,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Magnificent Desolation 2H",
    ["Name"] = "sound\\music\\Draenor\\mus_60_MagnificentDesolation2_H.mp3",
    ["Length"] = 239,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Magnificent Desolation 2H1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_MagnificentDesolation2_H1.mp3",
    ["Length"] = 130,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Magnificent Desolation 2H2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_MagnificentDesolation2_H2.mp3",
    ["Length"] = 111,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Magnificent Desolation A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_MagnificentDesolation_A.mp3",
    ["Length"] = 237,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Magnificent Desolation B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_MagnificentDesolation_B.mp3",
    ["Length"] = 159,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Magnificent Desolation H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_MagnificentDesolation_H.mp3",
    ["Length"] = 237,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Magnificent Desolation Piano A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_MagnificentDesolation_Piano_A.mp3",
    ["Length"] = 35,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Malach H1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Malach_H1.mp3",
    ["Length"] = 128,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Malach H2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Malach_H2.mp3",
    ["Length"] = 140,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Malach H3",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Malach_H3.mp3",
    ["Length"] = 46,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Malach H4",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Malach_H4.mp3",
    ["Length"] = 66,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mobilize E Stinger",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Mobilize_E_Stinger.mp3",
    ["Length"] = 23,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mountains Ambient 2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Mountains_Ambient2.mp3",
    ["Length"] = 72,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mountains Ambient 3",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Mountains_Ambient3.mp3",
    ["Length"] = 81,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mountains Stinger1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Mountains_Stinger1.mp3",
    ["Length"] = 17,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mountains Intro Amb1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_MountainsIntro_A1.mp3",
    ["Length"] = 224,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mountains Intro Amb2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_MountainsIntro_A2.mp3",
    ["Length"] = 107,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mystic B1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Mystic_B1.mp3",
    ["Length"] = 58,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mystic C",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Mystic_C.mp3",
    ["Length"] = 68,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mystic C2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Mystic_C2.mp3",
    ["Length"] = 87,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mystic D1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Mystic_D1.mp3",
    ["Length"] = 65,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Mystic D2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Mystic_D2.mp3",
    ["Length"] = 83,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Nagrand v1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Nagrand_v1.mp3",
    ["Length"] = 149,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Nagrand v2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Nagrand_v2.mp3",
    ["Length"] = 149,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Nagrand v3A",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Nagrand_v3A.mp3",
    ["Length"] = 62,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Nagrand v3B",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Nagrand_v3B.mp3",
    ["Length"] = 58,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Nagrand v4",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Nagrand_v4.mp3",
    ["Length"] = 87,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Nagrand v5",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Nagrand_v5.mp3",
    ["Length"] = 79,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Nagrand v6",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Nagrand_v6.mp3",
    ["Length"] = 134,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Nagrand v7",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Nagrand_v7.mp3",
    ["Length"] = 88,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Night Spires v1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_NightSpires_v1.mp3",
    ["Length"] = 136,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Night Spires v2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_NightSpires_v2.mp3",
    ["Length"] = 115,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Night Spires v3",
    ["Name"] = "sound\\music\\Draenor\\mus_60_NightSpires_v3.mp3",
    ["Length"] = 135,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Night Spires v4",
    ["Name"] = "sound\\music\\Draenor\\mus_60_NightSpires_v4.mp3",
    ["Length"] = 122,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Ogre Mines A1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_OgreMines_A1.mp3",
    ["Length"] = 131,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Ogre Mines A2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_OgreMines_A2.mp3",
    ["Length"] = 127,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Ogre Mines B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_OgreMines_B.mp3",
    ["Length"] = 133,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Ogre Mines H1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_OgreMines_H1.mp3",
    ["Length"] = 131,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Ogre Mines H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_OgreMines_H2.mp3",
    ["Length"] = 124,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Plight of the Ogres H1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_PlightoftheOgres_H1.mp3",
    ["Length"] = 100,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Plight of the Ogres H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_PlightoftheOgres_H2.mp3",
    ["Length"] = 78,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "Premonition H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Premonition_H.mp3",
    ["Length"] = 132,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Protect the Throne Intro H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ProtecttheThrone_H1.mp3",
    ["Length"] = 67,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Protect the Throne H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ProtecttheThrone_H2.mp3",
    ["Length"] = 98,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Protect the Throne H3",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ProtecttheThrone_H3.mp3",
    ["Length"] = 92,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Proudmoore H",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Proudmoore_H.mp3",
    ["Length"] = 104,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Quiet Heart A",
    ["Name"] = "sound\\music\\Draenor\\mus_60_QuietHeart_a.mp3",
    ["Length"] = 224,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Quiet Heart A1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_QuietHeart_a1.mp3",
    ["Length"] = 109,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Quiet Heart A2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_QuietHeart_a2.mp3",
    ["Length"] = 117,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Quiet Heart H",
    ["Name"] = "sound\\music\\Draenor\\mus_60_QuietHeart_H.mp3",
    ["Length"] = 230,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Quiet Heart H1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_QuietHeart_H1.mp3",
    ["Length"] = 114,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Quiet Heart H2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_QuietHeart_H2.mp3",
    ["Length"] = 119,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Rise to the Dark H1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_RisetotheDark_H1.mp3",
    ["Length"] = 94,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Rise to the Dark H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_RisetotheDark_H2.mp3",
    ["Length"] = 124,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Sacrifice 2A",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Sacrifice_2A.mp3",
    ["Length"] = 89,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Sacrifice 2H",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Sacrifice_2H.mp3",
    ["Length"] = 89,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon v1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Shadowmoon_v1.mp3",
    ["Length"] = 128,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon v2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Shadowmoon_v2.mp3",
    ["Length"] = 127,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon v3",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Shadowmoon_v3.mp3",
    ["Length"] = 123,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon v4",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Shadowmoon_v4.mp3",
    ["Length"] = 61,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon v5",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Shadowmoon_v5.mp3",
    ["Length"] = 95,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon Pt1A",
    ["Name"] = "sound\\music\\Draenor\\mus_60_ShadowmoonPt1_A.mp3",
    ["Length"] = 111,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon Pt1H",
    ["Name"] = "sound\\music\\Draenor\\mus_60_ShadowmoonPt1_H.mp3",
    ["Length"] = 139,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon Rising H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ShadowmoonRising_H.mp3",
    ["Length"] = 155,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon Sunset Intro H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ShadowmoonSunsetIntro_H.mp3",
    ["Length"] = 70,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Shadowmoon Sunset Reprise H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_ShadowmoonSunsetReprise_H.mp3",
    ["Length"] = 46,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Smack the Giant H1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_SmacktheGiant_H1.mp3",
    ["Length"] = 55,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Smack the Giant H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_SmacktheGiant_H2.mp3",
    ["Length"] = 53,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Smack the Giant H3",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_SmacktheGiant_H3.mp3",
    ["Length"] = 53,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Smack the Giant H4",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_SmacktheGiant_H4.mp3",
    ["Length"] = 22,
    ["Artist"] = "Craig Stuart Garfinkle",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Spires of Arak v1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_SpiresofArak_v1.mp3",
    ["Length"] = 159,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Spires of Arak v2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_SpiresofArak_v2.mp3",
    ["Length"] = 102,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Spires of Arak v4",
    ["Name"] = "sound\\music\\Draenor\\mus_60_SpiresofArak_v4.mp3",
    ["Length"] = 56,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Stormlords on the March H1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_StormlordsontheMarch_H1.mp3",
    ["Length"] = 88,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Stormlords on the March H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_StormlordsontheMarch_H2.mp3",
    ["Length"] = 47,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Stormlords on the March H3",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_StormlordsontheMarch_H3.mp3",
    ["Length"] = 102,
    ["Artist"] = "Eimear Noone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "The Clans Join A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_TheClansJoin_A.mp3",
    ["Length"] = 213,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "The Clans Join B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_TheClansJoin_B.mp3",
    ["Length"] = 213,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6 (BC)",
    ["Song"] = "The Clans Join H",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_TheClansJoin_H.mp3",
    ["Length"] = 213,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Traversing the Spires A",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_TraversingtheSpires_A.mp3",
    ["Length"] = 128,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Traversing the Spires B",
    ["Name"] = "sound\\music\\Draenor\\mus_60_TraversingtheSpires_B.mp3",
    ["Length"] = 124,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Traversing the Spires C",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_TraversingtheSpires_C.mp3",
    ["Length"] = 157,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Traversing the Spires H1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_TraversingtheSpires_H1.mp3",
    ["Length"] = 129,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Traversing the Spires H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_TraversingtheSpires_H2.mp3",
    ["Length"] = 127,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Village C1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Village_C1.mp3",
    ["Length"] = 63,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Village C2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Village_C2.mp3",
    ["Length"] = 88,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows A1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_A1.mp3",
    ["Length"] = 56,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows A2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_A2.mp3",
    ["Length"] = 50,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows A3",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_A3.mp3",
    ["Length"] = 102,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows B",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Vows_B.mp3",
    ["Length"] = 119,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows C1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_C1.mp3",
    ["Length"] = 82,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows C2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_C2.mp3",
    ["Length"] = 98,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows C3",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_C3.mp3",
    ["Length"] = 131,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows D1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Vows_D1.mp3",
    ["Length"] = 89,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows D2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_D2.mp3",
    ["Length"] = 87,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows H1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_H1.mp3",
    ["Length"] = 100,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows H2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_H2.mp3",
    ["Length"] = 85,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows H3",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_H3.mp3",
    ["Length"] = 103,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows H4",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Vows_H4.mp3",
    ["Length"] = 107,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Vows H5",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Vows_H5.mp3",
    ["Length"] = 117,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Warsong v1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Warsong_v1.mp3",
    ["Length"] = 153,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Warsong v2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Warsong_v2.mp3",
    ["Length"] = 153,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Warsong v3A",
    ["Name"] = "sound\\music\\Draenor\\mus_60_Warsong_v3A.mp3",
    ["Length"] = 84,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Warsong v3B",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Warsong_v3B.mp3",
    ["Length"] = 72,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "Warsong v4",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_Warsong_v4.mp3",
    ["Length"] = 155,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo A1",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_WorldExpo_A1.mp3",
    ["Length"] = 55,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo A2",
    ["Name"] = "sound\\music\\Draenor\\MUS_60_WorldExpo_A2.mp3",
    ["Length"] = 55,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo A3",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_a3.mp3",
    ["Length"] = 61,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo B",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_b.mp3",
    ["Length"] = 15,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo C",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_c.mp3",
    ["Length"] = 23,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo D",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_d.mp3",
    ["Length"] = 23,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo E1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_e1.mp3",
    ["Length"] = 56,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo E2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_e2.mp3",
    ["Length"] = 65,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo F1",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_f1.mp3",
    ["Length"] = 64,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo F2",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_f2.mp3",
    ["Length"] = 65,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo F3",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_f3.mp3",
    ["Length"] = 39,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo G",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_g.mp3",
    ["Length"] = 20,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6",
    ["Song"] = "World Expo H",
    ["Name"] = "sound\\music\\Draenor\\mus_60_worldexpo_h.mp3",
    ["Length"] = 169,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Falling 1A",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Falling_1A.mp3",
    ["Length"] = 71,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Falling 1B",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Falling_1B.mp3",
    ["Length"] = 74,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Falling 2H",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Falling_2H.mp3",
    ["Length"] = 71,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Fel Essence A",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_FelEssence_A.mp3",
    ["Length"] = 86,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Fel Essence B",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_FelEssence_B.mp3",
    ["Length"] = 60,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Fel Essence C",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_FelEssence_C.mp3",
    ["Length"] = 46,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Fel Essence D",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_FelEssence_D.mp3",
    ["Length"] = 49,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Fel Essence H",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_FelEssence_H.mp3",
    ["Length"] = 121,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Feu De L'Enfer A",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_FeuDeLEnfer_A.mp3",
    ["Length"] = 116,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Feu De L'Enfer H",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_FeuDeLEnfer_H.mp3",
    ["Length"] = 119,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Lost Moon A",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_LostMoon_A.mp3",
    ["Length"] = 79,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Lost Moon B",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_LostMoon_B.mp3",
    ["Length"] = 60,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Lost Moon H",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_LostMoon_H.mp3",
    ["Length"] = 88,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Mortal Night A",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_MortalNight_A.mp3",
    ["Length"] = 50,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Mortal Night B",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_MortalNight_B.mp3",
    ["Length"] = 14,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Mortal Night C",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_MortalNight_C.mp3",
    ["Length"] = 74,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Mortal Night H",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_MortalNight_H.mp3",
    ["Length"] = 152,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Tanaander A",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Tanaander_A.mp3",
    ["Length"] = 119,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Tanaander B",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Tanaander_B.mp3",
    ["Length"] = 119,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Tanaander C",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Tanaander_C.mp3",
    ["Length"] = 125,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Tanaander H",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Tanaander_H.mp3",
    ["Length"] = 125,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Tanaan Gloom A",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_TanaanGloom_A.mp3",
    ["Length"] = 109,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Tanaan Gloom B",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_TanaanGloom_B.mp3",
    ["Length"] = 103,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Tanaan Gloom C",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_TanaanGloom_C.mp3",
    ["Length"] = 63,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Tanaan Gloom H",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_TanaanGloom_H.mp3",
    ["Length"] = 115,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "The Wanderer A",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_TheWanderer_A.mp3",
    ["Length"] = 138,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "The Wanderer B",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_TheWanderer_B.mp3",
    ["Length"] = 72,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "The Wanderer H",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_TheWanderer_H.mp3",
    ["Length"] = 162,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Undaunted A",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Undaunted_A.mp3",
    ["Length"] = 102,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Undaunted B",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Undaunted_B.mp3",
    ["Length"] = 87,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Undaunted H",
    ["Name"] = "sound\\music\\Draenor\\MUS_62_Undaunted_H.mp3",
    ["Length"] = 101,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "Fall of the Lich King",
    ["Song"] = "Invincible",
    ["Name"] = "sound\\music\\Draenor\\MUS_Invincible.mp3",
    ["Length"] = 197,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
}
local EpicMusicPlayer = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer")if not EpicMusicPlayer then return end
EpicMusicPlayer:AddPlayList("Draenor", playlist1, false, true)
