local _, _, _, tocversion = GetBuildInfo()
if tocversion < 80200 then return end

local L = LibStub("AceLocale-3.0"):GetLocale("EpicMusicPlayer")

local BestofWoW = {
  ["listName"] = L["Epic"],
  ["playlistVersion"] = "4.0",
  ["locked"] =  "true",
  {
    ["Album"] = "WarCraft III Expansion",
    ["Song"] = "Power Of The Horde",
    ["Name"] = "Sound\\Music\\ZoneMusic\\DMF_L70ETC01.mp3",
    ["Id"] = 53438,
    ["Length"] = 282,
    ["Artist"] =  "Tenth Level Tauren Chieftain",
    ["WoW"] = true,
  }, -- [2]
  {
    ["Album"] = "WoW 1.0 - WoW Main Theme",
    ["Song"] = "Main Title - Vanilla",
    ["Name"] = "Sound\\Music\\GlueScreenMusic\\wow_main_theme.mp3",
    ["Id"] = 53223,
    ["Length"] = 161,
    ["Artist"] =  "Main Title",
    ["WoW"] = true,
  }, -- [3]
  {
    ["Album"] = "WoW 2.0 - BC Main Theme",
    ["Song"] = "Main Title - The Burning Legion",
    ["Name"] = "Sound\\Music\\GlueScreenMusic\\BC_main_theme.mp3",
    ["Id"] = 53220,
    ["Length"] = 226,
    ["Artist"] =  "",
    ["WoW"] = true,
  }, -- [4]
  {
    ["Album"] = "WoW 3.0 - WotLK Main Theme",
    ["Song"] = "Main Title - Wrath of the Lich King",
    ["Name"] = "Sound\\Music\\GlueScreenMusic\\WotLK_main_title.mp3",
    ["Id"] = 53222,
    ["Length"] = 544,
    ["Artist"] =  "",
    ["WoW"] = true,
  }, -- [5]
  {
    ["Album"] = "WoW 4.0 - The Shattering",
    ["Song"] = "Main Title - Cataclysm",
    ["Name"] = "Sound\\Music\\cataclysm\\MUS_Shattering_UU01.mp3",
    ["Id"] = 441737,
    ["Length"] = 725,
    ["Artist"] =  "",
    ["WoW"] = true,
  }, -- [6]
  {
    ["Album"] = "WoW 5.0 - Heart of Pandaria",
    ["Song"] = "Main Title - Mists of Pandaria",
    ["Name"] = "Sound\\Music\\Pandaria\\MUS_50_HeartofPandaria_01.mp3",
    ["Id"] = 625753,
    ["Length"] = 480,
    ["Artist"] =  "",
    ["WoW"] = true,
  }, -- [7]
  {
    ["Album"] = "WoW 6.0 - A Siege of Worlds",
    ["Song"] = "Main Title - Warlords of Dreanor",
    ["Name"] = "Sound\\Music\\Draenor\\MUS_60_ASiegeofWorlds_MainTitle.mp3",
    ["Id"] = 1042428,
    ["Length"] = 726,
    ["Artist"] =  "",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.0 - Kingdoms Will Burn",
    ["Song"] = "Main Title - Legion",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Kingdomswillburn_MainTitle.mp3",
    ["Id"] = 1496267,
    ["Length"] = 650,
    ["Artist"] = "",
    ["WoW"] = true,
  },
  {
	["Album"] = "WoW 8.0 - Before the Storm",
	["Song"] = "Main Title - Battle for Azeroth",
	["Name"] = "sound\\music\\battleforazeroth\\mus_80_beforethestorm_maintitle.mp3",
    ["Id"] = 2146580,
	["Length"] = 677,
	["Artist"] = "",
	["WoW"] =  "true",
  },
  {
		["Album"] = "WoW 9.0 - Shadowlands",
		["Song"] = "Through the Roof of the World",
		["Name"] = "sound\\music\\shadowlands\\mus_90_throughtheroofoftheworld_maintitle.mp3",
		["Id"] =  3850553,
		["Length"] = 684,
		["Artist"] = "Main Title",
		["WoW"] =  "true",
	},
  {
    ["Album"] = "WoW 1.1 - World of Warcraft",
    ["Song"] = "Spooky 01 Moment",
    ["Name"] = "sound\\music\\musical moments\\spooky\\spooky01-moment.mp3",
    ["Id"] =  53252,
    ["Length"] = 25,
    ["Artist"] = "Jason Hayes",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 1.1 - World of Warcraft",
    ["Song"] = "Stormwind Intro Moment",
    ["Name"] = "sound\\music\\citymusic\\stormwind\\stormwind_intro-moment.mp3",
    ["Id"] =  53211,
    ["Length"] = 66,
    ["Artist"] = "Jason Hayes",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 1.1 - World of Warcraft",
    ["Song"] = "Zul'Gurub Voodoo",
    ["Name"] = "sound\\music\\musical moments\\zulgurubvoodoo.mp3",
    ["Id"] =  53254,
    ["Length"] = 84,
    ["Artist"] = "Derek Duke",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 1.1 - World of Warcraft",
    ["Song"] = "Battle 01",
    ["Name"] = "sound\\music\\musical moments\\battle\\battle01.mp3",
    ["Id"] =  53225,
    ["Length"] = 48,
    ["Artist"] = "Unknown",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 1.1 - World of Warcraft",
    ["Song"] = "Enchanted Forest 01",
    ["Name"] = "sound\\music\\zonemusic\\enchantedforest\\enchantedforest01.mp3",
    ["Id"] =  53453,
    ["Length"] = 49,
    ["Artist"] = "Jason Hayes",
    ["WoW"] =  "true",
  },
  {
		["Album"] = "WoW 1.12 - Drums of War",
		["Song"] = "PVP 3",
		["Name"] = "sound\\music\\zonemusic\\pvp\\pvp3.mp3",
		["Id"] =  53686,
		["Length"] = 40,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
  {
    ["Album"] = "WoW 2.0 - The Burning Crusade",
    ["Song"] = "CT Thrall Escape Intro",
    ["Name"] = "sound\\music\\zonemusic\\cavernsoftime\\ct_thrallescapeintrouni.mp3",
    ["Id"] =  53425,
    ["Length"] = 45,
    ["Artist"] = "Russell Brower",
    ["WoW"] =  "true",
  },
  {
		["Album"] = "WoW 2.0 - The Burning Crusade",
		["Song"] = "Fire Festival (Alliance)",
		["Name"] = "sound\\music\\worldevents\\alliancefirepole.mp3",
		["Id"] =  53255,
		["Length"] = 68,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
  {
		["Album"] = "WoW 2.0 - The Burning Crusade",
		["Song"] = "CT Brazens Flight Intro ",
		["Name"] = "sound\\music\\zonemusic\\cavernsoftime\\ct_brazensflightintrouni.mp3",
		["Id"] =  53379,
		["Length"] = 93,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
  {
    ["Album"] = "WoW 2.0 - The Burning Crusade",
    ["Song"] = "CT Durnholde Keep Ext Walk 3",
    ["Name"] = "sound\\music\\zonemusic\\cavernsoftime\\ct_durnholdekeepextwalk3uni.mp3",
    ["Id"] =  53394,
    ["Length"] = 70,
    ["Artist"] = "Russell Brower",
    ["WoW"] =  "true",
  },
  {
		["Album"] = "WoW 2.0 - The Burning Crusade",
		["Song"] = "CT Escape Durnholde Intro",
		["Name"] = "sound\\music\\zonemusic\\cavernsoftime\\ct_escapedurnintrouni.mp3",
		["Id"] =  53401,
		["Length"] = 112,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
  {
		["Album"] = "WoW 2.0 - The Burning Crusade",
		["Song"] = "CT Hillsbrad Ext Walk 2",
		["Name"] = "sound\\music\\zonemusic\\cavernsoftime\\ct_hillsbradextwalk2uni.mp3",
		["Id"] =  53403,
		["Length"] = 56,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
  {
		["Album"] = "WoW 2.0 - The Burning Crusade",
		["Song"] = "CT Hyjal Ext Walk 7",
		["Name"] = "sound\\music\\zonemusic\\cavernsoftime\\ct_hyjalextwalk7uni.mp3",
		["Id"] =  53404,
		["Length"] = 66,
		["Artist"] = "Jason Hayes",
		["WoW"] =  "true",
	},
  {
    ["Album"] = "WoW 2.0 - The Burning Crusade",
    ["Song"] = "CT Hyjal Ext Walk 8",
    ["Name"] = "sound\\music\\zonemusic\\cavernsoftime\\ct_hyjalextwalk8uni.mp3",
    ["Id"] =  53405,
    ["Length"] = 70,
    ["Artist"] = "Jason Hayes",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 2.0 - The Burning Crusade",
    ["Song"] = "Lament of the Highborne",
    ["Name"] = "sound\\music\\gluescreenmusic\\bccredits_lament_of_the_highborne.mp3",
    ["Id"] =  53221,
    ["Length"] = 171,
    ["Artist"] = "Russell Brower & Derek Duke",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 2.1 - The Black Temple",
    ["Song"] = "Black Temple Summit 3",
    ["Name"] = "sound\\music\\zonemusic\\blacktemple\\bt_summitwalkuni03.mp3",
    ["Id"] =  53347,
    ["Length"] = 41,
    ["Artist"] = "Russell Brower",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 2.1 - The Black Temple",
    ["Song"] = "Black Temple Gates 9",
    ["Name"] = "sound\\music\\zonemusic\\blacktemple\\bt_illidariwalkhero09.mp3",
    ["Id"] =  53309,
    ["Length"] = 74,
    ["Artist"] = "Russell Brower",
    ["WoW"] =  "true",
  },
  {
		["Album"] = "WoW 2.4 - Fury of the Sunwell",
		["Song"] = "Sunwell Flyby",
		["Name"] = "sound\\music\\zonemusic\\sunwell\\sw_sunwellflybyuni01.mp3",
		["Id"] =  53733,
		["Length"] = 57,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
  {
		["Album"] = "WoW 2.4 - Fury of the Sunwell",
		["Song"] = "Shorel'Aran Vocal",
		["Name"] = "sound\\music\\zonemusic\\sunwell\\sw_shorelaranwalkuni01.mp3",
		["Id"] =  53731,
		["Length"] = 87,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
  {
		["Album"] = "WoW 2.4 - Fury of the Sunwell",
		["Song"] = "Silvermoon 2",
		["Name"] = "sound\\music\\zonemusic\\sunwell\\sw_magistersasylumwalkuni01.mp3",
		["Id"] =  53713,
		["Length"] = 97,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
  {
		["Album"] = "WoW 3.0 - Wrath of the Lich King",
		["Song"] = "Iron Dwarf Walk E Dark Uni",
		["Name"] = "sound\\music\\zonemusic\\northrend\\irondwarf\\nr_dwarf_generalwalkddark_uni05.mp3",
		["Id"] =  229903,
		["Length"] = 69,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
  {
		["Album"] = "WoW 3.0 - Wrath of the Lich King",
		["Song"] = "Storm Peaks Walk B Day",
		["Name"] = "sound\\music\\zonemusic\\stormpeaks\\sp_generalwalkb_day02.mp3",
		["Id"] =  229956,
		["Length"] = 82,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
  {
    ["Album"] = "WoW 3.0 - Wrath of the Lich King",
    ["Song"] = "Iron Dwarf Walk B Day",
    ["Name"] = "sound\\music\\zonemusic\\northrend\\irondwarf\\nr_dwarf_generalwalkb_day02.mp3",
    ["Id"] =  229894,
    ["Length"] = 97,
    ["Artist"] = "Unknown",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 3.0 - Wrath of the Lich King",
    ["Song"] = "Storm Peaks Walk B Uni",
    ["Name"] = "sound\\music\\zonemusic\\stormpeaks\\sp_generalwalkb_uni02.mp3",
    ["Id"] =  229958,
    ["Length"] = 82,
    ["Artist"] = "Unknown",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 3.0 - Wrath of the Lich King",
    ["Song"] = "Culling of Strathholme Alley Intro",
    ["Name"] = "sound\\music\\zonemusic\\stratholmepast\\ct_stratholmepastalleyintro.mp3",
    ["Id"] =  229969,
    ["Length"] = 99,
    ["Artist"] = "Unknown",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 3.0 - Wrath of the Lich King",
    ["Song"] = "Dalaran 1",
    ["Name"] = "sound\\music\\zonemusic\\dalaran\\dc_generalwalkuni01.mp3",
    ["Id"] =  229800,
    ["Length"] = 67,
    ["Artist"] = "Russell Brower",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 3.0 - Wrath of the Lich King",
    ["Song"] = "Dalaran Intro",
    ["Name"] = "sound\\music\\zonemusic\\dalaran\\dc_introuni01.mp3",
    ["Id"] =  229804,
    ["Length"] = 68,
    ["Artist"] = "Russell Brower",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 3.0 - Wrath of the Lich King",
    ["Song"] = "Ebon Hold 1",
    ["Name"] = "sound\\music\\zonemusic\\ebon hold\\eh_generalwalkuni01.mp3",
    ["Id"] =  229831,
    ["Length"] = 82,
    ["Artist"] = "Russell Brower",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 3.0 - Wrath of the Lich King",
    ["Song"] = "Assault 2",
    ["Name"] = "sound\\music\\zonemusic\\ebon hold\\eh_assaultuni02.mp3",
    ["Id"] =  229825,
    ["Length"] = 69,
    ["Artist"] = "Russell Brower",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 3.0 - Wrath of the Lich King",
    ["Song"] = "Grizzly Hills 1 Harpa",
    ["Name"] = "sound\\music\\zonemusic\\grizzlyhills\\gh_intro1uni01.mp3",
    ["Id"] =  229834,
    ["Length"] = 284,
    ["Artist"] = "Russell Brower",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 3.0 - Wrath of the Lich King",
    ["Song"] = "Grizzly Hills 2 Hero v3",
    ["Name"] = "sound\\music\\zonemusic\\grizzlyhills\\gh_intro2uni01.mp3",
    ["Id"] =  229835,
    ["Length"] = 149,
    ["Artist"] = "Russell Brower",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 3.1 - Secrets of Ulduar",
    ["Song"] = "Argent Joust",
    ["Name"] = "sound\\music\\zonemusic\\argenttournament\\at_joustevent.mp3",
    ["Id"] =  303111,
    ["Length"] = 123,
    ["Artist"] = "David Arkenstone",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 3.3 - Fall of the Lich King",
    ["Song"] = "Invincible",
    ["Name"] = "sound\\music\\draenor\\mus_invincible.mp3",
    ["Id"] =  1100052,
    ["Length"] = 197,
    ["Artist"] = "Russell Brower",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 4.0 - Cataclysm",
    ["Song"] = "Night Elves 1",
    ["Name"] = "sound\\music\\cataclysm\\mus_nightelves_gu01.mp3",
    ["Id"] =  441705,
    ["Length"] = 160,
    ["Artist"] = "Neal Acree",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 4.0 - Cataclysm",
    ["Song"] = "LI Event Rescue 01",
    ["Name"] = "sound\\music\\cataclysm\\mus_lirescue_eu01.mp3",
    ["Id"] =  443303,
    ["Length"] = 37,
    ["Artist"] = "Derek Duke",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 4.0 - Cataclysm",
    ["Song"] = "Darnassus Intro New NA v1",
    ["Name"] = "sound\\music\\cataclysm\\mus_darnassus_gi01.mp3",
    ["Id"] =  441574,
    ["Length"] = 48,
    ["Artist"] = "Neal Acree",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 4.0 - Cataclysm",
    ["Song"] = "Stormwind Variation v4",
    ["Name"] = "sound\\music\\cataclysm\\mus_stormwind_gu04.mp3",
    ["Id"] =  441767,
    ["Length"] = 66,
    ["Artist"] = "Neal Acree",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 4.0 - Cataclysm",
    ["Song"] = "Aftermath 1",
    ["Name"] = "sound\\music\\cataclysm\\mus_aftermath_uu01.mp3",
    ["Id"] =  441521,
    ["Length"] = 125,
    ["Artist"] = "David Arkenstone",
    ["WoW"] =  "true",
  },
  {
    ["Album"] = "WoW 4.2 - Rage of the Firelands",
    ["Song"] = "Druids of the Flame 1H",
    ["Name"] = "sound\\music\\cataclysm\\mus_42_druidsoftheflamea_hero_uu01.mp3",
    ["Id"] =  528352,
    ["Length"] = 91,
    ["Artist"] = "Russell Brower",
    ["WoW"] =  "true",
  },
  {
		["Album"] = "WoW 4.2 - Rage of the Firelands",
		["Song"] = "Thrall & Aggra 1",
		["Name"] = "sound\\music\\cataclysm\\mus_42_thrallaggraa_ed01.mp3",
		["Id"] =  528174,
		["Length"] = 72,
		["Artist"] = "Unknown",
		["WoW"] =  "true",
	},
  {
		["Album"] = "WoW 5.0 - Mists of Pandaria",
		["Song"] = "Gecko 2H",
		["Name"] = "sound\\music\\zonemusic\\wanderingisle\\mus_50_wanderingisleb_hero_uu01.mp3",
		["Id"] =  574908,
		["Length"] = 135,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
  {
		["Album"] = "WoW 5.0 - Mists of Pandaria",
		["Song"] = "Balloon Ride H",
		["Name"] = "sound\\music\\pandaria\\mus_50_balloonride_hero_01.mp3",
		["Id"] =  642176,
		["Length"] = 168,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
  {
		["Album"] = "WoW 5.0 - Mists of Pandaria",
		["Song"] = "Song of Liulang 1H (with Voice)",
		["Name"] = "sound\\music\\pandaria\\mus_50_songofliulang_vox_hero_01.mp3",
		["Id"] =  642577,
		["Length"] = 170,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
  {
		["Album"] = "WoW 5.0 - Mists of Pandaria",
		["Song"] = "Serpent Riders Race",
		["Name"] = "sound\\music\\pandaria\\mus_50_serpentriders_serpentrace.mp3",
		["Id"] =  653741,
		["Length"] = 238,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
  {
		["Album"] = "WoW 5.0 - Mists of Pandaria",
		["Song"] = "Ginsu Valor 3H",
		["Name"] = "sound\\music\\pandaria\\mus_50_shadopan_a_hero_03.mp3",
		["Id"] =  642268,
		["Length"] = 172,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
  {
		["Album"] = "WoW 5.0 - Mists of Pandaria",
		["Song"] = "Shado-Pan Walk 2 (Cardon 4 Strings)",
		["Name"] = "sound\\music\\pandaria\\mus_50_shadopan_a_walk_02.mp3",
		["Id"] =  644930,
		["Length"] = 65,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
  {
		["Album"] = "WoW 5.0 - Mists of Pandaria",
		["Song"] = "Way of the Monk v2",
		["Name"] = "sound\\music\\pandaria\\mus_50_monk_windwalker_a_01.mp3",
		["Id"] =  642243,
		["Length"] = 157,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
  },
  {
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Stormlords on the March H1",
		["Name"] = "sound\\music\\draenor\\mus_60_stormlordsonthemarch_h1.mp3",
		["Id"] =  1067075,
		["Length"] = 88,
		["Artist"] = "Eimear Noone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Stormlords on the March H2",
		["Name"] = "sound\\music\\draenor\\mus_60_stormlordsonthemarch_h2.mp3",
		["Id"] =  1067076,
		["Length"] = 46,
		["Artist"] = "Eimear Noone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW 6.0 - Warlords of Draenor",
		["Song"] = "Stormlords on the March H3",
		["Name"] = "sound\\music\\draenor\\mus_60_stormlordsonthemarch_h3.mp3",
		["Id"] =  1067077,
		["Length"] = 101,
		["Artist"] = "Eimear Noone",
		["WoW"] =  "true",
	},
  {
		["Album"] = "WoW 7.0 - Legion",
		["Song"] = "Anduin Pt2 H",
		["Name"] = "sound\\music\\legion\\mus_70_anduinpt2_h.mp3",
		["Id"] =  1417250,
		["Length"] = 122,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
  {
		["Album"] = "WoW 8.0 - Battle for Azeroth",
		["Song"] = "Battle for Azeroth 8.0 RTC - Jaina Intro",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_design_kultiras_jainaintro.mp3",
		["Id"] =  2204149,
		["Length"] = 109,
		["Artist"] = "",
		["WoW"] =  "true",
	},
}

local EpicMusicPlayer = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer")

if not EpicMusicPlayer then return end

EpicMusicPlayer:AddPlayList("Best of Wow", BestofWoW, false)
