-- EpicMusicPlayer playlist created by EpicPlaylistCreator version 1.6.
local playlist1={
  ["listName"] = "Legion",
  ["playlistVersion"] = "3.1",
  ["playlistType"] = "generated",
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_arguscore1_h",
    ["Name"] = "sound\\music\\legion\\mus_73_arguscore1_h.mp3",
    ["Length"] = 87,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 3 B",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain3_b.mp3",
    ["Length"] = 66,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare J",
    ["Name"] = "sound\\music\\legion\\mus_70_emeraldnightmare_j.mp3",
    ["Length"] = 100,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Bucket O' Zurchgrax A",
    ["Name"] = "sound\\music\\legion\\mus_72_tombofsargeras_battlea.mp3",
    ["Length"] = 60,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Fel Glade H",
    ["Name"] = "sound\\music\\legion\\mus_70_felglade_h.mp3",
    ["Length"] = 97,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Tempest A",
    ["Name"] = "sound\\music\\legion\\mus_70_tempest_a.mp3",
    ["Length"] = 146,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Ley Lines C",
    ["Name"] = "sound\\music\\legion\\mus_70_leylines_c.mp3",
    ["Length"] = 65,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Ruined Cathedral D",
    ["Name"] = "sound\\music\\legion\\mus_72_ruinedcathedrald.mp3",
    ["Length"] = 61,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Last Stand E",
    ["Name"] = "sound\\music\\legion\\mus_70_laststand_e.mp3",
    ["Length"] = 79,
    ["Artist"] = "Sam Cardon, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Half Bucket H",
    ["Name"] = "sound\\music\\legion\\mus_72_tombofsargeras_battleh2.mp3",
    ["Length"] = 54,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Last Stand D",
    ["Name"] = "sound\\music\\legion\\mus_70_laststand_d.mp3",
    ["Length"] = 79,
    ["Artist"] = "Sam Cardon, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Passage H1",
    ["Name"] = "sound\\music\\legion\\mus_70_passage_h1.mp3",
    ["Length"] = 102,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Ley Lines B",
    ["Name"] = "sound\\music\\legion\\mus_70_leylines_b.mp3",
    ["Length"] = 69,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Ruined Cathedral E",
    ["Name"] = "sound\\music\\legion\\mus_72_ruinedcathedrale.mp3",
    ["Length"] = 50,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 9 H",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain9_h.mp3",
    ["Length"] = 37,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus2pt2_h",
    ["Name"] = "sound\\music\\legion\\mus_73_argus2pt2_h.mp3",
    ["Length"] = 123,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 1 A",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain1_a.mp3",
    ["Length"] = 84,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Laila Demon D2",
    ["Name"] = "sound\\music\\legion\\mus_70_lailademon_d2.mp3",
    ["Length"] = 97,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Kil'Jaeden D",
    ["Name"] = "sound\\music\\legion\\mus_72_kiljaedend.mp3",
    ["Length"] = 85,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare K",
    ["Name"] = "sound\\music\\legion\\mus_70_emeraldnightmare_k.mp3",
    ["Length"] = 114,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt1 H2",
    ["Name"] = "sound\\music\\legion\\mus_70_anduinpt1_h2.mp3",
    ["Length"] = 115,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 3 A",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain3_a.mp3",
    ["Length"] = 66,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Bucket O' Zurchgrax B",
    ["Name"] = "sound\\music\\legion\\mus_72_tombofsargeras_battleb.mp3",
    ["Length"] = 71,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Tempest B",
    ["Name"] = "sound\\music\\legion\\mus_70_tempest_b.mp3",
    ["Length"] = 40,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Canticle of Sacrifice H",
    ["Name"] = "sound\\music\\legion\\mus_70_canticleofsacrifice_h.mp3",
    ["Length"] = 253,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Dusk H",
    ["Name"] = "sound\\music\\legion\\mus_70_dalarandusk_h.mp3",
    ["Length"] = 98,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Nos'Sharah E",
    ["Name"] = "sound\\music\\legion\\mus_70_nossharah_e.mp3",
    ["Length"] = 76,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Last Stand F",
    ["Name"] = "sound\\music\\legion\\mus_70_laststand_f.mp3",
    ["Length"] = 79,
    ["Artist"] = "Sam Cardon, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Cavern Wind H",
    ["Name"] = "sound\\music\\legion\\mus_72_cavernwindh.mp3",
    ["Length"] = 124,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Bucket O' Zurchgrax H",
    ["Name"] = "sound\\music\\legion\\mus_72_tombofsargeras_battleh1.mp3",
    ["Length"] = 29,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Passage H2",
    ["Name"] = "sound\\music\\legion\\mus_70_passage_h2.mp3",
    ["Length"] = 85,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Nos'Sharah D",
    ["Name"] = "sound\\music\\legion\\mus_70_nossharah_d.mp3",
    ["Length"] = 127,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Ruined Cathedral F",
    ["Name"] = "sound\\music\\legion\\mus_72_ruinedcathedralf.mp3",
    ["Length"] = 124,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Ley Lines A",
    ["Name"] = "sound\\music\\legion\\mus_70_leylines_a.mp3",
    ["Length"] = 69,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 1 B",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain1_b.mp3",
    ["Length"] = 92,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Enchanted Night Elves H",
    ["Name"] = "sound\\music\\legion\\mus_70_enchantednightelves_h.mp3",
    ["Length"] = 101,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Tempest C",
    ["Name"] = "sound\\music\\legion\\mus_70_tempest_c.mp3",
    ["Length"] = 77,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_Invincible_Stinger_01",
    ["Name"] = "sound\\music\\legion\\mus_70_invincible_stinger_01.mp3",
    ["Length"] = 12,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Laila Demon D1",
    ["Name"] = "sound\\music\\legion\\mus_70_lailademon_d1.mp3",
    ["Length"] = 95,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt1 H1",
    ["Name"] = "sound\\music\\legion\\mus_70_anduinpt1_h1.mp3",
    ["Length"] = 88,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "R2Kara 1H",
    ["Name"] = "sound\\music\\legion\\mus_71_karazhan_1h.mp3",
    ["Length"] = 59,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Sewers 1 H",
    ["Name"] = "sound\\music\\legion\\mus_70_dalaransewers1_h.mp3",
    ["Length"] = 131,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Kil'Jaeden C",
    ["Name"] = "sound\\music\\legion\\mus_72_kiljaedenc.mp3",
    ["Length"] = 58,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare L",
    ["Name"] = "sound\\music\\legion\\mus_70_emeraldnightmare_l.mp3",
    ["Length"] = 97,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_MylunesMelody_Full",
    ["Name"] = "sound\\music\\legion\\mus_70_mylunesmelody_full.mp3",
    ["Length"] = 44,
    ["Artist"] = "Derek Duke, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Dawn H",
    ["Name"] = "sound\\music\\legion\\mus_70_dalarandawn_h.mp3",
    ["Length"] = 93,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Tempest G",
    ["Name"] = "sound\\music\\legion\\mus_70_tempest_g.mp3",
    ["Length"] = 25,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Ruined Cathedral B",
    ["Name"] = "sound\\music\\legion\\mus_72_ruinedcathedralb.mp3",
    ["Length"] = 38,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "We Are Not Alone A",
    ["Name"] = "sound\\music\\legion\\mus_70_wearenotalone_a.mp3",
    ["Length"] = 90,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt2 C",
    ["Name"] = "sound\\music\\legion\\mus_70_demonhunterpt2_c.mp3",
    ["Length"] = 73,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus1pt1_b",
    ["Name"] = "sound\\music\\legion\\mus_73_argus1pt1_b.mp3",
    ["Length"] = 103,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 5 B",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain5_b.mp3",
    ["Length"] = 62,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Last Stand C",
    ["Name"] = "sound\\music\\legion\\mus_70_laststand_c.mp3",
    ["Length"] = 79,
    ["Artist"] = "Sam Cardon, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Last Stand B",
    ["Name"] = "sound\\music\\legion\\mus_70_laststand_b.mp3",
    ["Length"] = 79,
    ["Artist"] = "Sam Cardon, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Chaos Chimes",
    ["Name"] = "sound\\music\\legion\\mus_70_chaoschimes_01.mp3",
    ["Length"] = 82,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Nos'Sharah A",
    ["Name"] = "sound\\music\\legion\\mus_70_nossharah_a.mp3",
    ["Length"] = 76,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus1pt1_c",
    ["Name"] = "sound\\music\\legion\\mus_73_argus1pt1_c.mp3",
    ["Length"] = 102,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Ruined Cathedral C",
    ["Name"] = "sound\\music\\legion\\mus_72_ruinedcathedralc.mp3",
    ["Length"] = 59,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 7 A",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain7_a.mp3",
    ["Length"] = 43,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus1pt3_a",
    ["Name"] = "sound\\music\\legion\\mus_73_argus1pt3_a.mp3",
    ["Length"] = 68,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Order Hall Devotions H",
    ["Name"] = "sound\\music\\legion\\mus_70_orderhalldevotions_h.mp3",
    ["Length"] = 126,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Tempest F",
    ["Name"] = "sound\\music\\legion\\mus_70_tempest_f.mp3",
    ["Length"] = 16,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Halls 2 A",
    ["Name"] = "sound\\music\\legion\\mus_70_dalaranhalls2_a.mp3",
    ["Length"] = 110,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Suramar Pt1 A",
    ["Name"] = "sound\\music\\legion\\mus_70_suramar_pt1_a.mp3",
    ["Length"] = 69,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare M",
    ["Name"] = "sound\\music\\legion\\mus_70_emeraldnightmare_m.mp3",
    ["Length"] = 92,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Elf Tomb H1",
    ["Name"] = "sound\\music\\legion\\mus_70_highelftomb_h1.mp3",
    ["Length"] = 101,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Kil'Jaeden B",
    ["Name"] = "sound\\music\\legion\\mus_72_kiljaedenb.mp3",
    ["Length"] = 44,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Stormheim B2",
    ["Name"] = "sound\\music\\legion\\mus_70_stormheim_b2.mp3",
    ["Length"] = 123,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Oath H",
    ["Name"] = "sound\\music\\legion\\mus_70_holywarriorsoath_h.mp3",
    ["Length"] = 132,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_ClientScene_MAW_Intro_Moment",
    ["Name"] = "sound\\music\\legion\\mus_70_clientscene_maw_intro_moment.mp3",
    ["Length"] = 20,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "As Soon As'Pret H",
    ["Name"] = "sound\\music\\legion\\mus_70_assoonaspret_h.mp3",
    ["Length"] = 126,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Tempest D",
    ["Name"] = "sound\\music\\legion\\mus_70_tempest_d.mp3",
    ["Length"] = 76,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus1pt3_c",
    ["Name"] = "sound\\music\\legion\\mus_73_argus1pt3_c.mp3",
    ["Length"] = 67,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "Eternal Holly Brew H",
    ["Name"] = "sound\\music\\legion\\mus_71_eternalhollybrew_h.mp3",
    ["Length"] = 206,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Ruined Cathedral A",
    ["Name"] = "sound\\music\\legion\\mus_72_ruinedcathedrala.mp3",
    ["Length"] = 53,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "We Are Not Alone B",
    ["Name"] = "sound\\music\\legion\\mus_70_wearenotalone_b.mp3",
    ["Length"] = 60,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus1pt1_a",
    ["Name"] = "sound\\music\\legion\\mus_73_argus1pt1_a.mp3",
    ["Length"] = 102,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Nos'Sharah C",
    ["Name"] = "sound\\music\\legion\\mus_70_nossharah_c.mp3",
    ["Length"] = 46,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 5 A",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain5_a.mp3",
    ["Length"] = 62,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Last Stand H3 End",
    ["Name"] = "sound\\music\\legion\\mus_70_laststand_h3end.mp3",
    ["Length"] = 72,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Last Stand A",
    ["Name"] = "sound\\music\\legion\\mus_70_laststand_a.mp3",
    ["Length"] = 79,
    ["Artist"] = "Sam Cardon, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "No Returning H",
    ["Name"] = "sound\\music\\legion\\mus_72_noreturningh.mp3",
    ["Length"] = 180,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Nos'Sharah B",
    ["Name"] = "sound\\music\\legion\\mus_70_nossharah_b.mp3",
    ["Length"] = 63,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Sacred Stone H",
    ["Name"] = "sound\\music\\legion\\mus_70_sacredstone_h.mp3",
    ["Length"] = 124,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt2 H",
    ["Name"] = "sound\\music\\legion\\mus_70_anduinpt2_h.mp3",
    ["Length"] = 123,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_balefulnight_h",
    ["Name"] = "sound\\music\\legion\\mus_73_balefulnight_h.mp3",
    ["Length"] = 91,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt2 A",
    ["Name"] = "sound\\music\\legion\\mus_70_demonhunterpt2_a.mp3",
    ["Length"] = 56,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 7 B",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain7_b.mp3",
    ["Length"] = 44,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Kingdoms Will Burn",
    ["Name"] = "sound\\music\\legion\\mus_70_kingdomswillburn_maintitle.mp3",
    ["Length"] = 650,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus1pt3_b",
    ["Name"] = "sound\\music\\legion\\mus_73_argus1pt3_b.mp3",
    ["Length"] = 68,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Suramar Pt1 B",
    ["Name"] = "sound\\music\\legion\\mus_70_suramar_pt1_b.mp3",
    ["Length"] = 59,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Tempest E",
    ["Name"] = "sound\\music\\legion\\mus_70_tempest_e.mp3",
    ["Length"] = 16,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Halls 2 B",
    ["Name"] = "sound\\music\\legion\\mus_70_dalaranhalls2_b.mp3",
    ["Length"] = 111,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Kil'Jaeden A",
    ["Name"] = "sound\\music\\legion\\mus_72_kiljaedena.mp3",
    ["Length"] = 62,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Elf Tomb H2",
    ["Name"] = "sound\\music\\legion\\mus_70_highelftomb_h2.mp3",
    ["Length"] = 112,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Stormheim B1",
    ["Name"] = "sound\\music\\legion\\mus_70_stormheim_b1.mp3",
    ["Length"] = 77,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt1 D",
    ["Name"] = "sound\\music\\legion\\mus_70_demonhunterpt1_d.mp3",
    ["Length"] = 79,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3.2",
    ["Song"] = "MUS_73_SeatofthePantheon_B",
    ["Name"] = "sound\\music\\legion\\mus_73_seatofthepantheon_b.mp3",
    ["Length"] = 73,
    ["Artist"] = "Glenn Stafford, Adam Burgess",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_xera_a",
    ["Name"] = "sound\\music\\legion\\mus_73_xera_a.mp3",
    ["Length"] = 109,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_ClientScene_70_IF1_01",
    ["Name"] = "sound\\music\\legion\\mus_70_clientscene_70_if1_01.mp3",
    ["Length"] = 45,
    ["Artist"] = "Tracy W. Bush",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus1pt4_c",
    ["Name"] = "sound\\music\\legion\\mus_73_argus1pt4_c.mp3",
    ["Length"] = 102,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Shackled H",
    ["Name"] = "sound\\music\\legion\\mus_72_shackledh.mp3",
    ["Length"] = 120,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Relentless J",
    ["Name"] = "sound\\music\\legion\\mus_70_relentless_j.mp3",
    ["Length"] = 78,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 2 A",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain2_a.mp3",
    ["Length"] = 84,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus2pt1_h",
    ["Name"] = "sound\\music\\legion\\mus_73_argus2pt1_h.mp3",
    ["Length"] = 69,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Weep Horn",
    ["Name"] = "sound\\music\\legion\\mus_70_weep_horn.mp3",
    ["Length"] = 111,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_arguscore2_h",
    ["Name"] = "sound\\music\\legion\\mus_73_arguscore2_h.mp3",
    ["Length"] = 85,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Jaina H",
    ["Name"] = "sound\\music\\legion\\mus_70_dalaranjaina_h.mp3",
    ["Length"] = 66,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Enraptured Woodlands A",
    ["Name"] = "sound\\music\\legion\\mus_70_enrapturedwoodlands_a.mp3",
    ["Length"] = 123,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "Kara Vortex",
    ["Name"] = "sound\\music\\legion\\mus_71_karazhan_vortex_01.mp3",
    ["Length"] = 74,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Last Stand H1",
    ["Name"] = "sound\\music\\legion\\mus_70_laststand_h1.mp3",
    ["Length"] = 84,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Gather A",
    ["Name"] = "sound\\music\\legion\\mus_70_holywarriorsgather_a.mp3",
    ["Length"] = 61,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3.2",
    ["Song"] = "MUS_73_SeatofthePantheon_C",
    ["Name"] = "sound\\music\\legion\\mus_73_seatofthepantheon_c.mp3",
    ["Length"] = 81,
    ["Artist"] = "Glenn Stafford, Adam Burgess",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "mus_71_karazhan_7h",
    ["Name"] = "sound\\music\\legion\\mus_71_karazhan_7h.mp3",
    ["Length"] = 38,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_RuinsOfAuberdine_01_Stinger_01",
    ["Name"] = "sound\\music\\legion\\mus_70_ruinsofauberdine_01_stinger_01.mp3",
    ["Length"] = 9,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3.2",
    ["Song"] = "MUS_73_SeatofthePantheon_A",
    ["Name"] = "sound\\music\\legion\\mus_73_seatofthepantheon_a.mp3",
    ["Length"] = 68,
    ["Artist"] = "Glenn Stafford, Adam Burgess",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Gather C",
    ["Name"] = "sound\\music\\legion\\mus_70_holywarriorsgather_c.mp3",
    ["Length"] = 138,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Sewers 2 H",
    ["Name"] = "sound\\music\\legion\\mus_70_dalaransewers2_h.mp3",
    ["Length"] = 155,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Enraptured Woodlands C",
    ["Name"] = "sound\\music\\legion\\mus_70_enrapturedwoodlands_c.mp3",
    ["Length"] = 93,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Awakenings H",
    ["Name"] = "sound\\music\\legion\\mus_72_awakeningsh.mp3",
    ["Length"] = 72,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Tomb of Sargeras H",
    ["Name"] = "sound\\music\\legion\\mus_72_tombofsargerash.mp3",
    ["Length"] = 155,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 2 B",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain2_b.mp3",
    ["Length"] = 84,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Relentless H",
    ["Name"] = "sound\\music\\legion\\mus_70_relentless_h.mp3",
    ["Length"] = 149,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "Winter Holiday H",
    ["Name"] = "sound\\music\\legion\\mus_71_winterholiday_h.mp3",
    ["Length"] = 112,
    ["Artist"] = "Shelly and Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "MUS_72_Mount_Scene_Hero",
    ["Name"] = "sound\\music\\legion\\mus_72_mount_scene_hero.mp3",
    ["Length"] = 29,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Laila Demon H",
    ["Name"] = "sound\\music\\legion\\mus_70_lailademon_h.mp3",
    ["Length"] = 192,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities H3",
    ["Name"] = "sound\\music\\legion\\mus_70_requiemforthelostcities_h3end.mp3",
    ["Length"] = 92,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus1pt4_a",
    ["Name"] = "sound\\music\\legion\\mus_73_argus1pt4_a.mp3",
    ["Length"] = 102,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Enraptured Woodlands B",
    ["Name"] = "sound\\music\\legion\\mus_70_enrapturedwoodlands_b.mp3",
    ["Length"] = 102,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "MUS_72_Mount_Scene_Dark",
    ["Name"] = "sound\\music\\legion\\mus_72_mount_scene_dark.mp3",
    ["Length"] = 32,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Last Stand H2",
    ["Name"] = "sound\\music\\legion\\mus_70_laststand_h2.mp3",
    ["Length"] = 87,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Rose A",
    ["Name"] = "sound\\music\\legion\\mus_70_rose_a.mp3",
    ["Length"] = 75,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt3 D",
    ["Name"] = "sound\\music\\legion\\mus_70_demonhunterpt3_d.mp3",
    ["Length"] = 65,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Gather B",
    ["Name"] = "sound\\music\\legion\\mus_70_holywarriorsgather_b.mp3",
    ["Length"] = 137,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 8 H",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain8_h.mp3",
    ["Length"] = 50,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "Eternal Holly Brew HwB",
    ["Name"] = "sound\\music\\legion\\mus_71_eternalhollybrew_hwb.mp3",
    ["Length"] = 208,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare Orch H",
    ["Name"] = "sound\\music\\legion\\mus_70_emeraldnightmareorch_h.mp3",
    ["Length"] = 138,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 4 A",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain4_a.mp3",
    ["Length"] = 104,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt1 B",
    ["Name"] = "sound\\music\\legion\\mus_70_demonhunterpt1_b.mp3",
    ["Length"] = 110,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus1pt2_c",
    ["Name"] = "sound\\music\\legion\\mus_73_argus1pt2_c.mp3",
    ["Length"] = 85,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_ancienteredar_h",
    ["Name"] = "sound\\music\\legion\\mus_73_ancienteredar_h.mp3",
    ["Length"] = 133,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Halls 1 A",
    ["Name"] = "sound\\music\\legion\\mus_70_dalaranhalls1_a.mp3",
    ["Length"] = 134,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Suramar Pt2 A",
    ["Name"] = "sound\\music\\legion\\mus_70_suramar_pt2_a.mp3",
    ["Length"] = 64,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Fel Titan A",
    ["Name"] = "sound\\music\\legion\\mus_72_feltitana.mp3",
    ["Length"] = 78,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Moon Rising A",
    ["Name"] = "sound\\music\\legion\\mus_70_moonrising_a.mp3",
    ["Length"] = 122,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt3 A",
    ["Name"] = "sound\\music\\legion\\mus_70_demonhunterpt3_a.mp3",
    ["Length"] = 72,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 6 B",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain6_b.mp3",
    ["Length"] = 80,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus1pt2_b",
    ["Name"] = "sound\\music\\legion\\mus_73_argus1pt2_b.mp3",
    ["Length"] = 86,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt1 C",
    ["Name"] = "sound\\music\\legion\\mus_70_demonhunterpt1_c.mp3",
    ["Length"] = 67,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities H2",
    ["Name"] = "sound\\music\\legion\\mus_70_requiemforthelostcities_h2.mp3",
    ["Length"] = 29,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 4 B",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain4_b.mp3",
    ["Length"] = 105,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "R2Kara 6H",
    ["Name"] = "sound\\music\\legion\\mus_71_karazhan_6h.mp3",
    ["Length"] = 105,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_ClientScene_70_IF3_01",
    ["Name"] = "sound\\music\\legion\\mus_70_clientscene_70_if3_01.mp3",
    ["Length"] = 70,
    ["Artist"] = "",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Khadgar Night H",
    ["Name"] = "sound\\music\\legion\\mus_70_dalarankhadgar_night_h.mp3",
    ["Length"] = 74,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt3 C",
    ["Name"] = "sound\\music\\legion\\mus_70_demonhunterpt3_c.mp3",
    ["Length"] = 37,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Moon Rising C",
    ["Name"] = "sound\\music\\legion\\mus_70_moonrising_c.mp3",
    ["Length"] = 125,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Fel Titan C",
    ["Name"] = "sound\\music\\legion\\mus_72_feltitanc.mp3",
    ["Length"] = 70,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Suramar Pt2 B",
    ["Name"] = "sound\\music\\legion\\mus_70_suramar_pt2_b.mp3",
    ["Length"] = 95,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Halls 1 B",
    ["Name"] = "sound\\music\\legion\\mus_70_dalaranhalls1_b.mp3",
    ["Length"] = 127,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Halls 1 C",
    ["Name"] = "sound\\music\\legion\\mus_70_dalaranhalls1_c.mp3",
    ["Length"] = 131,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "MUS_71_BondsofFate",
    ["Name"] = "sound\\music\\legion\\mus_71_bondsoffate.mp3",
    ["Length"] = 88,
    ["Artist"] = "Neal Acree, Jason Hayes",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare Syn H",
    ["Name"] = "sound\\music\\legion\\mus_70_emeraldnightmaresyn_h.mp3",
    ["Length"] = 129,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Stormheim H",
    ["Name"] = "sound\\music\\legion\\mus_70_stormheim_h.mp3",
    ["Length"] = 198,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Fel Titan B",
    ["Name"] = "sound\\music\\legion\\mus_72_feltitanb.mp3",
    ["Length"] = 68,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 10 H",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain10_h.mp3",
    ["Length"] = 111,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Moon Rising B",
    ["Name"] = "sound\\music\\legion\\mus_70_moonrising_b.mp3",
    ["Length"] = 120,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt3 B",
    ["Name"] = "sound\\music\\legion\\mus_70_demonhunterpt3_b.mp3",
    ["Length"] = 72,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 6 A",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain6_a.mp3",
    ["Length"] = 79,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus1pt2_a",
    ["Name"] = "sound\\music\\legion\\mus_73_argus1pt2_a.mp3",
    ["Length"] = 86,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Khadgar Day H",
    ["Name"] = "sound\\music\\legion\\mus_70_dalarankhadgar_day_h.mp3",
    ["Length"] = 68,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities H1",
    ["Name"] = "sound\\music\\legion\\mus_70_requiemforthelostcities_h1.mp3",
    ["Length"] = 92,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Winds Out of the East A",
    ["Name"] = "sound\\music\\legion\\mus_70_windsoutoftheeast_a.mp3",
    ["Length"] = 96,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Glimmer H",
    ["Name"] = "sound\\music\\legion\\mus_70_glimmer_h.mp3",
    ["Length"] = 47,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "R2Kara 5H",
    ["Name"] = "sound\\music\\legion\\mus_71_karazhan_5h.mp3",
    ["Length"] = 126,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt1 D",
    ["Name"] = "sound\\music\\legion\\mus_70_anduinpt1_d.mp3",
    ["Length"] = 90,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Tempest H2",
    ["Name"] = "sound\\music\\legion\\mus_70_tempest_h2.mp3",
    ["Length"] = 78,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Preserver H3 End",
    ["Name"] = "sound\\music\\legion\\mus_70_preserver_h3end.mp3",
    ["Length"] = 56,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_xera_h",
    ["Name"] = "sound\\music\\legion\\mus_73_xera_h.mp3",
    ["Length"] = 108,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Sewers 2 B",
    ["Name"] = "sound\\music\\legion\\mus_70_dalaransewers2_b.mp3",
    ["Length"] = 129,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Laila Demon C",
    ["Name"] = "sound\\music\\legion\\mus_70_lailademon_c.mp3",
    ["Length"] = 121,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Awakenings B",
    ["Name"] = "sound\\music\\legion\\mus_72_awakeningsb.mp3",
    ["Length"] = 58,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Stormheim E",
    ["Name"] = "sound\\music\\legion\\mus_70_stormheim_e.mp3",
    ["Length"] = 54,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus2pt1_a",
    ["Name"] = "sound\\music\\legion\\mus_73_argus2pt1_a.mp3",
    ["Length"] = 69,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 2 H",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain2_h.mp3",
    ["Length"] = 84,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Relentless C",
    ["Name"] = "sound\\music\\legion\\mus_70_relentless_c.mp3",
    ["Length"] = 7,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "Winter Holiday C",
    ["Name"] = "sound\\music\\legion\\mus_71_winterholiday_c.mp3",
    ["Length"] = 113,
    ["Artist"] = "Shelly and Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Tomb of Sargeras B",
    ["Name"] = "sound\\music\\legion\\mus_72_tombofsargerasb.mp3",
    ["Length"] = 58,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Shackled A",
    ["Name"] = "sound\\music\\legion\\mus_72_shackleda.mp3",
    ["Length"] = 121,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Tomb of Sargeras C",
    ["Name"] = "sound\\music\\legion\\mus_72_tombofsargerasc.mp3",
    ["Length"] = 54,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "Winter Holiday B",
    ["Name"] = "sound\\music\\legion\\mus_71_winterholiday_b.mp3",
    ["Length"] = 112,
    ["Artist"] = "Shelly and Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Relentless B",
    ["Name"] = "sound\\music\\legion\\mus_70_relentless_b.mp3",
    ["Length"] = 7,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Stormheim D",
    ["Name"] = "sound\\music\\legion\\mus_70_stormheim_d.mp3",
    ["Length"] = 42,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_arguscore2_a",
    ["Name"] = "sound\\music\\legion\\mus_73_arguscore2_a.mp3",
    ["Length"] = 83,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Awakenings C",
    ["Name"] = "sound\\music\\legion\\mus_72_awakeningsc.mp3",
    ["Length"] = 56,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Laila Demon B",
    ["Name"] = "sound\\music\\legion\\mus_70_lailademon_b.mp3",
    ["Length"] = 125,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Elf Tomb A",
    ["Name"] = "sound\\music\\legion\\mus_70_highelftomb_a.mp3",
    ["Length"] = 69,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_ancienteredar_f",
    ["Name"] = "sound\\music\\legion\\mus_73_ancienteredar_f.mp3",
    ["Length"] = 124,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Enraptured Woodlands H",
    ["Name"] = "sound\\music\\legion\\mus_70_enrapturedwoodlands_h.mp3",
    ["Length"] = 124,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Jaina A",
    ["Name"] = "sound\\music\\legion\\mus_70_dalaranjaina_a.mp3",
    ["Length"] = 102,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Gather H",
    ["Name"] = "sound\\music\\legion\\mus_70_holywarriorsgather_h.mp3",
    ["Length"] = 138,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 8 B",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain8_b.mp3",
    ["Length"] = 52,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt1 E",
    ["Name"] = "sound\\music\\legion\\mus_70_anduinpt1_e.mp3",
    ["Length"] = 71,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Mire 3 H",
    ["Name"] = "sound\\music\\legion\\mus_70_mire3_h.mp3",
    ["Length"] = 24,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare Orch B",
    ["Name"] = "sound\\music\\legion\\mus_70_emeraldnightmareorch_b.mp3",
    ["Length"] = 62,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Mire 1 H",
    ["Name"] = "sound\\music\\legion\\mus_70_mire1_h.mp3",
    ["Length"] = 9,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Tempest H1",
    ["Name"] = "sound\\music\\legion\\mus_70_tempest_h1.mp3",
    ["Length"] = 75,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "MUS_72_Mount_Scene_DeathKnight",
    ["Name"] = "sound\\music\\legion\\mus_72_mount_scene_deathknight.mp3",
    ["Length"] = 33,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_ancienteredar_d",
    ["Name"] = "sound\\music\\legion\\mus_73_ancienteredar_d.mp3",
    ["Length"] = 91,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Sewers 2 A",
    ["Name"] = "sound\\music\\legion\\mus_70_dalaransewers2_a.mp3",
    ["Length"] = 154,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Jaina C",
    ["Name"] = "sound\\music\\legion\\mus_70_dalaranjaina_c.mp3",
    ["Length"] = 65,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Awakenings A",
    ["Name"] = "sound\\music\\legion\\mus_72_awakeningsa.mp3",
    ["Length"] = 75,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_arguscore2_c",
    ["Name"] = "sound\\music\\legion\\mus_73_arguscore2_c.mp3",
    ["Length"] = 83,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Stormheim F",
    ["Name"] = "sound\\music\\legion\\mus_70_stormheim_f.mp3",
    ["Length"] = 65,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus2pt1_b",
    ["Name"] = "sound\\music\\legion\\mus_73_argus2pt1_b.mp3",
    ["Length"] = 69,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Shackled B",
    ["Name"] = "sound\\music\\legion\\mus_72_shackledb.mp3",
    ["Length"] = 58,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Tomb of Sargeras A",
    ["Name"] = "sound\\music\\legion\\mus_72_tombofsargerasa.mp3",
    ["Length"] = 55,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Passage B",
    ["Name"] = "sound\\music\\legion\\mus_70_passage_b.mp3",
    ["Length"] = 75,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_Tempest_B_Stinger_01",
    ["Name"] = "sound\\music\\legion\\mus_70_tempest_b_stinger_01.mp3",
    ["Length"] = 17,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "Winter Holiday A",
    ["Name"] = "sound\\music\\legion\\mus_71_winterholiday_a.mp3",
    ["Length"] = 112,
    ["Artist"] = "Shelly and Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Shackled C",
    ["Name"] = "sound\\music\\legion\\mus_72_shackledc.mp3",
    ["Length"] = 27,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Passage C",
    ["Name"] = "sound\\music\\legion\\mus_70_passage_c.mp3",
    ["Length"] = 79,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Relentless A",
    ["Name"] = "sound\\music\\legion\\mus_70_relentless_a.mp3",
    ["Length"] = 7,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus2pt1_c",
    ["Name"] = "sound\\music\\legion\\mus_73_argus2pt1_c.mp3",
    ["Length"] = 69,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Stormheim G",
    ["Name"] = "sound\\music\\legion\\mus_70_stormheim_g.mp3",
    ["Length"] = 66,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_arguscore2_b",
    ["Name"] = "sound\\music\\legion\\mus_73_arguscore2_b.mp3",
    ["Length"] = 83,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Laila Demon A",
    ["Name"] = "sound\\music\\legion\\mus_70_lailademon_a.mp3",
    ["Length"] = 127,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Jaina B",
    ["Name"] = "sound\\music\\legion\\mus_70_dalaranjaina_b.mp3",
    ["Length"] = 115,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_ancienteredar_e",
    ["Name"] = "sound\\music\\legion\\mus_73_ancienteredar_e.mp3",
    ["Length"] = 87,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus1pt4_h",
    ["Name"] = "sound\\music\\legion\\mus_73_argus1pt4_h.mp3",
    ["Length"] = 102,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Rose H",
    ["Name"] = "sound\\music\\legion\\mus_70_rose_h.mp3",
    ["Length"] = 75,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 8 A",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain8_a.mp3",
    ["Length"] = 51,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Totems H",
    ["Name"] = "sound\\music\\legion\\mus_70_totems_h.mp3",
    ["Length"] = 349,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare Orch A",
    ["Name"] = "sound\\music\\legion\\mus_70_emeraldnightmareorch_a.mp3",
    ["Length"] = 70,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt1 B",
    ["Name"] = "sound\\music\\legion\\mus_70_anduinpt1_b.mp3",
    ["Length"] = 140,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 4 H",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain4_h.mp3",
    ["Length"] = 105,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_TourneyBattle06_Stinger_01",
    ["Name"] = "sound\\music\\legion\\mus_70_tourneybattle06_stinger_01.mp3",
    ["Length"] = 10,
    ["Artist"] = "David Arkenstone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Khadgar Night B",
    ["Name"] = "sound\\music\\legion\\mus_70_dalarankhadgar_night_b.mp3",
    ["Length"] = 77,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Khadgar Day C",
    ["Name"] = "sound\\music\\legion\\mus_70_dalarankhadgar_day_c.mp3",
    ["Length"] = 67,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_ancienteredar_a",
    ["Name"] = "sound\\music\\legion\\mus_73_ancienteredar_a.mp3",
    ["Length"] = 124,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Stormheim C",
    ["Name"] = "sound\\music\\legion\\mus_70_stormheim_c.mp3",
    ["Length"] = 157,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Tomb of Sargeras D",
    ["Name"] = "sound\\music\\legion\\mus_72_tombofsargerasd.mp3",
    ["Length"] = 42,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Suramar Pt2 H",
    ["Name"] = "sound\\music\\legion\\mus_70_suramar_pt2_h.mp3",
    ["Length"] = 101,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "Winter Holiday E",
    ["Name"] = "sound\\music\\legion\\mus_71_winterholiday_e.mp3",
    ["Length"] = 39,
    ["Artist"] = "Shelly and Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Halls 1 H",
    ["Name"] = "sound\\music\\legion\\mus_70_dalaranhalls1_h.mp3",
    ["Length"] = 138,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Relentless E",
    ["Name"] = "sound\\music\\legion\\mus_70_relentless_e.mp3",
    ["Length"] = 13,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Mire 5 H",
    ["Name"] = "sound\\music\\legion\\mus_70_mire5_h.mp3",
    ["Length"] = 12,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Relentless D",
    ["Name"] = "sound\\music\\legion\\mus_70_relentless_d.mp3",
    ["Length"] = 7,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "Winter Holiday D",
    ["Name"] = "sound\\music\\legion\\mus_71_winterholiday_d.mp3",
    ["Length"] = 98,
    ["Artist"] = "Shelly and Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Passage A2",
    ["Name"] = "sound\\music\\legion\\mus_70_passage_a2.mp3",
    ["Length"] = 110,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Tomb of Sargeras E",
    ["Name"] = "sound\\music\\legion\\mus_72_tombofsargerase.mp3",
    ["Length"] = 68,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Shackled F",
    ["Name"] = "sound\\music\\legion\\mus_72_shackledf.mp3",
    ["Length"] = 125,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Fel Titan H",
    ["Name"] = "sound\\music\\legion\\mus_72_feltitanh.mp3",
    ["Length"] = 111,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 10 B",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain10_b.mp3",
    ["Length"] = 111,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Moon Rising H",
    ["Name"] = "sound\\music\\legion\\mus_70_moonrising_h.mp3",
    ["Length"] = 157,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt2 B 2",
    ["Name"] = "sound\\music\\legion\\mus_70_demonhunterpt2_b2.mp3",
    ["Length"] = 77,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt3 H",
    ["Name"] = "sound\\music\\legion\\mus_70_demonhunterpt3_h.mp3",
    ["Length"] = 130,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Khadgar Day B",
    ["Name"] = "sound\\music\\legion\\mus_70_dalarankhadgar_day_b.mp3",
    ["Length"] = 50,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Khadgar Night C",
    ["Name"] = "sound\\music\\legion\\mus_70_dalarankhadgar_night_c.mp3",
    ["Length"] = 67,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Menace of the Dark Titans H1",
    ["Name"] = "sound\\music\\legion\\mus_70_menaceofthedarktitans_h1.mp3",
    ["Length"] = 85,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt1 C",
    ["Name"] = "sound\\music\\legion\\mus_70_anduinpt1_c.mp3",
    ["Length"] = 137,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "R2Kara 8H",
    ["Name"] = "sound\\music\\legion\\mus_71_karazhan_8h.mp3",
    ["Length"] = 70,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt1 A1",
    ["Name"] = "sound\\music\\legion\\mus_70_anduinpt1_a1.mp3",
    ["Length"] = 75,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Sanctum of Karazhan H2",
    ["Name"] = "sound\\music\\legion\\mus_70_sanctumofkarazhan_h2.mp3",
    ["Length"] = 119,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt1 H",
    ["Name"] = "sound\\music\\legion\\mus_70_demonhunterpt1_h.mp3",
    ["Length"] = 128,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_LastStand_H1_Stinger_01",
    ["Name"] = "sound\\music\\legion\\mus_70_laststand_h1_stinger_01.mp3",
    ["Length"] = 10,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Weep Bass Flute",
    ["Name"] = "sound\\music\\legion\\mus_70_weep_flute.mp3",
    ["Length"] = 110,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Khadgar Night A",
    ["Name"] = "sound\\music\\legion\\mus_70_dalarankhadgar_night_a.mp3",
    ["Length"] = 73,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_ancienteredar_b",
    ["Name"] = "sound\\music\\legion\\mus_73_ancienteredar_b.mp3",
    ["Length"] = 87,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "Winter Holiday F",
    ["Name"] = "sound\\music\\legion\\mus_71_winterholiday_f.mp3",
    ["Length"] = 44,
    ["Artist"] = "Shelly and Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Shackled D",
    ["Name"] = "sound\\music\\legion\\mus_72_shackledd.mp3",
    ["Length"] = 73,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Passage D",
    ["Name"] = "sound\\music\\legion\\mus_70_passage_d.mp3",
    ["Length"] = 184,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Relentless F",
    ["Name"] = "sound\\music\\legion\\mus_70_relentless_f.mp3",
    ["Length"] = 10,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Relentless G",
    ["Name"] = "sound\\music\\legion\\mus_70_relentless_g.mp3",
    ["Length"] = 51,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Shackled E",
    ["Name"] = "sound\\music\\legion\\mus_72_shacklede.mp3",
    ["Length"] = 78,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Passage A1",
    ["Name"] = "sound\\music\\legion\\mus_70_passage_a1.mp3",
    ["Length"] = 77,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Tomb of Sargeras F",
    ["Name"] = "sound\\music\\legion\\mus_72_tombofsargerasf.mp3",
    ["Length"] = 61,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "Winter Holiday G",
    ["Name"] = "sound\\music\\legion\\mus_71_winterholiday_g.mp3",
    ["Length"] = 63,
    ["Artist"] = "Shelly and Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Stormheim A",
    ["Name"] = "sound\\music\\legion\\mus_70_stormheim_a.mp3",
    ["Length"] = 88,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare Syn A",
    ["Name"] = "sound\\music\\legion\\mus_70_emeraldnightmaresyn_a.mp3",
    ["Length"] = 112,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 10 A",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain10_a.mp3",
    ["Length"] = 111,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_arguscore2_d",
    ["Name"] = "sound\\music\\legion\\mus_73_arguscore2_d.mp3",
    ["Length"] = 84,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_ancienteredar_c",
    ["Name"] = "sound\\music\\legion\\mus_73_ancienteredar_c.mp3",
    ["Length"] = 89,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 6 H",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain6_h.mp3",
    ["Length"] = 81,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt2 B 1",
    ["Name"] = "sound\\music\\legion\\mus_70_demonhunterpt2_b1.mp3",
    ["Length"] = 83,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Khadgar Day A",
    ["Name"] = "sound\\music\\legion\\mus_70_dalarankhadgar_day_a.mp3",
    ["Length"] = 68,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus1pt2_h",
    ["Name"] = "sound\\music\\legion\\mus_73_argus1pt2_h.mp3",
    ["Length"] = 86,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Winds Out of the East H",
    ["Name"] = "sound\\music\\legion\\mus_70_windsoutoftheeast_h.mp3",
    ["Length"] = 90,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "R2Kara 4H",
    ["Name"] = "sound\\music\\legion\\mus_71_karazhan_4h.mp3",
    ["Length"] = 101,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Menace of the Dark Titans H2",
    ["Name"] = "sound\\music\\legion\\mus_70_menaceofthedarktitans_h2.mp3",
    ["Length"] = 66,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Sanctum of Karazhan H1",
    ["Name"] = "sound\\music\\legion\\mus_70_sanctumofkarazhan_h1.mp3",
    ["Length"] = 103,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Glimmer A",
    ["Name"] = "sound\\music\\legion\\mus_70_glimmer_a.mp3",
    ["Length"] = 46,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt1 A2",
    ["Name"] = "sound\\music\\legion\\mus_70_anduinpt1_a2.mp3",
    ["Length"] = 113,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Oath F",
    ["Name"] = "sound\\music\\legion\\mus_70_holywarriorsoath_f.mp3",
    ["Length"] = 74,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Sewers 1 C",
    ["Name"] = "sound\\music\\legion\\mus_70_dalaransewers1_c.mp3",
    ["Length"] = 70,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_arguscore1_a",
    ["Name"] = "sound\\music\\legion\\mus_73_arguscore1_a.mp3",
    ["Length"] = 87,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities E",
    ["Name"] = "sound\\music\\legion\\mus_70_requiemforthelostcities_e.mp3",
    ["Length"] = 96,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Fel Glade A",
    ["Name"] = "sound\\music\\legion\\mus_70_felglade_a.mp3",
    ["Length"] = 40,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare C",
    ["Name"] = "sound\\music\\legion\\mus_70_emeraldnightmare_c.mp3",
    ["Length"] = 130,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Enchanted Night Elves C",
    ["Name"] = "sound\\music\\legion\\mus_70_enchantednightelves_c.mp3",
    ["Length"] = 101,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Order Hall Devotions F",
    ["Name"] = "sound\\music\\legion\\mus_70_orderhalldevotions_f.mp3",
    ["Length"] = 127,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Dusk B",
    ["Name"] = "sound\\music\\legion\\mus_70_dalarandusk_b.mp3",
    ["Length"] = 95,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Canticle of Sacrifice B",
    ["Name"] = "sound\\music\\legion\\mus_70_canticleofsacrifice_b.mp3",
    ["Length"] = 250,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_LastStand_H3_Stinger_01",
    ["Name"] = "sound\\music\\legion\\mus_70_laststand_h3_stinger_01.mp3",
    ["Length"] = 12,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_Highmountain10_Stinger_01",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain10_stinger_01.mp3",
    ["Length"] = 13,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Canticle of Sacrifice C",
    ["Name"] = "sound\\music\\legion\\mus_70_canticleofsacrifice_c.mp3",
    ["Length"] = 177,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 9 A",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain9_a.mp3",
    ["Length"] = 38,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Dusk C",
    ["Name"] = "sound\\music\\legion\\mus_70_dalarandusk_c.mp3",
    ["Length"] = 97,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Place of Rest H1",
    ["Name"] = "sound\\music\\legion\\mus_72_placeofresth1.mp3",
    ["Length"] = 71,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 1 H",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain1_h.mp3",
    ["Length"] = 92,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus2pt2_a",
    ["Name"] = "sound\\music\\legion\\mus_73_argus2pt2_a.mp3",
    ["Length"] = 121,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Enchanted Night Elves B",
    ["Name"] = "sound\\music\\legion\\mus_70_enchantednightelves_b.mp3",
    ["Length"] = 100,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_BalloonRide_Stinger_01",
    ["Name"] = "sound\\music\\legion\\mus_70_balloonride_stinger_01.mp3",
    ["Length"] = 12,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Place of Rest A",
    ["Name"] = "sound\\music\\legion\\mus_72_placeofresta.mp3",
    ["Length"] = 71,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities D",
    ["Name"] = "sound\\music\\legion\\mus_70_requiemforthelostcities_d.mp3",
    ["Length"] = 66,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Sewers 1 B",
    ["Name"] = "sound\\music\\legion\\mus_70_dalaransewers1_b.mp3",
    ["Length"] = 95,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Oath G",
    ["Name"] = "sound\\music\\legion\\mus_70_holywarriorsoath_g.mp3",
    ["Length"] = 102,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Oath E",
    ["Name"] = "sound\\music\\legion\\mus_70_holywarriorsoath_e.mp3",
    ["Length"] = 132,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 3 H",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain3_h.mp3",
    ["Length"] = 66,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "R2Kara 3H",
    ["Name"] = "sound\\music\\legion\\mus_71_karazhan_3h.mp3",
    ["Length"] = 61,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_arguscore1_b",
    ["Name"] = "sound\\music\\legion\\mus_73_arguscore1_b.mp3",
    ["Length"] = 87,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities F",
    ["Name"] = "sound\\music\\legion\\mus_70_requiemforthelostcities_f.mp3",
    ["Length"] = 96,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Fel Glade B",
    ["Name"] = "sound\\music\\legion\\mus_70_felglade_b.mp3",
    ["Length"] = 82,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus2pt2_c",
    ["Name"] = "sound\\music\\legion\\mus_73_argus2pt2_c.mp3",
    ["Length"] = 122,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Place of Rest H3",
    ["Name"] = "sound\\music\\legion\\mus_72_placeofresth3.mp3",
    ["Length"] = 72,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Order Hall Devotions E",
    ["Name"] = "sound\\music\\legion\\mus_70_orderhalldevotions_e.mp3",
    ["Length"] = 67,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Dusk A",
    ["Name"] = "sound\\music\\legion\\mus_70_dalarandusk_a.mp3",
    ["Length"] = 98,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Canticle of Sacrifice A",
    ["Name"] = "sound\\music\\legion\\mus_70_canticleofsacrifice_a.mp3",
    ["Length"] = 248,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Mire 2 H",
    ["Name"] = "sound\\music\\legion\\mus_70_mire2_h.mp3",
    ["Length"] = 15,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Ley Lines H",
    ["Name"] = "sound\\music\\legion\\mus_70_leylines_h.mp3",
    ["Length"] = 93,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Order Hall Devotions D",
    ["Name"] = "sound\\music\\legion\\mus_70_orderhalldevotions_d.mp3",
    ["Length"] = 128,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Place of Rest H2",
    ["Name"] = "sound\\music\\legion\\mus_72_placeofresth2.mp3",
    ["Length"] = 72,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Enchanted Night Elves A",
    ["Name"] = "sound\\music\\legion\\mus_70_enchantednightelves_a.mp3",
    ["Length"] = 100,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus2pt2_b",
    ["Name"] = "sound\\music\\legion\\mus_73_argus2pt2_b.mp3",
    ["Length"] = 123,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Fel Glade C",
    ["Name"] = "sound\\music\\legion\\mus_70_felglade_c.mp3",
    ["Length"] = 100,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities G",
    ["Name"] = "sound\\music\\legion\\mus_70_requiemforthelostcities_g.mp3",
    ["Length"] = 82,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Place of Rest B",
    ["Name"] = "sound\\music\\legion\\mus_72_placeofrestb.mp3",
    ["Length"] = 64,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_arguscore1_c",
    ["Name"] = "sound\\music\\legion\\mus_73_arguscore1_c.mp3",
    ["Length"] = 86,
    ["Artist"] = "Clint Bajakian",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Sewers 1 A",
    ["Name"] = "sound\\music\\legion\\mus_70_dalaransewers1_a.mp3",
    ["Length"] = 131,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Oath D",
    ["Name"] = "sound\\music\\legion\\mus_70_holywarriorsoath_d.mp3",
    ["Length"] = 132,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "As Soon As'Pret B",
    ["Name"] = "sound\\music\\legion\\mus_70_assoonaspret_b.mp3",
    ["Length"] = 81,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Menace of the Dark Titans C",
    ["Name"] = "sound\\music\\legion\\mus_70_menaceofthedarktitans_c.mp3",
    ["Length"] = 118,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare E",
    ["Name"] = "sound\\music\\legion\\mus_70_emeraldnightmare_e.mp3",
    ["Length"] = 34,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities C",
    ["Name"] = "sound\\music\\legion\\mus_70_requiemforthelostcities_c.mp3",
    ["Length"] = 103,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Dawn A",
    ["Name"] = "sound\\music\\legion\\mus_70_dalarandawn_a.mp3",
    ["Length"] = 95,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Canticle of Sacrifice D",
    ["Name"] = "sound\\music\\legion\\mus_70_canticleofsacrifice_d.mp3",
    ["Length"] = 185,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "Eternal Holly Brew B",
    ["Name"] = "sound\\music\\legion\\mus_71_eternalhollybrew_b.mp3",
    ["Length"] = 203,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt2 C",
    ["Name"] = "sound\\music\\legion\\mus_70_anduinpt2_c.mp3",
    ["Length"] = 54,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "We Are Not Alone H",
    ["Name"] = "sound\\music\\legion\\mus_70_wearenotalone_h.mp3",
    ["Length"] = 106,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Sacred Stone B",
    ["Name"] = "sound\\music\\legion\\mus_70_sacredstone_b.mp3",
    ["Length"] = 113,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_ClientScene_70_IF2_01",
    ["Name"] = "sound\\music\\legion\\mus_70_clientscene_70_if2_01.mp3",
    ["Length"] = 73,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Nos'Sharah H",
    ["Name"] = "sound\\music\\legion\\mus_70_nossharah_h.mp3",
    ["Length"] = 127,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 7 H",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain7_h.mp3",
    ["Length"] = 43,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt2 B",
    ["Name"] = "sound\\music\\legion\\mus_70_anduinpt2_b.mp3",
    ["Length"] = 111,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Order Hall Devotions A",
    ["Name"] = "sound\\music\\legion\\mus_70_orderhalldevotions_a.mp3",
    ["Length"] = 114,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Preserver H2",
    ["Name"] = "sound\\music\\legion\\mus_70_preserver_h2.mp3",
    ["Length"] = 97,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus1pt3_h",
    ["Name"] = "sound\\music\\legion\\mus_73_argus1pt3_h.mp3",
    ["Length"] = 68,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Canticle of Sacrifice E",
    ["Name"] = "sound\\music\\legion\\mus_70_canticleofsacrifice_e.mp3",
    ["Length"] = 13,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Weep WW",
    ["Name"] = "sound\\music\\legion\\mus_70_weep_ww.mp3",
    ["Length"] = 111,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Suramar Pt1 H",
    ["Name"] = "sound\\music\\legion\\mus_70_suramar_pt1_h.mp3",
    ["Length"] = 70,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Halls 2 H",
    ["Name"] = "sound\\music\\legion\\mus_70_dalaranhalls2_h.mp3",
    ["Length"] = 111,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities B",
    ["Name"] = "sound\\music\\legion\\mus_70_requiemforthelostcities_b.mp3",
    ["Length"] = 49,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare D",
    ["Name"] = "sound\\music\\legion\\mus_70_emeraldnightmare_d.mp3",
    ["Length"] = 119,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "R2Kara 2H",
    ["Name"] = "sound\\music\\legion\\mus_71_karazhan_2h.mp3",
    ["Length"] = 94,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Oath A",
    ["Name"] = "sound\\music\\legion\\mus_70_holywarriorsoath_a.mp3",
    ["Length"] = 75,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Menace of the Dark Titans B",
    ["Name"] = "sound\\music\\legion\\mus_70_menaceofthedarktitans_b.mp3",
    ["Length"] = 115,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Weep Viola",
    ["Name"] = "sound\\music\\legion\\mus_70_weep_viola.mp3",
    ["Length"] = 110,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "As Soon As'Pret A",
    ["Name"] = "sound\\music\\legion\\mus_70_assoonaspret_a.mp3",
    ["Length"] = 89,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Oath C",
    ["Name"] = "sound\\music\\legion\\mus_70_holywarriorsoath_c.mp3",
    ["Length"] = 130,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare F",
    ["Name"] = "sound\\music\\legion\\mus_70_emeraldnightmare_f.mp3",
    ["Length"] = 34,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Dawn B",
    ["Name"] = "sound\\music\\legion\\mus_70_dalarandawn_b.mp3",
    ["Length"] = 92,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7.1",
    ["Song"] = "Eternal Holly Brew A",
    ["Name"] = "sound\\music\\legion\\mus_71_eternalhollybrew_a.mp3",
    ["Length"] = 161,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Order Hall Devotions C",
    ["Name"] = "sound\\music\\legion\\mus_70_orderhalldevotions_c.mp3",
    ["Length"] = 119,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Ruined Cathedral H",
    ["Name"] = "sound\\music\\legion\\mus_72_ruinedcathedralh.mp3",
    ["Length"] = 80,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus1pt1_h",
    ["Name"] = "sound\\music\\legion\\mus_73_argus1pt1_h.mp3",
    ["Length"] = 102,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "MUS_72_Mount_Scene_Monk",
    ["Name"] = "sound\\music\\legion\\mus_72_mount_scene_monk.mp3",
    ["Length"] = 29,
    ["Artist"] = "Sam Cardon, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 5 H",
    ["Name"] = "sound\\music\\legion\\mus_70_highmountain5_h.mp3",
    ["Length"] = 63,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Sacred Stone A",
    ["Name"] = "sound\\music\\legion\\mus_70_sacredstone_a.mp3",
    ["Length"] = 120,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt2 H",
    ["Name"] = "sound\\music\\legion\\mus_70_demonhunterpt2_h.mp3",
    ["Length"] = 123,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_balefulnight_a",
    ["Name"] = "sound\\music\\legion\\mus_73_balefulnight_a.mp3",
    ["Length"] = 87,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Preserver H1",
    ["Name"] = "sound\\music\\legion\\mus_70_preserver_h1.mp3",
    ["Length"] = 91,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Order Hall Devotions B",
    ["Name"] = "sound\\music\\legion\\mus_70_orderhalldevotions_b.mp3",
    ["Length"] = 128,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Canticle of Sacrifice F",
    ["Name"] = "sound\\music\\legion\\mus_70_canticleofsacrifice_f.mp3",
    ["Length"] = 54,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW7.3",
    ["Song"] = "mus_73_argus2pt2_d",
    ["Name"] = "sound\\music\\legion\\mus_73_argus2pt2_d.mp3",
    ["Length"] = 174,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities A",
    ["Name"] = "sound\\music\\legion\\mus_70_requiemforthelostcities_a.mp3",
    ["Length"] = 55,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare G",
    ["Name"] = "sound\\music\\legion\\mus_70_emeraldnightmare_g.mp3",
    ["Length"] = 114,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 7.2",
    ["Song"] = "Kil'Jaeden H",
    ["Name"] = "sound\\music\\legion\\mus_72_kiljaedenh.mp3",
    ["Length"] = 95,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Mire 4 H",
    ["Name"] = "sound\\music\\legion\\mus_70_mire4_h.mp3",
    ["Length"] = 10,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Menace of the Dark Titans A",
    ["Name"] = "sound\\music\\legion\\mus_70_menaceofthedarktitans_a.mp3",
    ["Length"] = 123,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Oath B",
    ["Name"] = "sound\\music\\legion\\mus_70_holywarriorsoath_b.mp3",
    ["Length"] = 110,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
}
local EpicMusicPlayer = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer")if not EpicMusicPlayer then return end
EpicMusicPlayer:AddPlayList("Legion", playlist1, false, true)
