--Created by PlaylistCreator.vbs version 4.0 (https://github.com/Kiatra/EpicMusicPlayer_MP3)
local EpicMusicPlayer = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer")
if not EpicMusicPlayer then return end

local playlist1 = {
	["listName"] = "The War Within",
	["playlistVersion"] = "4.0",
	["locked"] =  "true",
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "The War Within Main Title",
		["Name"] = "sound\\music\\warwithin\\mus_110_thewarwithin_maintitle.mp3",
		["Length"] = 976,
		["Artist"] = "Main Title",
		["WoW"] =  "true",
		["Id"] =  "6075186",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "The War Within Main Title Beta",
		["Name"] = "sound\\music\\warwithin\\mus_110_thewarwithin_maintitle_beta.mp3",
		["Length"] = 155,
		["Artist"] = "Main Title",
		["WoW"] =  "true",
		["Id"] =  "6024173",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Alleria",
		["Name"] = "sound\\music\\warwithin\\mus_110_alleria_a.mp3",
		["Length"] = 77,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042833",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Alleria",
		["Name"] = "sound\\music\\warwithin\\mus_110_alleria_b.mp3",
		["Length"] = 102,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042831",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Alleria",
		["Name"] = "sound\\music\\warwithin\\mus_110_alleria_h.mp3",
		["Length"] = 262,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6034298",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Ancient Falls",
		["Name"] = "sound\\music\\warwithin\\mus_110_ancient_falls_a.mp3",
		["Length"] = 66,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6034300",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Ancient Falls",
		["Name"] = "sound\\music\\warwithin\\mus_110_ancient_falls_b.mp3",
		["Length"] = 125,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6034302",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Ancient Falls",
		["Name"] = "sound\\music\\warwithin\\mus_110_ancient_falls_c.mp3",
		["Length"] = 92,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6034304",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Ancient Falls",
		["Name"] = "sound\\music\\warwithin\\mus_110_ancient_falls_d.mp3",
		["Length"] = 128,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6034306",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Ancient Falls",
		["Name"] = "sound\\music\\warwithin\\mus_110_ancient_falls_h.mp3",
		["Length"] = 126,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6034308",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arachnophob",
		["Name"] = "sound\\music\\warwithin\\mus_110_arachnophobia_a.mp3",
		["Length"] = 94,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6068142",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arachnophob",
		["Name"] = "sound\\music\\warwithin\\mus_110_arachnophobia_b.mp3",
		["Length"] = 107,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6068150",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arachnophob",
		["Name"] = "sound\\music\\warwithin\\mus_110_arachnophobia_c.mp3",
		["Length"] = 82,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6068154",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arachnophob",
		["Name"] = "sound\\music\\warwithin\\mus_110_arachnophobia_d.mp3",
		["Length"] = 83,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6068156",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arachnophob",
		["Name"] = "sound\\music\\warwithin\\mus_110_arachnophobia_e.mp3",
		["Length"] = 103,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6068158",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arachnophob",
		["Name"] = "sound\\music\\warwithin\\mus_110_arachnophobia_h.mp3",
		["Length"] = 103,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6068160",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arathi_airshi",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_airships_a.mp3",
		["Length"] = 199,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074915",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arathi_airshi",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_airships_b.mp3",
		["Length"] = 142,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074917",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arathi_airshi",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_airships_c.mp3",
		["Length"] = 108,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074919",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arathi_airshi",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_airships_d.mp3",
		["Length"] = 107,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074921",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Arathi Airships",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_airships_h.mp3",
		["Length"] = 178,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6034310",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Arathi Combat Dark",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_combat_dark_a.mp3",
		["Length"] = 85,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042835",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Arathi Combat Dark",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_combat_dark_b.mp3",
		["Length"] = 129,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042837",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Arathi Combat Dark",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_combat_dark_c.mp3",
		["Length"] = 62,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042839",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Arathi Combat Dark",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_combat_dark_d.mp3",
		["Length"] = 138,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042841",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Arathi Combat Dark",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_combat_dark_e.mp3",
		["Length"] = 92,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042843",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Arathi Combat Dark",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_combat_dark_f.mp3",
		["Length"] = 137,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042845",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Arathi Combat Dark",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_combat_dark_g.mp3",
		["Length"] = 86,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6055465",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Arathi Combat Dark",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_combat_dark_h.mp3",
		["Length"] = 154,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6037072",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Arathi Combat Dark",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_combat_dark_i.mp3",
		["Length"] = 137,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6055467",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Arathi Combat Dark",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_combat_dark_j.mp3",
		["Length"] = 136,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6055469",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arathi_combat_lig",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_combat_light_a.mp3",
		["Length"] = 107,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6067037",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arathi_combat_lig",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_combat_light_b.mp3",
		["Length"] = 136,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6067040",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arathi_combat_lig",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_combat_light_c.mp3",
		["Length"] = 111,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6067042",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arathi_combat_lig",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_combat_light_d.mp3",
		["Length"] = 130,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6067044",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arathi_combat_lig",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_combat_light_e.mp3",
		["Length"] = 136,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6067046",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arathi_combat_lig",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_combat_light_f.mp3",
		["Length"] = 105,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6067048",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arathi_combat_lig",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_combat_light_g.mp3",
		["Length"] = 107,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6067050",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Arathi Combat Light",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_combat_light_h.mp3",
		["Length"] = 125,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042847",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arathi_memori",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_memorial_a.mp3",
		["Length"] = 158,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6065431",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arathi_memori",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_memorial_b.mp3",
		["Length"] = 263,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6065433",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arathi_memori",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_memorial_c.mp3",
		["Length"] = 179,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6065435",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arathi_memori",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_memorial_d.mp3",
		["Length"] = 129,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6065437",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arathi_memori",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_memorial_e.mp3",
		["Length"] = 131,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6065439",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arathi_memori",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_memorial_f.mp3",
		["Length"] = 96,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6065441",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_arathi_memori",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_memorial_g.mp3",
		["Length"] = 94,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6065443",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Arathi Memorial",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathi_memorial_h.mp3",
		["Length"] = 279,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055471",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Arathor General",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathor_general_a.mp3",
		["Length"] = 131,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6034312",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Arathor General",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathor_general_b.mp3",
		["Length"] = 111,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6034314",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Arathor General",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathor_general_c.mp3",
		["Length"] = 112,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6034316",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Arathor General",
		["Name"] = "sound\\music\\warwithin\\mus_110_arathor_general_h.mp3",
		["Length"] = 112,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6034318",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Boulder Springs",
		["Name"] = "sound\\music\\warwithin\\mus_110_boulder_springs_a.mp3",
		["Length"] = 113,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042849",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Boulder Springs",
		["Name"] = "sound\\music\\warwithin\\mus_110_boulder_springs_b.mp3",
		["Length"] = 79,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042851",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Boulder Springs",
		["Name"] = "sound\\music\\warwithin\\mus_110_boulder_springs_c.mp3",
		["Length"] = 123,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042853",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Boulder Springs",
		["Name"] = "sound\\music\\warwithin\\mus_110_boulder_springs_d.mp3",
		["Length"] = 108,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042855",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Boulder Springs",
		["Name"] = "sound\\music\\warwithin\\mus_110_boulder_springs_e.mp3",
		["Length"] = 141,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042857",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Boulder Springs",
		["Name"] = "sound\\music\\warwithin\\mus_110_boulder_springs_f.mp3",
		["Length"] = 90,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042859",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Boulder Springs",
		["Name"] = "sound\\music\\warwithin\\mus_110_boulder_springs_g.mp3",
		["Length"] = 93,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042861",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Boulder Springs",
		["Name"] = "sound\\music\\warwithin\\mus_110_boulder_springs_h.mp3",
		["Length"] = 192,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6037075",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Boulder Springs",
		["Name"] = "sound\\music\\warwithin\\mus_110_boulder_springs_i.mp3",
		["Length"] = 76,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042863",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_chittering_d",
		["Name"] = "sound\\music\\warwithin\\mus_110_chittering_den_a.mp3",
		["Length"] = 108,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6034320",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_chittering_d",
		["Name"] = "sound\\music\\warwithin\\mus_110_chittering_den_b.mp3",
		["Length"] = 92,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6065445",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Chittering Den",
		["Name"] = "sound\\music\\warwithin\\mus_110_chittering_den_c.mp3",
		["Length"] = 71,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6076456",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Chittering Den",
		["Name"] = "sound\\music\\warwithin\\mus_110_chittering_den_h.mp3",
		["Length"] = 116,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6034322",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_cinderbrew_meade",
		["Name"] = "sound\\music\\warwithin\\mus_110_cinderbrew_meadery_a.mp3",
		["Length"] = 127,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074923",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_cinderbrew_meade",
		["Name"] = "sound\\music\\warwithin\\mus_110_cinderbrew_meadery_b.mp3",
		["Length"] = 127,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074925",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_cinderbrew_meade",
		["Name"] = "sound\\music\\warwithin\\mus_110_cinderbrew_meadery_c.mp3",
		["Length"] = 117,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074927",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_cinderbrew_meade",
		["Name"] = "sound\\music\\warwithin\\mus_110_cinderbrew_meadery_d.mp3",
		["Length"] = 107,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074929",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_cinderbrew_meade",
		["Name"] = "sound\\music\\warwithin\\mus_110_cinderbrew_meadery_e.mp3",
		["Length"] = 127,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074931",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_cinderbrew_meade",
		["Name"] = "sound\\music\\warwithin\\mus_110_cinderbrew_meadery_h.mp3",
		["Length"] = 126,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6065447",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Cinderwold",
		["Name"] = "sound\\music\\warwithin\\mus_110_cinderwold_a.mp3",
		["Length"] = 207,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055473",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Cinderwold",
		["Name"] = "sound\\music\\warwithin\\mus_110_cinderwold_b.mp3",
		["Length"] = 121,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055475",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Cinderwold",
		["Name"] = "sound\\music\\warwithin\\mus_110_cinderwold_c.mp3",
		["Length"] = 155,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055477",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Cinderwold",
		["Name"] = "sound\\music\\warwithin\\mus_110_cinderwold_d.mp3",
		["Length"] = 123,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055479",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Cinderwold",
		["Name"] = "sound\\music\\warwithin\\mus_110_cinderwold_e.mp3",
		["Length"] = 125,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055481",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Cinderwold",
		["Name"] = "sound\\music\\warwithin\\mus_110_cinderwold_f.mp3",
		["Length"] = 128,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055483",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Cinderwold",
		["Name"] = "sound\\music\\warwithin\\mus_110_cinderwold_h.mp3",
		["Length"] = 236,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6050206",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "City Of Threads",
		["Name"] = "sound\\music\\warwithin\\mus_110_city_of_threads_a.mp3",
		["Length"] = 194,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6046734",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "City Of Threads",
		["Name"] = "sound\\music\\warwithin\\mus_110_city_of_threads_b.mp3",
		["Length"] = 143,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055485",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "City Of Threads",
		["Name"] = "sound\\music\\warwithin\\mus_110_city_of_threads_c.mp3",
		["Length"] = 88,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055487",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "City Of Threads",
		["Name"] = "sound\\music\\warwithin\\mus_110_city_of_threads_d.mp3",
		["Length"] = 88,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055489",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "City Of Threads",
		["Name"] = "sound\\music\\warwithin\\mus_110_city_of_threads_e.mp3",
		["Length"] = 118,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055491",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "City Of Threads",
		["Name"] = "sound\\music\\warwithin\\mus_110_city_of_threads_f.mp3",
		["Length"] = 109,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055493",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "City Of Threads",
		["Name"] = "sound\\music\\warwithin\\mus_110_city_of_threads_g.mp3",
		["Length"] = 120,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055495",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "City Of Threads",
		["Name"] = "sound\\music\\warwithin\\mus_110_city_of_threads_h.mp3",
		["Length"] = 225,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6075162",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "City Of Threads",
		["Name"] = "sound\\music\\warwithin\\mus_110_city_of_threads_i.mp3",
		["Length"] = 131,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055497",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_city_of_threa",
		["Name"] = "sound\\music\\warwithin\\mus_110_city_of_threads_j.mp3",
		["Length"] = 125,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6065453",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Crawling Chasm",
		["Name"] = "sound\\music\\warwithin\\mus_110_crawling_chasm_a.mp3",
		["Length"] = 145,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055499",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Crawling Chasm",
		["Name"] = "sound\\music\\warwithin\\mus_110_crawling_chasm_b.mp3",
		["Length"] = 134,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055501",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Crawling Chasm",
		["Name"] = "sound\\music\\warwithin\\mus_110_crawling_chasm_c.mp3",
		["Length"] = 111,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055503",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Crawling Chasm",
		["Name"] = "sound\\music\\warwithin\\mus_110_crawling_chasm_d.mp3",
		["Length"] = 150,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055505",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Crawling Chasm",
		["Name"] = "sound\\music\\warwithin\\mus_110_crawling_chasm_e.mp3",
		["Length"] = 151,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055507",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Crawling Chasm",
		["Name"] = "sound\\music\\warwithin\\mus_110_crawling_chasm_f.mp3",
		["Length"] = 187,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055509",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Crawling Chasm",
		["Name"] = "sound\\music\\warwithin\\mus_110_crawling_chasm_h.mp3",
		["Length"] = 242,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055513",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Crawling Chasm",
		["Name"] = "sound\\music\\warwithin\\mus_110_crawling_chasm_h1.mp3",
		["Length"] = 147,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055524",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Crawling Chasm",
		["Name"] = "sound\\music\\warwithin\\mus_110_crawling_chasm_h2.mp3",
		["Length"] = 94,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055511",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Dark Crystal",
		["Name"] = "sound\\music\\warwithin\\mus_110_dark_crystal_a.mp3",
		["Length"] = 132,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065627",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Dark Crystal",
		["Name"] = "sound\\music\\warwithin\\mus_110_dark_crystal_b.mp3",
		["Length"] = 147,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065629",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Dark Crystal",
		["Name"] = "sound\\music\\warwithin\\mus_110_dark_crystal_c.mp3",
		["Length"] = 138,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065631",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Dark Crystal",
		["Name"] = "sound\\music\\warwithin\\mus_110_dark_crystal_d.mp3",
		["Length"] = 152,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065633",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Dark Crystal",
		["Name"] = "sound\\music\\warwithin\\mus_110_dark_crystal_h.mp3",
		["Length"] = 239,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065635",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_dark_crystal_sti",
		["Name"] = "sound\\music\\warwithin\\mus_110_dark_crystal_stinger.mp3",
		["Length"] = 18,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6074939",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Dornogal",
		["Name"] = "sound\\music\\warwithin\\mus_110_dornogal_a.mp3",
		["Length"] = 96,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065645",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Dornogal",
		["Name"] = "sound\\music\\warwithin\\mus_110_dornogal_b.mp3",
		["Length"] = 134,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065647",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Dornogal",
		["Name"] = "sound\\music\\warwithin\\mus_110_dornogal_c.mp3",
		["Length"] = 113,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065649",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Dornogal",
		["Name"] = "sound\\music\\warwithin\\mus_110_dornogal_d.mp3",
		["Length"] = 134,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065651",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Dornogal",
		["Name"] = "sound\\music\\warwithin\\mus_110_dornogal_e.mp3",
		["Length"] = 114,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065653",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Dornogal",
		["Name"] = "sound\\music\\warwithin\\mus_110_dornogal_f.mp3",
		["Length"] = 132,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065655",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Dornogal",
		["Name"] = "sound\\music\\warwithin\\mus_110_dornogal_g.mp3",
		["Length"] = 86,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065657",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_dornog",
		["Name"] = "sound\\music\\warwithin\\mus_110_dornogal_h.mp3",
		["Length"] = 174,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6068108",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Dornogal",
		["Name"] = "sound\\music\\warwithin\\mus_110_dornogal_i.mp3",
		["Length"] = 20,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065659",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Dorn Country",
		["Name"] = "sound\\music\\warwithin\\mus_110_dorn_country_a.mp3",
		["Length"] = 92,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065637",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Dorn Country",
		["Name"] = "sound\\music\\warwithin\\mus_110_dorn_country_b.mp3",
		["Length"] = 92,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065639",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Dorn Country",
		["Name"] = "sound\\music\\warwithin\\mus_110_dorn_country_c.mp3",
		["Length"] = 103,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065641",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Dorn Country",
		["Name"] = "sound\\music\\warwithin\\mus_110_dorn_country_d.mp3",
		["Length"] = 99,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065643",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_dorn_count",
		["Name"] = "sound\\music\\warwithin\\mus_110_dorn_country_h.mp3",
		["Length"] = 121,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6068106",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_combat_a.mp3",
		["Length"] = 127,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065663",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_combat_b.mp3",
		["Length"] = 116,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065665",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_combat_c.mp3",
		["Length"] = 111,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065667",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_combat_d.mp3",
		["Length"] = 114,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065669",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_combat_e.mp3",
		["Length"] = 111,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065671",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_combat_f.mp3",
		["Length"] = 23,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065673",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_combat_g.mp3",
		["Length"] = 111,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065675",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_combat_h.mp3",
		["Length"] = 252,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065661",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_combat_i.mp3",
		["Length"] = 120,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065677",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_combat_j.mp3",
		["Length"] = 121,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065679",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_combat_k.mp3",
		["Length"] = 112,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065681",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_combat_l.mp3",
		["Length"] = 132,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065683",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Countryside",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_countryside_a.mp3",
		["Length"] = 169,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6034324",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_earthen_countrysi",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_countryside_b.mp3",
		["Length"] = 117,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074941",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_earthen_countrysi",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_countryside_c.mp3",
		["Length"] = 181,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074943",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Countryside",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_countryside_h.mp3",
		["Length"] = 253,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6034326",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Factory",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_factory_a.mp3",
		["Length"] = 86,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065685",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Factory",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_factory_b.mp3",
		["Length"] = 91,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065687",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Factory",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_factory_c.mp3",
		["Length"] = 125,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065689",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Factory",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_factory_d.mp3",
		["Length"] = 118,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065691",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Factory",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_factory_e.mp3",
		["Length"] = 147,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065693",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Factory",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_factory_h.mp3",
		["Length"] = 156,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065695",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Memorial",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_memorial_a.mp3",
		["Length"] = 120,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065697",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Memorial",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_memorial_b.mp3",
		["Length"] = 118,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065699",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Memorial",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_memorial_c.mp3",
		["Length"] = 107,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065701",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Memorial",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_memorial_d.mp3",
		["Length"] = 123,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065703",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Memorial",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_memorial_h.mp3",
		["Length"] = 220,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065705",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Works",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_works_a.mp3",
		["Length"] = 136,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065707",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Works",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_works_b.mp3",
		["Length"] = 135,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065709",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Works",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_works_c.mp3",
		["Length"] = 158,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065711",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Works",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_works_d.mp3",
		["Length"] = 137,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6074869",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Earthen Works",
		["Name"] = "sound\\music\\warwithin\\mus_110_earthen_works_h.mp3",
		["Length"] = 182,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065713",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_fungarian_fol",
		["Name"] = "sound\\music\\warwithin\\mus_110_fungarian_folly_a.mp3",
		["Length"] = 92,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
		["Id"] =  "6075176",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_fungarian_fol",
		["Name"] = "sound\\music\\warwithin\\mus_110_fungarian_folly_b.mp3",
		["Length"] = 87,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
		["Id"] =  "6075178",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_fungarian_fol",
		["Name"] = "sound\\music\\warwithin\\mus_110_fungarian_folly_c.mp3",
		["Length"] = 71,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
		["Id"] =  "6075180",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_fungarian_fol",
		["Name"] = "sound\\music\\warwithin\\mus_110_fungarian_folly_d.mp3",
		["Length"] = 90,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
		["Id"] =  "6075182",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_fungarian_fol",
		["Name"] = "sound\\music\\warwithin\\mus_110_fungarian_folly_h.mp3",
		["Length"] = 105,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
		["Id"] =  "6075174",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Glimmering Shore",
		["Name"] = "sound\\music\\warwithin\\mus_110_glimmering_shore_a.mp3",
		["Length"] = 109,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065715",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Glimmering Shore",
		["Name"] = "sound\\music\\warwithin\\mus_110_glimmering_shore_b.mp3",
		["Length"] = 107,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065717",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Glimmering Shore",
		["Name"] = "sound\\music\\warwithin\\mus_110_glimmering_shore_c.mp3",
		["Length"] = 95,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065719",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Glimmering Shore",
		["Name"] = "sound\\music\\warwithin\\mus_110_glimmering_shore_d.mp3",
		["Length"] = 140,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065721",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Glimmering Shore",
		["Name"] = "sound\\music\\warwithin\\mus_110_glimmering_shore_e.mp3",
		["Length"] = 144,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065723",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_glimmering_sho",
		["Name"] = "sound\\music\\warwithin\\mus_110_glimmering_shore_h.mp3",
		["Length"] = 186,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6068112",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_gundarg",
		["Name"] = "sound\\music\\warwithin\\mus_110_gundargaz_a.mp3",
		["Length"] = 125,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6065459",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_gundarg",
		["Name"] = "sound\\music\\warwithin\\mus_110_gundargaz_b.mp3",
		["Length"] = 126,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6065455",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_gundarg",
		["Name"] = "sound\\music\\warwithin\\mus_110_gundargaz_c.mp3",
		["Length"] = 126,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6065457",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_gundarg",
		["Name"] = "sound\\music\\warwithin\\mus_110_gundargaz_h.mp3",
		["Length"] = 118,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074945",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_hallowfa",
		["Name"] = "sound\\music\\warwithin\\mus_110_hallowfall_a.mp3",
		["Length"] = 111,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "6065778",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_hallowfa",
		["Name"] = "sound\\music\\warwithin\\mus_110_hallowfall_b.mp3",
		["Length"] = 93,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "6065780",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_hallowfa",
		["Name"] = "sound\\music\\warwithin\\mus_110_hallowfall_c.mp3",
		["Length"] = 79,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "6065782",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_hallowfa",
		["Name"] = "sound\\music\\warwithin\\mus_110_hallowfall_d.mp3",
		["Length"] = 97,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "6065784",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_hallowfa",
		["Name"] = "sound\\music\\warwithin\\mus_110_hallowfall_e.mp3",
		["Length"] = 97,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "6065786",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_hallowfa",
		["Name"] = "sound\\music\\warwithin\\mus_110_hallowfall_f.mp3",
		["Length"] = 92,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "6065788",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_hallowfa",
		["Name"] = "sound\\music\\warwithin\\mus_110_hallowfall_h.mp3",
		["Length"] = 97,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "6065790",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_harronir_wildca",
		["Name"] = "sound\\music\\warwithin\\mus_110_harronir_wildcamp_h.mp3",
		["Length"] = 125,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6065816",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Isle Of Dorn",
		["Name"] = "sound\\music\\warwithin\\mus_110_isle_of_dorn_a.mp3",
		["Length"] = 105,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065725",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Isle Of Dorn",
		["Name"] = "sound\\music\\warwithin\\mus_110_isle_of_dorn_b.mp3",
		["Length"] = 138,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065727",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Isle Of Dorn",
		["Name"] = "sound\\music\\warwithin\\mus_110_isle_of_dorn_c.mp3",
		["Length"] = 118,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065729",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Isle Of Dorn",
		["Name"] = "sound\\music\\warwithin\\mus_110_isle_of_dorn_d.mp3",
		["Length"] = 120,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065731",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Isle Of Dorn",
		["Name"] = "sound\\music\\warwithin\\mus_110_isle_of_dorn_e.mp3",
		["Length"] = 90,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065733",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Isle Of Dorn",
		["Name"] = "sound\\music\\warwithin\\mus_110_isle_of_dorn_f.mp3",
		["Length"] = 120,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065735",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Isle Of Dorn",
		["Name"] = "sound\\music\\warwithin\\mus_110_isle_of_dorn_h.mp3",
		["Length"] = 257,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065737",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_khaz_algar_i",
		["Name"] = "sound\\music\\warwithin\\mus_110_khaz_algar_inn_a.mp3",
		["Length"] = 162,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6065463",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_khaz_algar_i",
		["Name"] = "sound\\music\\warwithin\\mus_110_khaz_algar_inn_h.mp3",
		["Length"] = 166,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6065461",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Living Grotto",
		["Name"] = "sound\\music\\warwithin\\mus_110_living_grotto_a.mp3",
		["Length"] = 67,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074871",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Living Grotto",
		["Name"] = "sound\\music\\warwithin\\mus_110_living_grotto_b.mp3",
		["Length"] = 125,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074873",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Living Grotto",
		["Name"] = "sound\\music\\warwithin\\mus_110_living_grotto_c.mp3",
		["Length"] = 157,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074875",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Living Grotto",
		["Name"] = "sound\\music\\warwithin\\mus_110_living_grotto_h.mp3",
		["Length"] = 175,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6034328",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Lorels Crossing",
		["Name"] = "sound\\music\\warwithin\\mus_110_lorels_crossing_a.mp3",
		["Length"] = 133,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065739",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Lorels Crossing",
		["Name"] = "sound\\music\\warwithin\\mus_110_lorels_crossing_b.mp3",
		["Length"] = 100,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065741",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Lorels Crossing",
		["Name"] = "sound\\music\\warwithin\\mus_110_lorels_crossing_c.mp3",
		["Length"] = 76,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065743",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Lorels Crossing",
		["Name"] = "sound\\music\\warwithin\\mus_110_lorels_crossing_d.mp3",
		["Length"] = 157,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065745",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Lorels Crossing",
		["Name"] = "sound\\music\\warwithin\\mus_110_lorels_crossing_e.mp3",
		["Length"] = 126,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065747",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Lorels Crossing",
		["Name"] = "sound\\music\\warwithin\\mus_110_lorels_crossing_f.mp3",
		["Length"] = 125,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065749",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Lorels Crossing",
		["Name"] = "sound\\music\\warwithin\\mus_110_lorels_crossing_g.mp3",
		["Length"] = 119,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065751",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Lorels Crossing",
		["Name"] = "sound\\music\\warwithin\\mus_110_lorels_crossing_h.mp3",
		["Length"] = 179,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6065753",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Lost Mines",
		["Name"] = "sound\\music\\warwithin\\mus_110_lost_mines_a.mp3",
		["Length"] = 190,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074877",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Lost Mines",
		["Name"] = "sound\\music\\warwithin\\mus_110_lost_mines_b.mp3",
		["Length"] = 142,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074879",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Lost Mines",
		["Name"] = "sound\\music\\warwithin\\mus_110_lost_mines_c.mp3",
		["Length"] = 125,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6075164",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Lost Mines",
		["Name"] = "sound\\music\\warwithin\\mus_110_lost_mines_d.mp3",
		["Length"] = 141,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6075166",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Lost Mines",
		["Name"] = "sound\\music\\warwithin\\mus_110_lost_mines_e.mp3",
		["Length"] = 115,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6075168",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Lost Mines",
		["Name"] = "sound\\music\\warwithin\\mus_110_lost_mines_f.mp3",
		["Length"] = 111,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6075170",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Lost Mines",
		["Name"] = "sound\\music\\warwithin\\mus_110_lost_mines_g.mp3",
		["Length"] = 112,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6075172",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Lost Mines",
		["Name"] = "sound\\music\\warwithin\\mus_110_lost_mines_h.mp3",
		["Length"] = 182,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6034330",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Maddening Deep",
		["Name"] = "sound\\music\\warwithin\\mus_110_maddening_deep_a.mp3",
		["Length"] = 132,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055526",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Maddening Deep",
		["Name"] = "sound\\music\\warwithin\\mus_110_maddening_deep_b.mp3",
		["Length"] = 120,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055528",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Maddening Deep",
		["Name"] = "sound\\music\\warwithin\\mus_110_maddening_deep_c.mp3",
		["Length"] = 118,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055530",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Maddening Deep",
		["Name"] = "sound\\music\\warwithin\\mus_110_maddening_deep_d.mp3",
		["Length"] = 115,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055532",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Maddening Deep",
		["Name"] = "sound\\music\\warwithin\\mus_110_maddening_deep_e.mp3",
		["Length"] = 124,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055534",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Maddening Deep",
		["Name"] = "sound\\music\\warwithin\\mus_110_maddening_deep_f.mp3",
		["Length"] = 124,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055536",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Maddening Deep",
		["Name"] = "sound\\music\\warwithin\\mus_110_maddening_deep_h.mp3",
		["Length"] = 122,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055538",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Mereldar",
		["Name"] = "sound\\music\\warwithin\\mus_110_mereldar_a.mp3",
		["Length"] = 123,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6037079",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Mereldar",
		["Name"] = "sound\\music\\warwithin\\mus_110_mereldar_b.mp3",
		["Length"] = 135,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6037081",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Mereldar",
		["Name"] = "sound\\music\\warwithin\\mus_110_mereldar_c.mp3",
		["Length"] = 136,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6037084",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Mereldar Chorale",
		["Name"] = "sound\\music\\warwithin\\mus_110_mereldar_chorale_a.mp3",
		["Length"] = 122,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042865",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Mereldar Chorale",
		["Name"] = "sound\\music\\warwithin\\mus_110_mereldar_chorale_b.mp3",
		["Length"] = 119,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042867",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Mereldar Chorale",
		["Name"] = "sound\\music\\warwithin\\mus_110_mereldar_chorale_h.mp3",
		["Length"] = 121,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6042869",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Mereldar",
		["Name"] = "sound\\music\\warwithin\\mus_110_mereldar_d.mp3",
		["Length"] = 134,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6037086",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Mereldar",
		["Name"] = "sound\\music\\warwithin\\mus_110_mereldar_h.mp3",
		["Length"] = 138,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6037088",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Nerubian Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_nerubian_combat_a.mp3",
		["Length"] = 225,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6065755",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Nerubian Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_nerubian_combat_b.mp3",
		["Length"] = 229,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6065757",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Nerubian Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_nerubian_combat_c.mp3",
		["Length"] = 222,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6065759",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Nerubian Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_nerubian_combat_d.mp3",
		["Length"] = 110,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6065761",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Nerubian Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_nerubian_combat_e.mp3",
		["Length"] = 152,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6065763",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Nerubian Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_nerubian_combat_f.mp3",
		["Length"] = 117,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6065765",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Nerubian Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_nerubian_combat_g.mp3",
		["Length"] = 118,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6065767",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Nerubian Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_nerubian_combat_h.mp3",
		["Length"] = 229,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6065769",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Nerubian Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_nerubian_combat_i.mp3",
		["Length"] = 203,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6065771",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Nerubian Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_nerubian_combat_j.mp3",
		["Length"] = 202,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6065773",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Nerubian Combat",
		["Name"] = "sound\\music\\warwithin\\mus_110_nerubian_combat_k.mp3",
		["Length"] = 196,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6065775",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Nerubian Raid",
		["Name"] = "sound\\music\\warwithin\\mus_110_nerubian_raid_a.mp3",
		["Length"] = 145,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6034332",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Nerubian Raid",
		["Name"] = "sound\\music\\warwithin\\mus_110_nerubian_raid_b.mp3",
		["Length"] = 151,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6034334",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Nerubian Raid",
		["Name"] = "sound\\music\\warwithin\\mus_110_nerubian_raid_c.mp3",
		["Length"] = 145,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6034336",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Nerubian Raid",
		["Name"] = "sound\\music\\warwithin\\mus_110_nerubian_raid_d.mp3",
		["Length"] = 133,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6055540",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Nerubian Raid",
		["Name"] = "sound\\music\\warwithin\\mus_110_nerubian_raid_h.mp3",
		["Length"] = 172,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6075204",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_order_of_nig",
		["Name"] = "sound\\music\\warwithin\\mus_110_order_of_night_a.mp3",
		["Length"] = 35,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "6065792",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_order_of_nig",
		["Name"] = "sound\\music\\warwithin\\mus_110_order_of_night_b.mp3",
		["Length"] = 69,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "6065794",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_order_of_nig",
		["Name"] = "sound\\music\\warwithin\\mus_110_order_of_night_c.mp3",
		["Length"] = 73,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "6065796",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_order_of_nig",
		["Name"] = "sound\\music\\warwithin\\mus_110_order_of_night_d.mp3",
		["Length"] = 69,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "6065798",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_order_of_nig",
		["Name"] = "sound\\music\\warwithin\\mus_110_order_of_night_e.mp3",
		["Length"] = 32,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "6065800",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_order_of_nig",
		["Name"] = "sound\\music\\warwithin\\mus_110_order_of_night_h.mp3",
		["Length"] = 132,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "6065802",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_pillar_ne",
		["Name"] = "sound\\music\\warwithin\\mus_110_pillar_nest_a.mp3",
		["Length"] = 132,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "true",
		["Id"] =  "6065465",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_pillar_ne",
		["Name"] = "sound\\music\\warwithin\\mus_110_pillar_nest_b.mp3",
		["Length"] = 132,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "true",
		["Id"] =  "6065467",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_pillar_ne",
		["Name"] = "sound\\music\\warwithin\\mus_110_pillar_nest_c.mp3",
		["Length"] = 125,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "true",
		["Id"] =  "6068114",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_pillar_ne",
		["Name"] = "sound\\music\\warwithin\\mus_110_pillar_nest_d.mp3",
		["Length"] = 126,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "true",
		["Id"] =  "6068116",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_pillar_ne",
		["Name"] = "sound\\music\\warwithin\\mus_110_pillar_nest_e.mp3",
		["Length"] = 125,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "true",
		["Id"] =  "6068118",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_pillar_ne",
		["Name"] = "sound\\music\\warwithin\\mus_110_pillar_nest_f.mp3",
		["Length"] = 123,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "true",
		["Id"] =  "6068120",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_pillar_ne",
		["Name"] = "sound\\music\\warwithin\\mus_110_pillar_nest_g.mp3",
		["Length"] = 129,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "true",
		["Id"] =  "6068122",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_pillar_ne",
		["Name"] = "sound\\music\\warwithin\\mus_110_pillar_nest_h.mp3",
		["Length"] = 132,
		["Artist"] = "Grant Kirkhope",
		["WoW"] =  "true",
		["Id"] =  "6065469",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Proscenium",
		["Name"] = "sound\\music\\warwithin\\mus_110_proscenium_a.mp3",
		["Length"] = 193,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074881",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Proscenium",
		["Name"] = "sound\\music\\warwithin\\mus_110_proscenium_b.mp3",
		["Length"] = 148,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074883",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Proscenium",
		["Name"] = "sound\\music\\warwithin\\mus_110_proscenium_c.mp3",
		["Length"] = 66,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6034338",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Proscenium",
		["Name"] = "sound\\music\\warwithin\\mus_110_proscenium_d.mp3",
		["Length"] = 137,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6034340",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Proscenium",
		["Name"] = "sound\\music\\warwithin\\mus_110_proscenium_h.mp3",
		["Length"] = 162,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074885",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Queen Ansurek",
		["Name"] = "sound\\music\\warwithin\\mus_110_queen_ansurek_a.mp3",
		["Length"] = 180,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6034342",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Queen Ansurek",
		["Name"] = "sound\\music\\warwithin\\mus_110_queen_ansurek_b.mp3",
		["Length"] = 64,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6034344",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Queen Ansurek",
		["Name"] = "sound\\music\\warwithin\\mus_110_queen_ansurek_c.mp3",
		["Length"] = 64,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6034346",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Queen Ansurek",
		["Name"] = "sound\\music\\warwithin\\mus_110_queen_ansurek_d.mp3",
		["Length"] = 115,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6034348",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Queen Ansurek",
		["Name"] = "sound\\music\\warwithin\\mus_110_queen_ansurek_e.mp3",
		["Length"] = 62,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6034350",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Queen Ansurek",
		["Name"] = "sound\\music\\warwithin\\mus_110_queen_ansurek_f.mp3",
		["Length"] = 62,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6034352",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Queen Ansurek",
		["Name"] = "sound\\music\\warwithin\\mus_110_queen_ansurek_g.mp3",
		["Length"] = 64,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6034354",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Queen Ansurek",
		["Name"] = "sound\\music\\warwithin\\mus_110_queen_ansurek_h.mp3",
		["Length"] = 64,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6034356",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Queen Ansurek",
		["Name"] = "sound\\music\\warwithin\\mus_110_queen_ansurek_i.mp3",
		["Length"] = 181,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6055542",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Queen Ansurek",
		["Name"] = "sound\\music\\warwithin\\mus_110_queen_ansurek_j.mp3",
		["Length"] = 172,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6055544",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Queen Ansurek",
		["Name"] = "sound\\music\\warwithin\\mus_110_queen_ansurek_k.mp3",
		["Length"] = 170,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6055546",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Queen Ansurek",
		["Name"] = "sound\\music\\warwithin\\mus_110_queen_ansurek_l.mp3",
		["Length"] = 123,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6075266",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Radient Song",
		["Name"] = "sound\\music\\warwithin\\mus_110_radient_song_a.mp3",
		["Length"] = 13,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6055550",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Radient Song",
		["Name"] = "sound\\music\\warwithin\\mus_110_radient_song_h.mp3",
		["Length"] = 17,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6055548",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Ringing Deeps Base",
		["Name"] = "sound\\music\\warwithin\\mus_110_ringing_deeps_base_a.mp3",
		["Length"] = 132,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055552",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Ringing Deeps Base",
		["Name"] = "sound\\music\\warwithin\\mus_110_ringing_deeps_base_b.mp3",
		["Length"] = 119,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055554",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Ringing Deeps Base",
		["Name"] = "sound\\music\\warwithin\\mus_110_ringing_deeps_base_c.mp3",
		["Length"] = 136,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055556",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Ringing Deeps Base",
		["Name"] = "sound\\music\\warwithin\\mus_110_ringing_deeps_base_d.mp3",
		["Length"] = 152,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055558",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Ringing Deeps Base",
		["Name"] = "sound\\music\\warwithin\\mus_110_ringing_deeps_base_e.mp3",
		["Length"] = 152,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055560",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Ringing Deeps Base",
		["Name"] = "sound\\music\\warwithin\\mus_110_ringing_deeps_base_f.mp3",
		["Length"] = 91,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055562",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Ringing Deeps Base",
		["Name"] = "sound\\music\\warwithin\\mus_110_ringing_deeps_base_g.mp3",
		["Length"] = 185,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055564",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Ringing Deeps Base",
		["Name"] = "sound\\music\\warwithin\\mus_110_ringing_deeps_base_h.mp3",
		["Length"] = 214,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055566",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_sacred_fla",
		["Name"] = "sound\\music\\warwithin\\mus_110_sacred_flame_a.mp3",
		["Length"] = 47,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "6065804",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_sacred_fla",
		["Name"] = "sound\\music\\warwithin\\mus_110_sacred_flame_b.mp3",
		["Length"] = 58,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "6065806",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_sacred_fla",
		["Name"] = "sound\\music\\warwithin\\mus_110_sacred_flame_c.mp3",
		["Length"] = 57,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "6065808",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_sacred_fla",
		["Name"] = "sound\\music\\warwithin\\mus_110_sacred_flame_d.mp3",
		["Length"] = 159,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "6065810",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_sacred_fla",
		["Name"] = "sound\\music\\warwithin\\mus_110_sacred_flame_e.mp3",
		["Length"] = 42,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "6065814",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_sacred_fla",
		["Name"] = "sound\\music\\warwithin\\mus_110_sacred_flame_h.mp3",
		["Length"] = 221,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "6065812",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scen",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_01.mp3",
		["Length"] = 45,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074183",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scen",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_02.mp3",
		["Length"] = 57,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074185",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scen",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_03.mp3",
		["Length"] = 72,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074187",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scen",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_04.mp3",
		["Length"] = 48,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074189",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scen",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_05.mp3",
		["Length"] = 66,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074191",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scen",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_06.mp3",
		["Length"] = 102,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074195",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scen",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_07.mp3",
		["Length"] = 123,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074197",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scen",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_08.mp3",
		["Length"] = 54,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074199",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scen",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_09.mp3",
		["Length"] = 20,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074203",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scen",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_10.mp3",
		["Length"] = 91,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074205",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scen",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_11.mp3",
		["Length"] = 51,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074207",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scen",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_12.mp3",
		["Length"] = 58,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074209",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scen",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_13.mp3",
		["Length"] = 40,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6067052",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scene_alleria_and_xala",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_alleria_and_xalatath.mp3",
		["Length"] = 122,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6075590",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "AIL",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_anduin_is_lost.mp3",
		["Length"] = 61,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074805",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "BSC",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_bsc.mp3",
		["Length"] = 76,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074807",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scene_candle_in_the_",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_candle_in_the_dark.mp3",
		["Length"] = 97,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6075592",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scene_final_resist",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_final_resistance.mp3",
		["Length"] = 27,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074289",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scene_impossible_",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_impossible_odds.mp3",
		["Length"] = 72,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074201",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scene_light_of_the_dawnt",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_light_of_the_dawntower.mp3",
		["Length"] = 88,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6067054",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "MDD",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_mdd.mp3",
		["Length"] = 63,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074809",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scene_restore_the_f",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_restore_the_flame.mp3",
		["Length"] = 105,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074193",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "STM",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_stm.mp3",
		["Length"] = 53,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074811",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_scene_whisper_on_the_",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_whisper_on_the_wall.mp3",
		["Length"] = 92,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6075594",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "XAS",
		["Name"] = "sound\\music\\warwithin\\mus_110_scene_xas.mp3",
		["Length"] = 54,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6074813",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Silken Path",
		["Name"] = "sound\\music\\warwithin\\mus_110_silken_path_a.mp3",
		["Length"] = 194,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055568",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Silken Path",
		["Name"] = "sound\\music\\warwithin\\mus_110_silken_path_b.mp3",
		["Length"] = 144,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055570",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Silken Path",
		["Name"] = "sound\\music\\warwithin\\mus_110_silken_path_c.mp3",
		["Length"] = 146,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055572",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Silken Path",
		["Name"] = "sound\\music\\warwithin\\mus_110_silken_path_d.mp3",
		["Length"] = 108,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055574",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Silken Path",
		["Name"] = "sound\\music\\warwithin\\mus_110_silken_path_e.mp3",
		["Length"] = 179,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055576",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Silken Path",
		["Name"] = "sound\\music\\warwithin\\mus_110_silken_path_h.mp3",
		["Length"] = 179,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055578",
	},
	{
		["Album"] = "",
		["Song"] = "mus_110_soundtest_musi",
		["Name"] = "sound\\music\\warwithin\\mus_110_soundtest_music_01.mp3",
		["Length"] = 197,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "6036524",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_stonelight_re",
		["Name"] = "sound\\music\\warwithin\\mus_110_stonelight_rest_a.mp3",
		["Length"] = 117,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074933",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_stonelight_re",
		["Name"] = "sound\\music\\warwithin\\mus_110_stonelight_rest_b.mp3",
		["Length"] = 117,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074935",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_stonelight_re",
		["Name"] = "sound\\music\\warwithin\\mus_110_stonelight_rest_c.mp3",
		["Length"] = 105,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074937",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_stonelight_re",
		["Name"] = "sound\\music\\warwithin\\mus_110_stonelight_rest_d.mp3",
		["Length"] = 129,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6065449",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_stonelight_re",
		["Name"] = "sound\\music\\warwithin\\mus_110_stonelight_rest_h.mp3",
		["Length"] = 116,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6065451",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_stormrid",
		["Name"] = "sound\\music\\warwithin\\mus_110_stormrider_a.mp3",
		["Length"] = 137,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6068124",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_stormrid",
		["Name"] = "sound\\music\\warwithin\\mus_110_stormrider_b.mp3",
		["Length"] = 122,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6068126",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_stormrid",
		["Name"] = "sound\\music\\warwithin\\mus_110_stormrider_c.mp3",
		["Length"] = 126,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6068128",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_stormrid",
		["Name"] = "sound\\music\\warwithin\\mus_110_stormrider_h.mp3",
		["Length"] = 111,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6068130",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Sunless Strand",
		["Name"] = "sound\\music\\warwithin\\mus_110_sunless_strand_a.mp3",
		["Length"] = 109,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6037090",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Sunless Strand",
		["Name"] = "sound\\music\\warwithin\\mus_110_sunless_strand_b.mp3",
		["Length"] = 147,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6037092",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Sunless Strand",
		["Name"] = "sound\\music\\warwithin\\mus_110_sunless_strand_c.mp3",
		["Length"] = 139,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6037094",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Sunless Strand",
		["Name"] = "sound\\music\\warwithin\\mus_110_sunless_strand_d.mp3",
		["Length"] = 112,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6037096",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Sunless Strand",
		["Name"] = "sound\\music\\warwithin\\mus_110_sunless_strand_h.mp3",
		["Length"] = 151,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6037098",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Taelloch",
		["Name"] = "sound\\music\\warwithin\\mus_110_taelloch_a.mp3",
		["Length"] = 196,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055582",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Taelloch",
		["Name"] = "sound\\music\\warwithin\\mus_110_taelloch_b.mp3",
		["Length"] = 102,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055584",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Taelloch",
		["Name"] = "sound\\music\\warwithin\\mus_110_taelloch_c.mp3",
		["Length"] = 140,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055586",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Taelloch",
		["Name"] = "sound\\music\\warwithin\\mus_110_taelloch_d.mp3",
		["Length"] = 205,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055588",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Taelloch",
		["Name"] = "sound\\music\\warwithin\\mus_110_taelloch_e.mp3",
		["Length"] = 205,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055590",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Taelloch",
		["Name"] = "sound\\music\\warwithin\\mus_110_taelloch_h.mp3",
		["Length"] = 207,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
		["Id"] =  "6055580",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "The Aegis Wall",
		["Name"] = "sound\\music\\warwithin\\mus_110_the_aegis_wall_a.mp3",
		["Length"] = 137,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6037100",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "The Aegis Wall",
		["Name"] = "sound\\music\\warwithin\\mus_110_the_aegis_wall_b.mp3",
		["Length"] = 79,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6037102",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "The Aegis Wall",
		["Name"] = "sound\\music\\warwithin\\mus_110_the_aegis_wall_c.mp3",
		["Length"] = 166,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6037104",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "The Aegis Wall",
		["Name"] = "sound\\music\\warwithin\\mus_110_the_aegis_wall_d.mp3",
		["Length"] = 92,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6037112",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "The Aegis Wall",
		["Name"] = "sound\\music\\warwithin\\mus_110_the_aegis_wall_e.mp3",
		["Length"] = 149,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6037114",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "The Aegis Wall",
		["Name"] = "sound\\music\\warwithin\\mus_110_the_aegis_wall_f.mp3",
		["Length"] = 106,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6037116",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "The Aegis Wall",
		["Name"] = "sound\\music\\warwithin\\mus_110_the_aegis_wall_h.mp3",
		["Length"] = 184,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6034358",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_the_aegis_wall_sting",
		["Name"] = "sound\\music\\warwithin\\mus_110_the_aegis_wall_stinger_a.mp3",
		["Length"] = 11,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6067056",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_the_aegis_wall_sting",
		["Name"] = "sound\\music\\warwithin\\mus_110_the_aegis_wall_stinger_b.mp3",
		["Length"] = 10,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6067058",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "The Warrens",
		["Name"] = "sound\\music\\warwithin\\mus_110_the_warrens_a.mp3",
		["Length"] = 88,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074889",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "The Warrens",
		["Name"] = "sound\\music\\warwithin\\mus_110_the_warrens_b.mp3",
		["Length"] = 90,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074891",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "The Warrens",
		["Name"] = "sound\\music\\warwithin\\mus_110_the_warrens_c.mp3",
		["Length"] = 96,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074893",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "The Warrens",
		["Name"] = "sound\\music\\warwithin\\mus_110_the_warrens_d.mp3",
		["Length"] = 66,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6034360",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "The Warrens",
		["Name"] = "sound\\music\\warwithin\\mus_110_the_warrens_h.mp3",
		["Length"] = 94,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
		["Id"] =  "6074887",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "The War Soul Saga",
		["Name"] = "sound\\music\\warwithin\\mus_110_the_war_soul_saga_h.mp3",
		["Length"] = 339,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6037118",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Tranquil Strand",
		["Name"] = "sound\\music\\warwithin\\mus_110_tranquil_strand_a.mp3",
		["Length"] = 83,
		["Artist"] = "Neal Acree, Russell Brower",
		["WoW"] =  "true",
		["Id"] =  "6029090",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Tranquil Strand",
		["Name"] = "sound\\music\\warwithin\\mus_110_tranquil_strand_b.mp3",
		["Length"] = 86,
		["Artist"] = "Neal Acree, Russell Brower",
		["WoW"] =  "true",
		["Id"] =  "6029092",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Tranquil Strand",
		["Name"] = "sound\\music\\warwithin\\mus_110_tranquil_strand_h.mp3",
		["Length"] = 121,
		["Artist"] = "Neal Acree, Russell Brower",
		["WoW"] =  "true",
		["Id"] =  "6029094",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Vault Of Memories",
		["Name"] = "sound\\music\\warwithin\\mus_110_vault_of_memories_a.mp3",
		["Length"] = 83,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6029098",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Vault Of Memories",
		["Name"] = "sound\\music\\warwithin\\mus_110_vault_of_memories_b.mp3",
		["Length"] = 95,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6029100",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Vault Of Memories",
		["Name"] = "sound\\music\\warwithin\\mus_110_vault_of_memories_c.mp3",
		["Length"] = 79,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6029102",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Vault Of Memories",
		["Name"] = "sound\\music\\warwithin\\mus_110_vault_of_memories_h.mp3",
		["Length"] = 87,
		["Artist"] = "Adam Burgess",
		["WoW"] =  "true",
		["Id"] =  "6029096",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Warcraft Battle",
		["Name"] = "sound\\music\\warwithin\\mus_110_warcraft_battle_a.mp3",
		["Length"] = 61,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6074895",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Warcraft Battle",
		["Name"] = "sound\\music\\warwithin\\mus_110_warcraft_battle_b.mp3",
		["Length"] = 66,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6074897",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Warcraft Battle",
		["Name"] = "sound\\music\\warwithin\\mus_110_warcraft_battle_c.mp3",
		["Length"] = 71,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6074899",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Warcraft Battle",
		["Name"] = "sound\\music\\warwithin\\mus_110_warcraft_battle_d.mp3",
		["Length"] = 66,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6074901",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Warcraft Battle",
		["Name"] = "sound\\music\\warwithin\\mus_110_warcraft_battle_e.mp3",
		["Length"] = 50,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6074903",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_warcraft_batt",
		["Name"] = "sound\\music\\warwithin\\mus_110_warcraft_battle_f.mp3",
		["Length"] = 79,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6075184",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_warcraft_batt",
		["Name"] = "sound\\music\\warwithin\\mus_110_warcraft_battle_h.mp3",
		["Length"] = 124,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6074947",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_warcraft_battl",
		["Name"] = "sound\\music\\warwithin\\mus_110_warcraft_battle_h1.mp3",
		["Length"] = 124,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6068110",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Weaver's Lair",
		["Name"] = "sound\\music\\warwithin\\mus_110_weavers_lair_a.mp3",
		["Length"] = 133,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6074905",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Weaver's Lair",
		["Name"] = "sound\\music\\warwithin\\mus_110_weavers_lair_b.mp3",
		["Length"] = 123,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6074907",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Weaver's Lair",
		["Name"] = "sound\\music\\warwithin\\mus_110_weavers_lair_c.mp3",
		["Length"] = 135,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6074909",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Weaver's Lair",
		["Name"] = "sound\\music\\warwithin\\mus_110_weavers_lair_d.mp3",
		["Length"] = 131,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6074911",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Weaver's Lair",
		["Name"] = "sound\\music\\warwithin\\mus_110_weavers_lair_e.mp3",
		["Length"] = 130,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6074913",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "mus_110_weavers_la",
		["Name"] = "sound\\music\\warwithin\\mus_110_weavers_lair_h.mp3",
		["Length"] = 131,
		["Artist"] = "Jake Lefkowitz",
		["WoW"] =  "true",
		["Id"] =  "6068162",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "Xalatath",
		["Name"] = "sound\\music\\warwithin\\mus_110_xalatath_h.mp3",
		["Length"] = 233,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
		["Id"] =  "6055592",
	},
	{
		["Album"] = "WoW: The War Within",
		["Song"] = "scenescript_unknown_53719_604",
		["Name"] = "sound\\music\\warwithin\\scenescript_unknown_53719_6046776.mp3",
		["Length"] = 51,
		["Artist"] = "Blizzard Entertainment",
		["WoW"] =  "true",
		["Id"] =  "6046776",
	},
}
if LE_EXPANSION_LEVEL_CURRENT > 7 then
	EpicMusicPlayer:AddPlayList(nil, playlist1, false)
end