local emp = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer", true) ---@class emp
if not emp then return end

-- playlist metadata
local requiredExpansion = "The Burning Crusade"

emp:RegisterPlaylist(requiredExpansion, function()
return {
	listName = requiredExpansion,
	playlistVersion = "5.0",
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "The Burning Legion",
		path = "sound\\music\\gluescreenmusic\\bc_main_theme.mp3",
		id =  53220,
		duration = 226,
		artist = "Main Title",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Auchindoun Walking 1",
		path = "sound\\music\\zonemusic\\terokkar\\tf_auchindounwalkuni01.mp3",
		id =  53796,
		duration = 120,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Auchindoun Walking 2",
		path = "sound\\music\\zonemusic\\terokkar\\tf_auchindounwalkuni02.mp3",
		id =  53797,
		duration = 150,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Auchindoun Walking 3",
		path = "sound\\music\\zonemusic\\terokkar\\tf_auchindounwalkuni03.mp3",
		id =  53798,
		duration = 120,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Draenei 1",
		path = "sound\\music\\zonemusic\\azuremyst\\av_draeneiwalkuni01.mp3",
		id =  53293,
		duration = 206,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Draenei 2A",
		path = "sound\\music\\zonemusic\\azuremyst\\av_draeneiwalkuni02.mp3",
		id =  53294,
		duration = 124,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Draenei 2B",
		path = "sound\\music\\zonemusic\\azuremyst\\av_draeneiwalkuni02r.mp3",
		id =  53295,
		duration = 129,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Draenei 3A",
		path = "sound\\music\\zonemusic\\azuremyst\\av_draeneiwalkuni03.mp3",
		id =  53296,
		duration = 187,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Draenei 3B",
		path = "sound\\music\\zonemusic\\azuremyst\\av_draeneiwalkuni03r.mp3",
		id =  53297,
		duration = 188,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Draenei 4",
		path = "sound\\music\\zonemusic\\azuremyst\\av_draeneiwalkuni04.mp3",
		id =  53298,
		duration = 158,
		artist = "Derek Duke",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Draenei 5",
		path = "sound\\music\\zonemusic\\azuremyst\\ai_draeneiwalkuni05.mp3",
		id =  53278,
		duration = 191,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Draenei 6",
		path = "sound\\music\\zonemusic\\azuremyst\\ai_draeneiwalkuni06.mp3",
		id =  53279,
		duration = 110,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Draenei 7",
		path = "sound\\music\\zonemusic\\azuremyst\\ai_draeneiwalkuni07r.mp3",
		id =  53280,
		duration = 110,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Draenei 8",
		path = "sound\\music\\zonemusic\\azuremyst\\ai_draeneiwalkuni08r.mp3",
		id =  53281,
		duration = 99,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Exodar Intro",
		path = "sound\\music\\zonemusic\\azuremyst\\ai_exodarintro01.mp3",
		id =  53282,
		duration = 82,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Exodar 1",
		path = "sound\\music\\zonemusic\\azuremyst\\ai_exodarwalkuni01.mp3",
		id =  53283,
		duration = 109,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Exodar 2",
		path = "sound\\music\\zonemusic\\azuremyst\\ai_exodarwalkuni02.mp3",
		id =  53284,
		duration = 107,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Exodar 3",
		path = "sound\\music\\zonemusic\\azuremyst\\ai_exodarwalkuni03.mp3",
		id =  53285,
		duration = 93,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Naga 1",
		path = "sound\\music\\zonemusic\\azuremyst\\ai_nagawalkuni01.mp3",
		id =  53286,
		duration = 103,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Naga 2",
		path = "sound\\music\\zonemusic\\azuremyst\\ai_nagawalkuni02.mp3",
		id =  53287,
		duration = 74,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Naga 3",
		path = "sound\\music\\zonemusic\\azuremyst\\ai_nagawalkuni03.mp3",
		id =  53288,
		duration = 149,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Naga 4",
		path = "sound\\music\\zonemusic\\azuremyst\\ai_nagawalkuni04.mp3",
		id =  53289,
		duration = 73,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Naga 5",
		path = "sound\\music\\zonemusic\\azuremyst\\ai_nagawalkuni05.mp3",
		id =  53290,
		duration = 98,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Owlkin 1",
		path = "sound\\music\\zonemusic\\azuremyst\\ai_owlkinwalkuni01.mp3",
		id =  53291,
		duration = 49,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Azuremyst Owlkin 2",
		path = "sound\\music\\zonemusic\\azuremyst\\ai_owlkinwalkuni02.mp3",
		id =  53292,
		duration = 45,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Blade's Edge Dry Forest Walking 1",
		path = "sound\\music\\zonemusic\\bladesedge\\bl_dryforestwalkuni01.mp3",
		id =  53350,
		duration = 89,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Blade's Edge Dry Forest Walking 2",
		path = "sound\\music\\zonemusic\\bladesedge\\bl_dryforestwalkuni02.mp3",
		id =  53351,
		duration = 127,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Blade's Edge Dry Forest Walking 3",
		path = "sound\\music\\zonemusic\\bladesedge\\bl_dryforestwalkuni03.mp3",
		id =  53352,
		duration = 131,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Blade's Edge Walking 1",
		path = "sound\\music\\zonemusic\\bladesedge\\bl_generalwalkuni01.mp3",
		id =  53353,
		duration = 80,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Blade's Edge Walking 2",
		path = "sound\\music\\zonemusic\\bladesedge\\bl_generalwalkuni02.mp3",
		id =  53354,
		duration = 75,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Blade's Edge Walking 3",
		path = "sound\\music\\zonemusic\\bladesedge\\bl_generalwalkuni03.mp3",
		id =  53355,
		duration = 158,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Blade's Edge Walking 4",
		path = "sound\\music\\zonemusic\\bladesedge\\bl_generalwalkuni04.mp3",
		id =  53356,
		duration = 110,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Blade's Edge Walking 5",
		path = "sound\\music\\zonemusic\\bladesedge\\bl_generalwalkuni05.mp3",
		id =  53357,
		duration = 110,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Blade's Edge Ogre Walking 1",
		path = "sound\\music\\zonemusic\\bladesedge\\bl_ogrewalkuni01.mp3",
		id =  53358,
		duration = 75,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Blade's Edge Ogre Walking 2",
		path = "sound\\music\\zonemusic\\bladesedge\\bl_ogrewalkuni02.mp3",
		id =  53359,
		duration = 110,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Blade's Edge Ogre Walking 3",
		path = "sound\\music\\zonemusic\\hellfirepeninsula\\bl_he_ogrewalkuni01.mp3",
		id =  53520,
		duration = 75,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Blade's Edge Ogre Walking 4",
		path = "sound\\music\\zonemusic\\hellfirepeninsula\\bl_he_ogrewalkuni02.mp3",
		id =  53521,
		duration = 110,
		artist = "Matt Uelmen",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Bloodmyst Naga Intro 2",
		path = "sound\\music\\zonemusic\\bloodmyst\\bi_nagaintro01.mp3",
		id =  53360,
		duration = 31,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Bloodmyst Naga Intro 1",
		path = "sound\\music\\zonemusic\\bloodmyst\\bi_nagaintro01r.mp3",
		id =  53361,
		duration = 25,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Bloodmyst Satyr 1",
		path = "sound\\music\\zonemusic\\bloodmyst\\bi_satyrwalkuni01r.mp3",
		id =  53362,
		duration = 126,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Bloodmyst Satyr 2",
		path = "sound\\music\\zonemusic\\bloodmyst\\bi_satyrwalkuni02.mp3",
		id =  53363,
		duration = 129,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Bloodmyst Satyr 3",
		path = "sound\\music\\zonemusic\\bloodmyst\\bi_satyrwalkuni03.mp3",
		id =  53364,
		duration = 114,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Bloodmyst Satyr 4",
		path = "sound\\music\\zonemusic\\bloodmyst\\bi_satyrwalkuni04.mp3",
		id =  53365,
		duration = 69,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Bloodmyst Satyr 5",
		path = "sound\\music\\zonemusic\\bloodmyst\\bi_satyrwalkuni05.mp3",
		id =  53366,
		duration = 143,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Corrupt 1",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_corrupt01.mp3",
		id =  53649,
		duration = 60,
		artist = "Brian David Farr",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Corrupt 2",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_corrupt02.mp3",
		id =  53650,
		duration = 62,
		artist = "Brian David Farr",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Corrupt 3",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_corrupt03.mp3",
		id =  53651,
		duration = 74,
		artist = "Brian David Farr",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Corrupt 4",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_corrupt04.mp3",
		id =  53652,
		duration = 71,
		artist = "Brian David Farr",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Corrupt 5",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_corrupt05.mp3",
		id =  53653,
		duration = 72,
		artist = "Brian David Farr",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Corrupt 6",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_corrupt06.mp3",
		id =  53654,
		duration = 74,
		artist = "Brian David Farr",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Corrupt 7",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_corrupt07.mp3",
		id =  53655,
		duration = 52,
		artist = "Brian David Farr",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Corrupt Intro",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_corruptintro.mp3",
		id =  53656,
		duration = 75,
		artist = "Brian David Farr",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Black Morass Portal Intro",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_morassportalintro01.mp3",
		id =  53416,
		duration = 28,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Black Morass Walk Uni P",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_morasswalkuni01.mp3",
		id =  53417,
		duration = 108,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Black Morass Walk Uni Q",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_morasswalkuni02.mp3",
		id =  53418,
		duration = 79,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Black Morass Walk Uni R",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_morasswalkuni03.mp3",
		id =  53419,
		duration = 114,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Black Morass Walk Uni S",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_morasswalkuni04.mp3",
		id =  53420,
		duration = 123,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Black Morass Walk Uni V",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_morasswalkuni05.mp3",
		id =  53421,
		duration = 73,
		artist = "Derek Duke",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Brazens Flight Intro ",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_brazensflightintrouni.mp3",
		id =  53379,
		duration = 93,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Caverns Walk 1",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_cavernswalk1uni.mp3",
		id =  53380,
		duration = 112,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Caverns Walk 2",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_cavernswalk2uni.mp3",
		id =  53381,
		duration = 120,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Caverns Walk 3",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_cavernswalk3uni.mp3",
		id =  53382,
		duration = 168,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Caverns Walk 4",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_cavernswalk4uni.mp3",
		id =  53383,
		duration = 130,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Caverns Walk 5",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_cavernswalk5uni.mp3",
		id =  53384,
		duration = 151,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Caverns Walk 6",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_cavernswalk6uni.mp3",
		id =  53385,
		duration = 161,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Caverns Walk 7",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_cavernswalk7uni.mp3",
		id =  53386,
		duration = 178,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Caverns Walk 8",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_cavernswalk8uni.mp3",
		id =  53387,
		duration = 139,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Caverns Walk 9",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_cavernswalk9uni.mp3",
		id =  53388,
		duration = 161,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Durnholde Cellar Walk 1",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_durnholdecellarwalk1uni.mp3",
		id =  53389,
		duration = 103,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Durnholde Cellar Walk 2",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_durnholdecellarwalk2uni.mp3",
		id =  53390,
		duration = 59,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Durnholde Cellar Walk 3",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_durnholdecellarwalk3uni.mp3",
		id =  53391,
		duration = 66,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Durnholde Keep Ext Walk 1",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_durnholdekeepextwalk1uni.mp3",
		id =  53392,
		duration = 81,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Durnholde Keep Ext Walk 2",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_durnholdekeepextwalk2uni.mp3",
		id =  53393,
		duration = 66,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Durnholde Keep Ext Walk 3",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_durnholdekeepextwalk3uni.mp3",
		id =  53394,
		duration = 70,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Durnholde Keep Ext Walk 4",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_durnholdekeepextwalk4uni.mp3",
		id =  53395,
		duration = 58,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Durnholde Keep Ext Walk 5",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_durnholdekeepextwalk5uni.mp3",
		id =  53396,
		duration = 93,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Durnholde Keep Ext Walk 6",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_durnholdekeepextwalk6uni.mp3",
		id =  53397,
		duration = 60,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Durnholde Keep Int Walk 1",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_durnholdekeepintwalk1uni.mp3",
		id =  53398,
		duration = 69,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Durnholde Keep Int Walk 2",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_durnholdekeepintwalk2uni.mp3",
		id =  53399,
		duration = 122,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Durnholde Keep Int Walk 3",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_durnholdekeepintwalk3uni.mp3",
		id =  53400,
		duration = 73,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Escape Durnholde Intro",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_escapedurnintrouni.mp3",
		id =  53401,
		duration = 112,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Hillsbrad Ext Walk 1",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_hillsbradextwalk1uni.mp3",
		id =  53402,
		duration = 61,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Hillsbrad Ext Walk 2",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_hillsbradextwalk2uni.mp3",
		id =  53403,
		duration = 56,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Hyjal Ext Walk 7",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_hyjalextwalk7uni.mp3",
		id =  53404,
		duration = 66,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Hyjal Ext Walk 8",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_hyjalextwalk8uni.mp3",
		id =  53405,
		duration = 70,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Hyjal Ext Walk 9",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_hyjalextwalk9uni.mp3",
		id =  53406,
		duration = 73,
		artist = "Derek Duke, Jason Hayes",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Hyjal Ext Walk 1",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_hyjalextwalkuni01.mp3",
		id =  53407,
		duration = 69,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Hyjal Ext Walk 2",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_hyjalextwalkuni02.mp3",
		id =  53408,
		duration = 48,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Hyjal Ext Walk 3",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_hyjalextwalkuni03.mp3",
		id =  53409,
		duration = 45,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Hyjal Ext Walk 4",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_hyjalextwalkuni04.mp3",
		id =  53410,
		duration = 85,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Hyjal Ext Walk 5",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_hyjalextwalkuni05.mp3",
		id =  53411,
		duration = 47,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Hyjal Ext Walk 6",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_hyjalextwalkuni06.mp3",
		id =  53412,
		duration = 46,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Hyjal Ext Walk 10",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_hyjalextwalkuni10.mp3",
		id =  53413,
		duration = 66,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Hyjal Ext Walk 11",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_hyjalextwalkuni11.mp3",
		id =  53414,
		duration = 49,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Hyjal Ext Walk 12",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_hyjalextwalkuni12.mp3",
		id =  53415,
		duration = 67,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Tarren Mill Ext Walk 1",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_tarrenmillextwalk1uni.mp3",
		id =  53422,
		duration = 78,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Tarren Mill Ext Walk 2",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_tarrenmillextwalk2uni.mp3",
		id =  53423,
		duration = 65,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Tarren Mill Ext Walk 3",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_tarrenmillextwalk3uni.mp3",
		id =  53424,
		duration = 62,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "CT Thrall Escape Intro",
		path = "sound\\music\\zonemusic\\cavernsoftime\\ct_thrallescapeintrouni.mp3",
		id =  53425,
		duration = 45,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Dwarves Tavern 1A",
		path = "sound\\music\\zonemusic\\taverndwarf\\ra_dwarftavern1a.mp3",
		id =  53739,
		duration = 79,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Dwarves Tavern 1B",
		path = "sound\\music\\zonemusic\\taverndwarf\\ra_dwarftavern1b.mp3",
		id =  53740,
		duration = 82,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Dwarves Tavern 2A",
		path = "sound\\music\\zonemusic\\taverndwarf\\ra_dwarftavern2a.mp3",
		id =  53741,
		duration = 86,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Dwarves Tavern 2B",
		path = "sound\\music\\zonemusic\\taverndwarf\\ra_dwarftavern2b.mp3",
		id =  53742,
		duration = 91,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Dwarves Tavern 3",
		path = "sound\\music\\zonemusic\\taverndwarf\\ra_dwarftavern3.mp3",
		id =  53743,
		duration = 102,
		artist = "David Arkenstone",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong 2A",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_eversongdarkwalkuni01.mp3",
		id =  53499,
		duration = 62,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong 2B",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_eversongdarkwalkuni02.mp3",
		id =  53500,
		duration = 62,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong 2C",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_eversongdarkwalkuni03.mp3",
		id =  53501,
		duration = 63,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong 2D",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_eversongdarkwalkuni04.mp3",
		id =  53502,
		duration = 60,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Building Day 01",
		path = "sound\\music\\zonemusic\\eversong\\es_buildingwalkday01.mp3",
		id =  53458,
		duration = 65,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Building Day 02",
		path = "sound\\music\\zonemusic\\eversong\\es_buildingwalkday02.mp3",
		id =  53459,
		duration = 68,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Building Night 01",
		path = "sound\\music\\zonemusic\\eversong\\es_buildingwalknight01.mp3",
		id =  53460,
		duration = 84,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Building Night 02",
		path = "sound\\music\\zonemusic\\eversong\\es_buildingwalknight02.mp3",
		id =  53461,
		duration = 83,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Ruins Day 01",
		path = "sound\\music\\zonemusic\\eversong\\es_ruinswalkday01.mp3",
		id =  53462,
		duration = 48,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Ruins Day 02",
		path = "sound\\music\\zonemusic\\eversong\\es_ruinswalkday02.mp3",
		id =  53463,
		duration = 71,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Ruins Day 03",
		path = "sound\\music\\zonemusic\\eversong\\es_ruinswalkday03.mp3",
		id =  53464,
		duration = 70,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Ruins Night 01",
		path = "sound\\music\\zonemusic\\eversong\\es_ruinswalknight01.mp3",
		id =  53465,
		duration = 50,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Ruins Night 02",
		path = "sound\\music\\zonemusic\\eversong\\es_ruinswalknight02.mp3",
		id =  53466,
		duration = 83,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Ruins Night 03",
		path = "sound\\music\\zonemusic\\eversong\\es_ruinswalknight03.mp3",
		id =  53467,
		duration = 67,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Scenic Intro Night 01",
		path = "sound\\music\\zonemusic\\eversong\\es_scenicintronight01.mp3",
		id =  53468,
		duration = 97,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Scortched Day 01",
		path = "sound\\music\\zonemusic\\eversong\\es_scortchedwalkday01.mp3",
		id =  53469,
		duration = 116,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Scortched Day 02",
		path = "sound\\music\\zonemusic\\eversong\\es_scortchedwalkday02.mp3",
		id =  53470,
		duration = 102,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Scortched Night 01",
		path = "sound\\music\\zonemusic\\eversong\\es_scortchedwalknight01.mp3",
		id =  53471,
		duration = 69,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Scortched Night 02",
		path = "sound\\music\\zonemusic\\eversong\\es_scortchedwalknight02.mp3",
		id =  53472,
		duration = 61,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Silvermoon Intro 01",
		path = "sound\\music\\zonemusic\\eversong\\es_silvermoonintro01.mp3",
		id =  53473,
		duration = 132,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Silvermoon Day 01",
		path = "sound\\music\\zonemusic\\eversong\\es_silvermoonwalkday01.mp3",
		id =  53474,
		duration = 64,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Silvermoon Day 02",
		path = "sound\\music\\zonemusic\\eversong\\es_silvermoonwalkday02.mp3",
		id =  53475,
		duration = 79,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Silvermoon Day 03",
		path = "sound\\music\\zonemusic\\eversong\\es_silvermoonwalkday03.mp3",
		id =  53476,
		duration = 64,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Silvermoon Night 01",
		path = "sound\\music\\zonemusic\\eversong\\es_silvermoonwalknight01.mp3",
		id =  53477,
		duration = 177,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Silvermoon Night 02",
		path = "sound\\music\\zonemusic\\eversong\\es_silvermoonwalknight02.mp3",
		id =  53478,
		duration = 71,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Silvermoon Night 03",
		path = "sound\\music\\zonemusic\\eversong\\es_silvermoonwalknight03.mp3",
		id =  53479,
		duration = 80,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Sunstrider Day 01",
		path = "sound\\music\\zonemusic\\eversong\\es_sunstriderwalkday01.mp3",
		id =  53480,
		duration = 80,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Sunstrider Day 02",
		path = "sound\\music\\zonemusic\\eversong\\es_sunstriderwalkday02.mp3",
		id =  53481,
		duration = 58,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Sunstrider Day 03",
		path = "sound\\music\\zonemusic\\eversong\\es_sunstriderwalkday03.mp3",
		id =  53482,
		duration = 67,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Sunstrider Night 01",
		path = "sound\\music\\zonemusic\\eversong\\es_sunstriderwalknight01.mp3",
		id =  53483,
		duration = 100,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Sunstrider Night 02",
		path = "sound\\music\\zonemusic\\eversong\\es_sunstriderwalknight02.mp3",
		id =  53484,
		duration = 100,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Eversong Sunstrider Night 03",
		path = "sound\\music\\zonemusic\\eversong\\es_sunstriderwalknight03.mp3",
		id =  53485,
		duration = 86,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Fire Festival (Alliance)",
		path = "sound\\music\\worldevents\\alliancefirepole.mp3",
		id =  53255,
		duration = 68,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Fire Festival (Horde)",
		path = "sound\\music\\worldevents\\hordefirepole.mp3",
		id =  53260,
		duration = 72,
		artist = "David Arkenstone",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Ghostlands Forest 1 Walk Day 01",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_forest1walkday01.mp3",
		id =  53503,
		duration = 66,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Ghostlands Forest 1 Walk Day 02",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_forest1walkday02.mp3",
		id =  53504,
		duration = 70,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Ghostlands Forest 1 Walk Night 01",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_forest1walknight01.mp3",
		id =  53505,
		duration = 67,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Ghostlands Forest 2 Walk Day 01",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_forest2walkday01.mp3",
		id =  53506,
		duration = 83,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Ghostlands Forest 2 Walk Night 01",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_forest2walknight01.mp3",
		id =  53507,
		duration = 59,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Ghostlands Forest 2 Walk Night 02",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_forest2walknight02.mp3",
		id =  53508,
		duration = 60,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Ghostlands Forest 3 Walk Day 01",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_forest3walkday01.mp3",
		id =  53509,
		duration = 154,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Ghostlands Forest 3 Walk Night 01",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_forest3walknight01.mp3",
		id =  53510,
		duration = 51,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Ghostlands Forest 3 Walk Night 02",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_forest3walknight02.mp3",
		id =  53511,
		duration = 28,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Ghostlands Forest 3 Walk Night 03",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_forest3walknight03.mp3",
		id =  53512,
		duration = 44,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Ghostlands Scenic Walk 01",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_scenicwalkuni01.mp3",
		id =  53513,
		duration = 89,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Ghostlands Scenic Walk 02",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_scenicwalkuni02.mp3",
		id =  53514,
		duration = 81,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Ghostlands Scenic Walk 03",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_scenicwalkuni03.mp3",
		id =  53515,
		duration = 78,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Hellfire Citadel Demon Wing 1",
		path = "sound\\music\\zonemusic\\hellfirepeninsula\\he_citadeldemonwalkuni01.mp3",
		id =  53523,
		duration = 53,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Hellfire Citadel Demon Wing 2",
		path = "sound\\music\\zonemusic\\hellfirepeninsula\\he_citadeldemonwalkuni02.mp3",
		id =  53524,
		duration = 63,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Hellfire Citadel Outland Moment",
		path = "sound\\music\\zonemusic\\hellfirepeninsula\\he_citadelintrouni01.mp3",
		id =  53525,
		duration = 19,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Hellfire Peninsula Walking 1",
		path = "sound\\music\\zonemusic\\hellfirepeninsula\\he_generalwalkuni01.mp3",
		id =  53526,
		duration = 130,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Hellfire Peninsula Walking 2",
		path = "sound\\music\\zonemusic\\hellfirepeninsula\\he_generalwalkuni02.mp3",
		id =  53527,
		duration = 66,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Hellfire Peninsula Walking 3",
		path = "sound\\music\\zonemusic\\hellfirepeninsula\\he_generalwalkuni03.mp3",
		id =  53528,
		duration = 59,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Hellfire Peninsula Walking 4",
		path = "sound\\music\\zonemusic\\hellfirepeninsula\\he_generalwalkuni04.mp3",
		id =  53529,
		duration = 96,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Hellfire Peninsula Walking 5",
		path = "sound\\music\\zonemusic\\hellfirepeninsula\\he_generalwalkuni05.mp3",
		id =  53530,
		duration = 126,
		artist = "Matt Uelmen",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Hellfire Ramparts Walking 1",
		path = "sound\\music\\zonemusic\\hellfirepeninsula\\he_rampartswalkuni01.mp3",
		id =  53532,
		duration = 62,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Hellfire Ramparts Walking 2",
		path = "sound\\music\\zonemusic\\hellfirepeninsula\\he_rampartswalkuni02.mp3",
		id =  53533,
		duration = 69,
		artist = "Matt Uelmen",
	},		
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Human Tavern 1A",
		path = "sound\\music\\zonemusic\\tavernhuman\\ra_humantavern1a.mp3",
		id =  53748,
		duration = 92,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Human Tavern 1B",
		path = "sound\\music\\zonemusic\\tavernhuman\\ra_humantavern1b.mp3",
		id =  53749,
		duration = 79,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Human Tavern 2A",
		path = "sound\\music\\zonemusic\\tavernhuman\\ra_humantavern2a.mp3",
		id =  53750,
		duration = 86,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Human Tavern 2B",
		path = "sound\\music\\zonemusic\\tavernhuman\\ra_humantavern2b.mp3",
		id =  53751,
		duration = 81,
		artist = "David Arkenstone",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Backstage Walk 01",
		path = "sound\\music\\zonemusic\\karazhan\\ka_backstagewalkuni01.mp3",
		id =  53547,
		duration = 98,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Backstage Walk 02",
		path = "sound\\music\\zonemusic\\karazhan\\ka_backstagewalkuni02.mp3",
		id =  53548,
		duration = 98,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Foyer Intro",
		path = "sound\\music\\zonemusic\\karazhan\\ka_foyerintrouni01.mp3",
		id =  53549,
		duration = 117,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Foyer Walk 01",
		path = "sound\\music\\zonemusic\\karazhan\\ka_foyerwalkuni01.mp3",
		id =  53550,
		duration = 113,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Foyer Walk 02",
		path = "sound\\music\\zonemusic\\karazhan\\ka_foyerwalkuni02.mp3",
		id =  53551,
		duration = 112,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Foyer Walk 03",
		path = "sound\\music\\zonemusic\\karazhan\\ka_foyerwalkuni03.mp3",
		id =  53552,
		duration = 124,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Foyer Walk 04",
		path = "sound\\music\\zonemusic\\karazhan\\ka_foyerwalkuni04.mp3",
		id =  53553,
		duration = 31,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan General Walk 01",
		path = "sound\\music\\zonemusic\\karazhan\\ka_generalwalkuni01.mp3",
		id =  53554,
		duration = 130,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan General Walk 02",
		path = "sound\\music\\zonemusic\\karazhan\\ka_generalwalkuni02.mp3",
		id =  53555,
		duration = 123,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan General Walk 03",
		path = "sound\\music\\zonemusic\\karazhan\\ka_generalwalkuni03.mp3",
		id =  53556,
		duration = 118,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan General Walk 04",
		path = "sound\\music\\zonemusic\\karazhan\\ka_generalwalkuni04.mp3",
		id =  53557,
		duration = 112,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan General Walk 05",
		path = "sound\\music\\zonemusic\\karazhan\\ka_generalwalkuni05.mp3",
		id =  53558,
		duration = 124,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan General Walk 06",
		path = "sound\\music\\zonemusic\\karazhan\\ka_generalwalkuni06.mp3",
		id =  53559,
		duration = 92,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan General Walk 07",
		path = "sound\\music\\zonemusic\\karazhan\\ka_generalwalkuni07.mp3",
		id =  53560,
		duration = 81,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Library Walk 01",
		path = "sound\\music\\zonemusic\\karazhan\\ka_librarywalkuni01.mp3",
		id =  53561,
		duration = 127,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Library Walk 02",
		path = "sound\\music\\zonemusic\\karazhan\\ka_librarywalkuni02.mp3",
		id =  53562,
		duration = 147,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Library Walk 03",
		path = "sound\\music\\zonemusic\\karazhan\\ka_librarywalkuni03.mp3",
		id =  53563,
		duration = 126,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Library Walk 04",
		path = "sound\\music\\zonemusic\\karazhan\\ka_librarywalkuni04.mp3",
		id =  53564,
		duration = 123,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Malchezar Walk 1",
		path = "sound\\music\\zonemusic\\karazhan\\ka_malchezarwalkuni01.mp3",
		id =  53565,
		duration = 124,
		artist = "Brian David Farr & Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Malchezar Walk 2",
		path = "sound\\music\\zonemusic\\karazhan\\ka_malchezarwalkuni02.mp3",
		id =  53566,
		duration = 111,
		artist = "Brian David Farr & Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Malchezar Walk 03",
		path = "sound\\music\\zonemusic\\karazhan\\ka_malchezarwalkuni03.mp3",
		id =  53567,
		duration = 114,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Opera Harpsi Walk 01",
		path = "sound\\music\\zonemusic\\karazhan\\ka_operaharpsiwalkuni01.mp3",
		id =  53568,
		duration = 82,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Opera Organ Walk 01",
		path = "sound\\music\\zonemusic\\karazhan\\ka_operaorganwalkuni01.mp3",
		id =  53569,
		duration = 80,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Stable Intro",
		path = "sound\\music\\zonemusic\\karazhan\\ka_stableintrouni01.mp3",
		id =  53570,
		duration = 53,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Stable Walk 01",
		path = "sound\\music\\zonemusic\\karazhan\\ka_stablewalkuni01.mp3",
		id =  53571,
		duration = 95,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Stable Walk 02",
		path = "sound\\music\\zonemusic\\karazhan\\ka_stablewalkuni02.mp3",
		id =  53572,
		duration = 111,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Stable Walk 03",
		path = "sound\\music\\zonemusic\\karazhan\\ka_stablewalkuni03.mp3",
		id =  53573,
		duration = 114,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Tower Walk 01",
		path = "sound\\music\\zonemusic\\karazhan\\ka_towerwalkuni01.mp3",
		id =  53574,
		duration = 93,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Tower Walk 02",
		path = "sound\\music\\zonemusic\\karazhan\\ka_towerwalkuni02.mp3",
		id =  53575,
		duration = 115,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Karazhan Tower Walk 03",
		path = "sound\\music\\zonemusic\\karazhan\\ka_towerwalkuni03.mp3",
		id =  53576,
		duration = 127,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Lament of the Highborne",
		path = "sound\\music\\gluescreenmusic\\bccredits_lament_of_the_highborne.mp3",
		id =  53221,
		duration = 171,
		artist = "Russell Brower & Derek Duke",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Nagrand Day 1",
		path = "sound\\music\\zonemusic\\nagrand\\na_generalwalkday01.mp3",
		id =  53585,
		duration = 72,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Nagrand Day 2",
		path = "sound\\music\\zonemusic\\nagrand\\na_generalwalkday02.mp3",
		id =  53586,
		duration = 100,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Nagrand Day 3",
		path = "sound\\music\\zonemusic\\nagrand\\na_generalwalkday03.mp3",
		id =  53587,
		duration = 63,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Nagrand Night 1",
		path = "sound\\music\\zonemusic\\nagrand\\na_generalwalknight01.mp3",
		id =  53588,
		duration = 87,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Nagrand Night 2",
		path = "sound\\music\\zonemusic\\nagrand\\na_generalwalknight02.mp3",
		id =  53589,
		duration = 80,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Nagrand Night 3",
		path = "sound\\music\\zonemusic\\nagrand\\na_generalwalknight03.mp3",
		id =  53590,
		duration = 166,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Netherstorm Walking 1",
		path = "sound\\music\\zonemusic\\netherstorm\\ns_generalwalkuni01.mp3",
		id =  53620,
		duration = 150,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Netherstorm Walking 2",
		path = "sound\\music\\zonemusic\\netherstorm\\ns_generalwalkuni02.mp3",
		id =  53621,
		duration = 175,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Netherstorm Walking 3",
		path = "sound\\music\\zonemusic\\netherstorm\\ns_generalwalkuni03.mp3",
		id =  53622,
		duration = 178,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Netherstorm Walking 4",
		path = "sound\\music\\zonemusic\\netherstorm\\ns_generalwalkuni04.mp3",
		id =  53623,
		duration = 181,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Netherstorm Walking 5",
		path = "sound\\music\\zonemusic\\netherstorm\\ns_generalwalkuni05.mp3",
		id =  53624,
		duration = 184,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Netherstorm Walking 6",
		path = "sound\\music\\zonemusic\\netherstorm\\ns_generalwalkuni06.mp3",
		id =  53625,
		duration = 192,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Netherstorm Walking 7",
		path = "sound\\music\\zonemusic\\netherstorm\\ns_generalwalkuni07.mp3",
		id =  53626,
		duration = 193,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Netherstorm Walking 8",
		path = "sound\\music\\zonemusic\\netherstorm\\ns_generalwalkuni08.mp3",
		id =  53627,
		duration = 168,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Netherstorm Walking 9",
		path = "sound\\music\\zonemusic\\netherstorm\\ns_generalwalkuni09.mp3",
		id =  53628,
		duration = 199,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Netherstorm Walking 10",
		path = "sound\\music\\zonemusic\\netherstorm\\ns_generalwalkuni10.mp3",
		id =  53629,
		duration = 222,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Orc Rest Area 1A",
		path = "sound\\music\\zonemusic\\tavernorc\\ra_orcrestarea1a.mp3",
		id =  53756,
		duration = 99,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Orc Rest Area 1B",
		path = "sound\\music\\zonemusic\\tavernorc\\ra_orcrestarea1b.mp3",
		id =  53757,
		duration = 91,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Orc Rest Area 2A",
		path = "sound\\music\\zonemusic\\tavernorc\\ra_orcrestarea2a.mp3",
		id =  53758,
		duration = 87,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Orc Rest Area 2B",
		path = "sound\\music\\zonemusic\\tavernorc\\ra_orcrestarea2b.mp3",
		id =  53759,
		duration = 86,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Orc Rest Area 3A",
		path = "sound\\music\\zonemusic\\tavernorc\\ra_orcrestarea3a.mp3",
		id =  53760,
		duration = 85,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Orc Rest Area 3B",
		path = "sound\\music\\zonemusic\\tavernorc\\ra_orcrestarea3b.mp3",
		id =  53761,
		duration = 81,
		artist = "David Arkenstone",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Armoury",
		path = "sound\\music\\zonemusic\\hellfirepeninsula\\he_armouryintrouni01.mp3",
		id =  53522,
		duration = 14,
		artist = "Matt Uelmen",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Cenarion 1",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_cenarionintrouni01.mp3",
		id =  53646,
		duration = 44,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Cenarion 2",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_cenarionintrouni02.mp3",
		id =  53647,
		duration = 45,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Cenarion 3",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_cenarionintrouni03.mp3",
		id =  53648,
		duration = 71,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Crystal 1",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_crystalintrouni01.mp3",
		id =  53657,
		duration = 26,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Crystal 2",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_crystalintrouni02.mp3",
		id =  53658,
		duration = 21,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Crystal 3",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_crystalintrouni03.mp3",
		id =  53659,
		duration = 21,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Demons",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_demonintrouni01.mp3",
		id =  53660,
		duration = 46,
		artist = "Matt Uelmen",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Diamond Mountain",
		path = "sound\\music\\zonemusic\\nagrand\\na_diamondintrouni01.mp3",
		id =  53584,
		duration = 73,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Fel Orc 1",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_felorcintrouni01.mp3",
		id =  53663,
		duration = 16,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Fel Orc 2",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_felorcintrouni02.mp3",
		id =  53664,
		duration = 14,
		artist = "Matt Uelmen",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Historic",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_historicintrouni01.mp3",
		id =  53665,
		duration = 79,
		artist = "Matt Uelmen",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Horde Base 1",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_hordebasewalkuni01.mp3",
		id =  53666,
		duration = 40,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Horde Base 2",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_hordebasewalkuni02.mp3",
		id =  53667,
		duration = 37,
		artist = "Matt Uelmen",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Illidan's Army",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_illidansarmyintrouni01.mp3",
		id =  53670,
		duration = 35,
		artist = "Matt Uelmen",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Legion 1",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_burninglegionintrouni01.mp3",
		id =  53644,
		duration = 16,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Legion 2",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_burninglegionintrouni02.mp3",
		id =  53645,
		duration = 35,
		artist = "Matt Uelmen",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Mushroom 1",
		path = "sound\\music\\zonemusic\\netherstorm\\ns_mushroomintrouni01.mp3",
		id =  53630,
		duration = 39,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Mushroom 2",
		path = "sound\\music\\zonemusic\\netherstorm\\ns_mushroomintrouni02.mp3",
		id =  53631,
		duration = 33,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Mushroom 3",
		path = "sound\\music\\zonemusic\\netherstorm\\ns_mushroomintrouni03.mp3",
		id =  53632,
		duration = 36,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Nature",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_scenicintrouni01.mp3",
		id =  53677,
		duration = 31,
		artist = "Matt Uelmen",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Nether Plant 1",
		path = "sound\\music\\zonemusic\\netherstorm\\ns_netherplantintrouni01.mp3",
		id =  53633,
		duration = 44,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Nether Plant 2",
		path = "sound\\music\\zonemusic\\netherstorm\\ns_netherplantintrouni02.mp3",
		id =  53634,
		duration = 51,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Nether Plant 3",
		path = "sound\\music\\zonemusic\\netherstorm\\ns_netherplantintrouni03.mp3",
		id =  53635,
		duration = 47,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Nether Plant 4",
		path = "sound\\music\\zonemusic\\netherstorm\\ns_netherplantintrouni04.mp3",
		id =  53636,
		duration = 45,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Ogre 1",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_ogreintrouni01.mp3",
		id =  53671,
		duration = 28,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Ogre 2",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_ogreintrouni02.mp3",
		id =  53672,
		duration = 25,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Orc 1",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_orcintrouni01.mp3",
		id =  53673,
		duration = 11,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Orc 2",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_orcintrouni02.mp3",
		id =  53674,
		duration = 17,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Orc 3",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_orcintrouni03.mp3",
		id =  53675,
		duration = 11,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Orc 4",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_orcintrouni04.mp3",
		id =  53676,
		duration = 13,
		artist = "Matt Uelmen",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Path Of Glory",
		path = "sound\\music\\zonemusic\\hellfirepeninsula\\he_pathofgloryintrouni01.mp3",
		id =  53531,
		duration = 17,
		artist = "Matt Uelmen",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Shaman 1",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_shamanintrouni01.mp3",
		id =  53678,
		duration = 44,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Shaman 2",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_shamanintrouni02.mp3",
		id =  53679,
		duration = 53,
		artist = "Matt Uelmen",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Stairs Of Destiny",
		path = "sound\\music\\zonemusic\\hellfirepeninsula\\he_stairsintrouni01.mp3",
		id =  53534,
		duration = 18,
		artist = "Matt Uelmen",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Wistful 1",
		path = "sound\\music\\zonemusic\\hellfirepeninsula\\he_wistfulintrouni01.mp3",
		id =  53535,
		duration = 25,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Moment Wistful 2",
		path = "sound\\music\\zonemusic\\hellfirepeninsula\\he_wistfulintrouni02.mp3",
		id =  53536,
		duration = 17,
		artist = "Matt Uelmen",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Draenei Base Walk 1",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_draeneibasewalkuni01.mp3",
		id =  53661,
		duration = 106,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Draenei Base Walk 2",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_draeneibasewalkuni02r.mp3",
		id =  53662,
		duration = 99,
		artist = "Derek Duke",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Horde Base 1",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_hordebasewalkuni03.mp3",
		id =  53668,
		duration = 66,
		artist = "Russell Brower & Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Outland Horde Base 2",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_hordebasewalkuni04.mp3",
		id =  53669,
		duration = 68,
		artist = "Russell Brower & Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Pirate Tavern 1A",
		path = "sound\\music\\zonemusic\\tavernpirate\\ra_piratetavern1a.mp3",
		id =  53762,
		duration = 82,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Pirate Tavern 1B",
		path = "sound\\music\\zonemusic\\tavernpirate\\ra_piratetavern1b.mp3",
		id =  53763,
		duration = 81,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Pirate Tavern 2A",
		path = "sound\\music\\zonemusic\\tavernpirate\\ra_piratetavern2a.mp3",
		id =  53764,
		duration = 82,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Pirate Tavern 2B",
		path = "sound\\music\\zonemusic\\tavernpirate\\ra_piratetavern2b.mp3",
		id =  53765,
		duration = 81,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Pirate Tavern 3A",
		path = "sound\\music\\zonemusic\\tavernpirate\\ra_piratetavern3a.mp3",
		id =  53766,
		duration = 88,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Pirate Tavern 3B",
		path = "sound\\music\\zonemusic\\tavernpirate\\ra_piratetavern3b.mp3",
		id =  53767,
		duration = 85,
		artist = "David Arkenstone",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Shadowmoon Valley Walking 1",
		path = "sound\\music\\zonemusic\\shadowmoonvalley\\sv_generalwalkuni01.mp3",
		id =  53689,
		duration = 67,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Shadowmoon Valley Walking 2",
		path = "sound\\music\\zonemusic\\shadowmoonvalley\\sv_generalwalkuni02.mp3",
		id =  53690,
		duration = 112,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Shadowmoon Valley Walking 3",
		path = "sound\\music\\zonemusic\\shadowmoonvalley\\sv_generalwalkuni03.mp3",
		id =  53691,
		duration = 106,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Shadowmoon Valley Walking 4",
		path = "sound\\music\\zonemusic\\shadowmoonvalley\\sv_generalwalkuni04.mp3",
		id =  53692,
		duration = 93,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Shadowmoon Valley Walking 5",
		path = "sound\\music\\zonemusic\\shadowmoonvalley\\sv_generalwalkuni05.mp3",
		id =  53693,
		duration = 93,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Shadowmoon Valley Walking 6",
		path = "sound\\music\\zonemusic\\shadowmoonvalley\\sv_generalwalkuni06.mp3",
		id =  53694,
		duration = 67,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Shalandis Isle 1",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_shalandiswalkuni01.mp3",
		id =  53516,
		duration = 131,
		artist = "David Arkenstone & Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Shalandis Isle 2",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_shalandiswalkuni02.mp3",
		id =  53517,
		duration = 103,
		artist = "David Arkenstone & Russell Brower",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Shalandis Isle 3",
		path = "sound\\music\\zonemusic\\ghostlands\\gl_shalandiswalkuni03.mp3",
		id =  53518,
		duration = 67,
		artist = "Jason Hayes & Russell Brower",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Shattrath Walking 1",
		path = "sound\\music\\zonemusic\\terokkar\\tf_shattrathwalkuni01.mp3",
		id =  53806,
		duration = 137,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Shattrath Walking 2",
		path = "sound\\music\\zonemusic\\terokkar\\tf_shattrathwalkuni02.mp3",
		id =  53807,
		duration = 100,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Shattrath Walking 3",
		path = "sound\\music\\zonemusic\\terokkar\\tf_shattrathwalkuni03.mp3",
		id =  53808,
		duration = 92,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Shattrath Walking 4",
		path = "sound\\music\\zonemusic\\terokkar\\tf_shattrathwalkuni04.mp3",
		id =  53809,
		duration = 81,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Shattrath Walking 5",
		path = "sound\\music\\zonemusic\\terokkar\\tf_shattrathwalkuni05.mp3",
		id =  53810,
		duration = 117,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Shattrath Walking 6",
		path = "sound\\music\\zonemusic\\terokkar\\tf_shattrathwalkuni06.mp3",
		id =  53811,
		duration = 137,
		artist = "Matt Uelmen",
	},		
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tauren Rest Area 1A",
		path = "sound\\music\\zonemusic\\taverntauren\\ra_taurenrestarea1a.mp3",
		id =  53768,
		duration = 89,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tauren Rest Area 1B",
		path = "sound\\music\\zonemusic\\taverntauren\\ra_taurenrestarea1b.mp3",
		id =  53769,
		duration = 96,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tauren Rest Area 2A",
		path = "sound\\music\\zonemusic\\taverntauren\\ra_taurenrestarea2a.mp3",
		id =  53770,
		duration = 85,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tauren Rest Area 2B",
		path = "sound\\music\\zonemusic\\taverntauren\\ra_taurenrestarea2b.mp3",
		id =  53771,
		duration = 80,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tauren Rest Area 3A",
		path = "sound\\music\\zonemusic\\taverntauren\\ra_taurenrestarea3a.mp3",
		id =  53772,
		duration = 93,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tauren Rest Area 3B",
		path = "sound\\music\\zonemusic\\taverntauren\\ra_taurenrestarea3b.mp3",
		id =  53773,
		duration = 93,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tempest Keep Ambient 11",
		path = "sound\\music\\zonemusic\\tempestkeep\\tk_tempestkeep_amb_11.mp3",
		id =  53779,
		duration = 46,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tempest Keep Ambient 12",
		path = "sound\\music\\zonemusic\\tempestkeep\\tk_tempestkeep_amb_12.mp3",
		id =  53780,
		duration = 96,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tempest Keep Ambient 13",
		path = "sound\\music\\zonemusic\\tempestkeep\\tk_tempestkeep_amb_13.mp3",
		id =  53781,
		duration = 67,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tempest Keep Ambient 14",
		path = "sound\\music\\zonemusic\\tempestkeep\\tk_tempestkeep_amb_14.mp3",
		id =  53782,
		duration = 88,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tempest Keep Ambient 16",
		path = "sound\\music\\zonemusic\\tempestkeep\\tk_tempestkeep_amb_16.mp3",
		id =  53783,
		duration = 58,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tempest Keep Ambient 17",
		path = "sound\\music\\zonemusic\\tempestkeep\\tk_tempestkeep_amb_17.mp3",
		id =  53784,
		duration = 62,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tempest Keep Ambient 18",
		path = "sound\\music\\zonemusic\\tempestkeep\\tk_tempestkeep_amb_18.mp3",
		id =  53785,
		duration = 85,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tempest Keep Ambient 19",
		path = "sound\\music\\zonemusic\\tempestkeep\\tk_tempestkeep_amb_19.mp3",
		id =  53786,
		duration = 48,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tempest Keep Ambient 20",
		path = "sound\\music\\zonemusic\\tempestkeep\\tk_tempestkeep_amb_20.mp3",
		id =  53787,
		duration = 47,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tempest Keep Ambient 22",
		path = "sound\\music\\zonemusic\\tempestkeep\\tk_tempestkeep_amb_22.mp3",
		id =  53788,
		duration = 34,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tempest Keep Ambient 23",
		path = "sound\\music\\zonemusic\\tempestkeep\\tk_tempestkeep_amb_23.mp3",
		id =  53789,
		duration = 67,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tempest Keep Battle 10",
		path = "sound\\music\\zonemusic\\tempestkeep\\tk_tempestkeep_btl10.mp3",
		id =  53790,
		duration = 59,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tempest Keep Battle 11",
		path = "sound\\music\\zonemusic\\tempestkeep\\tk_tempestkeep_btl11.mp3",
		id =  53791,
		duration = 81,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tempest Keep Battle 13",
		path = "sound\\music\\zonemusic\\tempestkeep\\tk_tempestkeep_btl13.mp3",
		id =  53792,
		duration = 36,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tempest Keep STG 14",
		path = "sound\\music\\zonemusic\\tempestkeep\\tk_tempestkeep_stg14.mp3",
		id =  53793,
		duration = 11,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tempest Keep STG 15",
		path = "sound\\music\\zonemusic\\tempestkeep\\tk_tempestkeep_stg15.mp3",
		id =  53794,
		duration = 11,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Tempest Keep STG 16",
		path = "sound\\music\\zonemusic\\tempestkeep\\tk_tempestkeep_stg16.mp3",
		id =  53795,
		duration = 11,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Temple of the Moon A",
		path = "sound\\music\\zonemusic\\tavernnightelf\\ra_templeofthemoona.mp3",
		id =  53754,
		duration = 112,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Temple of the Moon B",
		path = "sound\\music\\zonemusic\\tavernnightelf\\ra_templeofthemoonb.mp3",
		id =  53755,
		duration = 119,
		artist = "David Arkenstone",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Terrokar Bone Wastes Walking 1",
		path = "sound\\music\\zonemusic\\terokkar\\tf_bonewalkuni01.mp3",
		id =  53799,
		duration = 65,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Terrokar Bone Wastes Walking 2",
		path = "sound\\music\\zonemusic\\terokkar\\tf_bonewalkuni02.mp3",
		id =  53800,
		duration = 63,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Terrokar Bone Wastes Walking 3",
		path = "sound\\music\\zonemusic\\terokkar\\tf_bonewalkuni03.mp3",
		id =  53801,
		duration = 56,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Terrokar Bone Wastes Walking 4",
		path = "sound\\music\\zonemusic\\terokkar\\tf_bonewalkuni04.mp3",
		id =  53802,
		duration = 189,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Terrokar Forest 1",
		path = "sound\\music\\zonemusic\\terokkar\\tf_forestwalkuni01.mp3",
		id =  53803,
		duration = 150,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Terrokar Forest 2",
		path = "sound\\music\\zonemusic\\terokkar\\tf_forestwalkuni02.mp3",
		id =  53804,
		duration = 190,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Terrokar Forest 3",
		path = "sound\\music\\zonemusic\\terokkar\\tf_forestwalkuni03.mp3",
		id =  53805,
		duration = 187,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Undead Tavern 1A",
		path = "sound\\music\\zonemusic\\tavernundead\\ra_undeadtavern1a.mp3",
		id =  53774,
		duration = 93,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Undead Tavern 1B",
		path = "sound\\music\\zonemusic\\tavernundead\\ra_undeadtavern1b.mp3",
		id =  53775,
		duration = 87,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Undead Tavern 2",
		path = "sound\\music\\zonemusic\\tavernundead\\ra_undeadtavern2.mp3",
		id =  53776,
		duration = 124,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Undead Tavern 3A",
		path = "sound\\music\\zonemusic\\tavernundead\\ra_undeadtavern3a.mp3",
		id =  53777,
		duration = 83,
		artist = "David Arkenstone",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Undead Tavern 3B",
		path = "sound\\music\\zonemusic\\tavernundead\\ra_undeadtavern3b.mp3",
		id =  53778,
		duration = 93,
		artist = "David Arkenstone",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "WoW Tavern 1 Revisited A",
		path = "sound\\music\\zonemusic\\tavernhuman\\ra_tavern1_revisiteda.mp3",
		id =  53752,
		duration = 70,
		artist = "David Arkenstone & Jason Hayes",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "WoW Tavern 1 Revisited B",
		path = "sound\\music\\zonemusic\\tavernhuman\\ra_tavern1_revisitedb.mp3",
		id =  53753,
		duration = 72,
		artist = "David Arkenstone & Jason Hayes",
	},	
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Zangarmarsh Coilfang 1",
		path = "sound\\music\\zonemusic\\zangarmarsh\\za_coilfangwalkuni01.mp3",
		id =  53816,
		duration = 133,
		artist = "Matt Uelmen & Joseph Lawrence",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Zangarmarsh Coilfang 2",
		path = "sound\\music\\zonemusic\\zangarmarsh\\za_coilfangwalkuni02.mp3",
		id =  53817,
		duration = 99,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Zangarmarsh Coilfang 3",
		path = "sound\\music\\zonemusic\\zangarmarsh\\za_coilfangwalkuni03.mp3",
		id =  53818,
		duration = 109,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Zangarmarsh General 1",
		path = "sound\\music\\zonemusic\\zangarmarsh\\za_generalwalkuni01.mp3",
		id =  53819,
		duration = 81,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Zangarmarsh General 2",
		path = "sound\\music\\zonemusic\\zangarmarsh\\za_generalwalkuni02.mp3",
		id =  53820,
		duration = 120,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Zangarmarsh General 3",
		path = "sound\\music\\zonemusic\\zangarmarsh\\za_generalwalkuni03.mp3",
		id =  53821,
		duration = 59,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Zangarmarsh General 4",
		path = "sound\\music\\zonemusic\\zangarmarsh\\za_generalwalkuni04.mp3",
		id =  53822,
		duration = 102,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Zangarmarsh General 5",
		path = "sound\\music\\zonemusic\\zangarmarsh\\za_generalwalkuni05.mp3",
		id =  53823,
		duration = 71,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 2.0 - The Burning Crusade",
		title = "Zangarmarsh General 6",
		path = "sound\\music\\zonemusic\\zangarmarsh\\za_generalwalkuni06.mp3",
		id =  53824,
		duration = 89,
		artist = "Matt Uelmen",
	},
-------------------------------	
--Patch 2.1 Music Starts Here--
-------------------------------	
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Arrival 1",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_arrivalwalkhero01.mp3",
		id =  53305,
		duration = 163,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Arrival 2",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_arrivalwalkuni02.mp3",
		id =  53306,
		duration = 81,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Arrival 3",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_arrivalwalkuni03.mp3",
		id =  53307,
		duration = 74,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Arrival 4",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_arrivalwalkuni04.mp3",
		id =  53308,
		duration = 63,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Gates 1",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_illidariwalkuni01.mp3",
		id =  53310,
		duration = 61,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Gates 2",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_illidariwalkuni02.mp3",
		id =  53311,
		duration = 71,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Gates 3",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_illidariwalkuni03.mp3",
		id =  53312,
		duration = 78,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Gates 4",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_illidariwalkuni04.mp3",
		id =  53313,
		duration = 91,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Gates 5",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_illidariwalkuni05.mp3",
		id =  53314,
		duration = 90,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Gates 6",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_illidariwalkuni06.mp3",
		id =  53315,
		duration = 29,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Gates 7",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_illidariwalkuni07.mp3",
		id =  53316,
		duration = 77,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Gates 8",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_illidariwalkuni08.mp3",
		id =  53317,
		duration = 65,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Gates 9",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_illidariwalkhero09.mp3",
		id =  53309,
		duration = 74,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Gates 10",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_illidariwalkuni10.mp3",
		id =  53318,
		duration = 75,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Gates 11",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_illidariwalkuni11.mp3",
		id =  53319,
		duration = 35,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Citadel 1",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_karaborwalkuni01.mp3",
		id =  53320,
		duration = 106,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Citadel 2",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_karaborwalkuni02.mp3",
		id =  53321,
		duration = 88,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Citadel 3",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_karaborwalkuni03.mp3",
		id =  53322,
		duration = 57,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Citadel 4",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_karaborwalkuni04.mp3",
		id =  53323,
		duration = 126,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Shattered 1",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_sanctuarywalkhero01.mp3",
		id =  53333,
		duration = 130,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Shattered 2",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_sanctuarywalkuni02.mp3",
		id =  53334,
		duration = 65,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Shattered 3",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_sanctuarywalkuni03.mp3",
		id =  53335,
		duration = 66,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Shattered 4",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_sanctuarywalkuni04.mp3",
		id =  53336,
		duration = 65,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Shattered 5",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_sanctuarywalkuni05.mp3",
		id =  53337,
		duration = 56,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Shattered 6",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_sanctuarywalkuni06.mp3",
		id =  53338,
		duration = 58,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Shattered 7",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_sanctuarywalkuni07.mp3",
		id =  53339,
		duration = 64,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Shattered 8",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_sanctuarywalkuni08.mp3",
		id =  53340,
		duration = 57,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Storm 1",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_stormwalkuni01.mp3",
		id =  53342,
		duration = 67,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Storm 2",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_stormwalkhero02.mp3",
		id =  53341,
		duration = 72,
		artist = "Russell Brower",
	},	
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Storm 3",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_stormwalkuni03.mp3",
		id =  53343,
		duration = 32,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Storm 4",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_stormwalkuni04.mp3",
		id =  53344,
		duration = 48,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Summit 1",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_summitwalkuni01.mp3",
		id =  53345,
		duration = 59,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Summit 2",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_summitwalkuni02.mp3",
		id =  53346,
		duration = 69,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Summit 3",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_summitwalkuni03.mp3",
		id =  53347,
		duration = 41,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Summit 4",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_summitwalkuni04.mp3",
		id =  53348,
		duration = 114,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Summit 5",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_summitwalkuni05.mp3",
		id =  53349,
		duration = 51,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Well 1",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_reliquarywalkhero01.mp3",
		id =  53325,
		duration = 111,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Well 2",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_reliquarywalkuni02.mp3",
		id =  53326,
		duration = 66,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Well 3",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_reliquarywalkuni03.mp3",
		id =  53327,
		duration = 79,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Well 4",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_reliquarywalkuni04.mp3",
		id =  53328,
		duration = 63,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Well 5",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_reliquarywalkuni05.mp3",
		id =  53329,
		duration = 75,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Well 6",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_reliquarywalkuni06.mp3",
		id =  53330,
		duration = 125,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Well 7",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_reliquarywalkuni07.mp3",
		id =  53331,
		duration = 64,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Black Temple Well 8",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_reliquarywalkuni08.mp3",
		id =  53332,
		duration = 88,
		artist = "Russell Brower",
	},	
	{
		album = "WoW 2.1 - The Black Temple",
		title = "Illikama Event Music Mix2",
		path = "sound\\music\\zonemusic\\blacktemple\\bt_preludeevent01.mp3",
		id =  53324,
		duration = 253,
		artist = "Russell Brower",
	},	
-------------------------------	
--Patch 2.2 Music Starts Here--
-------------------------------	
	{
		album = "WoW 2.2 - Voice Chat!",
		title = "Brewfest Dwarves 1",
		path = "sound\\music\\zonemusic\\brewfest\\bf_dwarves1.mp3",
		id =  228572,
		duration = 94,
		artist = "Unknown",
	},
	{
		album = "WoW 2.2 - Voice Chat!",
		title = "Brewfest Dwarves 2",
		path = "sound\\music\\zonemusic\\brewfest\\bf_dwarves2.mp3",
		id =  228573,
		duration = 115,
		artist = "Unknown",
	},
	{
		album = "WoW 2.2 - Voice Chat!",
		title = "Brewfest Dwarves 3",
		path = "sound\\music\\zonemusic\\brewfest\\bf_dwarves3.mp3",
		id =  228574,
		duration = 22,
		artist = "Unknown",
	},
	{
		album = "WoW 2.2 - Voice Chat!",
		title = "Brewfest Goblins 1",
		path = "sound\\music\\zonemusic\\brewfest\\bf_goblins1.mp3",
		id =  228575,
		duration = 67,
		artist = "Unknown",
	},
	{
		album = "WoW 2.2 - Voice Chat!",
		title = "Brewfest Goblins 2",
		path = "sound\\music\\zonemusic\\brewfest\\bf_goblins2.mp3",
		id =  228576,
		duration = 93,
		artist = "Unknown",
	},
	{
		album = "WoW 2.2 - Voice Chat!",
		title = "Brewfest Goblins 3",
		path = "sound\\music\\zonemusic\\brewfest\\bf_goblins3.mp3",
		id =  228577,
		duration = 28,
		artist = "Unknown",
	},	
-------------------------------	
--Patch 2.3 Music Starts Here--
-------------------------------	
	{
		album = "WoW 2.3 - The Gods of Zul'Aman",
		title = "Zul'Aman Ambient 10",
		path = "sound\\music\\zonemusic\\zulaman\\za_zulaman_amb10.mp3",
		id =  53825,
		duration = 113,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.3 - The Gods of Zul'Aman",
		title = "Zul'Aman Ambient 11",
		path = "sound\\music\\zonemusic\\zulaman\\za_zulaman_amb11.mp3",
		id =  53826,
		duration = 74,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.3 - The Gods of Zul'Aman",
		title = "Zul'Aman Ambient 12",
		path = "sound\\music\\zonemusic\\zulaman\\za_zulaman_amb12.mp3",
		id =  53827,
		duration = 108,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.3 - The Gods of Zul'Aman",
		title = "Zul'Aman Ambient 13",
		path = "sound\\music\\zonemusic\\zulaman\\za_zulaman_amb13.mp3",
		id =  53828,
		duration = 70,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.3 - The Gods of Zul'Aman",
		title = "Zul'Aman Ambient 14",
		path = "sound\\music\\zonemusic\\zulaman\\za_zulaman_amb14.mp3",
		id =  53829,
		duration = 90,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.3 - The Gods of Zul'Aman",
		title = "Zul'Aman Ambient 15",
		path = "sound\\music\\zonemusic\\zulaman\\za_zulaman_amb15.mp3",
		id =  53830,
		duration = 113,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.3 - The Gods of Zul'Aman",
		title = "Zul'Aman Battle 11",
		path = "sound\\music\\zonemusic\\zulaman\\za_zulaman_btl11.mp3",
		id =  53831,
		duration = 136,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.3 - The Gods of Zul'Aman",
		title = "Zul'Aman Battle 12",
		path = "sound\\music\\zonemusic\\zulaman\\za_zulaman_btl12.mp3",
		id =  53832,
		duration = 117,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.3 - The Gods of Zul'Aman",
		title = "Zul'Aman Battle 13",
		path = "sound\\music\\zonemusic\\zulaman\\za_zulaman_btl13.mp3",
		id =  53833,
		duration = 40,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.3 - The Gods of Zul'Aman",
		title = "Zul'Aman Battle 14",
		path = "sound\\music\\zonemusic\\zulaman\\za_zulaman_btl14.mp3",
		id =  53834,
		duration = 92,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.3 - The Gods of Zul'Aman",
		title = "Zul'Aman Battle 15",
		path = "sound\\music\\zonemusic\\zulaman\\za_zulaman_btl15.mp3",
		id =  53835,
		duration = 79,
		artist = "Derek Duke",
	},
	{
		album = "WoW 2.3 - The Gods of Zul'Aman",
		title = "Zul'Aman Victory 10",
		path = "sound\\music\\zonemusic\\zulaman\\za_zulaman_vct10.mp3",
		id =  53836,
		duration = 79,
		artist = "Derek Duke",
	},	
-------------------------------	
--Patch 2.4 Music Starts Here--
-------------------------------	
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Fel Energy Wash",
		path = "sound\\music\\zonemusic\\sunwell\\sw_felenergywalkuni01.mp3",
		id =  53702,
		duration = 125,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Fel Eversong 1A",
		path = "sound\\music\\zonemusic\\sunwell\\sw_islemedwalkuni01.mp3",
		id =  53709,
		duration = 117,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Fel Eversong 1B",
		path = "sound\\music\\zonemusic\\sunwell\\sw_islemedwalkuni02.mp3",
		id =  53710,
		duration = 126,
		artist = "Russell Brower",
	},	
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Fel Eversong 2A",
		path = "sound\\music\\zonemusic\\sunwell\\sw_islelightwalkuni01.mp3",
		id =  53706,
		duration = 115,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Fel Eversong 2B",
		path = "sound\\music\\zonemusic\\sunwell\\sw_islelightwalkuni02.mp3",
		id =  53707,
		duration = 119,
		artist = "Russell Brower",
	},	
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Fel Shorel'Aran",
		path = "sound\\music\\zonemusic\\sunwell\\sw_islemedwalkuni03.mp3",
		id =  53711,
		duration = 88,
		artist = "Russell Brower",
	},	
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Fel Shorel'Aran B",
		path = "sound\\music\\zonemusic\\sunwell\\sw_islelightwalkuni03.mp3",
		id =  53708,
		duration = 90,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Fel Sundering",
		path = "sound\\music\\zonemusic\\sunwell\\sw_isledarkwalkuni01.mp3",
		id =  53703,
		duration = 139,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Fel Sundering 2A",
		path = "sound\\music\\zonemusic\\sunwell\\sw_isledarkwalkuni02.mp3",
		id =  53704,
		duration = 137,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Fel Sundering 2B",
		path = "sound\\music\\zonemusic\\sunwell\\sw_isledarkwalkuni03.mp3",
		id =  53705,
		duration = 126,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Quel'Danas C1",
		path = "sound\\music\\zonemusic\\sunwell\\sw_magistersterracewalkuni05.mp3",
		id =  53720,
		duration = 123,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Quel'Danas C2",
		path = "sound\\music\\zonemusic\\sunwell\\sw_plateausunwellwalkuni01.mp3",
		id =  53722,
		duration = 85,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Quel'Danas C3",
		path = "sound\\music\\zonemusic\\sunwell\\sw_plateausunwellwalkuni02.mp3",
		id =  53723,
		duration = 78,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Quel'Danas C4",
		path = "sound\\music\\zonemusic\\sunwell\\sw_plateausunwellwalkuni03.mp3",
		id =  53724,
		duration = 90,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Quel'Danas Pt1",
		path = "sound\\music\\zonemusic\\sunwell\\sw_queldanaswalkuni01.mp3",
		id =  53728,
		duration = 108,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Quel'Danas Pt2",
		path = "sound\\music\\zonemusic\\sunwell\\sw_queldanaswalkuni02.mp3",
		id =  53729,
		duration = 84,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Shorel'Aran C",
		path = "sound\\music\\zonemusic\\sunwell\\sw_plateausunwellwalkuni06.mp3",
		id =  53727,
		duration = 87,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Shorel'Aran Choir",
		path = "sound\\music\\zonemusic\\sunwell\\sw_magistersarrivalwalkuni01.mp3",
		id =  53712,
		duration = 87,
		artist = "Russell Brower",
	},	
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Shorel'Aran D1",
		path = "sound\\music\\zonemusic\\sunwell\\sw_assemblychamberwalkuni01.mp3",
		id =  53700,
		duration = 82,
		artist = "Russell Brower",
	},	
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Shorel'Aran D2",
		path = "sound\\music\\zonemusic\\sunwell\\sw_sanctumwalkuni01.mp3",
		id =  53730,
		duration = 85,
		artist = "Russell Brower",
	},	
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Shorel'Aran Horn",
		path = "sound\\music\\zonemusic\\sunwell\\sw_assemblychamberwalkuni02.mp3",
		id =  53701,
		duration = 88,
		artist = "Russell Brower",
	},	
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Shorel'Aran Vocal",
		path = "sound\\music\\zonemusic\\sunwell\\sw_shorelaranwalkuni01.mp3",
		id =  53731,
		duration = 87,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Shorel'Aran Woods",
		path = "sound\\music\\zonemusic\\sunwell\\sw_magistersterracewalkuni01.mp3",
		id =  53716,
		duration = 88,
		artist = "Russell Brower",
	},	
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Silvermoon 2",
		path = "sound\\music\\zonemusic\\sunwell\\sw_magistersasylumwalkuni01.mp3",
		id =  53713,
		duration = 97,
		artist = "Russell Brower",
	},	
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Sunstrider 2",
		path = "sound\\music\\zonemusic\\sunwell\\sw_magistersasylumwalkuni02.mp3",
		id =  53714,
		duration = 95,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Sunstrider 2B",
		path = "sound\\music\\zonemusic\\sunwell\\sw_magistersasylumwalkuni03.mp3",
		id =  53715,
		duration = 65,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Sunstrider 2C1",
		path = "sound\\music\\zonemusic\\sunwell\\sw_magistersterracewalkuni02.mp3",
		id =  53717,
		duration = 90,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Sunstrider 2C2",
		path = "sound\\music\\zonemusic\\sunwell\\sw_magistersterracewalkuni03.mp3",
		id =  53718,
		duration = 89,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Sunstrider 2A",
		path = "sound\\music\\zonemusic\\sunwell\\sw_magistersterracewalkuni04.mp3",
		id =  53719,
		duration = 91,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Sunwell Bombing Run v2",
		path = "sound\\music\\zonemusic\\sunwell\\sw_sunwellbombingrununi01.mp3",
		id =  53732,
		duration = 259,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "Sunwell Flyby",
		path = "sound\\music\\zonemusic\\sunwell\\sw_sunwellflybyuni01.mp3",
		id =  53733,
		duration = 57,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "The Sundering",
		path = "sound\\music\\zonemusic\\sunwell\\sw_plateausunwellarrivalwalkuni01.mp3",
		id =  53721,
		duration = 138,
		artist = "Russell Brower",
	},	
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "The Sundering 2A",
		path = "sound\\music\\zonemusic\\sunwell\\sw_plateausunwellwalkuni04.mp3",
		id =  53725,
		duration = 91,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "The Sundering 2B",
		path = "sound\\music\\zonemusic\\sunwell\\sw_plateausunwellwalkuni05.mp3",
		id =  53726,
		duration = 93,
		artist = "Russell Brower",
	},	
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "The Well A",
		path = "sound\\music\\zonemusic\\sunwell\\sw_thewellwalkuni01.mp3",
		id =  53734,
		duration = 98,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "The Well B",
		path = "sound\\music\\zonemusic\\sunwell\\sw_thewellwalkuni02.mp3",
		id =  53735,
		duration = 95,
		artist = "Russell Brower",
	},
	{
		album = "WoW 2.4 - Fury of the Sunwell",
		title = "The Well C",
		path = "sound\\music\\zonemusic\\sunwell\\sw_thewellwalkuni03.mp3",
		id =  53736,
		duration = 95,
		artist = "Russell Brower",
	},
		{
		album = "WoW BC",
		title = "Ol Actionwalkuni01",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_actionwalkuni01.mp3",
		duration = 81,
		artist = "Brian David Farr",
		id =  "53637",
	},
	{
		album = "WoW BC",
		title = "Outlands Alliance Base 1",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_alliancebasewalkuni01.mp3",
		duration = 134,
		artist = "Matt Uelmen",
		id =  "53638",
	},
	{
		album = "WoW BC",
		title = "Outlands Alliance Base 2",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_alliancebasewalkuni02.mp3",
		duration = 111,
		artist = "Matt Uelmen (incorporating Nocturne by F. Chopin)",
		id =  "53639",
	},
	{
		album = "WoW BC",
		title = "Outlands Moment Arrakoa 1",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_arakkoaintrouni01.mp3",
		duration = 18,
		artist = "Matt Uelmen",
		id =  "53640",
	},
	{
		album = "WoW BC",
		title = "Outlands Moment Arrakoa 2",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_arakkoaintrouni02.mp3",
		duration = 14,
		artist = "Matt Uelmen",
		id =  "53641",
	},
	{
		album = "WoW BC",
		title = "Outlands Blood Elf Base 1",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_bloodelfbasewalkuni01.mp3",
		duration = 120,
		artist = "Russell Brower",
		id =  "53642",
	},
	{
		album = "WoW BC",
		title = "Outlands Blood Elf Base 2",
		path = "sound\\music\\zonemusic\\outlandgeneral\\ol_bloodelfbasewalkuni02.mp3",
		duration = 122,
		artist = "Russell Brower",
		id =  "53643",
	},
}end)