local emp = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer", true) ---@class emp
if not emp then return end

-- playlist metadata
local requiredExpansion = "Classic"

emp:RegisterPlaylist(requiredExpansion, function()
return {
	listName = requiredExpansion,
	playlistVersion = "5.0",
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "World of Warcraft",
		path = "sound\\music\\gluescreenmusic\\wow_main_theme.mp3",
		id =  53223,
		duration = 161,
		artist = "Main Title",
	},
--A--
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Angelic 01",
		path = "sound\\music\\musical moments\\angelic\\angelic01.mp3",
		id =  53224,
		duration = 47,
		artist = "Jason Hayes",
	},
--B--
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Battle 01",
		path = "sound\\music\\musical moments\\battle\\battle01.mp3",
		id =  53225,
		duration = 48,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Battle 02",
		path = "sound\\music\\musical moments\\battle\\battle02.mp3",
		id =  53226,
		duration = 62,
		artist = "Unknown", 
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Battle 03",
		path = "sound\\music\\musical moments\\battle\\battle03.mp3",
		id =  53227,
		duration = 27,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Battle 04",
		path = "sound\\music\\musical moments\\battle\\battle04.mp3",
		id =  53228,
		duration = 36,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Battle 05",
		path = "sound\\music\\musical moments\\battle\\battle05.mp3",
		id =  53229,
		duration = 44,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Battle 06",
		path = "sound\\music\\musical moments\\battle\\battle06.mp3",
		id =  53230,
		duration = 62,
		artist = "Unknown",
	},
--C--
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Cursed Land 01",
		path = "sound\\music\\zonemusic\\cursedland\\cursedland01.mp3",
		id =  53426,
		duration = 54,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Cursed Land 02",
		path = "sound\\music\\zonemusic\\cursedland\\cursedland02.mp3",
		id =  53427,
		duration = 58,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Cursed Land 03",
		path = "sound\\music\\zonemusic\\cursedland\\cursedland03.mp3",
		id =  53428,
		duration = 64,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Cursed Land 04",
		path = "sound\\music\\zonemusic\\cursedland\\cursedland04.mp3",
		id =  53429,
		duration = 79,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Cursed Land 05",
		path = "sound\\music\\zonemusic\\cursedland\\cursedland05.mp3",
		id =  53430,
		duration = 82,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Cursed Land 06",
		path = "sound\\music\\zonemusic\\cursedland\\cursedland06.mp3",
		id =  53431,
		duration = 74,
		artist = "Derek Duke",
	},
--D--	
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Darkmoon Faire 1",
		path = "sound\\music\\worldevents\\darkmoonfaire_1.mp3",
		id =  53256,
		duration = 28,
		artist = "D. Arkenstone, R. Brower",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Darkmoon Faire 2",
		path = "sound\\music\\worldevents\\darkmoonfaire_2.mp3",
		id =  53257,
		duration = 74,
		artist = "D. Arkenstone, R. Brower",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Darkmoon Faire 3",
		path = "sound\\music\\worldevents\\darkmoonfaire_3.mp3",
		id =  53258,
		duration = 58,
		artist = "D. Arkenstone, R. Brower",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Darkmoon Faire 4",
		path = "sound\\music\\worldevents\\darkmoonfaire_4.mp3",
		id =  53259,
		duration = 37,
		artist = "D. Arkenstone, R. Brower",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Darnassus Intro",
		path = "sound\\music\\citymusic\\darnassus\\darnassus intro.mp3",
		id =  53183,
		duration = 39,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Darnassus Walking 1",
		path = "sound\\music\\citymusic\\darnassus\\darnassus walking 1.mp3",
		id =  53184,
		duration = 85,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Darnassus Walking 2",
		path = "sound\\music\\citymusic\\darnassus\\darnassus walking 2.mp3",
		id =  53185,
		duration = 69,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Darnassus Walking 1",
		path = "sound\\music\\citymusic\\darnassus\\darnassus walking 3.mp3",
		id =  53186,
		duration = 67,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Darnassus Druid Grove",
		path = "sound\\music\\citymusic\\darnassus\\druid grove.mp3",
		id =  53187,
		duration = 44,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Darnassus Warrior Terrace",
		path = "sound\\music\\citymusic\\darnassus\\warrior terrace.mp3",
		id =  53188,
		duration = 53,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Barren Dry 01",
		path = "sound\\music\\zonemusic\\barrendry\\daybarrendry01.mp3",
		id =  53299,
		duration = 64,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Barren Dry 02",
		path = "sound\\music\\zonemusic\\barrendry\\daybarrendry02.mp3",
		id =  53300,
		duration = 64,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Barren Dry 03",
		path = "sound\\music\\zonemusic\\barrendry\\daybarrendry03.mp3",
		id =  53301,
		duration = 55,
		artist = "Derek Duke",
	},	
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Desert 01",
		path = "sound\\music\\zonemusic\\desert\\daydesert01.mp3",
		id =  53432,
		duration = 65,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Desert 02",
		path = "sound\\music\\zonemusic\\desert\\daydesert02.mp3",
		id =  53433,
		duration = 81,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Desert 03",
		path = "sound\\music\\zonemusic\\desert\\daydesert03.mp3",
		id =  53434,
		duration = 54,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Evil Forest 01",
		path = "sound\\music\\zonemusic\\evilforest\\dayevilforest01.mp3",
		id =  53486,
		duration = 70,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Evil Forest 02",
		path = "sound\\music\\zonemusic\\evilforest\\dayevilforest02.mp3",
		id =  53487,
		duration = 72,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Evil Forest 03",
		path = "sound\\music\\zonemusic\\evilforest\\dayevilforest03.mp3",
		id =  53488,
		duration = 70,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Forest 01",
		path = "sound\\music\\zonemusic\\forest\\dayforest01.mp3",
		id =  53492,
		duration = 55,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Forest 02",
		path = "sound\\music\\zonemusic\\forest\\dayforest02.mp3",
		id =  53493,
		duration = 72,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Forest 03",
		path = "sound\\music\\zonemusic\\forest\\dayforest03.mp3",
		id =  53494,
		duration = 64,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Jungle 01",
		path = "sound\\music\\zonemusic\\jungle\\dayjungle01.mp3",
		id =  53541,
		duration = 46,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Jungle 02",
		path = "sound\\music\\zonemusic\\jungle\\dayjungle02.mp3",
		id =  53542,
		duration = 98,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Jungle 03",
		path = "sound\\music\\zonemusic\\jungle\\dayjungle03.mp3",
		id =  53543,
		duration = 48,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Mountain 01",
		path = "sound\\music\\zonemusic\\mountain\\daymountain01.mp3",
		id =  53577,
		duration = 120,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Mountain 02",
		path = "sound\\music\\zonemusic\\mountain\\daymountain02.mp3",
		id =  53578,
		duration = 66,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Mountain 03",
		path = "sound\\music\\zonemusic\\mountain\\daymountain03.mp3",
		id =  53579,
		duration = 80,
		artist = "Jason Hayes",
	},	
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Plains 01",
		path = "sound\\music\\zonemusic\\plains\\dayplains01.mp3",
		id =  53680,
		duration = 53,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Plains 02",
		path = "sound\\music\\zonemusic\\plains\\dayplains02.mp3",
		id =  53681,
		duration = 76,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Volcanic 01",
		path = "sound\\music\\zonemusic\\volcanic\\dayvolcanic01.mp3",
		id =  53812,
		duration = 72,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Day Volcanic 02",
		path = "sound\\music\\zonemusic\\volcanic\\dayvolcanic02.mp3",
		id =  53813,
		duration = 87,
		artist = "Jason Hayes",
	},	
--E-- 
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Enchanted Forest 01",
		path = "sound\\music\\zonemusic\\enchantedforest\\enchantedforest01.mp3",
		id =  53453,
		duration = 49,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Enchanted Forest 02",
		path = "sound\\music\\zonemusic\\enchantedforest\\enchantedforest02.mp3",
		id =  53454,
		duration = 67,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Enchanted Forest 03",
		path = "sound\\music\\zonemusic\\enchantedforest\\enchantedforest03.mp3",
		id =  53455,
		duration = 234,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Enchanted Forest 04",
		path = "sound\\music\\zonemusic\\enchantedforest\\enchantedforest04.mp3",
		id =  53456,
		duration = 60,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Enchanted Forest 05",
		path = "sound\\music\\zonemusic\\enchantedforest\\enchantedforest05.mp3",
		id =  53457,
		duration = 70,
		artist = "Jason Hayes",
	},
--F-- 

--G-- 
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Ghost Muisc 03",
		path = "sound\\music\\zonemusic\\ghostmusic\\ghostmusic03.mp3",
		id =  53519,
		duration = 62,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Gloomy 01",
		path = "sound\\music\\musical moments\\gloomy\\gloomy01.mp3",
		id =  53231,
		duration = 36,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Gloomy 02",
		path = "sound\\music\\musical moments\\gloomy\\gloomy02.mp3",
		id =  53232,
		duration = 39,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Gnomeregan Event B",
		path = "sound\\music\\event\\gnomeregan_event_b.mp3",
		id =  369053,
		duration = 61,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Gnomeregan Event C",
		path = "sound\\music\\event\\gnomeregan_event_c.mp3",
		id =  369054,
		duration = 35,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Gnomeregan Event Complete",
		path = "sound\\music\\event\\gnomeregan_event_complete.mp3",
		id =  369055,
		duration = 63,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Gnomeregan Event D",
		path = "sound\\music\\event\\gnomeregan_event_d.mp3",
		id =  369056,
		duration = 38,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Gnomeregan Event E",
		path = "sound\\music\\event\\gnomeregan_event_e.mp3",
		id =  369057,
		duration = 34,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Gnomeregan Event Intro",
		path = "sound\\music\\event\\gnomeregan_event_intro.mp3",
		id =  369058,
		duration = 88,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Gnomeragon Zone 01",
		path = "sound\\music\\citymusic\\gnomeragon\\gnomeragon01-zone.mp3",
		id =  53189,
		duration = 64,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Gnomeragon Zone 02",
		path = "sound\\music\\citymusic\\gnomeragon\\gnomeragon02-zone.mp3",
		id =  53190,
		duration = 64,
		artist = "Derek Duke",
	},	
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Guldan's Entrance Theme",
		path = "sound\\music\\musical moments\\guldansentrancetheme.mp3",
		id =  53233,
		duration = 100,
		artist = "Unknown",
	},	
--H--
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Haunted 01",
		path = "sound\\music\\musical moments\\haunted\\haunted01.mp3",
		id =  53234,
		duration = 62,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Haunted 02",
		path = "sound\\music\\musical moments\\haunted\\haunted02.mp3",
		id =  53235,
		duration = 60,
		artist = "Jason Hayes",
	},
--I--
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Ironforge Intro",
		path = "sound\\music\\citymusic\\ironforge\\ironforge intro.mp3",
		id =  53191,
		duration = 86,
		artist = "Brian Farr",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Ironforge Walking 1",
		path = "sound\\music\\citymusic\\ironforge\\ironforge walking 01.mp3",
		id =  53192,
		duration = 123,
		artist = "Brian Farr",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Ironforge Walking 2",
		path = "sound\\music\\citymusic\\ironforge\\ironforge walking 02.mp3",
		id =  53193,
		duration = 50,
		artist = "Brian Farr",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Ironforge Walking 3",
		path = "sound\\music\\citymusic\\ironforge\\ironforge walking 03 (glenn).mp3",
		id =  53194,
		duration = 81,
		artist = "Brian Farr",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Ironforge Walking 4",
		path = "sound\\music\\citymusic\\ironforge\\ironforge walking 04.mp3",
		id =  53195,
		duration = 70,
		artist = "Unknown",
	},
--J--

--K--

--L--
--M--
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Magic 01 Moment",
		path = "sound\\music\\musical moments\\magic\\magic01-moment.mp3",
		id =  53236,
		duration = 63,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Magic 01 Zone 1",
		path = "sound\\music\\musical moments\\magic\\magic01-zone1.mp3",
		id =  53237,
		duration = 33,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Magic 01 Zone 2",
		path = "sound\\music\\musical moments\\magic\\magic01-zone2.mp3",
		id =  53238,
		duration = 39,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Mystery 01 Zone",
		path = "sound\\music\\musical moments\\mystery\\mystery01-zone.mp3",
		id =  53240,
		duration = 60,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Mystery 02 Zone",
		path = "sound\\music\\musical moments\\mystery\\mystery02-zone.mp3",
		id =  53241,
		duration = 53,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Mystery 03 Zone",
		path = "sound\\music\\musical moments\\mystery\\mystery03-zone.mp3",
		id =  53242,
		duration = 60,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Mystery 04 Zone",
		path = "sound\\music\\musical moments\\mystery\\mystery04-zone.mp3",
		id =  53243,
		duration = 64,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Mystery 05 Zone",
		path = "sound\\music\\musical moments\\mystery\\mystery05-zone.mp3",
		id =  53244,
		duration = 81,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Mystery 06 Zone",
		path = "sound\\music\\musical moments\\mystery\\mystery06-zone.mp3",
		id =  53245,
		duration = 65,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Mystery 07 Zone",
		path = "sound\\music\\musical moments\\mystery\\mystery07-zone.mp3",
		id =  53246,
		duration = 83,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Mystery 08 Zone",
		path = "sound\\music\\musical moments\\mystery\\mystery08-zone.mp3",
		id =  53247,
		duration = 83,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Mystery 09 Zone",
		path = "sound\\music\\musical moments\\mystery\\mystery09-zone.mp3",
		id =  53248,
		duration = 82,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Mystery 10 Zone",
		path = "sound\\music\\musical moments\\mystery\\mystery10-zone.mp3",
		id =  53249,
		duration = 62,
		artist = "Matt Uelmen",
	},
--N--
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Barren Dry 01",
		path = "sound\\music\\zonemusic\\barrendry\\nightbarrendry01.mp3",
		id =  53302,
		duration = 67,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Barren Dry 02",
		path = "sound\\music\\zonemusic\\barrendry\\nightbarrendry02.mp3",
		id =  53303,
		duration = 40,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Barren Dry 03",
		path = "sound\\music\\zonemusic\\barrendry\\nightbarrendry03.mp3",
		id =  53304,
		duration = 47,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Desert 01",
		path = "sound\\music\\zonemusic\\desert\\nightdesert01.mp3",
		id =  53435,
		duration = 77,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Desert 02",
		path = "sound\\music\\zonemusic\\desert\\nightdesert02.mp3",
		id =  53436,
		duration = 62,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Desert 03",
		path = "sound\\music\\zonemusic\\desert\\nightdesert03.mp3",
		id =  53437,
		duration = 57,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Evil Forest 01",
		path = "sound\\music\\zonemusic\\evilforest\\nightevilforest01.mp3",
		id =  53489,
		duration = 57,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Evil Forest 02",
		path = "sound\\music\\zonemusic\\evilforest\\nightevilforest02.mp3",
		id =  53490,
		duration = 75,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Evil Forest 03",
		path = "sound\\music\\zonemusic\\evilforest\\nightevilforest03.mp3",
		id =  53491,
		duration = 70,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Forest 01",
		path = "sound\\music\\zonemusic\\forest\\nightforest01.mp3",
		id =  53495,
		duration = 53,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Forest 02",
		path = "sound\\music\\zonemusic\\forest\\nightforest02.mp3",
		id =  53496,
		duration = 42,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Forest 03",
		path = "sound\\music\\zonemusic\\forest\\nightforest03.mp3",
		id =  53497,
		duration = 59,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Forest 04",
		path = "sound\\music\\zonemusic\\forest\\nightforest04.mp3",
		id =  53498,
		duration = 54,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Jungle 01",
		path = "sound\\music\\zonemusic\\jungle\\nightjungle01.mp3",
		id =  53544,
		duration = 54,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Jungle 02",
		path = "sound\\music\\zonemusic\\jungle\\nightjungle02.mp3",
		id =  53545,
		duration = 53,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Jungle 03",
		path = "sound\\music\\zonemusic\\jungle\\nightjungle03.mp3",
		id =  53546,
		duration = 89,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Mountain 01",
		path = "sound\\music\\zonemusic\\mountain\\nightmountain01.mp3",
		id =  53580,
		duration = 64,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Mountain 02",
		path = "sound\\music\\zonemusic\\mountain\\nightmountain02.mp3",
		id =  53581,
		duration = 63,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Mountain 03",
		path = "sound\\music\\zonemusic\\mountain\\nightmountain03.mp3",
		id =  53582,
		duration = 69,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Mountain 04",
		path = "sound\\music\\zonemusic\\mountain\\nightmountain04.mp3",
		id =  53583,
		duration = 63,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Plains 01",
		path = "sound\\music\\zonemusic\\plains\\nightplains01.mp3",
		id =  53682,
		duration = 58,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Plains 02",
		path = "sound\\music\\zonemusic\\plains\\nightplains02.mp3",
		id =  53683,
		duration = 68,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Volcanic 01",
		path = "sound\\music\\zonemusic\\volcanic\\nightvolcanic01.mp3",
		id =  53814,
		duration = 71,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Night Volcanic 02",
		path = "sound\\music\\zonemusic\\volcanic\\nightvolcanic02.mp3",
		id =  53815,
		duration = 64,
		artist = "Jason Hayes",
	},	
--O--
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Orgrimmar 1 Moment",
		path = "sound\\music\\citymusic\\orgrimmar\\orgrimmar01-moment.mp3",
		id =  53197,
		duration = 68,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Orgrimmar 1 Zone",
		path = "sound\\music\\citymusic\\orgrimmar\\orgrimmar01-zone.mp3",
		id =  53198,
		duration = 68,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Orgrimmar 2 Moment",
		path = "sound\\music\\citymusic\\orgrimmar\\orgrimmar02-moment.mp3",
		id =  53199,
		duration = 62,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Orgrimmar 2 Zone",
		path = "sound\\music\\citymusic\\orgrimmar\\orgrimmar02-zone.mp3",
		id =  53200,
		duration = 62,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Orgrimmar Intro Moment",
		path = "sound\\music\\citymusic\\orgrimmar\\orgrimmar_intro-moment.mp3",
		id =  53201,
		duration = 40,
		artist = "Jason Hayes",
	},
--P--
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "PVP 6-1",
		path = "sound\\music\\zonemusic\\pvp\\mus_pvp6_01.mp3",
		id =  521021,
		duration = 157,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "PVP 6-2",
		path = "sound\\music\\zonemusic\\pvp\\mus_pvp6_02.mp3",
		id =  521022,
		duration = 162,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "PVP 7 Moment 1-1",
		path = "sound\\music\\zonemusic\\pvp\\mus_pvp7moment1_01.mp3",
		id =  521023,
		duration = 40,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "PVP 7 Moment 1-2",
		path = "sound\\music\\zonemusic\\pvp\\mus_pvp7moment1_02.mp3",
		id =  521024,
		duration = 42,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "PVP 7 Moment 2-1",
		path = "sound\\music\\zonemusic\\pvp\\mus_pvp7moment2_01.mp3",
		id =  521025,
		duration = 36,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "PVP 7 Moment 2-2",
		path = "sound\\music\\zonemusic\\pvp\\mus_pvp7moment2_02.mp3",
		id =  521026,
		duration = 36,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "PVP 7 Moment 3-1",
		path = "sound\\music\\zonemusic\\pvp\\mus_pvp7moment3_01.mp3",
		id =  521027,
		duration = 40,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "PVP 7 Stinger End",
		path = "sound\\music\\zonemusic\\pvp\\mus_pvp7stingerend_01.mp3",
		id =  521028,
		duration = 31,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "PVP 7 Stinger Intro",
		path = "sound\\music\\zonemusic\\pvp\\mus_pvp7stingerintro_01.mp3",
		id =  521029,
		duration = 21,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "PVP 7-1",
		path = "sound\\music\\zonemusic\\pvp\\mus_pvp7_01.mp3",
		id =  521030,
		duration = 99,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "PVP 7-2",
		path = "sound\\music\\zonemusic\\pvp\\mus_pvp7_02.mp3",
		id =  521031,
		duration = 99,
		artist = "Unknown",
	},
--Q--
--R--
--S--
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Sacred 01 (Monastery 01)",
		path = "sound\\music\\musical moments\\sacred\\sacred01.mp3",
		id =  53250,
		duration = 16,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Sacred 02",
		path = "sound\\music\\musical moments\\sacred\\sacred02.mp3",
		id =  53251,
		duration = 19,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Soggy Place Zone 1",
		path = "sound\\music\\zonemusic\\soggyplace\\soggyplace-zone1.mp3",
		id =  53695,
		duration = 97,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Soggy Place Zone 2",
		path = "sound\\music\\zonemusic\\soggyplace\\soggyplace-zone2.mp3",
		id =  53696,
		duration = 97,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Soggy Place Zone 3",
		path = "sound\\music\\zonemusic\\soggyplace\\soggyplace-zone3.mp3",
		id =  53697,
		duration = 90,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Soggy Place Zone 4",
		path = "sound\\music\\zonemusic\\soggyplace\\soggyplace-zone4.mp3",
		id =  53698,
		duration = 89,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Soggy Place Zone 5",
		path = "sound\\music\\zonemusic\\soggyplace\\soggyplace-zone5.mp3",
		id =  53699,
		duration = 70,
		artist = "Derek Duke",
	},	
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Spooky 01 Moment",
		path = "sound\\music\\musical moments\\spooky\\spooky01-moment.mp3",
		id =  53252,
		duration = 25,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Stormwind 1 Moment",
		path = "sound\\music\\citymusic\\stormwind\\stormwind01-moment.mp3",
		id =  53202,
		duration = 54,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Stormwind 2 Moment",
		path = "sound\\music\\citymusic\\stormwind\\stormwind02-moment.mp3",
		id =  53203,
		duration = 35,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Stormwind 3 Moment",
		path = "sound\\music\\citymusic\\stormwind\\stormwind03-moment.mp3",
		id =  53204,
		duration = 69,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Stormwind 4 Zone",
		path = "sound\\music\\citymusic\\stormwind\\stormwind04-zone.mp3",
		id =  53205,
		duration = 62,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Stormwind 5 Zone",
		path = "sound\\music\\citymusic\\stormwind\\stormwind05-zone.mp3",
		id =  53206,
		duration = 60,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Stormwind 6 Zone",
		path = "sound\\music\\citymusic\\stormwind\\stormwind06-zone.mp3",
		id =  53207,
		duration = 53,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Stormwind 7 Zone",
		path = "sound\\music\\citymusic\\stormwind\\stormwind07-zone.mp3",
		id =  53208,
		duration = 86,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Stormwind 8 Zone",
		path = "sound\\music\\citymusic\\stormwind\\stormwind08-zone.mp3",
		id =  53209,
		duration = 77,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Stormwind High Seas Moment",
		path = "sound\\music\\citymusic\\stormwind\\stormwind_highseas-moment.mp3",
		id =  53210,
		duration = 133,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Stormwind Intro Moment",
		path = "sound\\music\\citymusic\\stormwind\\stormwind_intro-moment.mp3",
		id =  53211,
		duration = 66,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Swamp 01",
		path = "sound\\music\\musical moments\\swamp\\swamp01.mp3",
		id =  53253,
		duration = 34,
		artist = "Jason Hayes",
	},		
--T--
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Tavern Alliance 1",
		path = "sound\\music\\zonemusic\\tavernalliance\\tavernalliance01.mp3",
		id =  53737,
		duration = 47,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Tavern Alliance 2",
		path = "sound\\music\\zonemusic\\tavernalliance\\tavernalliance02.mp3",
		id =  53738,
		duration = 51,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Tavern Horde 1",
		path = "sound\\music\\zonemusic\\tavernhorde\\tavernhorde01.mp3",
		id =  53744,
		duration = 48,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Tavern Horde 2",
		path = "sound\\music\\zonemusic\\tavernhorde\\tavernhorde02.mp3",
		id =  53745,
		duration = 39,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Tavern Horde 3",
		path = "sound\\music\\zonemusic\\tavernhorde\\tavernhorde03.mp3",
		id =  53746,
		duration = 47,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Tinker Town Intro",
		path = "sound\\music\\citymusic\\ironforge\\tinkertownintro_moment.mp3",
		id =  53196,
		duration = 51,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Thunder Bluff Intro",
		path = "sound\\music\\citymusic\\thunderbluff\\thunderbluff intro.mp3",
		id =  53212,
		duration = 46,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Thunder Bluff Walking 1",
		path = "sound\\music\\citymusic\\thunderbluff\\thunderbluff walking 01.mp3",
		id =  53213,
		duration = 117,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Thunder Bluff Walking 2",
		path = "sound\\music\\citymusic\\thunderbluff\\thunderbluff walking 02.mp3",
		id =  53214,
		duration = 116,
		artist = "Unknown",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Thunder Bluff Walking 3",
		path = "sound\\music\\citymusic\\thunderbluff\\thunderbluff walking 03.mp3",
		id =  53215,
		duration = 121,
		artist = "Unknown",
	},	
--U--
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Undead Dance",
		path = "sound\\music\\zonemusic\\tavernhorde\\undead_dance.mp3",
		id =  53747,
		duration = 25,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Undercity 1 Zone",
		path = "sound\\music\\citymusic\\undercity\\undercity01-zone.mp3",
		id =  53216,
		duration = 67,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Undercity 2 Zone",
		path = "sound\\music\\citymusic\\undercity\\undercity02-zone.mp3",
		id =  53217,
		duration = 85,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Undercity 3 Zone",
		path = "sound\\music\\citymusic\\undercity\\undercity03-zone.mp3",
		id =  53218,
		duration = 75,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Undercity Intro Moment",
		path = "sound\\music\\citymusic\\undercity\\undercityintro-moment.mp3",
		id =  53219,
		duration = 28,
		artist = "Derek Duke",
	},
--V--
--W--
--X--
--Y--
--Z--	
	{
		album = "WoW 1.1 - World of Warcraft",
		title = "Zul'Gurub Voodoo",
		path = "sound\\music\\musical moments\\zulgurubvoodoo.mp3",
		id =  53254,
		duration = 84,
		artist = "Derek Duke",
	},
--------------------------------
--Patch 1.9 Music Starts Here--
--------------------------------
	{
		album = "WoW 1.9 - The Gates of Ahn'Qiraj",
		title = "Ahn'Qiraj Breath 1",
		path = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajinterior1.mp3",
		id =  53265,
		duration = 52,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.9 - The Gates of Ahn'Qiraj",
		title = "Ahn'Qiraj Breath 2",
		path = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajinterior2.mp3",
		id =  53266,
		duration = 81,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.9 - The Gates of Ahn'Qiraj",
		title = "Ahn'Qiraj Breath 3",
		path = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajinterior3.mp3",
		id =  53267,
		duration = 67,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.9 - The Gates of Ahn'Qiraj",
		title = "Ahn'Qiraj Fireflies 1",
		path = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajinteriorintromain.mp3",
		id =  53269,
		duration = 69,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.9 - The Gates of Ahn'Qiraj",
		title = "Ahn'Qiraj Exterior 1",
		path = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajexteriorwalking1.mp3",
		id =  53261,
		duration = 67,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 1.9 - The Gates of Ahn'Qiraj",
		title = "Ahn'Qiraj Exterior 2",
		path = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajexteriorwalking2.mp3",
		id =  53262,
		duration = 84,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 1.9 - The Gates of Ahn'Qiraj",
		title = "Ahn'Qiraj Exterior 3",
		path = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajexteriorwalking3.mp3",
		id =  53263,
		duration = 57,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 1.9 - The Gates of Ahn'Qiraj",
		title = "Ahn'Qiraj Exterior 4",
		path = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajexteriorwalking4.mp3",
		id =  53264,
		duration = 59,
		artist = "Matt Uelmen",
	},	
	{
		album = "WoW 1.9 - The Gates of Ahn'Qiraj",
		title = "Ahn'Qiraj Interior Center Room 1",
		path = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajinteriorcenterroom1.mp3",
		id =  53268,
		duration = 69,
		artist = "Matt Uelmen",
	},	
	{
		album = "WoW 1.9 - The Gates of Ahn'Qiraj",
		title = "Ahn'Qiraj Intro Theme",
		path = "sound\\music\\musical moments\\mystery\\ahnqirajintro1.mp3",
		id =  53239,
		duration = 143,
		artist = "Matt Uelmen",
	},	
	{
		album = "WoW 1.9 - The Gates of Ahn'Qiraj",
		title = "Ahn'Qiraj King Room",
		path = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajkingroom.mp3",
		id =  53270,
		duration = 73,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.9 - The Gates of Ahn'Qiraj",
		title = "Ahn'Qiraj Triangle 1",
		path = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom1.mp3",
		id =  53271,
		duration = 23,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.9 - The Gates of Ahn'Qiraj",
		title = "Ahn'Qiraj Triangle 2",
		path = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom2.mp3",
		id =  53272,
		duration = 17,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.9 - The Gates of Ahn'Qiraj",
		title = "Ahn'Qiraj Triangle 3",
		path = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom3.mp3",
		id =  53273,
		duration = 15,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.9 - The Gates of Ahn'Qiraj",
		title = "Ahn'Qiraj Triangle 4",
		path = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom4.mp3",
		id =  53274,
		duration = 19,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.9 - The Gates of Ahn'Qiraj",
		title = "Ahn'Qiraj Triangle 5",
		path = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom5.mp3",
		id =  53275,
		duration = 31,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.9 - The Gates of Ahn'Qiraj",
		title = "Ahn'Qiraj Triangle 6",
		path = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom6.mp3",
		id =  53276,
		duration = 20,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.9 - The Gates of Ahn'Qiraj",
		title = "Ahn'Qiraj Triangle 7",
		path = "sound\\music\\zonemusic\\ahnqiraj\\ahnqirajtriangleroom7.mp3",
		id =  53277,
		duration = 17,
		artist = "Russell Brower",
	},	
--------------------------------
--Patch 1.11 Music Starts Here--
--------------------------------
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Abomination Boss 1",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramasabominationboss1.mp3",
		id =  53591,
		duration = 61,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Abomination Boss 2",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramasabominationboss2.mp3",
		id =  53592,
		duration = 67,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Abomination Wing 1",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramasabominationwing1.mp3",
		id =  53593,
		duration = 61,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Abomination Wing 2",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramasabominationwing2.mp3",
		id =  53594,
		duration = 66,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Abomination Wing 3",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramasabominationwing3.mp3",
		id =  53595,
		duration = 61,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Frostwyrm 1",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramasfrostwyrm1.mp3",
		id =  53596,
		duration = 57,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Frostwyrm 2",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramasfrostwyrm2.mp3",
		id =  53597,
		duration = 81,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Frostwyrm 3",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramasfrostwyrm3.mp3",
		id =  53598,
		duration = 61,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Frostwyrm 4",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramasfrostwyrm4.mp3",
		id =  53599,
		duration = 60,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Hub Base 1",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramashubbase1.mp3",
		id =  53600,
		duration = 72,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Hub Base 2",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramashubbase2.mp3",
		id =  53601,
		duration = 81,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Kel'Thuzad 1A",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramaskelthuzad1.mp3",
		id =  53602,
		duration = 94,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Kel'Thuzad 2A",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramaskelthuzad2.mp3",
		id =  53603,
		duration = 97,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Kel'Thuzad 3A",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramaskelthuzad3.mp3",
		id =  53604,
		duration = 75,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Plague Boss 1",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramasplagueboss1.mp3",
		id =  53605,
		duration = 86,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Plague Wing 1",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramasplaguewing1.mp3",
		id =  53606,
		duration = 87,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Plague Wing 2",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramasplaguewing2.mp3",
		id =  53607,
		duration = 71,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Plague Wing 3",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramasplaguewing3.mp3",
		id =  53608,
		duration = 76,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Spider Boss 1",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramasspiderboss1.mp3",
		id =  53609,
		duration = 60,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Spider Boss 2",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramasspiderboss2.mp3",
		id =  53610,
		duration = 63,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Spider Wing 1",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramasspiderwing1.mp3",
		id =  53611,
		duration = 88,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Spider Wing 2",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramasspiderwing2.mp3",
		id =  53612,
		duration = 67,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Spider Wing 3",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramasspiderwing3.mp3",
		id =  53613,
		duration = 47,
		artist = "Russell Brower",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Naxxramas Walking 1",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramaswalking1.mp3",
		id =  53614,
		duration = 101,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Naxxramas Walking 2",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramaswalking2.mp3",
		id =  53615,
		duration = 72,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Naxxramas Walking 3",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramaswalking3.mp3",
		id =  53616,
		duration = 86,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Naxxramas Walking 4",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramaswalking4.mp3",
		id =  53617,
		duration = 82,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Naxxramas Walking 5",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramaswalking5.mp3",
		id =  53618,
		duration = 99,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 1.11 - Shadow of the Necropolis",
		title = "Naxxramas Walking 6",
		path = "sound\\music\\zonemusic\\naxxramas\\naxxramaswalking6.mp3",
		id =  53619,
		duration = 99,
		artist = "Matt Uelmen",
	},
	{
		album = "WoW 1.12 - Drums of War",
		title = "PVP 1",
		path = "sound\\music\\zonemusic\\pvp\\pvp1.mp3",
		id =  53684,
		duration = 46,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.12 - Drums of War",
		title = "PVP 2",
		path = "sound\\music\\zonemusic\\pvp\\pvp2.mp3",
		id =  53685,
		duration = 52,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.12 - Drums of War",
		title = "PVP 3",
		path = "sound\\music\\zonemusic\\pvp\\pvp3.mp3",
		id =  53686,
		duration = 40,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.12 - Drums of War",
		title = "PVP 4",
		path = "sound\\music\\zonemusic\\pvp\\pvp4.mp3",
		id =  53687,
		duration = 62,
		artist = "Derek Duke",
	},
	{
		album = "WoW 1.12 - Drums of War",
		title = "PVP 5",
		path = "sound\\music\\zonemusic\\pvp\\pvp5.mp3",
		id =  53688,
		duration = 61,
		artist = "Derek Duke",
	},		
	{
		album = "WarCraft III Expansion",
		title = "Power Of The Horde",
		path = "sound\\music\\zonemusic\\dmf_l70etc01.mp3",
		id =  53438,
		duration = 281,
		artist = "Tenth Level Tauren Chieftain",
	},	
}end)
