local emp = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer", true) ---@class emp
if not emp then return end

-- playlist metadata
local requiredExpansion = "Warlords of Draenor"

emp:RegisterPlaylist(requiredExpansion, function()
return {
	listName = requiredExpansion,
	playlistVersion = "5.0",
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "A Siege of Worlds",
		path = "sound\\music\\draenor\\mus_60_asiegeofworlds_maintitle.mp3",
		id =  1042428,
		duration = 726,
		artist = "Main Title",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "A Hero's Sacrifice v1",
		path = "sound\\music\\draenor\\mus_60_aherossacrifice_v1.mp3",
		id =  1068302,
		duration = 116,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "A Hero's Sacrifice v2",
		path = "sound\\music\\draenor\\mus_60_aherossacrifice_v2.mp3",
		id =  1068303,
		duration = 101,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "A Hero's Sacrifice v3A",
		path = "sound\\music\\draenor\\mus_60_aherossacrifice_v3a.mp3",
		id =  1068304,
		duration = 55,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "A Hero's Sacrifice v3B",
		path = "sound\\music\\draenor\\mus_60_aherossacrifice_v3b.mp3",
		id =  1068305,
		duration = 60,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "A Hero's Sacrifice v4",
		path = "sound\\music\\draenor\\mus_60_aherossacrifice_v4.mp3",
		id =  1068306,
		duration = 24,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "A Hero's Sacrifice v5",
		path = "sound\\music\\draenor\\mus_60_aherossacrifice_v5.mp3",
		id =  1068307,
		duration = 67,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "A Light in the Darkness v1",
		path = "sound\\music\\draenor\\mus_60_alightinthedarkness_v1.mp3",
		id =  1068308,
		duration = 155,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "A Light in the Darkness v2",
		path = "sound\\music\\draenor\\mus_60_alightinthedarkness_v2.mp3",
		id =  1068309,
		duration = 137,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "A Light in the Darkness v3",
		path = "sound\\music\\draenor\\mus_60_alightinthedarkness_v3.mp3",
		id =  1061098,
		duration = 153,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "A Light in the Darkness v3A",
		path = "sound\\music\\draenor\\mus_60_alightinthedarkness_v3a.mp3",
		id =  1061099,
		duration = 69,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Arak 2 H",
		path = "sound\\music\\draenor\\mus_60_arak2_h.mp3",
		id =  1064152,
		duration = 157,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Army Life H",
		path = "sound\\music\\draenor\\mus_60_armylife_h.mp3",
		id =  1064153,
		duration = 141,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Army A",
		path = "sound\\music\\draenor\\mus_60_army_a.mp3",
		id =  1080405,
		duration = 142,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Army Stinger1",
		path = "sound\\music\\draenor\\mus_60_army_stinger1.mp3",
		id =  1080406,
		duration = 11,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Army Stinger2",
		path = "sound\\music\\draenor\\mus_60_army_stinger2.mp3",
		id =  1080407,
		duration = 12,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "A Siege of Worlds v2",
		path = "sound\\music\\draenor\\mus_60_asiegeofworlds_maintitle.mp3",
		id =  1042428,
		duration = 726,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "BFreedom H1",
		path = "sound\\music\\draenor\\mus_60_bfreedom_h1.mp3",
		id =  1064154,
		duration = 67,
		artist = "Craig Stuart Garfinkle",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "BFreedom H2",
		path = "sound\\music\\draenor\\mus_60_bfreedom_h2.mp3",
		id =  1064155,
		duration = 106,
		artist = "Craig Stuart Garfinkle",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Blackrock A",
		path = "sound\\music\\draenor\\mus_60_blackrock_a.mp3",
		id =  1080491,
		duration = 83,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Blackrock B",
		path = "sound\\music\\draenor\\mus_60_blackrock_b.mp3",
		id =  1080492,
		duration = 41,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Blackrock C",
		path = "sound\\music\\draenor\\mus_60_blackrock_c.mp3",
		id =  1080493,
		duration = 39,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Blackrock D",
		path = "sound\\music\\draenor\\mus_60_blackrock_d.mp3",
		id =  1080494,
		duration = 8,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Blackrock E",
		path = "sound\\music\\draenor\\mus_60_blackrock_e.mp3",
		id =  1080495,
		duration = 37,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Blackrock H",
		path = "sound\\music\\draenor\\mus_60_blackrock_h.mp3",
		id =  1080496,
		duration = 188,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Call of the Warrior A",
		path = "sound\\music\\draenor\\mus_60_callofthewarrior_a.mp3",
		id =  1080518,
		duration = 150,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Call of the Warrior C",
		path = "sound\\music\\draenor\\mus_60_callofthewarrior_c.mp3",
		id =  1080519,
		duration = 150,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Call of the Warrior H",
		path = "sound\\music\\draenor\\mus_60_callofthewarrior_h.mp3",
		id =  1080520,
		duration = 150,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Caverns of Life H",
		path = "sound\\music\\draenor\\mus_60_cavernsoflife_h.mp3",
		id =  1064156,
		duration = 112,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Chieftans Gather H",
		path = "sound\\music\\draenor\\mus_60_chieftansgather_h.mp3",
		id =  1067039,
		duration = 96,
		artist = "Eimear Noone",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Cold Mountain Duet H",
		path = "sound\\music\\draenor\\mus_60_coldmountain_duet_h.mp3",
		id =  1080507,
		duration = 156,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Eagle of Draenor H",
		path = "sound\\music\\draenor\\mus_60_eagleofdraenor_h.mp3",
		id =  1064157,
		duration = 126,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Eagle A",
		path = "sound\\music\\draenor\\mus_60_eagle_a.mp3",
		id =  1080408,
		duration = 127,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Eagle B",
		path = "sound\\music\\draenor\\mus_60_eagle_b.mp3",
		id =  1080409,
		duration = 59,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Eagle C",
		path = "sound\\music\\draenor\\mus_60_eagle_c.mp3",
		id =  1080410,
		duration = 30,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Eagle D",
		path = "sound\\music\\draenor\\mus_60_eagle_d.mp3",
		id =  1080411,
		duration = 27,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "Elune's Shadow A",
		path = "sound\\music\\draenor\\mus_60_elunesshadow_a.mp3",
		id =  936323,
		duration = 44,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "Elune's Shadow B",
		path = "sound\\music\\draenor\\mus_60_elunesshadow_b.mp3",
		id =  936324,
		duration = 33,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "Elune's Shadow C",
		path = "sound\\music\\draenor\\mus_60_elunesshadow_c.mp3",
		id =  936325,
		duration = 52,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "Elune's Shadow H",
		path = "sound\\music\\draenor\\mus_60_elunesshadow_h.mp3",
		id =  936326,
		duration = 94,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "Eternal Night H",
		path = "sound\\music\\draenor\\mus_60_eternalnight_h.mp3",
		id =  936327,
		duration = 75,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Ethereal Embers C",
		path = "sound\\music\\draenor\\mus_60_etherealembers_c.mp3",
		id =  1061100,
		duration = 80,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Ethereal Embers D",
		path = "sound\\music\\draenor\\mus_60_etherealembers_d.mp3",
		id =  1061101,
		duration = 79,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Ethereal Embers E",
		path = "sound\\music\\draenor\\mus_60_etherealembers_e.mp3",
		id =  1061102,
		duration = 81,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Ethereal Embers F",
		path = "sound\\music\\draenor\\mus_60_etherealembers_f.mp3",
		id =  1061103,
		duration = 74,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Ethereal Embers H",
		path = "sound\\music\\draenor\\mus_60_etherealembers_h.mp3",
		id =  1061104,
		duration = 79,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Ethereal Essence H1",
		path = "sound\\music\\draenor\\mus_60_etherealessence_h1.mp3",
		id =  1064158,
		duration = 102,
		artist = "Craig Stuart Garfinkle",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Ethereal Essence H2",
		path = "sound\\music\\draenor\\mus_60_etherealessence_h2.mp3",
		id =  1064159,
		duration = 87,
		artist = "Craig Stuart Garfinkle",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "Fel Wasteland A",
		path = "sound\\music\\draenor\\mus_60_felwasteland_a.mp3",
		id =  936328,
		duration = 71,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "Fel Wasteland B",
		path = "sound\\music\\draenor\\mus_60_felwasteland_b.mp3",
		id =  936329,
		duration = 90,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "Fel Wasteland C",
		path = "sound\\music\\draenor\\mus_60_felwasteland_c.mp3",
		id =  936330,
		duration = 31,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "Fel Wasteland H",
		path = "sound\\music\\draenor\\mus_60_felwasteland_h.mp3",
		id =  936331,
		duration = 85,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "Foreshadowing H",
		path = "sound\\music\\draenor\\mus_60_foreshadowing_h.mp3",
		id =  936332,
		duration = 124,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "Forsaken A",
		path = "sound\\music\\draenor\\mus_60_forsaken_a.mp3",
		id =  936333,
		duration = 82,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "Forsaken H",
		path = "sound\\music\\draenor\\mus_60_forsaken_h.mp3",
		id =  936334,
		duration = 124,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "Gardens of Karabor A",
		path = "sound\\music\\draenor\\mus_60_gardensofkarabor_a.mp3",
		id =  936335,
		duration = 99,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "Gardens of Karabor B",
		path = "sound\\music\\draenor\\mus_60_gardensofkarabor_b.mp3",
		id =  936336,
		duration = 47,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "Gardens of Karabor H",
		path = "sound\\music\\draenor\\mus_60_gardensofkarabor_h.mp3",
		id =  936337,
		duration = 126,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Garrison Building Complete",
		path = "sound\\music\\draenor\\mus_60_garrisonbuildingcomplete.mp3",
		id =  1080412,
		duration = 13,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Garrison Building Complete v2",
		path = "sound\\music\\draenor\\mus_60_garrisonbuildingcomplete2.mp3",
		id =  1087470,
		duration = 8,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Grinspiration A",
		path = "sound\\music\\draenor\\mus_60_grinspiration_a.mp3",
		id =  1067040,
		duration = 89,
		artist = "Craig Stuart Garfinkle",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Grinspiration B",
		path = "sound\\music\\draenor\\mus_60_grinspiration_b.mp3",
		id =  1067041,
		duration = 81,
		artist = "Craig Stuart Garfinkle",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Grinspiration C",
		path = "sound\\music\\draenor\\mus_60_grinspiration_c.mp3",
		id =  1067042,
		duration = 123,
		artist = "Craig Stuart Garfinkle",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Grinspiration H1",
		path = "sound\\music\\draenor\\mus_60_grinspiration_h1.mp3",
		id =  1067043,
		duration = 101,
		artist = "Craig Stuart Garfinkle",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Grinspiration H2",
		path = "sound\\music\\draenor\\mus_60_grinspiration_h2.mp3",
		id =  1067044,
		duration = 84,
		artist = "Craig Stuart Garfinkle",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Grommash Hellscream v3",
		path = "sound\\music\\draenor\\mus_60_grommashhellscreamv_3.mp3",
		id =  1061108,
		duration = 72,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Grommash Hellscream v1",
		path = "sound\\music\\draenor\\mus_60_grommashhellscream_v1.mp3",
		id =  1061105,
		duration = 165,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Grommash Hellscream v2A",
		path = "sound\\music\\draenor\\mus_60_grommashhellscream_v2a.mp3",
		id =  1061106,
		duration = 47,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Grommash Hellscream v2B",
		path = "sound\\music\\draenor\\mus_60_grommashhellscream_v2b.mp3",
		id =  1061107,
		duration = 55,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Herding Clans H",
		path = "sound\\music\\draenor\\mus_60_herdingclans_h.mp3",
		id =  1064160,
		duration = 131,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Iron Dawn v1",
		path = "sound\\music\\draenor\\mus_60_irondawn_v1.mp3",
		id =  1061109,
		duration = 150,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Iron Dawn v2",
		path = "sound\\music\\draenor\\mus_60_irondawn_v2.mp3",
		id =  1061110,
		duration = 97,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Iron Dawn v3A",
		path = "sound\\music\\draenor\\mus_60_irondawn_v3a.mp3",
		id =  1061111,
		duration = 59,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Iron Dawn v3B",
		path = "sound\\music\\draenor\\mus_60_irondawn_v3b.mp3",
		id =  1061112,
		duration = 75,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Iron Dawn v4",
		path = "sound\\music\\draenor\\mus_60_irondawn_v4.mp3",
		id =  1061113,
		duration = 154,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Keepers of the Temple H",
		path = "sound\\music\\draenor\\mus_60_keepersofthetemple_h.mp3",
		id =  1067045,
		duration = 190,
		artist = "Eimear Noone",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Khadgar's Plan v1",
		path = "sound\\music\\draenor\\mus_60_khadgarsplan_v1.mp3",
		id =  1061114,
		duration = 144,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Khadgar's Plan v2",
		path = "sound\\music\\draenor\\mus_60_khadgarsplan_v2.mp3",
		id =  1061115,
		duration = 127,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Khadgar's Plan v3",
		path = "sound\\music\\draenor\\mus_60_khadgarsplan_v3.mp3",
		id =  1061116,
		duration = 139,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Khadgar's Plan v4",
		path = "sound\\music\\draenor\\mus_60_khadgarsplan_v4.mp3",
		id =  1061117,
		duration = 114,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Laborious Misery A",
		path = "sound\\music\\draenor\\mus_60_laboriousmisery_a.mp3",
		id =  1061118,
		duration = 68,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Laborious Misery H",
		path = "sound\\music\\draenor\\mus_60_laboriousmisery_h.mp3",
		id =  1061119,
		duration = 69,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Magnificent Desolation 2A1",
		path = "sound\\music\\draenor\\mus_60_magnificentdesolation2_a1.mp3",
		id =  1067555,
		duration = 83,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Magnificent Desolation 2A2",
		path = "sound\\music\\draenor\\mus_60_magnificentdesolation2_a2.mp3",
		id =  1067556,
		duration = 97,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Magnificent Desolation 2H",
		path = "sound\\music\\draenor\\mus_60_magnificentdesolation2_h.mp3",
		id =  1067557,
		duration = 239,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Magnificent Desolation 2H1",
		path = "sound\\music\\draenor\\mus_60_magnificentdesolation2_h1.mp3",
		id =  1067558,
		duration = 130,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Magnificent Desolation 2H2",
		path = "sound\\music\\draenor\\mus_60_magnificentdesolation2_h2.mp3",
		id =  1067559,
		duration = 111,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "Magnificent Desolation A",
		path = "sound\\music\\draenor\\mus_60_magnificentdesolation_a.mp3",
		id =  936338,
		duration = 236,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "Magnificent Desolation B",
		path = "sound\\music\\draenor\\mus_60_magnificentdesolation_b.mp3",
		id =  936339,
		duration = 158,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "Magnificent Desolation H",
		path = "sound\\music\\draenor\\mus_60_magnificentdesolation_h.mp3",
		id =  936340,
		duration = 236,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Magnificent Desolation Piano A",
		path = "sound\\music\\draenor\\mus_60_magnificentdesolation_piano_a.mp3",
		id =  1080508,
		duration = 35,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Malach H1",
		path = "sound\\music\\draenor\\mus_60_malach_h1.mp3",
		id =  1067046,
		duration = 127,
		artist = "Eimear Noone",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Malach H2",
		path = "sound\\music\\draenor\\mus_60_malach_h2.mp3",
		id =  1067047,
		duration = 139,
		artist = "Eimear Noone",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Malach H3",
		path = "sound\\music\\draenor\\mus_60_malach_h3.mp3",
		id =  1067048,
		duration = 46,
		artist = "Eimear Noone",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Malach H4",
		path = "sound\\music\\draenor\\mus_60_malach_h4.mp3",
		id =  1067049,
		duration = 66,
		artist = "Eimear Noone",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Malevolent Mystique A",
		path = "sound\\music\\draenor\\mus_60_malevolentmystique_a.mp3",
		id =  1061120,
		duration = 78,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Malevolent Mystique B1",
		path = "sound\\music\\draenor\\mus_60_malevolentmystique_b1.mp3",
		id =  1061121,
		duration = 78,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Malevolent Mystique B2",
		path = "sound\\music\\draenor\\mus_60_malevolentmystique_b2.mp3",
		id =  1061122,
		duration = 88,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Malevolent Mystique C",
		path = "sound\\music\\draenor\\mus_60_malevolentmystique_c.mp3",
		id =  1061123,
		duration = 90,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Malevolent Mystique H",
		path = "sound\\music\\draenor\\mus_60_malevolentmystique_h.mp3",
		id =  1061124,
		duration = 124,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Malevolent Prescience B",
		path = "sound\\music\\draenor\\mus_60_malevolentprescience_b.mp3",
		id =  1061125,
		duration = 66,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Malevolent Prescience H",
		path = "sound\\music\\draenor\\mus_60_malevolentprescience_h.mp3",
		id =  1061126,
		duration = 145,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Man Down A1",
		path = "sound\\music\\draenor\\mus_60_mandown_a1.mp3",
		id =  1061127,
		duration = 62,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Man Down A2",
		path = "sound\\music\\draenor\\mus_60_mandown_a2.mp3",
		id =  1061128,
		duration = 60,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Man Down A3",
		path = "sound\\music\\draenor\\mus_60_mandown_a3.mp3",
		id =  1061129,
		duration = 61,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Man Down B",
		path = "sound\\music\\draenor\\mus_60_mandown_b.mp3",
		id =  1061130,
		duration = 82,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Man Down C",
		path = "sound\\music\\draenor\\mus_60_mandown_c.mp3",
		id =  1061131,
		duration = 82,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Man Down D",
		path = "sound\\music\\draenor\\mus_60_mandown_d.mp3",
		id =  1061132,
		duration = 168,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Man Down E",
		path = "sound\\music\\draenor\\mus_60_mandown_e.mp3",
		id =  1061133,
		duration = 102,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Man Down F",
		path = "sound\\music\\draenor\\mus_60_mandown_f.mp3",
		id =  1061134,
		duration = 89,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Man Down H1",
		path = "sound\\music\\draenor\\mus_60_mandown_h1.mp3",
		id =  1061135,
		duration = 60,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mobilize A",
		path = "sound\\music\\draenor\\mus_60_mobilize_a.mp3",
		id =  1080413,
		duration = 141,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mobilize B1",
		path = "sound\\music\\draenor\\mus_60_mobilize_b1.mp3",
		id =  1080414,
		duration = 115,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mobilize B2",
		path = "sound\\music\\draenor\\mus_60_mobilize_b2.mp3",
		id =  1080415,
		duration = 107,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mobilize C1",
		path = "sound\\music\\draenor\\mus_60_mobilize_c1.mp3",
		id =  1080416,
		duration = 113,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mobilize C2",
		path = "sound\\music\\draenor\\mus_60_mobilize_c2.mp3",
		id =  1080417,
		duration = 123,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mobilize D",
		path = "sound\\music\\draenor\\mus_60_mobilize_d.mp3",
		id =  1080418,
		duration = 58,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mobilize E Stinger",
		path = "sound\\music\\draenor\\mus_60_mobilize_e_stinger.mp3",
		id =  1080419,
		duration = 22,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mobilize H",
		path = "sound\\music\\draenor\\mus_60_mobilize_h.mp3",
		id =  1064161,
		duration = 157,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mountains Intro Amb1",
		path = "sound\\music\\draenor\\mus_60_mountainsintro_a1.mp3",
		id =  1080423,
		duration = 223,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mountains Intro Amb2",
		path = "sound\\music\\draenor\\mus_60_mountainsintro_a2.mp3",
		id =  1080424,
		duration = 106,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mountains of Nagrand A1",
		path = "sound\\music\\draenor\\mus_60_mountainsofnagrand_a1.mp3",
		id =  1080425,
		duration = 70,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mountains of Nagrand A2",
		path = "sound\\music\\draenor\\mus_60_mountainsofnagrand_a2.mp3",
		id =  1080426,
		duration = 123,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mountains of Nagrand B",
		path = "sound\\music\\draenor\\mus_60_mountainsofnagrand_b.mp3",
		id =  1080427,
		duration = 120,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mountains of Nagrand H",
		path = "sound\\music\\draenor\\mus_60_mountainsofnagrand_h.mp3",
		id =  1064162,
		duration = 193,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mountains Ambient 2",
		path = "sound\\music\\draenor\\mus_60_mountains_ambient2.mp3",
		id =  1080420,
		duration = 72,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mountains Ambient 3",
		path = "sound\\music\\draenor\\mus_60_mountains_ambient3.mp3",
		id =  1080421,
		duration = 81,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mountains Stinger1",
		path = "sound\\music\\draenor\\mus_60_mountains_stinger1.mp3",
		id =  1080422,
		duration = 16,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mystic A1",
		path = "sound\\music\\draenor\\mus_60_mystic_a1.mp3",
		id =  1067050,
		duration = 73,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mystic A2",
		path = "sound\\music\\draenor\\mus_60_mystic_a2.mp3",
		id =  1067051,
		duration = 86,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mystic B1",
		path = "sound\\music\\draenor\\mus_60_mystic_b1.mp3",
		id =  1067052,
		duration = 58,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mystic B2",
		path = "sound\\music\\draenor\\mus_60_mystic_b2.mp3",
		id =  1067053,
		duration = 63,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mystic C",
		path = "sound\\music\\draenor\\mus_60_mystic_c.mp3",
		id =  1067054,
		duration = 68,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mystic C2",
		path = "sound\\music\\draenor\\mus_60_mystic_c2.mp3",
		id =  1067055,
		duration = 87,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mystic D1",
		path = "sound\\music\\draenor\\mus_60_mystic_d1.mp3",
		id =  1067056,
		duration = 65,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mystic D2",
		path = "sound\\music\\draenor\\mus_60_mystic_d2.mp3",
		id =  1067057,
		duration = 83,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mystic E",
		path = "sound\\music\\draenor\\mus_60_mystic_e.mp3",
		id =  1067058,
		duration = 22,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mystic F",
		path = "sound\\music\\draenor\\mus_60_mystic_f.mp3",
		id =  1067059,
		duration = 25,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mystic G",
		path = "sound\\music\\draenor\\mus_60_mystic_g.mp3",
		id =  1067060,
		duration = 15,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Mystic H",
		path = "sound\\music\\draenor\\mus_60_mystic_h.mp3",
		id =  1064163,
		duration = 134,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Nagrand v1",
		path = "sound\\music\\draenor\\mus_60_nagrand_v1.mp3",
		id =  1061136,
		duration = 149,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Nagrand v2",
		path = "sound\\music\\draenor\\mus_60_nagrand_v2.mp3",
		id =  1061137,
		duration = 149,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Nagrand v3A",
		path = "sound\\music\\draenor\\mus_60_nagrand_v3a.mp3",
		id =  1061138,
		duration = 62,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Nagrand v3B",
		path = "sound\\music\\draenor\\mus_60_nagrand_v3b.mp3",
		id =  1061139,
		duration = 57,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Nagrand v4",
		path = "sound\\music\\draenor\\mus_60_nagrand_v4.mp3",
		id =  1061140,
		duration = 86,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Nagrand v5",
		path = "sound\\music\\draenor\\mus_60_nagrand_v5.mp3",
		id =  1061141,
		duration = 79,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Nagrand v6",
		path = "sound\\music\\draenor\\mus_60_nagrand_v6.mp3",
		id =  1061142,
		duration = 133,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Nagrand v7",
		path = "sound\\music\\draenor\\mus_60_nagrand_v7.mp3",
		id =  1061143,
		duration = 88,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Night Spires v1",
		path = "sound\\music\\draenor\\mus_60_nightspires_v1.mp3",
		id =  1061144,
		duration = 135,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Night Spires v2",
		path = "sound\\music\\draenor\\mus_60_nightspires_v2.mp3",
		id =  1061145,
		duration = 115,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Night Spires v3",
		path = "sound\\music\\draenor\\mus_60_nightspires_v3.mp3",
		id =  1061146,
		duration = 134,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Night Spires v4",
		path = "sound\\music\\draenor\\mus_60_nightspires_v4.mp3",
		id =  1061147,
		duration = 121,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Ogre Mines A1",
		path = "sound\\music\\draenor\\mus_60_ogremines_a1.mp3",
		id =  1067560,
		duration = 130,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Ogre Mines A2",
		path = "sound\\music\\draenor\\mus_60_ogremines_a2.mp3",
		id =  1067561,
		duration = 126,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Ogre Mines B",
		path = "sound\\music\\draenor\\mus_60_ogremines_b.mp3",
		id =  1067562,
		duration = 133,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Ogre Mines H1",
		path = "sound\\music\\draenor\\mus_60_ogremines_h1.mp3",
		id =  1067563,
		duration = 131,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Ogre Mines H2",
		path = "sound\\music\\draenor\\mus_60_ogremines_h2.mp3",
		id =  1067564,
		duration = 124,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Patience Point A1",
		path = "sound\\music\\draenor\\mus_60_patiencepoint_a1.mp3",
		id =  1061148,
		duration = 77,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Patience Point A2",
		path = "sound\\music\\draenor\\mus_60_patiencepoint_a2.mp3",
		id =  1061149,
		duration = 97,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Patience Point B1",
		path = "sound\\music\\draenor\\mus_60_patiencepoint_b1.mp3",
		id =  1061150,
		duration = 77,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Patience Point B2",
		path = "sound\\music\\draenor\\mus_60_patiencepoint_b2.mp3",
		id =  1061151,
		duration = 97,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Patience Point H",
		path = "sound\\music\\draenor\\mus_60_patiencepoint_h.mp3",
		id =  1061152,
		duration = 179,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Plight of the Ogres H1",
		path = "sound\\music\\draenor\\mus_60_plightoftheogres_h1.mp3",
		id =  1067061,
		duration = 99,
		artist = "Craig Stuart Garfinkle",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Plight of the Ogres H2",
		path = "sound\\music\\draenor\\mus_60_plightoftheogres_h2.mp3",
		id =  1067062,
		duration = 77,
		artist = "Craig Stuart Garfinkle",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "Premonition H",
		path = "sound\\music\\draenor\\mus_60_premonition_h.mp3",
		id =  936341,
		duration = 131,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Prevalent Confliction A",
		path = "sound\\music\\draenor\\mus_60_prevalentconfliction_a.mp3",
		id =  1061153,
		duration = 94,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Protect the Throne Intro H",
		path = "sound\\music\\draenor\\mus_60_protectthethrone_h1.mp3",
		id =  1067063,
		duration = 67,
		artist = "Eimear Noone",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Protect the Throne H2",
		path = "sound\\music\\draenor\\mus_60_protectthethrone_h2.mp3",
		id =  1067064,
		duration = 98,
		artist = "Eimear Noone",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Protect the Throne H3",
		path = "sound\\music\\draenor\\mus_60_protectthethrone_h3.mp3",
		id =  1067065,
		duration = 92,
		artist = "Eimear Noone",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Proudmoore H",
		path = "sound\\music\\draenor\\mus_60_proudmoore_h.mp3",
		id =  1064164,
		duration = 104,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Quiet Heart A",
		path = "sound\\music\\draenor\\mus_60_quietheart_a.mp3",
		id =  1067565,
		duration = 224,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Quiet Heart A1",
		path = "sound\\music\\draenor\\mus_60_quietheart_a1.mp3",
		id =  1067566,
		duration = 108,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Quiet Heart A2",
		path = "sound\\music\\draenor\\mus_60_quietheart_a2.mp3",
		id =  1067567,
		duration = 116,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Quiet Heart H",
		path = "sound\\music\\draenor\\mus_60_quietheart_h.mp3",
		id =  1067568,
		duration = 229,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Quiet Heart H1",
		path = "sound\\music\\draenor\\mus_60_quietheart_h1.mp3",
		id =  1067569,
		duration = 114,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Quiet Heart H2",
		path = "sound\\music\\draenor\\mus_60_quietheart_h2.mp3",
		id =  1067570,
		duration = 118,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Rise to the Dark H1",
		path = "sound\\music\\draenor\\mus_60_risetothedark_h1.mp3",
		id =  1067066,
		duration = 93,
		artist = "Eimear Noone",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Rise to the Dark H2",
		path = "sound\\music\\draenor\\mus_60_risetothedark_h2.mp3",
		id =  1067067,
		duration = 124,
		artist = "Eimear Noone",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Sacrifice 2A",
		path = "sound\\music\\draenor\\mus_60_sacrifice_2a.mp3",
		id =  1061154,
		duration = 89,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Sacrifice 2H",
		path = "sound\\music\\draenor\\mus_60_sacrifice_2h.mp3",
		id =  1061155,
		duration = 88,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Sacrifice B",
		path = "sound\\music\\draenor\\mus_60_sacrifice_b.mp3",
		id =  1061156,
		duration = 89,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Shadowmoon Pt1A",
		path = "sound\\music\\draenor\\mus_60_shadowmoonpt1_a.mp3",
		id =  1067571,
		duration = 110,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Shadowmoon Pt1H",
		path = "sound\\music\\draenor\\mus_60_shadowmoonpt1_h.mp3",
		id =  1067572,
		duration = 138,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Shadowmoon Rising H",
		path = "sound\\music\\draenor\\mus_60_shadowmoonrising_h.mp3",
		id =  1067068,
		duration = 155,
		artist = "Eimear Noone",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Shadowmoon Sunset Intro H",
		path = "sound\\music\\draenor\\mus_60_shadowmoonsunsetintro_h.mp3",
		id =  1067069,
		duration = 70,
		artist = "Craig Stuart Garfinkle",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Shadowmoon Sunset Reprise H",
		path = "sound\\music\\draenor\\mus_60_shadowmoonsunsetreprise_h.mp3",
		id =  1067070,
		duration = 45,
		artist = "Craig Stuart Garfinkle",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Shadowmoon v1",
		path = "sound\\music\\draenor\\mus_60_shadowmoon_v1.mp3",
		id =  1061157,
		duration = 128,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Shadowmoon v2",
		path = "sound\\music\\draenor\\mus_60_shadowmoon_v2.mp3",
		id =  1061158,
		duration = 127,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Shadowmoon v3",
		path = "sound\\music\\draenor\\mus_60_shadowmoon_v3.mp3",
		id =  1061159,
		duration = 122,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Shadowmoon v4",
		path = "sound\\music\\draenor\\mus_60_shadowmoon_v4.mp3",
		id =  1061160,
		duration = 61,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Shadowmoon v5",
		path = "sound\\music\\draenor\\mus_60_shadowmoon_v5.mp3",
		id =  1061161,
		duration = 94,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Shakedown A",
		path = "sound\\music\\draenor\\mus_60_shakedown_a.mp3",
		id =  1061162,
		duration = 103,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Shakedown B",
		path = "sound\\music\\draenor\\mus_60_shakedown_b.mp3",
		id =  1061163,
		duration = 65,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Shakedown C",
		path = "sound\\music\\draenor\\mus_60_shakedown_c.mp3",
		id =  1061164,
		duration = 102,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Smack the Giant H1",
		path = "sound\\music\\draenor\\mus_60_smackthegiant_h1.mp3",
		id =  1067071,
		duration = 55,
		artist = "Craig Stuart Garfinkle",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Smack the Giant H2",
		path = "sound\\music\\draenor\\mus_60_smackthegiant_h2.mp3",
		id =  1067072,
		duration = 53,
		artist = "Craig Stuart Garfinkle",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Smack the Giant H3",
		path = "sound\\music\\draenor\\mus_60_smackthegiant_h3.mp3",
		id =  1067073,
		duration = 52,
		artist = "Craig Stuart Garfinkle",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Smack the Giant H4",
		path = "sound\\music\\draenor\\mus_60_smackthegiant_h4.mp3",
		id =  1067074,
		duration = 21,
		artist = "Craig Stuart Garfinkle",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Spires of Arak v1",
		path = "sound\\music\\draenor\\mus_60_spiresofarak_v1.mp3",
		id =  1061165,
		duration = 158,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Spires of Arak v2",
		path = "sound\\music\\draenor\\mus_60_spiresofarak_v2.mp3",
		id =  1061166,
		duration = 101,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Spires of Arak v4",
		path = "sound\\music\\draenor\\mus_60_spiresofarak_v4.mp3",
		id =  1061167,
		duration = 56,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Stormlords on the March H1",
		path = "sound\\music\\draenor\\mus_60_stormlordsonthemarch_h1.mp3",
		id =  1067075,
		duration = 88,
		artist = "Eimear Noone",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Stormlords on the March H2",
		path = "sound\\music\\draenor\\mus_60_stormlordsonthemarch_h2.mp3",
		id =  1067076,
		duration = 46,
		artist = "Eimear Noone",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Stormlords on the March H3",
		path = "sound\\music\\draenor\\mus_60_stormlordsonthemarch_h3.mp3",
		id =  1067077,
		duration = 101,
		artist = "Eimear Noone",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "The Clans Join A",
		path = "sound\\music\\draenor\\mus_60_theclansjoin_a.mp3",
		id =  936342,
		duration = 212,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "The Clans Join B",
		path = "sound\\music\\draenor\\mus_60_theclansjoin_b.mp3",
		id =  936343,
		duration = 212,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor (BC)",
		title = "The Clans Join H",
		path = "sound\\music\\draenor\\mus_60_theclansjoin_h.mp3",
		id =  936344,
		duration = 212,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Tome A",
		path = "sound\\music\\draenor\\mus_60_tome_a.mp3",
		id =  1061171,
		duration = 54,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Tome B",
		path = "sound\\music\\draenor\\mus_60_tome_b.mp3",
		id =  1061172,
		duration = 55,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Tome H",
		path = "sound\\music\\draenor\\mus_60_tome_h.mp3",
		id =  1061173,
		duration = 56,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Traversing the Spires A",
		path = "sound\\music\\draenor\\mus_60_traversingthespires_a.mp3",
		id =  1067573,
		duration = 128,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Traversing the Spires B",
		path = "sound\\music\\draenor\\mus_60_traversingthespires_b.mp3",
		id =  1067574,
		duration = 123,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Traversing the Spires C",
		path = "sound\\music\\draenor\\mus_60_traversingthespires_c.mp3",
		id =  1067575,
		duration = 156,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Traversing the Spires H1",
		path = "sound\\music\\draenor\\mus_60_traversingthespires_h1.mp3",
		id =  1067576,
		duration = 128,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Traversing the Spires H2",
		path = "sound\\music\\draenor\\mus_60_traversingthespires_h2.mp3",
		id =  1067577,
		duration = 127,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Ts Have It A",
		path = "sound\\music\\draenor\\mus_60_tshaveit_a.mp3",
		id =  1061174,
		duration = 115,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Ts Have It B",
		path = "sound\\music\\draenor\\mus_60_tshaveit_b.mp3",
		id =  1061175,
		duration = 52,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Ts Have It H",
		path = "sound\\music\\draenor\\mus_60_tshaveit_h.mp3",
		id =  1061177,
		duration = 164,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Village A",
		path = "sound\\music\\draenor\\mus_60_village_a.mp3",
		id =  1067078,
		duration = 151,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Village B",
		path = "sound\\music\\draenor\\mus_60_village_b.mp3",
		id =  1067079,
		duration = 91,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Village C1",
		path = "sound\\music\\draenor\\mus_60_village_c1.mp3",
		id =  1067080,
		duration = 63,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Village C2",
		path = "sound\\music\\draenor\\mus_60_village_c2.mp3",
		id =  1067081,
		duration = 88,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Village D",
		path = "sound\\music\\draenor\\mus_60_village_d.mp3",
		id =  1067082,
		duration = 91,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Village E",
		path = "sound\\music\\draenor\\mus_60_village_e.mp3",
		id =  1067083,
		duration = 9,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Village F",
		path = "sound\\music\\draenor\\mus_60_village_f.mp3",
		id =  1067084,
		duration = 11,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Village H",
		path = "sound\\music\\draenor\\mus_60_village_h.mp3",
		id =  1064165,
		duration = 150,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Voce C",
		path = "sound\\music\\draenor\\mus_60_voce_c.mp3",
		id =  1061178,
		duration = 48,
		artist = "Edo Guidotti",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Vows A1",
		path = "sound\\music\\draenor\\mus_60_vows_a1.mp3",
		id =  1067578,
		duration = 55,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Vows A2",
		path = "sound\\music\\draenor\\mus_60_vows_a2.mp3",
		id =  1067579,
		duration = 49,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Vows A3",
		path = "sound\\music\\draenor\\mus_60_vows_a3.mp3",
		id =  1067580,
		duration = 101,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Vows B",
		path = "sound\\music\\draenor\\mus_60_vows_b.mp3",
		id =  1067581,
		duration = 118,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Vows C1",
		path = "sound\\music\\draenor\\mus_60_vows_c1.mp3",
		id =  1067582,
		duration = 82,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Vows C2",
		path = "sound\\music\\draenor\\mus_60_vows_c2.mp3",
		id =  1067583,
		duration = 98,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Vows C3",
		path = "sound\\music\\draenor\\mus_60_vows_c3.mp3",
		id =  1067584,
		duration = 130,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Vows D1",
		path = "sound\\music\\draenor\\mus_60_vows_d1.mp3",
		id =  1067585,
		duration = 89,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Vows D2",
		path = "sound\\music\\draenor\\mus_60_vows_d2.mp3",
		id =  1067586,
		duration = 86,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Vows H1",
		path = "sound\\music\\draenor\\mus_60_vows_h1.mp3",
		id =  1067587,
		duration = 100,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Vows H2",
		path = "sound\\music\\draenor\\mus_60_vows_h2.mp3",
		id =  1067588,
		duration = 85,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Vows H3",
		path = "sound\\music\\draenor\\mus_60_vows_h3.mp3",
		id =  1067589,
		duration = 103,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Vows H4",
		path = "sound\\music\\draenor\\mus_60_vows_h4.mp3",
		id =  1067590,
		duration = 107,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Vows H5",
		path = "sound\\music\\draenor\\mus_60_vows_h5.mp3",
		id =  1067591,
		duration = 117,
		artist = "Sam Cardon",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Warriors Journey A",
		path = "sound\\music\\draenor\\mus_60_warriorsjourney_a.mp3",
		id =  1067085,
		duration = 65,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Warriors Journey B1",
		path = "sound\\music\\draenor\\mus_60_warriorsjourney_b1.mp3",
		id =  1067086,
		duration = 65,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Warriors Journey B2",
		path = "sound\\music\\draenor\\mus_60_warriorsjourney_b2.mp3",
		id =  1067087,
		duration = 53,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Warriors Journey B3",
		path = "sound\\music\\draenor\\mus_60_warriorsjourney_b3.mp3",
		id =  1067088,
		duration = 66,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Warriors Journey C",
		path = "sound\\music\\draenor\\mus_60_warriorsjourney_c.mp3",
		id =  1067089,
		duration = 17,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Warriors Journey D",
		path = "sound\\music\\draenor\\mus_60_warriorsjourney_d.mp3",
		id =  1067090,
		duration = 16,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Warriors Journey E",
		path = "sound\\music\\draenor\\mus_60_warriorsjourney_e.mp3",
		id =  1067091,
		duration = 17,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Warriors Journey H1",
		path = "sound\\music\\draenor\\mus_60_warriorsjourney_h1.mp3",
		id =  1064166,
		duration = 92,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Warriors Journey H2",
		path = "sound\\music\\draenor\\mus_60_warriorsjourney_h2.mp3",
		id =  1064167,
		duration = 73,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Warriors Journey H3",
		path = "sound\\music\\draenor\\mus_60_warriorsjourney_h3.mp3",
		id =  1064168,
		duration = 72,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Warriors Journey H4",
		path = "sound\\music\\draenor\\mus_60_warriorsjourney_h4.mp3",
		id =  1064169,
		duration = 79,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Warsong v1",
		path = "sound\\music\\draenor\\mus_60_warsong_v1.mp3",
		id =  1064170,
		duration = 153,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Warsong v2",
		path = "sound\\music\\draenor\\mus_60_warsong_v2.mp3",
		id =  1064171,
		duration = 152,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Warsong v3A",
		path = "sound\\music\\draenor\\mus_60_warsong_v3a.mp3",
		id =  1061179,
		duration = 83,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Warsong v3B",
		path = "sound\\music\\draenor\\mus_60_warsong_v3b.mp3",
		id =  1061180,
		duration = 72,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Warsong v4",
		path = "sound\\music\\draenor\\mus_60_warsong_v4.mp3",
		id =  1061181,
		duration = 155,
		artist = "Neal Acree",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Wolf at the Gates A",
		path = "sound\\music\\draenor\\mus_60_wolfatthegates_a.mp3",
		id =  1080510,
		duration = 162,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Wolf at the Gates B",
		path = "sound\\music\\draenor\\mus_60_wolfatthegates_b.mp3",
		id =  1080511,
		duration = 162,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Wolf at the Gates H",
		path = "sound\\music\\draenor\\mus_60_wolfatthegates_h.mp3",
		id =  1080514,
		duration = 162,
		artist = "Jason Hayes",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Wonder A",
		path = "sound\\music\\draenor\\mus_60_wonder_a.mp3",
		id =  1067092,
		duration = 19,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "Wonder H",
		path = "sound\\music\\draenor\\mus_60_wonder_h.mp3",
		id =  1064172,
		duration = 153,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "World Expo A1",
		path = "sound\\music\\draenor\\mus_60_worldexpo_a1.mp3",
		id =  1067093,
		duration = 54,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "World Expo A2",
		path = "sound\\music\\draenor\\mus_60_worldexpo_a2.mp3",
		id =  1067094,
		duration = 54,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "World Expo A3",
		path = "sound\\music\\draenor\\mus_60_worldexpo_a3.mp3",
		id =  1067095,
		duration = 60,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "World Expo B",
		path = "sound\\music\\draenor\\mus_60_worldexpo_b.mp3",
		id =  1067096,
		duration = 15,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "World Expo C",
		path = "sound\\music\\draenor\\mus_60_worldexpo_c.mp3",
		id =  1067097,
		duration = 22,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "World Expo D",
		path = "sound\\music\\draenor\\mus_60_worldexpo_d.mp3",
		id =  1067098,
		duration = 22,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "World Expo E1",
		path = "sound\\music\\draenor\\mus_60_worldexpo_e1.mp3",
		id =  1067099,
		duration = 56,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "World Expo E2",
		path = "sound\\music\\draenor\\mus_60_worldexpo_e2.mp3",
		id =  1067100,
		duration = 64,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "World Expo F1",
		path = "sound\\music\\draenor\\mus_60_worldexpo_f1.mp3",
		id =  1067101,
		duration = 64,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "World Expo F2",
		path = "sound\\music\\draenor\\mus_60_worldexpo_f2.mp3",
		id =  1067102,
		duration = 64,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "World Expo F3",
		path = "sound\\music\\draenor\\mus_60_worldexpo_f3.mp3",
		id =  1067103,
		duration = 39,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "World Expo G",
		path = "sound\\music\\draenor\\mus_60_worldexpo_g.mp3",
		id =  1067104,
		duration = 19,
		artist = "Clint Bajakian",
	},
	{
		album = "WoW 6.0 - Warlords of Draenor",
		title = "World Expo H",
		path = "sound\\music\\draenor\\mus_60_worldexpo_h.mp3",
		id =  1064173,
		duration = 168,
		artist = "Clint Bajakian",
	},
-------------------------------
--Patch 6.0 Music Starts Here--
-------------------------------	
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Falling 1A",
		path = "sound\\music\\draenor\\mus_62_falling_1a.mp3",
		id =  1146873,
		duration = 71,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Falling 1B",
		path = "sound\\music\\draenor\\mus_62_falling_1b.mp3",
		id =  1146874,
		duration = 74,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Falling 2H",
		path = "sound\\music\\draenor\\mus_62_falling_2h.mp3",
		id =  1146875,
		duration = 71,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Fel Essence A",
		path = "sound\\music\\draenor\\mus_62_felessence_a.mp3",
		id =  1146876,
		duration = 86,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Fel Essence B",
		path = "sound\\music\\draenor\\mus_62_felessence_b.mp3",
		id =  1146877,
		duration = 60,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Fel Essence C",
		path = "sound\\music\\draenor\\mus_62_felessence_c.mp3",
		id =  1146878,
		duration = 46,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Fel Essence D",
		path = "sound\\music\\draenor\\mus_62_felessence_d.mp3",
		id =  1146879,
		duration = 48,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Fel Essence H",
		path = "sound\\music\\draenor\\mus_62_felessence_h.mp3",
		id =  1146880,
		duration = 120,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Feu De L'Enfer A",
		path = "sound\\music\\draenor\\mus_62_feudelenfer_a.mp3",
		id =  1146881,
		duration = 116,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Feu De L'Enfer H",
		path = "sound\\music\\draenor\\mus_62_feudelenfer_h.mp3",
		id =  1146882,
		duration = 119,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Lost Moon A",
		path = "sound\\music\\draenor\\mus_62_lostmoon_a.mp3",
		id =  1146883,
		duration = 79,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Lost Moon B",
		path = "sound\\music\\draenor\\mus_62_lostmoon_b.mp3",
		id =  1146884,
		duration = 60,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Lost Moon H",
		path = "sound\\music\\draenor\\mus_62_lostmoon_h.mp3",
		id =  1146885,
		duration = 88,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Mortal Night A",
		path = "sound\\music\\draenor\\mus_62_mortalnight_a.mp3",
		id =  1146886,
		duration = 50,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Mortal Night B",
		path = "sound\\music\\draenor\\mus_62_mortalnight_b.mp3",
		id =  1146887,
		duration = 13,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Mortal Night C",
		path = "sound\\music\\draenor\\mus_62_mortalnight_c.mp3",
		id =  1146888,
		duration = 74,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Mortal Night H",
		path = "sound\\music\\draenor\\mus_62_mortalnight_h.mp3",
		id =  1146889,
		duration = 152,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Tanaander A",
		path = "sound\\music\\draenor\\mus_62_tanaander_a.mp3",
		id =  1146890,
		duration = 118,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Tanaander B",
		path = "sound\\music\\draenor\\mus_62_tanaander_b.mp3",
		id =  1146891,
		duration = 118,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Tanaander C",
		path = "sound\\music\\draenor\\mus_62_tanaander_c.mp3",
		id =  1146892,
		duration = 125,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Tanaander H",
		path = "sound\\music\\draenor\\mus_62_tanaander_h.mp3",
		id =  1146893,
		duration = 125,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Tanaan Gloom A",
		path = "sound\\music\\draenor\\mus_62_tanaangloom_a.mp3",
		id =  1146894,
		duration = 109,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Tanaan Gloom B",
		path = "sound\\music\\draenor\\mus_62_tanaangloom_b.mp3",
		id =  1146895,
		duration = 103,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Tanaan Gloom C",
		path = "sound\\music\\draenor\\mus_62_tanaangloom_c.mp3",
		id =  1146896,
		duration = 62,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Tanaan Gloom H",
		path = "sound\\music\\draenor\\mus_62_tanaangloom_h.mp3",
		id =  1146897,
		duration = 114,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "The Wanderer A",
		path = "sound\\music\\draenor\\mus_62_thewanderer_a.mp3",
		id =  1146898,
		duration = 138,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "The Wanderer B",
		path = "sound\\music\\draenor\\mus_62_thewanderer_b.mp3",
		id =  1146899,
		duration = 71,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "The Wanderer H",
		path = "sound\\music\\draenor\\mus_62_thewanderer_h.mp3",
		id =  1146900,
		duration = 161,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Undaunted A",
		path = "sound\\music\\draenor\\mus_62_undaunted_a.mp3",
		id =  1146901,
		duration = 101,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Undaunted B",
		path = "sound\\music\\draenor\\mus_62_undaunted_b.mp3",
		id =  1146902,
		duration = 87,
		artist = "Russell Brower",
	},
	{
		album = "WoW 6.2 - Fury of Hellfire",
		title = "Undaunted H",
		path = "sound\\music\\draenor\\mus_62_undaunted_h.mp3",
		id =  1146903,
		duration = 101,
		artist = "Russell Brower",
	},
	{
		album = "WoW 3.3 - Fall of the Lich King",
		title = "Invincible",
		path = "sound\\music\\draenor\\mus_invincible.mp3",
		id =  1100052,
		duration = 197,
		artist = "Russell Brower",
	},
}end)