-- I dceided to not add these files despite dem being under /sound/music/ 
-- If you want them added remove the # from the filme name in the toc. 
local _, _, _, tocversion = GetBuildInfo()

local L = LibStub("AceLocale-3.0"):GetLocale("EpicMusicPlayer")

local Ignored = {
  ["listName"] = "Ignored",
  ["playlistVersion"] = "4.0",
  ["locked"] =  "true",
  {
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 40 Ufs Unsheathgun Load",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_40_ufs_unsheathgun_load.mp3",
		["Length"] = 1,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "2109035",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 80 Ard Anvil Strike",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_80_ard_anvil_strike.ogg",
		["Length"] = 2,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "2174245",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 80 Kag Transitionfx In Old",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_80_kag_transitionfx_in_old.ogg",
		["Length"] = 4,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "2202399",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 80 Kag Transitionfx Out",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_80_kag_transitionfx_out.ogg",
		["Length"] = 5,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "2202398",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 80 Trogs Attack Warning Bell Sweetener",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_80_trogs_attack_warning_bell_sweetener.ogg",
		["Length"] = 6,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "1880888",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 80 Tsc Shipwreck",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_80_tsc_shipwreck.ogg",
		["Length"] = 9,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "2174875",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 80 Tsc Shipwreck Groan",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_80_tsc_shipwreck_groan.ogg",
		["Length"] = 7,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "2174876",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 80 Tsc Windy",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_80_tsc_windy.ogg",
		["Length"] = 7,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "2174877",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 80 Vzi Lightningbolt Shoot",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_80_vzi_lightningbolt_shoot.ogg",
		["Length"] = 3,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "2182421",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 815 Revealofnzoth Tentacleloop",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_815_revealofnzoth_tentacleloop.ogg",
		["Length"] = 4,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "2843500",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 815 Zdb Bowcreak",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_815_zdb_bowcreak.ogg",
		["Length"] = 1,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "2851181",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 815 Zdb Bowcreak 02 Fast",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_815_zdb_bowcreak_02_fast.ogg",
		["Length"] = 1,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "2851182",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 815 Zdb Marching",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_815_zdb_marching.ogg",
		["Length"] = 8,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "2851183",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 815 Zdb Marching 04",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_815_zdb_marching_04.ogg",
		["Length"] = 7,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "2851184",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 81 Tnw Battlebg Weapons Loop",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_81_tnw_battlebg_weapons_loop.ogg",
		["Length"] = 9,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "2565266",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 81 Wsw Harpoon Impact",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_81_wsw_harpoon_impact.ogg",
		["Length"] = 1,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "2565249",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 81 Zuldazarraid Jaina Iceberg Transition Ice Cast 01 03",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_81_zuldazarraid_jaina_iceberg_transition_ice_cast_01_03.ogg",
		["Length"] = 2,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "2563774",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 825 Wcg Chestthump A Nested",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_825_wcg_chestthump_a_nested.ogg",
		["Length"] = 1,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "3090075",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 825 Wcg Chestthump B Nested",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_825_wcg_chestthump_b_nested.ogg",
		["Length"] = 1,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "3090076",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 825 Wcg Horde Kneel",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_825_wcg_horde_kneel.ogg",
		["Length"] = 5,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "3090074",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 825 Wcg Horn",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_825_wcg_horn.ogg",
		["Length"] = 12,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "3088224",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 82 Mce Azerite Cast Sweetener",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_82_mce_azerite_cast_sweetener.ogg",
		["Length"] = 5,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "2974009",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 82 Mvr Dragon Wound 02",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_82_mvr_dragon_wound_02.mp3",
		["Length"] = 7,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "3014245",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 82 Nsa Alliance Naga Horn",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_82_nsa_alliance_naga_horn.ogg",
		["Length"] = 8,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "3034388",
	},
	{
		["Album"] = "WoW: Battleforazeroth",
		["Song"] = "Rtc 82 Nsa Alliance Naga Walla",
		["Name"] = "sound\\music\\battleforazeroth\\rtc_82_nsa_alliance_naga_walla.ogg",
		["Length"] = 7,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "3034335",
	},
  {
		["Album"] = "WoW: Mus_Soundtest_Music01.Mp3",
		["Song"] = "MUS_SoundTest_Music01",
		["Name"] = "sound\\music\\mus_soundtest_music01.mp3",
		["Length"] = 0,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "629319",
	},
	{
		["Album"] = "WoW: Mus_Soundtest_Music02.Mp3",
		["Song"] = "MUS_SoundTest_Music02",
		["Name"] = "sound\\music\\mus_soundtest_music02.mp3",
		["Length"] = 0,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "629320",
	},
	{
		["Album"] = "WoW: Mus_Soundtest_Music03.Mp3",
		["Song"] = "MUS_SoundTest_Music03",
		["Name"] = "sound\\music\\mus_soundtest_music03.mp3",
		["Length"] = 0,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "629321",
	},
  {
		["Album"] = "WoW 5.2",
		["Song"] = "ThunderKingTrailer_Stinger1",
		["Name"] = "sound\\music\\pandaria\\mus_52_thunderking_c_stinger_01.mp3",
		["Length"] = 4,
		["Artist"] = "Jason Hayes, Arr. Glenn Stafford",
		["WoW"] =  "true",
		["Id"] =  "915822",
	},
  {
		["Album"] = "WoW: Shadowlands",
		["Song"] = "Raid 91 Torghast Sanctum Raid Eye Intro 3885397",
		["Name"] = "sound\\music\\shadowlands\\raid_91_torghast_sanctum_raid_eye_intro_3885397.mp3",
		["Length"] = 12,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "3885397",
	},
  -- currupt file?
  {
		["Album"] = "WoW: Shadowlands",
		["Song"] = "COV Seat Of The Primus 01",
		["Name"] = "sound\\music\\shadowlands\\mus_mx_cov_seatoftheprimus_01.mp3",
		["Length"] = 181,
		["Artist"] = "",
		["WoW"] =  "true",
		["Id"] =  "3931650",
	},
}

local EpicMusicPlayer = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer")

if not EpicMusicPlayer then return end

EpicMusicPlayer:AddPlayList("Ignored", Ignored, false)
