local emp = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer", true) ---@class emp
if not emp then return end

-- playlist metadata
local requiredExpansion = "Classic"

emp:RegisterPlaylist(requiredExpansion, function()
return {
  listName = "Ignored",
  playlistVersion = "5.0",
  {
		album = "WoW: Battleforazeroth",
		title = "Rtc 40 Ufs Unsheathgun Load",
		path = "sound\\music\\battleforazeroth\\rtc_40_ufs_unsheathgun_load.mp3",
		duration = 1,
		artist = "",
		id =  "2109035",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 80 Ard Anvil Strike",
		path = "sound\\music\\battleforazeroth\\rtc_80_ard_anvil_strike.ogg",
		duration = 2,
		artist = "",
		id =  "2174245",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 80 Kag Transitionfx In Old",
		path = "sound\\music\\battleforazeroth\\rtc_80_kag_transitionfx_in_old.ogg",
		duration = 4,
		artist = "",
		id =  "2202399",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 80 Kag Transitionfx Out",
		path = "sound\\music\\battleforazeroth\\rtc_80_kag_transitionfx_out.ogg",
		duration = 5,
		artist = "",
		id =  "2202398",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 80 Trogs Attack Warning Bell Sweetener",
		path = "sound\\music\\battleforazeroth\\rtc_80_trogs_attack_warning_bell_sweetener.ogg",
		duration = 6,
		artist = "",
		id =  "1880888",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 80 Tsc Shipwreck",
		path = "sound\\music\\battleforazeroth\\rtc_80_tsc_shipwreck.ogg",
		duration = 9,
		artist = "",
		id =  "2174875",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 80 Tsc Shipwreck Groan",
		path = "sound\\music\\battleforazeroth\\rtc_80_tsc_shipwreck_groan.ogg",
		duration = 7,
		artist = "",
		id =  "2174876",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 80 Tsc Windy",
		path = "sound\\music\\battleforazeroth\\rtc_80_tsc_windy.ogg",
		duration = 7,
		artist = "",
		id =  "2174877",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 80 Vzi Lightningbolt Shoot",
		path = "sound\\music\\battleforazeroth\\rtc_80_vzi_lightningbolt_shoot.ogg",
		duration = 3,
		artist = "",
		id =  "2182421",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 815 Revealofnzoth Tentacleloop",
		path = "sound\\music\\battleforazeroth\\rtc_815_revealofnzoth_tentacleloop.ogg",
		duration = 4,
		artist = "",
		id =  "2843500",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 815 Zdb Bowcreak",
		path = "sound\\music\\battleforazeroth\\rtc_815_zdb_bowcreak.ogg",
		duration = 1,
		artist = "",
		id =  "2851181",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 815 Zdb Bowcreak 02 Fast",
		path = "sound\\music\\battleforazeroth\\rtc_815_zdb_bowcreak_02_fast.ogg",
		duration = 1,
		artist = "",
		id =  "2851182",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 815 Zdb Marching",
		path = "sound\\music\\battleforazeroth\\rtc_815_zdb_marching.ogg",
		duration = 8,
		artist = "",
		id =  "2851183",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 815 Zdb Marching 04",
		path = "sound\\music\\battleforazeroth\\rtc_815_zdb_marching_04.ogg",
		duration = 7,
		artist = "",
		id =  "2851184",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 81 Tnw Battlebg Weapons Loop",
		path = "sound\\music\\battleforazeroth\\rtc_81_tnw_battlebg_weapons_loop.ogg",
		duration = 9,
		artist = "",
		id =  "2565266",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 81 Wsw Harpoon Impact",
		path = "sound\\music\\battleforazeroth\\rtc_81_wsw_harpoon_impact.ogg",
		duration = 1,
		artist = "",
		id =  "2565249",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 81 Zuldazarraid Jaina Iceberg Transition Ice Cast 01 03",
		path = "sound\\music\\battleforazeroth\\rtc_81_zuldazarraid_jaina_iceberg_transition_ice_cast_01_03.ogg",
		duration = 2,
		artist = "",
		id =  "2563774",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 825 Wcg Chestthump A Nested",
		path = "sound\\music\\battleforazeroth\\rtc_825_wcg_chestthump_a_nested.ogg",
		duration = 1,
		artist = "",
		id =  "3090075",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 825 Wcg Chestthump B Nested",
		path = "sound\\music\\battleforazeroth\\rtc_825_wcg_chestthump_b_nested.ogg",
		duration = 1,
		artist = "",
		id =  "3090076",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 825 Wcg Horde Kneel",
		path = "sound\\music\\battleforazeroth\\rtc_825_wcg_horde_kneel.ogg",
		duration = 5,
		artist = "",
		id =  "3090074",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 825 Wcg Horn",
		path = "sound\\music\\battleforazeroth\\rtc_825_wcg_horn.ogg",
		duration = 12,
		artist = "",
		id =  "3088224",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 82 Mce Azerite Cast Sweetener",
		path = "sound\\music\\battleforazeroth\\rtc_82_mce_azerite_cast_sweetener.ogg",
		duration = 5,
		artist = "",
		id =  "2974009",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 82 Mvr Dragon Wound 02",
		path = "sound\\music\\battleforazeroth\\rtc_82_mvr_dragon_wound_02.mp3",
		duration = 7,
		artist = "",
		id =  "3014245",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 82 Nsa Alliance Naga Horn",
		path = "sound\\music\\battleforazeroth\\rtc_82_nsa_alliance_naga_horn.ogg",
		duration = 8,
		artist = "",
		id =  "3034388",
	},
	{
		album = "WoW: Battleforazeroth",
		title = "Rtc 82 Nsa Alliance Naga Walla",
		path = "sound\\music\\battleforazeroth\\rtc_82_nsa_alliance_naga_walla.ogg",
		duration = 7,
		artist = "",
		id =  "3034335",
	},
  {
		album = "WoW: Mus_Soundtest_Music01.Mp3",
		title = "MUS_SoundTest_Music01",
		path = "sound\\music\\mus_soundtest_music01.mp3",
		duration = 0,
		artist = "",
		id =  "629319",
	},
	{
		album = "WoW: Mus_Soundtest_Music02.Mp3",
		title = "MUS_SoundTest_Music02",
		path = "sound\\music\\mus_soundtest_music02.mp3",
		duration = 0,
		artist = "",
		id =  "629320",
	},
	{
		album = "WoW: Mus_Soundtest_Music03.Mp3",
		title = "MUS_SoundTest_Music03",
		path = "sound\\music\\mus_soundtest_music03.mp3",
		duration = 0,
		artist = "",
		id =  "629321",
	},
  {
		album = "WoW 5.2",
		title = "ThunderKingTrailer_Stinger1",
		path = "sound\\music\\pandaria\\mus_52_thunderking_c_stinger_01.mp3",
		duration = 4,
		artist = "Jason Hayes, Arr. Glenn Stafford",
		id =  "915822",
	},
  {
		album = "WoW: Shadowlands",
		title = "Raid 91 Torghast Sanctum Raid Eye Intro 3885397",
		path = "sound\\music\\shadowlands\\raid_91_torghast_sanctum_raid_eye_intro_3885397.mp3",
		duration = 12,
		artist = "",
		id =  "3885397",
	},
  -- currupt file?
  {
		album = "WoW: Shadowlands",
		title = "COV Seat Of The Primus 01",
		path = "sound\\music\\shadowlands\\mus_mx_cov_seatoftheprimus_01.mp3",
		duration = 181,
		artist = "",
		id =  "3931650",
	},
}end)