--Created by kiatra (https://github.com/Kiatra/EpicMusicPlayer)
local emp = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer", true) ---@class emp
if not emp then return end

-- playlist metadata
local requiredExpansion = "Classic"

emp:RegisterPlaylist(requiredExpansion, function()
	return {
		listName = "Not in Retail?",
		playlistVersion = "5.0",
		{
			album = "WoW: Battleforazeroth",
			title = "Event 80 Teldrassil Burning Walk 2146761",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\event_80_teldrassil_burning_walk_2146761.mp3",
			duration = 0,
			artist = "",
			id = 2146761,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Intro 80 Tirgardesound Glacier 2144149",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\intro_80_tirgardesound_glacier_2144149.mp3",
			duration = 0,
			artist = "",
			id = 2144149,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Intro 80 Zuldazar Paku 2146263",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\intro_80_zuldazar_paku_2146263.mp3",
			duration = 0,
			artist = "",
			id = 2146263,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Bloodmagic D",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_bloodmagic_d.mp3",
			duration = 0,
			artist = "",
			id = 1780906,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Bloodmagic E",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_bloodmagic_e.mp3",
			duration = 0,
			artist = "",
			id = 1780907,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Kultiran Tavern A",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_kultiran_tavern_a.mp3",
			duration = 0,
			artist = "",
			id = 1780925,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Kultiran Tavern B",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_kultiran_tavern_b.mp3",
			duration = 0,
			artist = "",
			id = 1780926,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Kultiran Tavern H",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_kultiran_tavern_h.mp3",
			duration = 0,
			artist = "",
			id = 1780927,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Kultiras Peaks Day 03",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_day_03.mp3",
			duration = 0,
			artist = "",
			id = 2144119,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Kultiras Peaks Night 07",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_night_07.mp3",
			duration = 0,
			artist = "",
			id = 2144133,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Kultiras Peaks Night 08",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_night_08.mp3",
			duration = 0,
			artist = "",
			id = 2144134,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Kultiras Sky B",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_b.mp3",
			duration = 0,
			artist = "",
			id = 2144137,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Kultiras Stone Day 02",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_day_02.mp3",
			duration = 0,
			artist = "",
			id = 2144163,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Kultiras Stone Day 06",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_day_06.mp3",
			duration = 0,
			artist = "",
			id = 2144167,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Kultiras Stone Day 08",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_day_08.mp3",
			duration = 0,
			artist = "",
			id = 2144169,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Kultiras Stone Day 09",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_day_09.mp3",
			duration = 0,
			artist = "",
			id = 2144170,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Kultiras Stone Night 05",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_night_05.mp3",
			duration = 0,
			artist = "",
			id = 2144179,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Kultiras Stone Night 08",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_night_08.mp3",
			duration = 0,
			artist = "",
			id = 2144182,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Pointofimpact A",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_pointofimpact_a.mp3",
			duration = 0,
			artist = "",
			id = 1780936,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Pointofimpact B",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_pointofimpact_b.mp3",
			duration = 0,
			artist = "",
			id = 1780937,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Pointofimpact C",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_pointofimpact_c.mp3",
			duration = 0,
			artist = "",
			id = 1780938,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Pointofimpact D",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_pointofimpact_d.mp3",
			duration = 0,
			artist = "",
			id = 1780939,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Pointofimpact H",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_pointofimpact_h.mp3",
			duration = 0,
			artist = "",
			id = 1780940,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Rtc Zzf",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_rtc_zzf.mp3",
			duration = 0,
			artist = "",
			id = 2198107,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Stormsong F",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_stormsong_f.mp3",
			duration = 0,
			artist = "",
			id = 2150460,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Zuldazarjungle B",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_b.mp3",
			duration = 0,
			artist = "",
			id = 2143544,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Zuldazarjungle C",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_c.mp3",
			duration = 0,
			artist = "",
			id = 2143545,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Zuldazarjungle D",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_d.mp3",
			duration = 0,
			artist = "",
			id = 2148032,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Zuldazarjungle G",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_g.mp3",
			duration = 0,
			artist = "",
			id = 2148035,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Zuldazarjungle J",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_j.mp3",
			duration = 0,
			artist = "",
			id = 2148037,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Zuldazarjungle K",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_k.mp3",
			duration = 0,
			artist = "",
			id = 2148038,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Zuldazarjungle M",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_m.mp3",
			duration = 0,
			artist = "",
			id = 2148040,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Zuldazarjungle N",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_n.mp3",
			duration = 0,
			artist = "",
			id = 2148041,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Zuldazarjungle P",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_p.mp3",
			duration = 0,
			artist = "",
			id = 2148043,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Zuldazarjungle R",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_r.mp3",
			duration = 0,
			artist = "",
			id = 2148045,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Zuldazarjungle S",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_s.mp3",
			duration = 0,
			artist = "",
			id = 2148046,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Zone 80 Stormsongvalley Walk 2144154",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\zone_80_stormsongvalley_walk_2144154.mp3",
			duration = 0,
			artist = "",
			id = 2144154,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Zone 80 Tiragardesound Lumberyard 2144166",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\zone_80_tiragardesound_lumberyard_2144166.mp3",
			duration = 0,
			artist = "",
			id = 2144166,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Zone 80 Tiragardesound Vigilhill 2144168",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\zone_80_tiragardesound_vigilhill_2144168.mp3",
			duration = 0,
			artist = "",
			id = 2144168,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Zone 80 Tiragardesound Walk 2144136",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\zone_80_tiragardesound_walk_2144136.mp3",
			duration = 0,
			artist = "",
			id = 2144136,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Zone 80 Voldun Generalwalk 2145687",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\zone_80_voldun_generalwalk_2145687.mp3",
			duration = 0,
			artist = "",
			id = 2145687,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Zone 80 Voldun Generalwalk 2145691",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\zone_80_voldun_generalwalk_2145691.mp3",
			duration = 0,
			artist = "",
			id = 2145691,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Zone 80 Voldun Generalwalk 2145692",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\zone_80_voldun_generalwalk_2145692.mp3",
			duration = 0,
			artist = "",
			id = 2145692,
		},
		{
			album = "WoW: Battleforazeroth",
			title = "Zone 80 Voldun Generalwalk 2145693",
			tagged_title = "",
			path = "sound\\music\\battleforazeroth\\zone_80_voldun_generalwalk_2145693.mp3",
			duration = 0,
			artist = "",
			id = 2145693,
		},
		{
			album = "WoW: Classic",
			title = "Karazhan Crypts 1",
			tagged_title = "",
			path = "sound\\music\\classic\\mus_115_karazhan_crypts_1.mp3",
			duration = 0,
			artist = "",
			id = 6653571,
		},
		{
			album = "WoW: Classic",
			title = "Karazhan Crypts 2",
			tagged_title = "",
			path = "sound\\music\\classic\\mus_115_karazhan_crypts_2.mp3",
			duration = 0,
			artist = "",
			id = 6653573,
		},
		{
			album = "WoW: Classic",
			title = "Karazhan Crypts 3",
			tagged_title = "",
			path = "sound\\music\\classic\\mus_115_karazhan_crypts_3.mp3",
			duration = 0,
			artist = "",
			id = 6653575,
		},
		{
			album = "WoW: Draenor",
			title = "Strangefever A",
			tagged_title = "",
			path = "sound\\music\\draenor\\mus_60_strangefever_a.mp3",
			duration = 0,
			artist = "",
			id = 1061168,
		},
		{
			album = "WoW: Draenor",
			title = "Strangefever C",
			tagged_title = "",
			path = "sound\\music\\draenor\\mus_60_strangefever_c.mp3",
			duration = 0,
			artist = "",
			id = 1061169,
		},
		{
			album = "WoW: Draenor",
			title = "Strangefever H",
			tagged_title = "",
			path = "sound\\music\\draenor\\mus_60_strangefever_h.mp3",
			duration = 0,
			artist = "",
			id = 1061170,
		},
		{
			album = "WoW: Draenor",
			title = "Tshaveit C",
			tagged_title = "",
			path = "sound\\music\\draenor\\mus_60_tshaveit_c.mp3",
			duration = 0,
			artist = "",
			id = 1061176,
		},
		{
			album = "WoW: Dragonflight",
			title = "Zone 100 Forbiddenreach Outdoor Walk 01",
			tagged_title = "",
			path = "sound\\music\\dragonflight\\zone_100_forbiddenreach_outdoor_walk_01.mp3",
			duration = 0,
			artist = "",
			id = 4872444,
		},
		{
			album = "WoW: Dragonflight",
			title = "Zone 100 Forbiddenreach Outdoor Walk 02",
			tagged_title = "",
			path = "sound\\music\\dragonflight\\zone_100_forbiddenreach_outdoor_walk_02.mp3",
			duration = 0,
			artist = "",
			id = 4872446,
		},
		{
			album = "WoW: Legion",
			title = "Dmf 725 Blightboar Lament",
			tagged_title = "",
			path = "sound\\music\\legion\\dmf_725_blightboar_lament.ogg",
			duration = 0,
			artist = "",
			id = 1674361,
		},
		{
			album = "WoW: Shadowlands",
			title = "Aw Nocturne Hunger D",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_hunger_d.mp3",
			duration = 0,
			artist = "",
			id = 3853372,
		},
		{
			album = "WoW: Shadowlands",
			title = "Aw Nocturne Hunger E",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_90_aw_nocturne_hunger_e.mp3",
			duration = 0,
			artist = "",
			id = 3853374,
		},
		{
			album = "WoW: Shadowlands",
			title = "Mx Deathisabattlefield Ambient H",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_90_mx_deathisabattlefield_ambient_h.mp3",
			duration = 0,
			artist = "",
			id = 3853612,
		},
		{
			album = "WoW: Shadowlands",
			title = "Mx Sansprimus Hero Sting A",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_sting_a.mp3",
			duration = 0,
			artist = "",
			id = 3853690,
		},
		{
			album = "WoW: Shadowlands",
			title = "Mx Sansprimus Hero Sting B",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_90_mx_sansprimus_hero_sting_b.mp3",
			duration = 0,
			artist = "",
			id = 3853692,
		},
		{
			album = "WoW: Shadowlands",
			title = "Or Oribos Thepurpose A",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_90_or_oribos_thepurpose_a.mp3",
			duration = 0,
			artist = "",
			id = 3853742,
		},
		{
			album = "WoW: Shadowlands",
			title = "Bastion Generalwalk 01",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_bastion_generalwalk_01.mp3",
			duration = 0,
			artist = "",
			id = 3552890,
		},
		{
			album = "WoW: Shadowlands",
			title = "Bastion Generalwalk 02",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_bastion_generalwalk_02.mp3",
			duration = 0,
			artist = "",
			id = 3552892,
		},
		{
			album = "WoW: Shadowlands",
			title = "Bastion Tobekyrian 01",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_bastion_tobekyrian_01.mp3",
			duration = 0,
			artist = "",
			id = 3552898,
		},
		{
			album = "WoW: Shadowlands",
			title = "Notused Zone 90 Bastion Aspirantsjourney 01",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_notused_zone_90_bastion_aspirantsjourney_01.mp3",
			duration = 0,
			artist = "",
			id = 3552894,
		},
		{
			album = "WoW: Shadowlands",
			title = "Notused Zone 90 Bastion Tobekyrian2 01",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_notused_zone_90_bastion_tobekyrian2_01.mp3",
			duration = 0,
			artist = "",
			id = 3552896,
		},
		{
			album = "WoW: Shadowlands",
			title = "Npe Generalwalk Alliance1 03",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_npe_generalwalk_alliance1_03.mp3",
			duration = 0,
			artist = "",
			id = 3813355,
		},
		{
			album = "WoW: Shadowlands",
			title = "Npe Generalwalk Alliance2 04",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_npe_generalwalk_alliance2_04.mp3",
			duration = 0,
			artist = "",
			id = 3813353,
		},
		{
			album = "WoW: Shadowlands",
			title = "Npe Generalwalk Alliance2 05",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_npe_generalwalk_alliance2_05.mp3",
			duration = 0,
			artist = "",
			id = 3813357,
		},
		{
			album = "WoW: Shadowlands",
			title = "Npe Generalwalk Alliance2 06",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_npe_generalwalk_alliance2_06.mp3",
			duration = 0,
			artist = "",
			id = 3813359,
		},
		{
			album = "WoW: Shadowlands",
			title = "Npe Generalwalk Alliance2 07",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_npe_generalwalk_alliance2_07.mp3",
			duration = 0,
			artist = "",
			id = 3813361,
		},
		{
			album = "WoW: Shadowlands",
			title = "Npe Generalwalk Horde1 03",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_npe_generalwalk_horde1_03.mp3",
			duration = 0,
			artist = "",
			id = 3813365,
		},
		{
			album = "WoW: Shadowlands",
			title = "Npe Generalwalk Horde1 04",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_npe_generalwalk_horde1_04.mp3",
			duration = 0,
			artist = "",
			id = 3813371,
		},
		{
			album = "WoW: Shadowlands",
			title = "Npe Generalwalk Horde2 04",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_npe_generalwalk_horde2_04.mp3",
			duration = 0,
			artist = "",
			id = 3813363,
		},
		{
			album = "WoW: Shadowlands",
			title = "Npe Generalwalk Horde2 05",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_npe_generalwalk_horde2_05.mp3",
			duration = 0,
			artist = "",
			id = 3813367,
		},
		{
			album = "WoW: Shadowlands",
			title = "Npe Generalwalk Horde2 06",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_npe_generalwalk_horde2_06.mp3",
			duration = 0,
			artist = "",
			id = 3813369,
		},
		{
			album = "WoW: Shadowlands",
			title = "Npe Generalwalk Horde2 07",
			tagged_title = "",
			path = "sound\\music\\shadowlands\\mus_npe_generalwalk_horde2_07.mp3",
			duration = 0,
			artist = "",
			id = 3813373,
		},
		{
			album = "WoW: Unknown",
			title = "1.15.7 - Raid - Scarlet Enclave - Boss - Battle 6865474",
			tagged_title = "",
			path = "sound\\music\\unknown\\1.15.7 - raid - scarlet enclave - boss - battle_6865474.mp3",
			duration = 0,
			artist = "",
			id = 6865474,
		},
		{
			album = "WoW: Unknown",
			title = "1.15.7 - Raid - Scarlet Enclave - Boss - Battle 6865476",
			tagged_title = "",
			path = "sound\\music\\unknown\\1.15.7 - raid - scarlet enclave - boss - battle_6865476.mp3",
			duration = 0,
			artist = "",
			id = 6865476,
		},
		{
			album = "WoW: Unknown",
			title = "1.15.7 - Raid - Scarlet Enclave - Boss - Battle 6865478",
			tagged_title = "",
			path = "sound\\music\\unknown\\1.15.7 - raid - scarlet enclave - boss - battle_6865478.mp3",
			duration = 0,
			artist = "",
			id = 6865478,
		},
		{
			album = "WoW: Unknown",
			title = "1.15.7 - Raid - Scarlet Enclave - Boss - Battle 6865480",
			tagged_title = "",
			path = "sound\\music\\unknown\\1.15.7 - raid - scarlet enclave - boss - battle_6865480.mp3",
			duration = 0,
			artist = "",
			id = 6865480,
		},
		{
			album = "WoW: Unknown",
			title = "1.15.7 - Raid - Scarlet Enclave - Boss - Battle 6865482",
			tagged_title = "",
			path = "sound\\music\\unknown\\1.15.7 - raid - scarlet enclave - boss - battle_6865482.mp3",
			duration = 0,
			artist = "",
			id = 6865482,
		},
		{
			album = "WoW: Unknown",
			title = "1.15.7 - Raid - Scarlet Enclave - Boss - Battle 6865488",
			tagged_title = "",
			path = "sound\\music\\unknown\\1.15.7 - raid - scarlet enclave - boss - battle_6865488.mp3",
			duration = 0,
			artist = "",
			id = 6865488,
		},
		{
			album = "WoW: Unknown",
			title = "1.15.7 - Raid - Scarlet Enclave - Boss - Battle 6865490",
			tagged_title = "",
			path = "sound\\music\\unknown\\1.15.7 - raid - scarlet enclave - boss - battle_6865490.mp3",
			duration = 0,
			artist = "",
			id = 6865490,
		},
		{
			album = "WoW: Unknown",
			title = "1.15.7 - Raid - Scarlet Enclave - Boss - Battle 6865492",
			tagged_title = "",
			path = "sound\\music\\unknown\\1.15.7 - raid - scarlet enclave - boss - battle_6865492.mp3",
			duration = 0,
			artist = "",
			id = 6865492,
		},
		{
			album = "WoW: Unknown",
			title = "1.15.7 - Raid - Scarlet Enclave - Boss - Battle 6865494",
			tagged_title = "",
			path = "sound\\music\\unknown\\1.15.7 - raid - scarlet enclave - boss - battle_6865494.mp3",
			duration = 0,
			artist = "",
			id = 6865494,
		},
		{
			album = "WoW: Unknown",
			title = "1.15.7 - Raid - Scarlet Enclave - Chapel - Walk 1 6861009",
			tagged_title = "",
			path = "sound\\music\\unknown\\1.15.7 - raid - scarlet enclave - chapel - walk 1_6861009.mp3",
			duration = 0,
			artist = "",
			id = 6861009,
		},
		{
			album = "WoW: Unknown",
			title = "1.15.7 - Raid - Scarlet Enclave - Chapel - Walk 1 6861011",
			tagged_title = "",
			path = "sound\\music\\unknown\\1.15.7 - raid - scarlet enclave - chapel - walk 1_6861011.mp3",
			duration = 0,
			artist = "",
			id = 6861011,
		},
		{
			album = "WoW: Unknown",
			title = "1.15.7 - Raid - Scarlet Enclave - Chapel - Walk 1 6861013",
			tagged_title = "",
			path = "sound\\music\\unknown\\1.15.7 - raid - scarlet enclave - chapel - walk 1_6861013.mp3",
			duration = 0,
			artist = "",
			id = 6861013,
		},
		{
			album = "WoW: Unknown",
			title = "1.15.7 - Raid - Scarlet Enclave - Epilogue 6865498",
			tagged_title = "",
			path = "sound\\music\\unknown\\1.15.7 - raid - scarlet enclave - epilogue_6865498.mp3",
			duration = 0,
			artist = "",
			id = 6865498,
		},
		{
			album = "WoW: Unknown",
			title = "1.15.7 - Raid - Scarlet Enclave - Epilogue 6865500",
			tagged_title = "",
			path = "sound\\music\\unknown\\1.15.7 - raid - scarlet enclave - epilogue_6865500.mp3",
			duration = 0,
			artist = "",
			id = 6865500,
		},
		{
			album = "WoW: Unknown",
			title = "1.15.7 - Raid - Scarlet Enclave - General - Walk 6865484",
			tagged_title = "",
			path = "sound\\music\\unknown\\1.15.7 - raid - scarlet enclave - general - walk_6865484.mp3",
			duration = 0,
			artist = "",
			id = 6865484,
		},
		{
			album = "WoW: Unknown",
			title = "1.15.7 - Raid - Scarlet Enclave - General - Walk 6865486",
			tagged_title = "",
			path = "sound\\music\\unknown\\1.15.7 - raid - scarlet enclave - general - walk_6865486.mp3",
			duration = 0,
			artist = "",
			id = 6865486,
		},
		{
			album = "WoW: Unknown",
			title = "1.15.7 - Raid - Scarlet Enclave - New Avalon - Walk 6865468",
			tagged_title = "",
			path = "sound\\music\\unknown\\1.15.7 - raid - scarlet enclave - new avalon - walk_6865468.mp3",
			duration = 0,
			artist = "",
			id = 6865468,
		},
		{
			album = "WoW: Unknown",
			title = "1.15.7 - Raid - Scarlet Enclave - New Avalon - Walk 6865470",
			tagged_title = "",
			path = "sound\\music\\unknown\\1.15.7 - raid - scarlet enclave - new avalon - walk_6865470.mp3",
			duration = 0,
			artist = "",
			id = 6865470,
		},
		{
			album = "WoW: Unknown",
			title = "1.15.7 - Raid - Scarlet Enclave - New Avalon - Walk 6865472",
			tagged_title = "",
			path = "sound\\music\\unknown\\1.15.7 - raid - scarlet enclave - new avalon - walk_6865472.mp3",
			duration = 0,
			artist = "",
			id = 6865472,
		},
		{
			album = "WoW: The War Within",
			title = "Raid 11.0 - Nerub-ar Palace - Ansurek - Rp - Phase 3 6036434",
			tagged_title = "",
			path = "sound\\music\\warwithin\\raid 11.0 - nerub-ar palace - ansurek - rp - phase 3_6036434.mp3",
			duration = 0,
			artist = "",
			id = 6036434,
		},
	}
end)
