local EpicMusicPlayer = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer")

local playlist3 = {
	{
		["ListName"] = "Battle for Azeroth",
		["PlaylistVersion"] = "3.1",
		["PlaylistType"] = "generated",
		["MusicDir"] = "MyMusic\\",
        --first song
		["Album"] = "WoW7.3.5",
		["Song"] = "mus_735_pointofimpact_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_735_pointofimpact_a.mp3",
		["Length"] = 134,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW7.3.5",
		["Song"] = "mus_735_pointofimpact_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_735_pointofimpact_b.mp3",
		["Length"] = 143,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW7.3.5",
		["Song"] = "mus_735_pointofimpact_battle_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_735_pointofimpact_battle_h.mp3",
		["Length"] = 127,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW7.3.5",
		["Song"] = "mus_735_pointofimpact_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_735_pointofimpact_c.mp3",
		["Length"] = 163,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW7.3.5",
		["Song"] = "mus_735_pointofimpact_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_735_pointofimpact_d.mp3",
		["Length"] = 143,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW7.3.5",
		["Song"] = "mus_735_pointofimpact_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_735_pointofimpact_h.mp3",
		["Length"] = 144,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_alliancevictory_3_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_alliancevictory_3_h.mp3",
		["Length"] = 21,
		["Artist"] = "Glenn Stafford, Jason Hayes, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ashvanecompany_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ashvanecompany_a.mp3",
		["Length"] = 125,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ashvanecompany_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ashvanecompany_b.mp3",
		["Length"] = 108,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ashvanecompany_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ashvanecompany_c.mp3",
		["Length"] = 108,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ashvanecompany_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ashvanecompany_d.mp3",
		["Length"] = 132,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ashvanecompany_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ashvanecompany_e.mp3",
		["Length"] = 132,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ashvanecompany_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ashvanecompany_h.mp3",
		["Length"] = 125,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ataldazar_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ataldazar_a.mp3",
		["Length"] = 93,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ataldazar_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ataldazar_b.mp3",
		["Length"] = 93,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ataldazar_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ataldazar_c.mp3",
		["Length"] = 93,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ataldazar_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ataldazar_d.mp3",
		["Length"] = 93,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_ataldazar_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_ataldazar_h.mp3",
		["Length"] = 93,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_beforethestorm_maintitle",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_beforethestorm_maintitle.mp3",
		["Length"] = 677,
		["Artist"] = "Glenn Stafford, Neal Acree, Sam Cardon, Clint Bajakian, David Arkenstone, Leo Kaliski, Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_bloodmagic_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_bloodmagic_a.mp3",
		["Length"] = 89,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_bloodmagic_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_bloodmagic_b.mp3",
		["Length"] = 89,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_bloodmagic_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_bloodmagic_c.mp3",
		["Length"] = 89,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_bloodmagic_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_bloodmagic_h.mp3",
		["Length"] = 89,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_bloodsacrifice_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_bloodsacrifice_a.mp3",
		["Length"] = 99,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_bloodsacrifice_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_bloodsacrifice_b.mp3",
		["Length"] = 99,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_bloodsacrifice_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_bloodsacrifice_c.mp3",
		["Length"] = 99,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_bloodsacrifice_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_bloodsacrifice_d.mp3",
		["Length"] = 99,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_bloodsacrifice_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_bloodsacrifice_h.mp3",
		["Length"] = 99,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_boralus_intro",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_boralus_intro.mp3",
		["Length"] = 26,
		["Artist"] = "Sam Cardon, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_cityofgold_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_cityofgold_a.mp3",
		["Length"] = 81,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_cityofgold_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_cityofgold_b.mp3",
		["Length"] = 81,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_cityofgold_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_cityofgold_h.mp3",
		["Length"] = 81,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_classicbattle_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_classicbattle_a.mp3",
		["Length"] = 163,
		["Artist"] = "Glenn Stafford, Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_classicbattle_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_classicbattle_b.mp3",
		["Length"] = 164,
		["Artist"] = "Glenn Stafford, Jason Hayes",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_classicbattle_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_classicbattle_c.mp3",
		["Length"] = 102,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_classicbattle_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_classicbattle_d.mp3",
		["Length"] = 87,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_classicbattle_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_classicbattle_e.mp3",
		["Length"] = 92,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_classicbattle_f",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_classicbattle_f.mp3",
		["Length"] = 102,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_classicbattle_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_classicbattle_h.mp3",
		["Length"] = 163,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_crimsonforest_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_crimsonforest_a.mp3",
		["Length"] = 213,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_crimsonforest_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_crimsonforest_b.mp3",
		["Length"] = 133,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_crimsonforest_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_crimsonforest_c.mp3",
		["Length"] = 133,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_crimsonforest_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_crimsonforest_h.mp3",
		["Length"] = 135,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_crimsonrise_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_crimsonrise_a.mp3",
		["Length"] = 76,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_crimsonrise_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_crimsonrise_b.mp3",
		["Length"] = 76,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_crimsonrise_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_crimsonrise_c.mp3",
		["Length"] = 76,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_crimsonrise_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_crimsonrise_d.mp3",
		["Length"] = 76,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_crimsonrise_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_crimsonrise_h.mp3",
		["Length"] = 76,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_darkirondwarves_1_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_darkirondwarves_1_a.mp3",
		["Length"] = 21,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_darkirondwarves_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_darkirondwarves_1_h.mp3",
		["Length"] = 21,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_darkirondwarves_2_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_darkirondwarves_2_a.mp3",
		["Length"] = 14,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_darkirondwarves_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_darkirondwarves_2_h.mp3",
		["Length"] = 14,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_darkirondwarves_3_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_darkirondwarves_3_a.mp3",
		["Length"] = 36,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_darkirondwarves_3_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_darkirondwarves_3_h.mp3",
		["Length"] = 36,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_darkirondwarves_4_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_darkirondwarves_4_a.mp3",
		["Length"] = 46,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_darkirondwarves_4_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_darkirondwarves_4_h.mp3",
		["Length"] = 47,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_divebar_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_divebar_a.mp3",
		["Length"] = 120,
		["Artist"] = "Sam Cardon, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_divebar_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_divebar_b.mp3",
		["Length"] = 86,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_divebar_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_divebar_c.mp3",
		["Length"] = 108,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_drustvar_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_drustvar_a.mp3",
		["Length"] = 165,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_drustvar_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_drustvar_b.mp3",
		["Length"] = 164,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_drustvar_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_drustvar_c.mp3",
		["Length"] = 167,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_drustvar_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_drustvar_h.mp3",
		["Length"] = 165,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_freeholdcombat_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_freeholdcombat_a.mp3",
		["Length"] = 90,
		["Artist"] = "Glenn Stafford, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_freeholdcombat_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_freeholdcombat_h.mp3",
		["Length"] = 90,
		["Artist"] = "Glenn Stafford, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_freehold_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_freehold_a.mp3",
		["Length"] = 107,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_freehold_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_freehold_b.mp3",
		["Length"] = 125,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_freehold_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_freehold_h.mp3",
		["Length"] = 125,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_glenbrookwoods_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_glenbrookwoods_a.mp3",
		["Length"] = 119,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_glenbrookwoods_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_glenbrookwoods_b.mp3",
		["Length"] = 118,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_glenbrookwoods_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_glenbrookwoods_c.mp3",
		["Length"] = 43,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_glenbrookwoods_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_glenbrookwoods_d.mp3",
		["Length"] = 72,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_glenbrookwoods_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_glenbrookwoods_h.mp3",
		["Length"] = 118,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_goblingreed_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_goblingreed_a.mp3",
		["Length"] = 103,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_goblingreed_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_goblingreed_b.mp3",
		["Length"] = 94,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_goblingreed_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_goblingreed_c.mp3",
		["Length"] = 103,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_goblingreed_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_goblingreed_d.mp3",
		["Length"] = 94,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_goblingreed_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_goblingreed_e.mp3",
		["Length"] = 193,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_goblingreed_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_goblingreed_h.mp3",
		["Length"] = 193,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_heartofsethraliss_1_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_heartofsethraliss_1_a.mp3",
		["Length"] = 56,
		["Artist"] = "Glenn Stafford, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_heartofsethraliss_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_heartofsethraliss_1_h.mp3",
		["Length"] = 56,
		["Artist"] = "Glenn Stafford, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_heartofsethraliss_2_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_heartofsethraliss_2_a.mp3",
		["Length"] = 64,
		["Artist"] = "Glenn Stafford, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_heartofsethraliss_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_heartofsethraliss_2_h.mp3",
		["Length"] = 64,
		["Artist"] = "Glenn Stafford, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_hordevictory_3_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_hordevictory_3_h.mp3",
		["Length"] = 19,
		["Artist"] = "Glenn Stafford, Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_houseashvane_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_houseashvane_a.mp3",
		["Length"] = 113,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_houseashvane_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_houseashvane_h.mp3",
		["Length"] = 112,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_housewaycrest_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_housewaycrest_a.mp3",
		["Length"] = 112,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_housewaycrest_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_housewaycrest_b.mp3",
		["Length"] = 97,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_housewaycrest_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_housewaycrest_c.mp3",
		["Length"] = 97,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_housewaycrest_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_housewaycrest_h.mp3",
		["Length"] = 97,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_adventure_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_adventure_a.mp3",
		["Length"] = 85,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_adventure_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_adventure_b.mp3",
		["Length"] = 115,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_adventure_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_adventure_c.mp3",
		["Length"] = 101,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_adventure_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_adventure_d.mp3",
		["Length"] = 105,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_adventure_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_adventure_e.mp3",
		["Length"] = 102,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_adventure_f",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_adventure_f.mp3",
		["Length"] = 100,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_adventure_h1",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_adventure_h1.mp3",
		["Length"] = 92,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_adventure_h2",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_adventure_h2.mp3",
		["Length"] = 92,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_mystical_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_mystical_a.mp3",
		["Length"] = 157,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_mystical_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_mystical_b.mp3",
		["Length"] = 157,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_mystical_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_mystical_c.mp3",
		["Length"] = 71,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_mystical_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_mystical_d.mp3",
		["Length"] = 47,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_mystical_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_mystical_e.mp3",
		["Length"] = 60,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_mystical_h1",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_mystical_h1.mp3",
		["Length"] = 157,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_mystical_h2",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_mystical_h2.mp3",
		["Length"] = 157,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_mystical_victory",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_mystical_victory.mp3",
		["Length"] = 14,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_winter_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_winter_a.mp3",
		["Length"] = 154,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_winter_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_winter_b.mp3",
		["Length"] = 154,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_winter_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_winter_c.mp3",
		["Length"] = 66,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_winter_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_winter_d.mp3",
		["Length"] = 90,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_winter_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_winter_h.mp3",
		["Length"] = 154,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_islands_winter_victory",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_islands_winter_victory.mp3",
		["Length"] = 18,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kthir_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kthir_a.mp3",
		["Length"] = 131,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kthir_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kthir_b.mp3",
		["Length"] = 131,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kthir_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kthir_c.mp3",
		["Length"] = 111,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kthir_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kthir_h.mp3",
		["Length"] = 131,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiran_highseas_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiran_highseas_a.mp3",
		["Length"] = 143,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiran_highseas_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiran_highseas_b.mp3",
		["Length"] = 143,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiran_highseas_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiran_highseas_h.mp3",
		["Length"] = 143,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiran_parley_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiran_parley_a.mp3",
		["Length"] = 64,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiran_parley_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiran_parley_b.mp3",
		["Length"] = 64,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiran_parley_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiran_parley_h.mp3",
		["Length"] = 64,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiran_parley_jukebox",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiran_parley_jukebox.mp3",
		["Length"] = 55,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_day_01",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_day_01.mp3",
		["Length"] = 78,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_day_04",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_day_04.mp3",
		["Length"] = 75,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_day_05",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_day_05.mp3",
		["Length"] = 82,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_day_08",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_day_08.mp3",
		["Length"] = 76,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_day_09",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_day_09.mp3",
		["Length"] = 77,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_night_02",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_night_02.mp3",
		["Length"] = 75,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_night_04",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_night_04.mp3",
		["Length"] = 72,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_night_05",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_night_05.mp3",
		["Length"] = 77,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_night_06",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_night_06.mp3",
		["Length"] = 82,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_peaks_night_09",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_peaks_night_09.mp3",
		["Length"] = 76,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_d.mp3",
		["Length"] = 132,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_day_02",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_day_02.mp3",
		["Length"] = 68,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_day_03",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_day_03.mp3",
		["Length"] = 68,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_day_04",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_day_04.mp3",
		["Length"] = 128,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_day_05",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_day_05.mp3",
		["Length"] = 92,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_day_06",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_day_06.mp3",
		["Length"] = 70,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_day_07",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_day_07.mp3",
		["Length"] = 141,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_night_01",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_night_01.mp3",
		["Length"] = 94,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_night_02",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_night_02.mp3",
		["Length"] = 92,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_night_04",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_night_04.mp3",
		["Length"] = 72,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_night_06",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_night_06.mp3",
		["Length"] = 141,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_sky_night_10",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_sky_night_10.mp3",
		["Length"] = 93,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_b.mp3",
		["Length"] = 151,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_day_03",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_day_03.mp3",
		["Length"] = 76,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_day_04",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_day_04.mp3",
		["Length"] = 76,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_day_10",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_day_10.mp3",
		["Length"] = 72,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_day_11",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_day_11.mp3",
		["Length"] = 72,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_day_12",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_day_12.mp3",
		["Length"] = 76,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_night_03",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_night_03.mp3",
		["Length"] = 70,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_night_04",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_night_04.mp3",
		["Length"] = 70,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_night_07",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_night_07.mp3",
		["Length"] = 72,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_stone_night_09",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_stone_night_09.mp3",
		["Length"] = 72,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_kultiras_winter",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_kultiras_winter.mp3",
		["Length"] = 40,
		["Artist"] = "Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_akunda_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_akunda_a.mp3",
		["Length"] = 36,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_akunda_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_akunda_b.mp3",
		["Length"] = 36,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_akunda_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_akunda_c.mp3",
		["Length"] = 36,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_akunda_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_akunda_h.mp3",
		["Length"] = 36,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_bwonsamdi_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_bwonsamdi_c.mp3",
		["Length"] = 36,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_bwonsamdi_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_bwonsamdi_d.mp3",
		["Length"] = 36,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_bwonsamdi_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_bwonsamdi_h.mp3",
		["Length"] = 38,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_paku_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_paku_a.mp3",
		["Length"] = 41,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_paku_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_paku_d.mp3",
		["Length"] = 41,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_shadra_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_shadra_d.mp3",
		["Length"] = 55,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_loa_shadra_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_loa_shadra_h.mp3",
		["Length"] = 55,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_1_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_1_a.mp3",
		["Length"] = 109,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_1_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_1_b.mp3",
		["Length"] = 35,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_1_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_1_c.mp3",
		["Length"] = 56,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_1_h.mp3",
		["Length"] = 109,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_2_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_2_a.mp3",
		["Length"] = 59,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_2_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_2_b.mp3",
		["Length"] = 59,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_2_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_2_c.mp3",
		["Length"] = 60,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_2_h.mp3",
		["Length"] = 59,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_3_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_3_a.mp3",
		["Length"] = 42,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_3_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_3_b.mp3",
		["Length"] = 49,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_3_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_3_c.mp3",
		["Length"] = 79,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronalliance_3_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronalliance_3_h.mp3",
		["Length"] = 45,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_1_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_1_a.mp3",
		["Length"] = 80,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_1_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_1_b.mp3",
		["Length"] = 83,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_1_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_1_c.mp3",
		["Length"] = 78,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_1_h.mp3",
		["Length"] = 80,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_2_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_2_a.mp3",
		["Length"] = 80,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_2_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_2_b.mp3",
		["Length"] = 26,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_2_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_2_c.mp3",
		["Length"] = 55,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_2_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_2_d.mp3",
		["Length"] = 46,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_2_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_2_e.mp3",
		["Length"] = 95,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_lordaeronhorde_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_lordaeronhorde_2_h.mp3",
		["Length"] = 80,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_maghar_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_maghar_a.mp3",
		["Length"] = 244,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_maghar_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_maghar_b.mp3",
		["Length"] = 143,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_maghar_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_maghar_c.mp3",
		["Length"] = 143,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_maghar_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_maghar_d.mp3",
		["Length"] = 142,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_maghar_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_maghar_h.mp3",
		["Length"] = 142,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nagaincursion_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nagaincursion_a.mp3",
		["Length"] = 154,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nagaincursion_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nagaincursion_b.mp3",
		["Length"] = 154,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nagaincursion_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nagaincursion_c.mp3",
		["Length"] = 69,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nagaincursion_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nagaincursion_h.mp3",
		["Length"] = 154,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nazmirswamp_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nazmirswamp_a.mp3",
		["Length"] = 156,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nazmirswamp_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nazmirswamp_b.mp3",
		["Length"] = 103,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nazmirswamp_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nazmirswamp_c.mp3",
		["Length"] = 102,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nazmirswamp_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nazmirswamp_d.mp3",
		["Length"] = 93,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nazmirswamp_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nazmirswamp_e.mp3",
		["Length"] = 97,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nazmirswamp_f",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nazmirswamp_f.mp3",
		["Length"] = 126,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_nazmirswamp_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_nazmirswamp_h.mp3",
		["Length"] = 155,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_outlawharbor_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_outlawharbor_a.mp3",
		["Length"] = 172,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_outlawharbor_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_outlawharbor_b.mp3",
		["Length"] = 169,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_outlawharbor_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_outlawharbor_c.mp3",
		["Length"] = 173,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_outlawharbor_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_outlawharbor_h.mp3",
		["Length"] = 172,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_pointofimpact_pvp_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_pointofimpact_pvp_a.mp3",
		["Length"] = 72,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_pointofimpact_pvp_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_pointofimpact_pvp_b.mp3",
		["Length"] = 63,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_pointofimpact_pvp_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_pointofimpact_pvp_c.mp3",
		["Length"] = 49,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_pointofimpact_pvp_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_pointofimpact_pvp_d.mp3",
		["Length"] = 48,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_pointofimpact_pvp_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_pointofimpact_pvp_e.mp3",
		["Length"] = 32,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_pointofimpact_pvp_f",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_pointofimpact_pvp_f.mp3",
		["Length"] = 31,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_pointofimpact_pvp_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_pointofimpact_pvp_h.mp3",
		["Length"] = 125,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_quilboar_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_quilboar_a.mp3",
		["Length"] = 98,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_quilboar_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_quilboar_h.mp3",
		["Length"] = 97,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_ard",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_ard.mp3",
		["Length"] = 39,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_aro",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_aro.mp3",
		["Length"] = 36,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_bem",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_bem.mp3",
		["Length"] = 42,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_bog",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_bog.mp3",
		["Length"] = 68,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_btt",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_btt.mp3",
		["Length"] = 51,
		["Artist"] = "Jason Hayes, Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_kag",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_kag.mp3",
		["Length"] = 82,
		["Artist"] = "Russell Brower",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_mhi",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_mhi.mp3",
		["Length"] = 39,
		["Artist"] = "Glenn Stafford, Adam Burgess",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_nlc",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_nlc.mp3",
		["Length"] = 80,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_sdb",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_sdb.mp3",
		["Length"] = 69,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_sha",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_sha.mp3",
		["Length"] = 52,
		["Artist"] = "Derek Duke, Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_sma",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_sma.mp3",
		["Length"] = 49,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_tsc",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_tsc.mp3",
		["Length"] = 68,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_tzf",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_tzf.mp3",
		["Length"] = 144,
		["Artist"] = "Neal Acree, Sam Cardon, David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_vmr",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_vmr.mp3",
		["Length"] = 78,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_rtc_ztc",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_rtc_ztc.mp3",
		["Length"] = 69,
		["Artist"] = "David Arkenstone, Sam Cardon, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_sethrak_1_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_sethrak_1_a.mp3",
		["Length"] = 70,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_sethrak_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_sethrak_1_h.mp3",
		["Length"] = 73,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_sethrak_2_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_sethrak_2_a.mp3",
		["Length"] = 74,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_sethrak_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_sethrak_2_h.mp3",
		["Length"] = 76,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_1_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_1_a.mp3",
		["Length"] = 16,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_1_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_1_b.mp3",
		["Length"] = 12,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_1_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_1_c.mp3",
		["Length"] = 30,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_1_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_1_d.mp3",
		["Length"] = 50,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_1_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_1_e.mp3",
		["Length"] = 50,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_1_h.mp3",
		["Length"] = 64,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_2_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_2_a.mp3",
		["Length"] = 75,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_2_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_2_b.mp3",
		["Length"] = 21,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_2_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_2_d.mp3",
		["Length"] = 38,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_shrineofstorms_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_shrineofstorms_2_h.mp3",
		["Length"] = 82,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_sirenssong_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_sirenssong_a.mp3",
		["Length"] = 64,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_sirenssong_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_sirenssong_b.mp3",
		["Length"] = 58,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_sirenssong_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_sirenssong_c.mp3",
		["Length"] = 57,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_sirenssong_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_sirenssong_h.mp3",
		["Length"] = 58,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_stormsong_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_stormsong_a.mp3",
		["Length"] = 300,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_stormsong_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_stormsong_b.mp3",
		["Length"] = 307,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_stormsong_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_stormsong_c.mp3",
		["Length"] = 179,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_stormsong_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_stormsong_d.mp3",
		["Length"] = 298,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_stormsong_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_stormsong_e.mp3",
		["Length"] = 160,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_stormsong_g",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_stormsong_g.mp3",
		["Length"] = 224,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_stormsong_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_stormsong_h.mp3",
		["Length"] = 297,
		["Artist"] = "Derek Duke",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_thetortollan_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_thetortollan_a.mp3",
		["Length"] = 128,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_thetortollan_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_thetortollan_b.mp3",
		["Length"] = 128,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_thetortollan_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_thetortollan_c.mp3",
		["Length"] = 125,
		["Artist"] = "Sam Cardon, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_thetortollan_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_thetortollan_d.mp3",
		["Length"] = 75,
		["Artist"] = "Sam Cardon, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_thetortollan_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_thetortollan_h.mp3",
		["Length"] = 128,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_toldagor_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_toldagor_a.mp3",
		["Length"] = 86,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_toldagor_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_toldagor_b.mp3",
		["Length"] = 89,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_toldagor_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_toldagor_c.mp3",
		["Length"] = 86,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_toldagor_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_toldagor_d.mp3",
		["Length"] = 91,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_toldagor_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_toldagor_h.mp3",
		["Length"] = 91,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_vanquished_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_vanquished_a.mp3",
		["Length"] = 140,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_vanquished_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_vanquished_b.mp3",
		["Length"] = 140,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_vanquished_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_vanquished_c.mp3",
		["Length"] = 140,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_vanquished_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_vanquished_h.mp3",
		["Length"] = 140,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_voldun_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_voldun_a.mp3",
		["Length"] = 151,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_voldun_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_voldun_b.mp3",
		["Length"] = 150,
		["Artist"] = "Sam Cardon, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_voldun_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_voldun_c.mp3",
		["Length"] = 72,
		["Artist"] = "Sam Cardon, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_voldun_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_voldun_d.mp3",
		["Length"] = 92,
		["Artist"] = "Sam Cardon, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_voldun_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_voldun_e.mp3",
		["Length"] = 149,
		["Artist"] = "Sam Cardon, Kory McMaster",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_voldun_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_voldun_h.mp3",
		["Length"] = 151,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_vulpera_1_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_vulpera_1_b.mp3",
		["Length"] = 121,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_vulpera_1_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_vulpera_1_c.mp3",
		["Length"] = 95,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_vulpera_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_vulpera_1_h.mp3",
		["Length"] = 123,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_vulpera_2_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_vulpera_2_d.mp3",
		["Length"] = 39,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_vulpera_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_vulpera_2_h.mp3",
		["Length"] = 75,
		["Artist"] = "Neal Acree",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_a.mp3",
		["Length"] = 135,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_b.mp3",
		["Length"] = 203,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_c.mp3",
		["Length"] = 129,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_d.mp3",
		["Length"] = 130,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_e.mp3",
		["Length"] = 129,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_f",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_f.mp3",
		["Length"] = 118,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_g",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_g.mp3",
		["Length"] = 88,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_h.mp3",
		["Length"] = 137,
		["Artist"] = "Clint Bajakian",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_i",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_i.mp3",
		["Length"] = 95,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_j",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_j.mp3",
		["Length"] = 83,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_k",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_k.mp3",
		["Length"] = 89,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_l",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_l.mp3",
		["Length"] = 90,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_m",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_m.mp3",
		["Length"] = 97,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_n",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_n.mp3",
		["Length"] = 99,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_o",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_o.mp3",
		["Length"] = 85,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_warfrontsbattle_p",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_warfrontsbattle_p.mp3",
		["Length"] = 92,
		["Artist"] = "Clint Bajakian, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_drust_1_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_drust_1_a.mp3",
		["Length"] = 48,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_drust_1_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_drust_1_b.mp3",
		["Length"] = 48,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_drust_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_drust_1_h.mp3",
		["Length"] = 48,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_drust_2_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_drust_2_a.mp3",
		["Length"] = 54,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_drust_2_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_drust_2_b.mp3",
		["Length"] = 54,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_drust_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_drust_2_h.mp3",
		["Length"] = 54,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_woods_1_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_woods_1_a.mp3",
		["Length"] = 43,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_woods_1_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_woods_1_b.mp3",
		["Length"] = 42,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_woods_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_woods_1_h.mp3",
		["Length"] = 43,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_woods_2_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_woods_2_a.mp3",
		["Length"] = 52,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_woods_2_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_woods_2_b.mp3",
		["Length"] = 52,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestmanor_woods_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestmanor_woods_2_h.mp3",
		["Length"] = 53,
		["Artist"] = "Glenn Stafford",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestwedding_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestwedding_a.mp3",
		["Length"] = 38,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_waycrestwedding_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_waycrestwedding_b.mp3",
		["Length"] = 77,
		["Artist"] = "Glenn Stafford, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_windrunner_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_windrunner_b.mp3",
		["Length"] = 72,
		["Artist"] = "Glenn Stafford, Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_windrunner_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_windrunner_c.mp3",
		["Length"] = 129,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_windrunner_d",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_windrunner_d.mp3",
		["Length"] = 81,
		["Artist"] = "Glenn Stafford, Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_windrunner_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_windrunner_e.mp3",
		["Length"] = 50,
		["Artist"] = "Glenn Stafford, Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_windrunner_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_windrunner_h.mp3",
		["Length"] = 129,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zandalarilament_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zandalarilament_a.mp3",
		["Length"] = 82,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zandalarilament_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zandalarilament_b.mp3",
		["Length"] = 82,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zandalarilament_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zandalarilament_h.mp3",
		["Length"] = 82,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarbazaar_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarbazaar_1_h.mp3",
		["Length"] = 148,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarbazaar_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarbazaar_2_h.mp3",
		["Length"] = 140,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarjungle_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_a.mp3",
		["Length"] = 159,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarjungle_e",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_e.mp3",
		["Length"] = 111,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarjungle_f",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_f.mp3",
		["Length"] = 117,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarjungle_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_h.mp3",
		["Length"] = 162,
		["Artist"] = "David Arkenstone",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarjungle_i",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_i.mp3",
		["Length"] = 122,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarjungle_l",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_l.mp3",
		["Length"] = 101,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarjungle_o",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_o.mp3",
		["Length"] = 92,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazarjungle_q",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazarjungle_q.mp3",
		["Length"] = 92,
		["Artist"] = "David Arkenstone, Leo Kaliski",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazar_1_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazar_1_a.mp3",
		["Length"] = 72,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazar_1_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazar_1_b.mp3",
		["Length"] = 72,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazar_1_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazar_1_h.mp3",
		["Length"] = 72,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazar_2_a",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazar_2_a.mp3",
		["Length"] = 85,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazar_2_b",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazar_2_b.mp3",
		["Length"] = 85,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazar_2_c",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazar_2_c.mp3",
		["Length"] = 85,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
	{
		["Album"] = "WoW8.0",
		["Song"] = "mus_80_zuldazar_2_h",
		["Name"] = "sound\\music\\battleforazeroth\\mus_80_zuldazar_2_h.mp3",
		["Length"] = 85,
		["Artist"] = "Sam Cardon",
		["WoW"] =  "true",
	},
}
EpicMusicPlayer:AddPlayList("Battle for Azeroth", playlist3, false, true)
