-- EpicMusicPlayer playlist created by EpicPlaylistCreator version 1.4.
local playlist1={
  {
    ["ListName"] = "Legion",
    ["PlaylistVersion"] = "3.1",
    ["PlaylistType"] = "generated",
    ["MusicDir"] = "MyMusic\\",
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt1 A1",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_AnduinPt1_A1.mp3",
    ["Length"] = 75,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt1 A2",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_AnduinPt1_A2.mp3",
    ["Length"] = 113,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt1 B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_AnduinPt1_B.mp3",
    ["Length"] = 140,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt1 C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_AnduinPt1_C.mp3",
    ["Length"] = 137,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt1 D",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_AnduinPt1_D.mp3",
    ["Length"] = 90,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt1 E",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_AnduinPt1_E.mp3",
    ["Length"] = 71,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt1 H1",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_AnduinPt1_H1.mp3",
    ["Length"] = 88,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt1 H2",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_AnduinPt1_H2.mp3",
    ["Length"] = 115,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt2 B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_AnduinPt2_B.mp3",
    ["Length"] = 111,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt2 C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_AnduinPt2_C.mp3",
    ["Length"] = 54,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Anduin Pt2 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_AnduinPt2_H.mp3",
    ["Length"] = 123,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "As Soon As'Pret A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_AsSoonAsPret_A.mp3",
    ["Length"] = 89,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "As Soon As'Pret B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_AsSoonAsPret_B.mp3",
    ["Length"] = 81,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "As Soon As'Pret H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_AsSoonAsPret_H.mp3",
    ["Length"] = 126,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_BalloonRide_Stinger_01",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_BalloonRide_Stinger_01.mp3",
    ["Length"] = 12,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Canticle of Sacrifice A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_CanticleofSacrifice_A.mp3",
    ["Length"] = 248,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Canticle of Sacrifice B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_CanticleofSacrifice_B.mp3",
    ["Length"] = 250,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Canticle of Sacrifice C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_CanticleofSacrifice_C.mp3",
    ["Length"] = 177,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Canticle of Sacrifice D",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_CanticleofSacrifice_D.mp3",
    ["Length"] = 185,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Canticle of Sacrifice E",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_CanticleofSacrifice_E.mp3",
    ["Length"] = 13,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Canticle of Sacrifice F",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_CanticleofSacrifice_F.mp3",
    ["Length"] = 54,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Canticle of Sacrifice H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_CanticleofSacrifice_H.mp3",
    ["Length"] = 253,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_ClientScene_70_IF1_01",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_ClientScene_70_IF1_01.mp3",
    ["Length"] = 45,
    ["Artist"] = "Tracy W. Bush",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_ClientScene_70_IF2_01",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_ClientScene_70_IF2_01.mp3",
    ["Length"] = 73,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_ClientScene_70_IF3_01",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_ClientScene_70_IF3_01.mp3",
    ["Length"] = 70,
    ["Artist"] = "",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_ClientScene_MAW_Intro_Moment",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_ClientScene_MAW_Intro_Moment.mp3",
    ["Length"] = 20,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Dawn A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranDawn_A.mp3",
    ["Length"] = 95,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Dawn B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranDawn_B.mp3",
    ["Length"] = 92,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Dawn H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranDawn_H.mp3",
    ["Length"] = 93,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Dusk A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranDusk_A.mp3",
    ["Length"] = 98,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Dusk B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranDusk_B.mp3",
    ["Length"] = 95,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Dusk C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranDusk_C.mp3",
    ["Length"] = 97,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Dusk H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranDusk_H.mp3",
    ["Length"] = 98,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Halls 1 A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranHalls1_A.mp3",
    ["Length"] = 134,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Halls 1 B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranHalls1_B.mp3",
    ["Length"] = 127,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Halls 1 C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranHalls1_C.mp3",
    ["Length"] = 131,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Halls 1 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranHalls1_H.mp3",
    ["Length"] = 138,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Halls 2 A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranHalls2_A.mp3",
    ["Length"] = 110,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Halls 2 B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranHalls2_B.mp3",
    ["Length"] = 111,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Halls 2 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranHalls2_H.mp3",
    ["Length"] = 111,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Jaina A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranJaina_A.mp3",
    ["Length"] = 102,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Jaina B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranJaina_B.mp3",
    ["Length"] = 115,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Jaina C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranJaina_C.mp3",
    ["Length"] = 65,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Jaina H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranJaina_H.mp3",
    ["Length"] = 66,
    ["Artist"] = "Neal Acree, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Khadgar Day A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranKhadgar_Day_A.mp3",
    ["Length"] = 68,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Khadgar Day B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranKhadgar_Day_B.mp3",
    ["Length"] = 50,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Khadgar Day C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranKhadgar_Day_C.mp3",
    ["Length"] = 67,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Khadgar Day H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranKhadgar_Day_H.mp3",
    ["Length"] = 68,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Khadgar Night A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranKhadgar_Night_A.mp3",
    ["Length"] = 73,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Khadgar Night B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranKhadgar_Night_B.mp3",
    ["Length"] = 77,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Khadgar Night C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranKhadgar_Night_C.mp3",
    ["Length"] = 67,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Khadgar Night H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranKhadgar_Night_H.mp3",
    ["Length"] = 74,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Sewers 1 A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranSewers1_A.mp3",
    ["Length"] = 131,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Sewers 1 B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranSewers1_B.mp3",
    ["Length"] = 95,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Sewers 1 C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranSewers1_C.mp3",
    ["Length"] = 70,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Sewers 1 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranSewers1_H.mp3",
    ["Length"] = 131,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Sewers 2 A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranSewers2_A.mp3",
    ["Length"] = 154,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Sewers 2 B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranSewers2_B.mp3",
    ["Length"] = 129,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Dalaran Sewers 2 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DalaranSewers2_H.mp3",
    ["Length"] = 155,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt1 B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DemonHunterPt1_B.mp3",
    ["Length"] = 110,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt1 C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DemonHunterPt1_C.mp3",
    ["Length"] = 67,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt1 D",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DemonHunterPt1_D.mp3",
    ["Length"] = 79,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt1 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DemonHunterPt1_H.mp3",
    ["Length"] = 128,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt2 A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DemonHunterPt2_A.mp3",
    ["Length"] = 56,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt2 B 1",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DemonHunterPt2_B1.mp3",
    ["Length"] = 83,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt2 B 2",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DemonHunterPt2_B2.mp3",
    ["Length"] = 77,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt2 C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DemonHunterPt2_C.mp3",
    ["Length"] = 73,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt2 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DemonHunterPt2_H.mp3",
    ["Length"] = 123,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt3 A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DemonHunterPt3_A.mp3",
    ["Length"] = 72,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt3 B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DemonHunterPt3_B.mp3",
    ["Length"] = 72,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt3 C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DemonHunterPt3_C.mp3",
    ["Length"] = 37,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt3 D",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DemonHunterPt3_D.mp3",
    ["Length"] = 65,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Demon Hunter Pt3 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_DemonHunterPt3_H.mp3",
    ["Length"] = 130,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EmeraldNightmare_C.mp3",
    ["Length"] = 130,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare D",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EmeraldNightmare_D.mp3",
    ["Length"] = 119,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare E",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EmeraldNightmare_E.mp3",
    ["Length"] = 34,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare F",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EmeraldNightmare_F.mp3",
    ["Length"] = 34,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare G",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EmeraldNightmare_G.mp3",
    ["Length"] = 114,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare J",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EmeraldNightmare_J.mp3",
    ["Length"] = 100,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare K",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EmeraldNightmare_K.mp3",
    ["Length"] = 114,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare L",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EmeraldNightmare_L.mp3",
    ["Length"] = 97,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare M",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EmeraldNightmare_M.mp3",
    ["Length"] = 92,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare Orch A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EmeraldNightmareOrch_A.mp3",
    ["Length"] = 70,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare Orch B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EmeraldNightmareOrch_B.mp3",
    ["Length"] = 62,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare Orch H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EmeraldNightmareOrch_H.mp3",
    ["Length"] = 138,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare Syn A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EmeraldNightmareSyn_A.mp3",
    ["Length"] = 112,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Emerald Nightmare Syn H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EmeraldNightmareSyn_H.mp3",
    ["Length"] = 129,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Enchanted Night Elves A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EnchantedNightElves_A.mp3",
    ["Length"] = 100,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Enchanted Night Elves B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EnchantedNightElves_B.mp3",
    ["Length"] = 100,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Enchanted Night Elves C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EnchantedNightElves_C.mp3",
    ["Length"] = 101,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Enchanted Night Elves H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EnchantedNightElves_H.mp3",
    ["Length"] = 101,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Enraptured Woodlands A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EnrapturedWoodlands_A.mp3",
    ["Length"] = 123,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Enraptured Woodlands B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EnrapturedWoodlands_B.mp3",
    ["Length"] = 102,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Enraptured Woodlands C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EnrapturedWoodlands_C.mp3",
    ["Length"] = 93,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Enraptured Woodlands H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_EnrapturedWoodlands_H.mp3",
    ["Length"] = 124,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Fel Glade A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_FelGlade_A.mp3",
    ["Length"] = 40,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Fel Glade B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_FelGlade_B.mp3",
    ["Length"] = 82,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Fel Glade C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_FelGlade_C.mp3",
    ["Length"] = 100,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Fel Glade H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_FelGlade_H.mp3",
    ["Length"] = 97,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Glimmer A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Glimmer_A.mp3",
    ["Length"] = 46,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Glimmer H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Glimmer_H.mp3",
    ["Length"] = 47,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Elf Tomb A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighElfTomb_A.mp3",
    ["Length"] = 69,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Elf Tomb H1",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighElfTomb_H1.mp3",
    ["Length"] = 101,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Elf Tomb H2",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighElfTomb_H2.mp3",
    ["Length"] = 112,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 10 A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain10_A.mp3",
    ["Length"] = 111,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 10 B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain10_B.mp3",
    ["Length"] = 111,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 10 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain10_H.mp3",
    ["Length"] = 111,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_Highmountain10_Stinger_01",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain10_Stinger_01.mp3",
    ["Length"] = 13,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 1 A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain1_A.mp3",
    ["Length"] = 84,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 1 B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain1_B.mp3",
    ["Length"] = 92,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 1 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain1_H.mp3",
    ["Length"] = 92,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 2 A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain2_A.mp3",
    ["Length"] = 84,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 2 B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain2_B.mp3",
    ["Length"] = 84,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 2 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain2_H.mp3",
    ["Length"] = 84,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 3 A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain3_A.mp3",
    ["Length"] = 66,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 3 B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain3_B.mp3",
    ["Length"] = 66,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 3 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain3_H.mp3",
    ["Length"] = 66,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 4 A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain4_A.mp3",
    ["Length"] = 104,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 4 B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain4_B.mp3",
    ["Length"] = 105,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 4 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain4_H.mp3",
    ["Length"] = 105,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 5 A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain5_A.mp3",
    ["Length"] = 62,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 5 B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain5_B.mp3",
    ["Length"] = 62,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "High Mountain 5 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain5_H.mp3",
    ["Length"] = 63,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 6 A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain6_A.mp3",
    ["Length"] = 79,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 6 B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain6_B.mp3",
    ["Length"] = 80,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 6 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain6_H.mp3",
    ["Length"] = 81,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 7 A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain7_A.mp3",
    ["Length"] = 43,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 7 B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain7_B.mp3",
    ["Length"] = 44,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 7 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain7_H.mp3",
    ["Length"] = 43,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 8 A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain8_A.mp3",
    ["Length"] = 51,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 8 B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain8_B.mp3",
    ["Length"] = 52,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 8 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain8_H.mp3",
    ["Length"] = 50,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 9 A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain9_A.mp3",
    ["Length"] = 38,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Highmountain 9 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HighMountain9_H.mp3",
    ["Length"] = 37,
    ["Artist"] = "Glenn Stafford",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Gather A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HolyWarriorsGather_A.mp3",
    ["Length"] = 61,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Gather B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HolyWarriorsGather_B.mp3",
    ["Length"] = 137,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Gather C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HolyWarriorsGather_C.mp3",
    ["Length"] = 138,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Gather H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HolyWarriorsGather_H.mp3",
    ["Length"] = 138,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Oath A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HolyWarriorsOath_A.mp3",
    ["Length"] = 75,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Oath B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HolyWarriorsOath_B.mp3",
    ["Length"] = 110,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Oath C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HolyWarriorsOath_C.mp3",
    ["Length"] = 130,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Oath D",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HolyWarriorsOath_D.mp3",
    ["Length"] = 132,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Oath E",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HolyWarriorsOath_E.mp3",
    ["Length"] = 132,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Oath F",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HolyWarriorsOath_F.mp3",
    ["Length"] = 74,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Oath G",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HolyWarriorsOath_G.mp3",
    ["Length"] = 102,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Holy Warriors Oath H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_HolyWarriorsOath_H.mp3",
    ["Length"] = 132,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_Invincible_Stinger_01",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Invincible_Stinger_01.mp3",
    ["Length"] = 12,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Kingdoms Will Burn",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Kingdomswillburn_MainTitle.mp3",
    ["Length"] = 650,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Laila Demon A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LailaDemon_A.mp3",
    ["Length"] = 127,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Laila Demon B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LailaDemon_B.mp3",
    ["Length"] = 125,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Laila Demon C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LailaDemon_C.mp3",
    ["Length"] = 121,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Laila Demon D1",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LailaDemon_D1.mp3",
    ["Length"] = 95,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Laila Demon D2",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LailaDemon_D2.mp3",
    ["Length"] = 97,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Laila Demon H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LailaDemon_H.mp3",
    ["Length"] = 192,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Last Stand A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LastStand_A.mp3",
    ["Length"] = 79,
    ["Artist"] = "Sam Cardon, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Last Stand B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LastStand_B.mp3",
    ["Length"] = 79,
    ["Artist"] = "Sam Cardon, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Last Stand C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LastStand_C.mp3",
    ["Length"] = 79,
    ["Artist"] = "Sam Cardon, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Last Stand D",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LastStand_D.mp3",
    ["Length"] = 79,
    ["Artist"] = "Sam Cardon, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Last Stand E",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LastStand_E.mp3",
    ["Length"] = 79,
    ["Artist"] = "Sam Cardon, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Last Stand F",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LastStand_F.mp3",
    ["Length"] = 79,
    ["Artist"] = "Sam Cardon, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Last Stand H1",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LastStand_H1.mp3",
    ["Length"] = 84,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_LastStand_H1_Stinger_01",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LastStand_H1_Stinger_01.mp3",
    ["Length"] = 10,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Last Stand H2",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LastStand_H2.mp3",
    ["Length"] = 87,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_LastStand_H3_Stinger_01",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LastStand_H3_Stinger_01.mp3",
    ["Length"] = 12,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Last Stand H3 End",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LastStand_H3End.mp3",
    ["Length"] = 72,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Ley Lines A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LeyLines_A.mp3",
    ["Length"] = 69,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Ley Lines B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LeyLines_B.mp3",
    ["Length"] = 69,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Ley Lines C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LeyLines_C.mp3",
    ["Length"] = 65,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Ley Lines H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_LeyLines_H.mp3",
    ["Length"] = 93,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Menace of the Dark Titans A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_MenaceoftheDarkTitans_A.mp3",
    ["Length"] = 123,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Menace of the Dark Titans B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_MenaceoftheDarkTitans_B.mp3",
    ["Length"] = 115,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Menace of the Dark Titans C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_MenaceoftheDarkTitans_C.mp3",
    ["Length"] = 118,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Menace of the Dark Titans H1",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_MenaceoftheDarkTitans_H1.mp3",
    ["Length"] = 85,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Menace of the Dark Titans H2",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_MenaceoftheDarkTitans_H2.mp3",
    ["Length"] = 66,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Mire 1 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Mire1_H.mp3",
    ["Length"] = 9,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Mire 2 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Mire2_H.mp3",
    ["Length"] = 15,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Mire 3 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Mire3_H.mp3",
    ["Length"] = 24,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Mire 4 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Mire4_H.mp3",
    ["Length"] = 10,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Mire 5 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Mire5_H.mp3",
    ["Length"] = 12,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Moon Rising A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_MoonRising_A.mp3",
    ["Length"] = 122,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Moon Rising B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_MoonRising_B.mp3",
    ["Length"] = 120,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Moon Rising C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_MoonRising_C.mp3",
    ["Length"] = 125,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Moon Rising H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_MoonRising_H.mp3",
    ["Length"] = 157,
    ["Artist"] = "Edo Guidotti",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_MylunesMelody_Full",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_MylunesMelody_Full.mp3",
    ["Length"] = 44,
    ["Artist"] = "Derek Duke, Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Nos'Sharah A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_NosSharah_A.mp3",
    ["Length"] = 76,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Nos'Sharah B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_NosSharah_B.mp3",
    ["Length"] = 63,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Nos'Sharah C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_NosSharah_C.mp3",
    ["Length"] = 46,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Nos'Sharah D",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_NosSharah_D.mp3",
    ["Length"] = 127,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Nos'Sharah E",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_NosSharah_E.mp3",
    ["Length"] = 76,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Nos'Sharah H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_NosSharah_H.mp3",
    ["Length"] = 127,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Order Hall Devotions A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_OrderHallDevotions_A.mp3",
    ["Length"] = 114,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Order Hall Devotions B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_OrderHallDevotions_B.mp3",
    ["Length"] = 128,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Order Hall Devotions C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_OrderHallDevotions_C.mp3",
    ["Length"] = 119,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Order Hall Devotions D",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_OrderHallDevotions_D.mp3",
    ["Length"] = 128,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Order Hall Devotions E",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_OrderHallDevotions_E.mp3",
    ["Length"] = 67,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Order Hall Devotions F",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_OrderHallDevotions_F.mp3",
    ["Length"] = 127,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Order Hall Devotions H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_OrderHallDevotions_H.mp3",
    ["Length"] = 126,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Passage A1",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Passage_A1.mp3",
    ["Length"] = 77,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Passage A2",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Passage_A2.mp3",
    ["Length"] = 110,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Passage B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Passage_B.mp3",
    ["Length"] = 75,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Passage C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Passage_C.mp3",
    ["Length"] = 79,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Passage D",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Passage_D.mp3",
    ["Length"] = 184,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Passage H1",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Passage_H1.mp3",
    ["Length"] = 102,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Passage H2",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Passage_H2.mp3",
    ["Length"] = 85,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Preserver H1",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Preserver_H1.mp3",
    ["Length"] = 91,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Preserver H2",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Preserver_H2.mp3",
    ["Length"] = 97,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Preserver H3 End",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Preserver_H3End.mp3",
    ["Length"] = 56,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Relentless A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Relentless_A.mp3",
    ["Length"] = 7,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Relentless B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Relentless_B.mp3",
    ["Length"] = 7,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Relentless C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Relentless_C.mp3",
    ["Length"] = 7,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Relentless D",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Relentless_D.mp3",
    ["Length"] = 7,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Relentless E",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Relentless_E.mp3",
    ["Length"] = 13,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Relentless F",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Relentless_F.mp3",
    ["Length"] = 10,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Relentless G",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Relentless_G.mp3",
    ["Length"] = 51,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Relentless H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Relentless_H.mp3",
    ["Length"] = 149,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Relentless J",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Relentless_J.mp3",
    ["Length"] = 78,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_RequiemfortheLostCities_A.mp3",
    ["Length"] = 55,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_RequiemfortheLostCities_B.mp3",
    ["Length"] = 49,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_RequiemfortheLostCities_C.mp3",
    ["Length"] = 103,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities D",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_RequiemfortheLostCities_D.mp3",
    ["Length"] = 66,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities E",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_RequiemfortheLostCities_E.mp3",
    ["Length"] = 96,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities F",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_RequiemfortheLostCities_F.mp3",
    ["Length"] = 96,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities G",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_RequiemfortheLostCities_G.mp3",
    ["Length"] = 82,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities H1",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_RequiemfortheLostCities_H1.mp3",
    ["Length"] = 92,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities H2",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_RequiemfortheLostCities_H2.mp3",
    ["Length"] = 29,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Requiem for the Lost Cities H3",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_RequiemfortheLostCities_H3End.mp3",
    ["Length"] = 92,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Rose A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Rose_A.mp3",
    ["Length"] = 75,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Rose H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Rose_H.mp3",
    ["Length"] = 75,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_RuinsOfAuberdine_01_Stinger_01",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_RuinsOfAuberdine_01_Stinger_01.mp3",
    ["Length"] = 9,
    ["Artist"] = "Neal Acree",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Sacred Stone A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_SacredStone_A.mp3",
    ["Length"] = 120,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Sacred Stone B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_SacredStone_B.mp3",
    ["Length"] = 113,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Sacred Stone H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_SacredStone_H.mp3",
    ["Length"] = 124,
    ["Artist"] = "Sam Cardon",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Sanctum of Karazhan H1",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_SanctumofKarazhan_H1.mp3",
    ["Length"] = 103,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Sanctum of Karazhan H2",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_SanctumofKarazhan_H2.mp3",
    ["Length"] = 119,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Stormheim A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Stormheim_A.mp3",
    ["Length"] = 88,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Stormheim B1",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Stormheim_B1.mp3",
    ["Length"] = 77,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Stormheim B2",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Stormheim_B2.mp3",
    ["Length"] = 123,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Stormheim C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Stormheim_C.mp3",
    ["Length"] = 157,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Stormheim D",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Stormheim_D.mp3",
    ["Length"] = 42,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Stormheim E",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Stormheim_E.mp3",
    ["Length"] = 54,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Stormheim F",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Stormheim_F.mp3",
    ["Length"] = 65,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Stormheim G",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Stormheim_G.mp3",
    ["Length"] = 66,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Stormheim H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Stormheim_H.mp3",
    ["Length"] = 198,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Suramar Pt1 A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Suramar_Pt1_A.mp3",
    ["Length"] = 69,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Suramar Pt1 B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Suramar_pt1_b.mp3",
    ["Length"] = 59,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Suramar Pt1 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Suramar_Pt1_H.mp3",
    ["Length"] = 70,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Suramar Pt2 A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Suramar_pt2_a.mp3",
    ["Length"] = 64,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Suramar Pt2 B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Suramar_pt2_b.mp3",
    ["Length"] = 95,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Suramar Pt2 H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Suramar_Pt2_H.mp3",
    ["Length"] = 101,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Tempest A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Tempest_A.mp3",
    ["Length"] = 146,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Tempest B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Tempest_B.mp3",
    ["Length"] = 40,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_Tempest_B_Stinger_01",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Tempest_B_Stinger_01.mp3",
    ["Length"] = 17,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Tempest C",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Tempest_C.mp3",
    ["Length"] = 77,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Tempest D",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Tempest_D.mp3",
    ["Length"] = 76,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Tempest E",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Tempest_E.mp3",
    ["Length"] = 16,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Tempest F",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Tempest_F.mp3",
    ["Length"] = 16,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Tempest G",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Tempest_G.mp3",
    ["Length"] = 25,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Tempest H1",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Tempest_H1.mp3",
    ["Length"] = 75,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "Tempest H2",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Tempest_H2.mp3",
    ["Length"] = 78,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Totems H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Totems_H.mp3",
    ["Length"] = 349,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "MUS_70_TourneyBattle06_Stinger_01",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_TourneyBAttle06_Stinger_01.mp3",
    ["Length"] = 10,
    ["Artist"] = "David Arkenstone",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "We Are Not Alone A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_WeAreNotAlone_A.mp3",
    ["Length"] = 90,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "We Are Not Alone B",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_WeAreNotAlone_B.mp3",
    ["Length"] = 60,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoWx7",
    ["Song"] = "We Are Not Alone H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_WeAreNotAlone_H.mp3",
    ["Length"] = 106,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Weep Bass Flute",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Weep_Flute.mp3",
    ["Length"] = 110,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Weep Horn",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Weep_Horn.mp3",
    ["Length"] = 111,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Weep Viola",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Weep_Viola.mp3",
    ["Length"] = 110,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Weep WW",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_Weep_WW.mp3",
    ["Length"] = 111,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Winds Out of the East A",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_WindsOutoftheEast_A.mp3",
    ["Length"] = 96,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
  {
    ["Album"] = "WoW 6.2",
    ["Song"] = "Winds Out of the East H",
    ["Name"] = "Sound\\music\\Legion\\MUS_70_WindsOutoftheEast_H.mp3",
    ["Length"] = 90,
    ["Artist"] = "Russell Brower",
    ["WoW"] = true,
  },
}
local EpicMusicPlayer = LibStub("AceAddon-3.0"):GetAddon("EpicMusicPlayer")if not EpicMusicPlayer then return end
EpicMusicPlayer:AddPlayList("Legion", playlist1, false)
